### PR TITLE
[#16851] Local RESP cache in clustered server

### LINKED ISSUE #16851: Handle local RESP configuration in clustered mode
### Describe the bug

After #15973, we started to store the configuration for the RESP cache. Starting an unclustered server (`infinispan-resp.xml`) creates a local cache. The RESP cache is created as a local cache. The RESP cache created by this setup should be acceptable when starting with a clustered server.

### Expected behavior

_No response_

### Actual behavior

The server fails to start with a clustered configuration and the local-cache configuration for RESP.

### How to Reproduce?

1. `./bin/server.sh -n node-0 -c infinispan-resp.xml`
2. Access the RESP cache in some way (application, cli, etc.)
3. Stop the server
4. `./bin/server.sh -n node-0`

The server will fail to start on step 4.

### PR DESCRIPTION
**Pull request by jabolina**
* Configure the hash function for non-clustered RESP.
* Validate hash configuration based on stored value.

Closes #16851.

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/RespServer.java [hunk 1]
```diff
@@ -118,9 +118,9 @@ private void defineCacheConfiguration() {
          } else {
             if (globalConfiguration.isClustered()) { // We are running in clustered mode
                builder.clustering().cacheMode(CacheMode.DIST_SYNC);
-               // See: https://redis.io/docs/reference/cluster-spec/#key-distribution-model
-               builder.clustering().hash().keyPartitioner(new RESPHashFunctionPartitioner());
             }
+            // See: https://redis.io/docs/reference/cluster-spec/#key-distribution-model
+            builder.clustering().hash().keyPartitioner(new RESPHashFunctionPartitioner());
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/RespServer.java:123]: Why are we setting the hash function on non clustered instances for a default? The only thing I can think this would affect is if you have a segmented store. Is this if you want to reuse the store later or something?

Comment (jabolina) [reply server/resp/src/main/java/org/infinispan/server/resp/RespServer.java:123]: It was mostly for symmetry, so any configuration uses the same hash function.

**Comment by tristantarrant** [comment]
Merged, thanks
