### PR TITLE
[#16022] Fine-grained configuration update

### LINKED ISSUE #16022: Cache configuration improper serialization and match
### Describe the bug

Currently, when creating a cache, the `GlobalConfigurationManagerImpl` uses `Configuration.toStringConfiguration` to transform the provided configuration to an XML string and insert it into the CONFIG cache.

https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java#L280-L282

After the insertion, the `GlobalConfigurationStateListener` is triggered, and creates the cache locally with the `GlobalConfigurationManagerImpl`. The listener uses the configuration serialized as XML to reconstruct the cache configuration. Right before creating the cache, the XML is serialized back into a `Configuration` object:

https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java#L333-L339

And the `VolatileLocalConfigurationStorage` asserts the configuration matches (in case it was registered previously):

https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/globalstate/impl/VolatileLocalConfigurationStorage.java#L77-L91

To ensure the RESP configuration isn't tampered with, we define the configuration when the server starts. This process ensures the configuration is valid from the start, and can't be changed to something invalid. However, the test suite found several cases where the serialization and deserialization aren't symmetrical, and the `match` method in the configuration uses parameters that it shouldn't.

For example, the following programmatic configuration:

```java
      ConfigurationBuilder cb = new ConfigurationBuilder();
      cb.clustering().cacheMode(CacheMode.LOCAL);
      cb.clustering().hash()
            .numOwners(1)
            .keyPartitioner(new RESPHashFunctionPartitioner());
      cb.invocationBatching().enable(true);
```

Is serialized as:

```xml
<?xml version="1.0"?>
<local-cache name="some-name">
   <transaction mode="BATCH"/>
</local-cache>
```

Which means that the `Configuration` created programmatically and the `Configuration` created by the XML won't match. This also applies to other parameters: 

* Utilizing a `REPL_CACHE`, we can define the `.numOwners(1)`, but this is not permitted in the XML format. The `match` will fail because it takes the `numOwners` parameter into account.
* Utilizing a `DIST_CACHE`, the deserialization of the XML to `Configuration` will set `useSynchronization=true` in the transaction configuration automatically: https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java#L565-L572 

In all of these cases, it won't be possible to create the cache.

### Expected behavior

The serialization to XML is missing some parameters, and/or the match verification includes more parameters than necessary. For example, numOwners can't be written in the XML configuration, so it shouldn't be taken into consideration when verifying for a match.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Configuration update also validate the attributes match.

An extra step after #16174 that I didn't find at first.
Closes #16022.

### CODE REVIEW

File: core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java [hunk 1]
```diff
@@ -109,4 +109,22 @@ public boolean matches(ClusteringConfiguration other) {
 
       return super.matches(other);
    }
+
+   @Override
+   public void update(String parentName, ClusteringConfiguration other) {
+      if (this.cacheMode == CacheMode.LOCAL && other.cacheMode == CacheMode.LOCAL) {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java:115]: I believe we need to care about ClusteringConfiguration/HashConfiguration if the local cache has a segmented store. But the more I think about it I wonder if we really want to support that configuration or not..

Comment (jabolina) [reply core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java:115]: I was a bit unsure about HashConfiguration, too. Not sure whether we should change the matches/update, or if we should add restrictions in the validate method in the builder :/

Comment (jabolina) [reply core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java:115]: @wburns, should we change the `validateUpdate` and `update` methods?

**Comment by tristantarrant** [comment]
Can you rebase please

File: core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java (hunk 1 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java:115]: It should be alright 🤞

**Review by wburns — APPROVED** [review]

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
