### PR TITLE
[#16440] Fixes protostream and java marshalling per cache

### LINKED ISSUE #16440: Query with Java Marshaller and Protostream failing per cache
### Describe the bug

 When we configure 

clientBuilder.marshaller(JavaSerializationMarshaller.class);
clientBuilder.addContextInitializer(TestDomainSCI.INSTANCE);
clientBuilder.remoteCache(TEST_CACHE_NAME).marshaller(ProtoStreamMarshaller.class);

trying to query the remote cache fails because protostream marshaller is not used properly

### Expected behavior

Even if the global marshaller is java, protostream is properly used

### Actual behavior

Query can't be done

### PR DESCRIPTION
**Pull request by karesti**
Fixes #16440

### CODE REVIEW

**Comment by wburns** [comment]
Looks like a bunch of jboss marshaller failures now :(

**Comment by karesti** [comment]
@wburns looks it's fine now

**Comment by karesti** [comment]
@tristantarrant

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/QuerySerializer.java [hunk 1]
```diff
@@ -40,33 +40,25 @@ JsonClientQueryResponse readQueryResponse(Marshaller marshaller, RemoteQuery<?>
...
+            Thread.currentThread().interrupt();
+            throw new HotRodClientException(e);
          }
       }
 
       @Override
       QueryResponse readQueryResponse(Marshaller marshaller, RemoteQuery<?> remoteQuery, byte[] bytesResponse) {
-         SerializationContext serCtx = remoteQuery.getSerializationContext();
-         if (serCtx != null) {
+         if (marshaller instanceof ProtoStreamMarshaller) {
```
Comment (wburns) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/QuerySerializer.java:59]: Shouldn't we also check for serCtx being null ike we are in the `serializeQueryRequest` method?

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/multimap/RemoteMultimapCacheImpl.java [hunk 2]
```diff
@@ -37,7 +37,7 @@ public class RemoteMultimapCacheImpl<K, V> implements RemoteMultimapCache<K, V>
    private final RemoteCacheManager remoteCacheManager;
    private MultimapOperationsFactory operationsFactory;
    private OperationDispatcher dispatcher;
-   private Marshaller marshaller;
+   private Marshaller defaultMarshaller;
```
Comment (wburns) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/multimap/RemoteMultimapCacheImpl.java:40]: Changes seem unneeded, but I am fine with keeping if you want.

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java [hunk 3]
```diff
@@ -213,11 +213,11 @@ CompletableFuture<V> invalidateNearCacheIfNeeded(boolean hasForceReturnValue, Ob
 
    @Override
    public void resolveStorage(MediaType key, MediaType value) {
-      if (key != null && !delegate.getRemoteCacheManager().getMarshaller().mediaType().match(key)) {
+      if (key != null && !delegate.getMarshaller().mediaType().match(key)) {
```
Comment (wburns) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java:215]: So this means the Cache <arshaller is always non null now right? I wonder if we should deprecate the method on RemoteCacheManager then so people don't accidentally reference it?

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java [hunk 4]
```diff
@@ -567,4 +569,31 @@ default <T> T execute(String taskName, Map<String, ?> params, Object key) {
     * @return {@code true} if the cache can participate in a transaction, {@code false} otherwise.
     */
    boolean isTransactional();
+
+   /**
+    * Gets configured marshaller for this cache on client side
+    *
+    * @return {@link Marshaller}
+    */
+   default Marshaller getMarshaller() {
```
Comment (wburns) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java]: I wonder if instead we should store the Marshaller as a field on the RemoteCacheImpl that is passed in when constructing it to not have to inline all this code?

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java [hunk 5]
```diff
@@ -0,0 +1,161 @@
...
+            .mediaType(MediaType.APPLICATION_PROTOSTREAM).build());
+      cache = cacheManager.getCache(TEST_CACHE_NAME);
+
+      hotRodServer = HotRodClientTestingUtil.startHotRodServer(cacheManager);
+
+      org.infinispan.client.hotrod.configuration.ConfigurationBuilder clientBuilder = HotRodClientTestingUtil.newRemoteConfigurationBuilder();
+      clientBuilder.addServer().host("127.0.0.1").port(hotRodServer.getPort());
+      clientBuilder.marshaller(JavaSerializationMarshaller.class);
+      clientBuilder.addContextInitializer(TestDomainSCI.INSTANCE);
+      clientBuilder.remoteCache(TEST_CACHE_NAME).marshaller(ProtoStreamMarshaller.class);
```
Comment (wburns) [inline client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java:70]: Does it make any sense to have a Marshaller that isn't protostream with a context initializer? Is the point of this config here so you set the default to be JavaSerialization and if you define a specific cache with ProtoStream it would just us the default initializers? I must admit it seems a bit odd to me. I would normally think a user would define their context initializer on the same cache configuration as well as the protostream marshaller.

**Review by wburns — COMMENTED** [review]
Looks good @karesti ! I didn't realize we messed up the marshallers so bad in the client, heh

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java (hunk 3 above)
Comment (karesti) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java:215]: I believe we should use the cache marshaller too, and deprecate the method. I'll do that

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java (hunk 5 above)
Comment (karesti) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java:70]: context initializer for protostream is global for all the caches. however, the marshaller is configured per cache. I think changing that, would impact the client code too much. To be honest, I believe this should be hidden and be done automatically, as we do in Quarkus, looks more like an implementation detail delegated to the user than an API to me

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/QuerySerializer.java (hunk 1 above)
Comment (karesti) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/QuerySerializer.java:59]: in this context, it's never null I believe

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java (hunk 4 above)
Comment (karesti) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java]: I did this change

**Comment by karesti** [comment]
@wburns I reported the changes

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java (hunk 5 above)
Comment (wburns) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java:70]: Don't users want to possibly add their own context initializer or you mean to automatically import them by class path scanning? I wonder if users want to have different initializers per cache to avoid caches containing incorrect data.

**Comment by wburns** [comment]
Changes look promising to me, have some test failures though :(

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java (hunk 5 above)
Comment (karesti) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/GlobalJavaMarshallerWithProtostreamMarshallerQueryTest.java:70]: I mean importing it for them
in which case do you think a user would add data containing incorrect data ? @wburns

**Comment by karesti** [comment]
@wburns pushed a change

**Comment by karesti** [comment]
@wburns other PR have these tests failing, I rebased main and pushed again

**Comment by karesti** [comment]
@wburns is this fine now ?

**Comment by wburns** [comment]
Integrated into main, thanks @karesti !
