### PR TITLE
[#14917] Terminate completes pending cache start exceptionally

### LINKED ISSUE #14917: Server does not do anything on SIG_TERM until started
### Describe the bug

Today we install a shutdown hook but only does things after the server is fully started. We should also have a way to stop a server even before it fully starts instead of having to wait or use SIG_KILL.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Terminate might hang until a cache has started.
* Terminate verifies if the cache has started, and completes exceptionally.

Closes #14917

### CODE REVIEW

**Comment by wburns** [comment]
@jabolina Can you post an example of a start being stopped and what is output?

**Comment by jabolina** [comment]
Adding some for when I've reproduced it when running with 15.0.15.Final. In this case, the cache is still initializing and waiting for state transfer to finish. After I CTRL-C it:

```
^C
2025-05-27 16:37:40,937 INFO  [o.i.SERVER] ISPN080002: Infinispan Server stopping
*** Server process (360302) received INT signal ***
^C*** Server process (360302) received INT signal ***
^C*** Server process (360302) received INT signal ***
```

And the thread dump shows:
```java
"Thread-0" #27 [360699] prio=5 os_prio=0 cpu=14.35ms elapsed=21.38s tid=0x000055594ee8dbc0 nid=360699 waiting on condition  [0x00007f05995fe000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@21/Native Method)
	- parking to wait for  <0x0000000693121c50> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@21/LockSupport.java:221)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@21/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@21/ForkJoinPool.java:3780)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21/ForkJoinPool.java:3725)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@21/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.join(java.base@21/CompletableFuture.java:2117)
	at org.infinispan.manager.DefaultCacheManager.terminate(DefaultCacheManager.java:809)
	at org.infinispan.manager.DefaultCacheManager.stopCaches(DefaultCacheManager.java:919)
	at org.infinispan.manager.DefaultCacheManager.internalStop(DefaultCacheManager.java:884)
	at org.infinispan.manager.DefaultCacheManager.stop(DefaultCacheManager.java:858)
	at org.infinispan.server.SecurityActions.lambda$stopCacheManager$1(SecurityActions.java:50)
	at org.infinispan.server.SecurityActions$$Lambda/0x00007f05be80eed8.get(Unknown Source)
	at org.infinispan.security.Security.doPrivileged(Security.java:49)
	at org.infinispan.server.SecurityActions.stopCacheManager(SecurityActions.java:56)
	at org.infinispan.server.Server.localShutdown(Server.java:621)
	at org.infinispan.server.Server.lambda$run$4(Server.java:421)
	at org.infinispan.server.Server$$Lambda/0x00007f05be24f7d8.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandle(java.base@21/CompletableFuture.java:934)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(java.base@21/CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@21/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@21/CompletableFuture.java:2179)
	at org.infinispan.server.DefaultExitHandler.exit(DefaultExitHandler.java:13)
	at org.infinispan.server.ShutdownHook.run(ShutdownHook.java:16)
````

**Review by wburns — APPROVED** [review]
LGTM

**Comment by pruivo** [comment]
failures seem related.

**Comment by jabolina** [comment]
I've added a few extra checks for the CM and global component registry status so that it will stop initialization altogether. When I press CTRL-C while a cache is starting, it will complete without throwing exceptions:

```
^C
*** Server process (49162) received INT signal ***
2025-06-02 13:17:58,582 INFO  [o.i.SERVER] ISPN080002: Infinispan Server stopping
2025-06-02 13:17:58,758 INFO  [o.i.LIFECYCLE] ISPN000973: Task 'state-transfer-sftrec' started at 2025-06-02T16:17:54.702655416Z and done 2025-06-02T16:17:58.758377353Z
2025-06-02 13:17:58,794 INFO  [o.i.CONTAINER] ISPN000390: Persisted state, version=16.0.0-SNAPSHOT timestamp=2025-06-02T16:17:58.793890778Z
2025-06-02 13:17:58,795 INFO  [o.i.CLUSTER] ISPN000080: Disconnecting JGroups channel `cluster`
*** Server process (49162) received TERM signal ***
```

File: core/src/main/java/org/infinispan/manager/DefaultCacheManager.java [hunk 1]
```diff
@@ -1008,7 +1014,12 @@ public CompletionStage<Void> removeListenerAsync(Object listener) {
 
    @Override
    public ComponentStatus getStatus() {
-      return status;
+      lifecycleLock.lock();
```
Comment (wburns) [inline core/src/main/java/org/infinispan/manager/DefaultCacheManager.java]: Status is volatile, is this really necessary?

File: core/src/main/java/org/infinispan/CoreModule.java [hunk 2]
```diff
@@ -26,6 +27,11 @@ public void cacheManagerStopping(GlobalComponentRegistry gcr) {
 
    public static void startLifecycleComponent(GlobalComponentRegistry gcr, Class<?>... klasses) {
       for (Class<?> klass : klasses) {
+         // Cache manager was stopped before all components were started.
+         // Check the manager status because it stops before the global component registry.
+         ComponentStatus status = gcr.getCacheManager().getStatus();
```
Comment (wburns) [inline core/src/main/java/org/infinispan/CoreModule.java:32]: Did you find the check in GlobalComponentRegistry not sufficient so we have to do the check on every component?

File: core/src/main/java/org/infinispan/manager/DefaultCacheManager.java (hunk 1 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/manager/DefaultCacheManager.java]: Is this so a certain method blocks when another is running concurrently? I feel like that should be done in the method instead.

Comment (jabolina) [reply core/src/main/java/org/infinispan/manager/DefaultCacheManager.java]: Yeah. Specifically, if a stop method is running.

File: core/src/main/java/org/infinispan/CoreModule.java (hunk 2 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/CoreModule.java:32]: Yeah, it was not sufficient. I can explain the cases I saw, bear in mind that a cache stopped while starting, won't throw any exception.

Here in the `CoreModule`, if we start a new cache and it is waiting for the state transfer to complete, it will block on:

https://github.com/infinispan/infinispan/blob/5c503731dee6e63a42ab84958a60792c4a3ef166/core/src/main/java/org/infinispan/CoreModule.java#L19

If the cache manager is stopped while the cache is blocked on the `postStart()`, it will unblock without exceptions and proceed to execute the `startLifecycleComponent`. This would try to start some components when we already know the cache manager has stopped. In my tests, an example here was the `ClusterPermissionMapper`.

If we keep only the changes here in the `CoreModule`, it will correctly skip the modules when the cache manager is stopped. But it will return to the `GlobalComponentRegistry, which will continue the `modulesManagerStarted`:

https://github.com/infinispan/infinispan/blob/5c503731dee6e63a42ab84958a60792c4a3ef166/core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java#L292-L303

The `CoreModule` was just one of the modules. If we don't add a check there as well, it will continue and try to initialize other modules. In my case, it will proceed to the scripting module and will throw the exception.

Comment (jabolina) [reply core/src/main/java/org/infinispan/CoreModule.java:32]: These extra checks are not really necessary for the shutdown to work. They only avoid throwing exceptions while stopping.

File: core/src/main/java/org/infinispan/manager/DefaultCacheManager.java (hunk 1 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/manager/DefaultCacheManager.java]: I don't think this is a good idea. This means it will block HealthCheckResponse in REST as well, when it should just be STOPPING that is returned immediately that shows it can't handle requests.

File: core/src/main/java/org/infinispan/CoreModule.java (hunk 2 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/CoreModule.java:32]: I guess it is fine, I just worry if we are trying to close all possible exceptions during startup with a concurrent stop that it is a fool's errand.

**Comment by wburns** [comment]
Looks like CacheManagerTest.testConcurrentCacheManagerStopAndGetCache  failure is related.

File: core/src/main/java/org/infinispan/manager/DefaultCacheManager.java (hunk 1 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/manager/DefaultCacheManager.java]: I'll check the tests failures and will revert this.

**Comment by jabolina** [comment]
I believe the failure with the `PreferConsistencyRestartTest` is not related. I'll open another PR fixing those and closing the flaky test issues.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
