### PR TITLE
[#16664] Fix javadoc tags missing descriptions

### LINKED ISSUE #16664: Missing description for javadoc tags
### Describe the bug

Several javadocs have tags with missing descriptions (@param @return @throws).

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #16664

### CODE REVIEW

**Review by karesti — APPROVED** [review]

File: counter/src/main/java/org/infinispan/counter/impl/weak/WeakCounterImpl.java [hunk 1]
```diff
@@ -439,7 +440,7 @@ public void updatePreferredKeys() {
          }
          this.preferredKeys = preferredKeys.isEmpty() ?
                null :
-               preferredKeys.toArray(new WeakCounterKey[preferredKeys.size()]);
+               preferredKeys.toArray(new WeakCounterKey[0]);
```
Comment (rigazilla) [inline counter/src/main/java/org/infinispan/counter/impl/weak/WeakCounterImpl.java:443]: looks good but unrelated to javadoc. Ok to keep it here?

Comment (tristantarrant) [reply counter/src/main/java/org/infinispan/counter/impl/weak/WeakCounterImpl.java:443]: pretty harmless

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @tristantarrant!
