### PR TITLE
[#16223] RESP JSON.MGET fixed arity check

### LINKED ISSUE #16223: JSON.MGET should be able to accept single key only
### Describe the bug

JSON.MGET fails if only single key is provided

### Expected behavior

127.0.0.1:6379> JSON.SET doc1 $ '{"a":1, "b": 2, "nested": {"a": 3}, "c": null}'
OK
127.0.0.1:6379> JSON.MGET doc1 $..a
1) "[1,3]"

### Actual behavior

127.0.0.1:6379> JSON.SET doc1 $ '{"a":1, "b": 2, "nested": {"a": 3}, "c": null}'
OK
127.0.0.1:6379> JSON.MGET doc1 $..a
(error) ERR wrong number of arguments for 'json.mget' command

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by rigazilla**
fixes #16223

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java [hunk 1]
```diff
@@ -32,10 +32,6 @@ public JSONMGET() {
    @Override
    public CompletionStage<RespRequestHandler> perform(Resp3Handler handler, ChannelHandlerContext ctx,
                                                       List<byte[]> arguments) {
-      if (arguments.size() < 3) {
```
Comment (Crumby) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java:35]: Out of curiosity, where's the check for the number of arguments happening? I can see it's still happening and the command will fail with single argument only

Comment (rigazilla) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java:35]: It's checkd in the superclass: https://github.com/infinispan/infinispan/blob/1ff657e2c7945e355d79477860d645364bf91398/server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java#L32-L40
