### PR TITLE
[#15726] Iteration without segments

### LINKED ISSUE #15726: JDBC store select all for each segment
### Describe the bug

The JDBC stores execute a select all query when publishing all the entries in the database. However, this operation is submitted for every segment. In [1] is the full log, here is only a smaller part:

```log
2025-09-26 16:30:27,040 TRACE [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {0}
2025-09-26 16:30:27,040 TRACE [o.i.p.j.c.s.BaseTableOperations] Running select all sql 'SELECT ID, ISBN, NAME, COUNTRY FROM AUTHORS'
2025-09-26 16:30:27,040 TRACE [o.i.p.j.c.i.c.PooledConnectionFactory] Connection checkout (active=0): wrapped[conn1: url=jdbc:h2:tcp://localhost:9123/~/example user=INFINISPAN]
2025-09-26 16:30:27,041 TRACE [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {1}
2025-09-26 16:30:27,041 TRACE [o.i.p.j.c.i.c.PooledConnectionFactory] Connection release (active=0): wrapped[conn1: url=jdbc:h2:tcp://localhost:9123/~/example user=INFINISPAN]
2025-09-26 16:30:27,041 TRACE [o.i.p.j.c.s.BaseTableOperations] Running select all sql 'SELECT ID, ISBN, NAME, COUNTRY FROM AUTHORS'
2025-09-26 16:30:27,041 TRACE [o.i.p.j.c.i.c.PooledConnectionFactory] Connection checkout (active=0): wrapped[conn1: url=jdbc:h2:tcp://localhost:9123/~/example user=INFINISPAN]
2025-09-26 16:30:27,042 TRACE [o.i.p.j.c.i.c.PooledConnectionFactory] Connection release (active=0): wrapped[conn1: url=jdbc:h2:tcp://localhost:9123/~/example user=INFINISPAN]
2025-09-26 16:30:27,042 TRACE [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {2}
...
```

I've used the simple tutorial for this [2]. The setup creates an H2 database, and I just invoked the REST endpoint with `?action=entries`.

[1] https://gist.github.com/jabolina/2858fba15f8da55c58b1b182852ba53f
[2] https://github.com/infinispan/infinispan-simple-tutorials/blob/main/infinispan-remote/persistence/README.md

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Allow iteration without tracking segment completion when requested in the publisher API.

Utilizing the publisher API and explicitly calling to publish without segments is transformed to always publish and track segment completion. This change now propagates whether the publisher should track segments or not.

For example, I've created the following cache:

```xml
<?xml version="1.0"?>
<distributed-cache name="dist-c" owners="2" mode="SYNC" statistics="true">
    <encoding media-type="application/x-protostream"/>
    <persistence passivation="false">
        <string-keyed-jdbc-store xmlns="urn:infinispan:config:store:jdbc:16.2" segmented="true" dialect="H2">
            <string-keyed-table prefix="ISPN_STRING_TABLE" create-on-start="true">
                <id-column name="ID_COLUMN" type="VARCHAR(255)"/>
                <data-column name="DATA_COLUMN" type="BINARY VARYING"/>
                <timestamp-column name="TIMESTAMP_COLUMN" type="BIGINT"/>
                <segment-column name="SEGMENT_COLUMN" type="INT"/>
            </string-keyed-table>
            <connection-pool username="***" password="***" driver="org.h2.Driver" connection-url="jdbc:h2:mem:infinispan"/>
        </string-keyed-jdbc-store>
    </persistence>
</distributed-cache>
```

Tracking segments is especially costly for the JDBC stores because it will perform the select all segment for each segment. Something like opening the console lists the entries (with some limit). Without the fix, we have:

```log
2026-03-12 20:51:43,658 TRACE (non-blocking-thread-node-0-1-14) [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {0}
2026-03-12 20:51:43,660 TRACE () [o.i.p.j.c.s.BaseTableOperations] Running select all sql 'SELECT DATA_COLUMN, ID_COLUMN FROM "ISPN_STRING_TABLE_dist_c" WHERE (TIMESTAMP_COLUMN > ? OR TIMESTAMP_COLUMN < 0) AND SEGMENT_COLUMN IN (?)'
2026-03-12 20:51:43,660 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection checkout (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
2026-03-12 20:51:43,662 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection release (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
2026-03-12 20:51:43,663 TRACE (non-blocking-thread-node-0-1-23) [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {1}
2026-03-12 20:51:43,663 TRACE () [o.i.p.j.c.s.BaseTableOperations] Running select all sql 'SELECT DATA_COLUMN, ID_COLUMN FROM "ISPN_STRING_TABLE_dist_c" WHERE (TIMESTAMP_COLUMN > ? OR TIMESTAMP_COLUMN < 0) AND SEGMENT_COLUMN IN (?)'
2026-03-12 20:51:43,663 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection checkout (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
2026-03-12 20:51:43,663 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection release (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
2026-03-12 20:51:43,663 TRACE (non-blocking-thread-node-0-1-25) [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {2}
2026-03-12 20:51:43,663 TRACE () [o.i.p.j.c.s.BaseTableOperations] Running select all sql 'SELECT DATA_COLUMN, ID_COLUMN FROM "ISPN_STRING_TABLE_dist_c" WHERE (TIMESTAMP_COLUMN > ? OR TIMESTAMP_COLUMN < 0) AND SEGMENT_COLUMN IN (?)'
2026-03-12 20:51:43,663 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection checkout (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
2026-03-12 20:51:43,664 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection release (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
2026-03-12 20:51:43,664 TRACE (non-blocking-thread-node-0-1-27) [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {3}
2026-03-12 20:51:43,664 TRACE () [o.i.p.j.c.s.BaseTableOperations] Running select all sql 'SELECT DATA_COLUMN, ID_COLUMN FROM "ISPN_STRING_TABLE_dist_c" WHERE (TIMESTAMP_COLUMN > ? OR TIMESTAMP_COLUMN < 0) AND SEGMENT_COLUMN IN (?)'
```

It performs the select all for each segment (it can complete sooner depending on the limit provided). With the fix, we have:

```log
2026-03-12 20:44:11,724 TRACE (non-blocking-thread-node-0-1-1) [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {0-255}
2026-03-12 20:44:11,724 INFO  (non-blocking-thread-node-0-1-1) [o.i.p.m.PersistenceManagerImpl] Publishing entries for segments {0-255}
2026-03-12 20:44:11,726 TRACE () [o.i.p.j.c.s.BaseTableOperations] Running select all sql 'SELECT DATA_COLUMN, ID_COLUMN FROM "ISPN_STRING_TABLE_dist_c" WHERE (TIMESTAMP_COLUMN > ? OR TIMESTAMP_COLUMN < 0) AND SEGMENT_COLUMN IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'
2026-03-12 20:44:11,726 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection checkout (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
2026-03-12 20:44:11,739 TRACE () [o.i.p.j.c.i.c.PooledConnectionFactory] Connection release (active=0): wrapped[conn0: url=jdbc:h2:mem:infinispan user=SA]
```

We perform only a single query.

Close #15726.

### CODE REVIEW

File: core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java [hunk 1]
```diff
@@ -284,8 +286,18 @@ void startProcessing(InitialPublisherCommand command) {
...
+            Notifications.NotificationBuilder<Object> builder = Notifications.newBuilder();
+            Flowable.fromPublisher(sap.publisherWithoutSegments())
+                  .map(v -> builder.value(v, 0))
+                  .concatWith(Flowable.fromIterable(segments)
+                        .map(builder::segmentComplete))
+                  .subscribe(this);
+         } else {
+            Flowable.fromPublisher(sap.publisherWithLostSegments(true))
+                  .subscribe(this);
+         }
```
Comment (wburns) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java:295]: We have to change how we do this. Unfortunately, this will cause issues when we have to track for EXACTLY_ONCE delivery guarantee without notifications, because we still want the segments completed in order. Instead what we need to do is ensure that when using AT_MOST_ONCE and no notifications that we can publish with all the segments. Unfortunately, when the user wants segments we should prioritize completing a segment first if possible as it most likely means the user needs to do some sort of by segment caching.

**Comment by jabolina** [comment]
@wburns, I've pushed a change. I've added a new method that will utilize the publisher call with all segments and track for lost segments. I guess the big caveat is that:

* Iteration has an arbitrary order. The entries will belong to any segment.
* We only publish segment completion after iterating on everything. So any cleanup is done after that.

**Comment by wburns** [comment]
Looks like two related failures.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/InitialPublisherCommand.java [hunk 2]
```diff
@@ -156,6 +161,11 @@ public boolean isReturnValueExpected() {
       return true;
    }
 
+   @ProtoField(13)
```
Comment (wburns) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/InitialPublisherCommand.java]: Shouldn't we set the default value to true? If we have a mixed cluster, the older version won't pass this and thus we don't know if it requires segments or not.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java [hunk 3]
```diff
@@ -578,19 +585,34 @@ void startProcessing(InitialPublisherCommand command) {
...
-                  Object key = toKeyFunction.apply(originalValue);
-                  return Flowable.fromPublisher(functionToApply.apply(Flowable.just(originalValue)))
-                        .map(v -> builder.value(v, notification.valueSegment()))
-                        // Signal the end of the key - flatMap could have 0 or multiple entries
-                        .concatWith(Single.just(keyBuilder.value(key, notification.valueSegment())));
-               })
-               .subscribe(this);
+         if (!command.isSegmentNotificationNeeded()) {
+            Flowable.fromPublisher(sap.publisherWithoutSegmentsNotifying())
+                  .concatMap(notification -> {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java]: This code is identical to the below else. We should be able to just encapsulate the call to `publisherWithoutSegmentsNotifying` or `publisherWithLostSegments` in the if/else instead

File: core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java [hunk 4]
```diff
@@ -578,19 +585,34 @@ void startProcessing(InitialPublisherCommand command) {
...
-                  }
-                  Object originalValue = notification.value();
-                  Object key = toKeyFunction.apply(originalValue);
-                  return Flowable.fromPublisher(functionToApply.apply(Flowable.just(originalValue)))
-                        .map(v -> builder.value(v, notification.valueSegment()))
-                        // Signal the end of the key - flatMap could have 0 or multiple entries
-                        .concatWith(Single.just(keyBuilder.value(key, notification.valueSegment())));
-               })
-               .subscribe(this);
+         if (!command.isSegmentNotificationNeeded()) {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java]: It doesn't make sense that we use no segment notification when key tracking is enabled, which is when this invoked as key tracking must be cleared up by segment to prevent memory issues.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/InitialPublisherCommand.java [hunk 5]
```diff
@@ -36,11 +36,13 @@ public class InitialPublisherCommand<K, I, R> extends BaseRpcCommand implements
...
    final boolean trackKeys;
    final Function<? super Publisher<I>, ? extends Publisher<R>> transformer;
+   final boolean segmentNotificationNeeded;
    private int topologyId = -1;
 
    public InitialPublisherCommand(ByteString cacheName, String requestId, DeliveryGuarantee deliveryGuarantee,
                                   int batchSize, IntSet segments, Set<K> keys, Set<K> excludedKeys, long explicitFlags, boolean entryStream,
-                                  boolean trackKeys, Function<? super Publisher<I>, ? extends Publisher<R>> transformer) {
+                                  boolean trackKeys, Function<? super Publisher<I>, ? extends Publisher<R>> transformer,
+                                  boolean segmentNotificationNeeded) {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/InitialPublisherCommand.java:45]: Lets add an assertion that doesn't allow for trackKeys to be true or deliveryGuarantee to be EXACTLY_ONCE  while includeSegmentNotification is false since we need to track segments in both of those cases.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/SegmentAwarePublisherSupplier.java [hunk 6]
```diff
@@ -48,6 +48,18 @@ default int lostSegment() {
...
 
+   /**
+    * Similar to {@link #publisherWithLostSegments()} but without requiring values to be published in segment order.
+    * Values from different segments may be interleaved, and all segment complete or lost notifications are published
+    * after all values.
+    * <p>
+    * The provided {@link DeliveryGuarantee} when creating this <i>SegmentAwarePublisherSupplier</i> controls
+    * how lost segment notifications are raised, following the same rules as {@link #publisherWithLostSegments()}.
+    */
+   default Publisher<NotificationWithLost<R>> publisherWithoutSegmentsNotifying() {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/SegmentAwarePublisherSupplier.java]: We should name this something else.. maybe something related due to that segment completion notifications are delayed as we still do "notify" segments.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/InitialPublisherCommand.java (hunk 2 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/InitialPublisherCommand.java]: Doh! Definitely, we want to default to using segments.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java (hunk 4 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java]: Sounds good, I think we are safe to remove the change for this part.

**Comment by jabolina** [comment]
I've added the suggestions. Now, it should not be possible to end up iterating without segments if key tracking or EXACTLY_ONCE. To take advantage of the optimization, I've added a second commit that adds a new query parameter to the REST endpoint when iterating over cache entries/keys. By default, EXACTLY_ONCE to keep the same behavior.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java [hunk 7]
```diff
@@ -1012,13 +1012,17 @@ class SubscriberHandler<I, R> implements ObjIntConsumer<I> {
...
       // Variable used to ensure we only read the context once - so it is not read again during a retry
       volatile int currentTopology = -1;
 
-      SubscriberHandler(AbstractSegmentAwarePublisher<I, R> publisher) {
+      SubscriberHandler(AbstractSegmentAwarePublisher<I, R> publisher, boolean withSegments) {
          this.publisher = publisher;
          this.requestId = rpcManager.getAddress() + "#" + requestCounter.incrementAndGet();
+         this.includeSegmentNotification = withSegments
+               || publisher.shouldTrackKeys
+               || publisher.deliveryGuarantee == DeliveryGuarantee.EXACTLY_ONCE;
```
Comment (wburns) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java:1024]: I looked a bit closer and `shouldTrackKeys` is only true if EXACTLY_ONCE is, so we can condense this down to just being about EXACTLY_ONCE.

File: server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java [hunk 8]
```diff
@@ -768,6 +775,18 @@ protected CompletionStage<RestResponse> streamEntries(RestRequest request) {
       return CompletableFuture.completedFuture(responseBuilder.build());
    }
 
+   private static DeliveryGuarantee deliveryGuarantee(RestRequest request) {
+      String param = request.getParameter("delivery-guarantee");
+      if (param == null || param.isEmpty()) {
+         return DeliveryGuarantee.EXACTLY_ONCE;
```
Comment (wburns) [inline server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java:781]: I am fine changing this to be less strict if needed... not sure what others think.

1. Entries will not be in segment order any longer
2. AT_MOST_ONCE may not show some values under topology change
3. AT_LEAST_ONCE may show some values more than once under topology changes

In turn iteration becomes much more performant, especially with a JDBC store. I wonder if we should detect if there is a store or not and then change default? @tristantarrant or @karesti wdyt?

File: server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java [hunk 9]
```diff
@@ -1197,6 +1197,54 @@ public void testEntryStreamWithFailure() {
...
    }
 
+   @Test
+   public void testStreamKeysWithDeliveryGuarantee() {
+      // Put some entries
+      putTextEntryInCache("default", "k1", "v1");
+
+      // Default (no param): EXACTLY_ONCE
+      try (RestResponse response = join(client.raw().get("/rest/v2/caches/default?action=keys"))) {
+         assertEquals(200, response.status());
```
Comment (wburns) [inline server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java:1207]: No verification of the body?

File: server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java (hunk 8 above)
Comment (jabolina) [reply server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java:781]: Yeah, now that we at least provide the option, I am fine with whatever guarantee we leave it. I guess the console would be able to identify whether a cache uses a JDBC store and fall back to one of the other guarantees? That would already be a good improvement. Would it help in the non-segmented stores?

Comment (wburns) [reply server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java:781]: The only non-segmented stores are JDBC and possibly user based ones. My original thought before was to change to AT_MOST_ONCE if we had a non-segmented store. Another possible optimization would be checking in memory size and if it is greater than the fetch amount, just skip STORE completely.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !

File: server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java (hunk 8 above)
Comment (jabolina) [reply server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java:781]: I'll check with Katia about applying the change in the console, specifically for JDBC stores, and reading the entries with AT_LEAST_ONCE.
