### PR TITLE
[#17218] Fix Hot Rod protocol version downgrade after handshake

### LINKED ISSUE #17218: Hot Rod client protocol version downgrade from 4.1 to 3.1 after handshake
## Description

When using the Hot Rod client with `PROTOCOL_VERSION_AUTO` (the default), the connection starts at HOTROD/4.1 but downgrades to HOTROD/3.1 after the first client-server interaction. The same happens when explicitly setting `protocol_version=4.1` — the initial connection shows 4.1 in the server console, but subsequent operations revert to 3.1.

## Root Cause

There is an inverted null-check in `HeaderDecoder.setCodec()`:

```java
public void setCodec(Codec codec) {
    assert channel.eventLoop().inEventLoop();
    if (configuration.version() == ProtocolVersion.PROTOCOL_VERSION_AUTO) {
        if (codec == null) {        // <-- should be != null
            this.codec = codec;
        }
        channel.attr(OperationChannel.OPERATION_CHANNEL_ATTRIBUTE_KEY).get().setCodec(codec);
    }
}
```

During the handshake, the PING is sent using the safe handshake codec (3.1) because `Codec41.isUnsafeForTheHandshake() == true`. When the PING response comes back, `NoCachePingOperation.createResponse()` calls `decoder.setCodec(Codec41)` to negotiate up to 4.1. However, the inverted `if (codec == null)` check prevents `HeaderDecoder.codec` from being updated, so it stays at 3.1.

## Steps to Reproduce

1. Use Hot Rod client 16.x with default configuration (no explicit `protocol_version`)
2. Connect to the server
3. Perform any cache operation
4. Observe in server console that the connection shows HOTROD/3.1 instead of HOTROD/4.1

## Expected Behavior

After the PING handshake negotiation, the connection should use HOTROD/4.1 (the latest protocol version).

## Affected Components

- `client/hotrod-client/.../transport/netty/HeaderDecoder.java`

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes: #17218

Fix inverted null-check (`== null` → `!= null`) in `HeaderDecoder.setCodec()` that prevented the codec from being updated after PING handshake negotiation. The bug caused the `HeaderDecoder` to remain on the safe handshake protocol version (3.1) instead of upgrading to the server's negotiated version (4.1).

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [ ] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.
  - No documentation changes required: this is a one-character bugfix in internal client code.
- [ ] Log messages of level `INFO` and above have been internationalized.
  - N/A: no new log messages.
- [ ] If the PR affects performance, include before/after benchmarks.
  - N/A.
- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).
  - N/A.
- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.
  - N/A.

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/ProtocolNegotiationTest.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+            headerDecoder.setCodec(negotiatedCodec);
+            future.complete(null);
+         } catch (Throwable t) {
+            future.completeExceptionally(t);
+         }
+      });
+      future.join();
+
+      // Verify the HeaderDecoder codec was updated to Codec41
+      Object codec = TestingUtil.extractField(headerDecoder, "codec");
```
Comment (wburns) [inline client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/ProtocolNegotiationTest.java:92]: Honestly, the rest of the code seems superfluous. But I would expect just a connect to a HR server and then assert the codec maps to PROTOCOL_VERSION_AUTO. But I am fine with this way as well.

**Comment by wburns** [comment]
Integrated into main, thanks @tristantarrant !

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java [hunk 2]
```diff
@@ -392,7 +392,7 @@ public void setCodec(Codec codec) {
       assert channel.eventLoop().inEventLoop();
       if (configuration.version() == ProtocolVersion.PROTOCOL_VERSION_AUTO) {
          // Here for the purpose of tests to override explicitly as needed
-         if (codec == null) {
+         if (codec != null) {
```
Comment (wburns) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:395]: Actually.. the more I thought about it.. this fix isn't what was originally what this was intended for.
It should have been `if (this.codec == null) {` so that it only sets the codec if it wasn't set.
