### PR TITLE
[#16815] Fix flaky HotRodAuthAccessLoggingTest access log ordering

### LINKED ISSUE #16815: Flaky test: org.infinispan.server.hotrod.logging.HotRodAuthAccessLoggingTest#testHotRodAccessLog
### Github Job:https://github.com/infinispan/infinispan/actions/runs/22309026140
java.lang.AssertionError: 
Expecting map:
  {&amp;quot;CLIENT&amp;quot;=&amp;quot;&amp;quot;, &amp;quot;IP&amp;quot;=&amp;quot;127.0.0.1&amp;quot;, &amp;quot;METHOD&amp;quot;=&amp;quot;PUT&amp;quot;, &amp;quot;PATH&amp;quot;=&amp;quot;/default/[B0x77726F6E672D6B302D74657374486F74..[28]&amp;quot;, &amp;quot;PROTOCOL&amp;quot;=&amp;quot;HOTROD/2.1&amp;quot;, &amp;quot;STATUS&amp;quot;=&amp;quot;&amp;quot;ISPN006017: Operation &amp;apos;PUT&amp;apos; requires authentication&amp;quot;&amp;quot;, &amp;quot;WHEN&amp;quot;=&amp;quot;[23/Feb/2026:14:16:25 +0000]&amp;quot;, &amp;quot;WHO&amp;quot;=&amp;quot;-&amp;quot;}
to contain entries:
  [&amp;quot;STATUS&amp;quot;=&amp;quot;&amp;quot;Authentication failure&amp;quot;&amp;quot;,
    &amp;quot;PROTOCOL&amp;quot;=&amp;quot;HOTROD/2.1&amp;quot;,
    &amp;quot;METHOD&amp;quot;=&amp;quot;AUTH&amp;quot;,
    &amp;quot;IP&amp;quot;=&amp;quot;127.0.0.1&amp;quot;,
    &amp;quot;WHO&amp;quot;=&amp;quot;-&amp;quot;]
but the following map entries had different values:
  [&amp;quot;STATUS&amp;quot;=&amp;quot;&amp;quot;ISPN006017: Operation &amp;apos;PUT&amp;apos; requires authentication&amp;quot;&amp;quot; (expected: &amp;quot;&amp;quot;Authentication failure&amp;quot;&amp;quot;), &amp;quot;METHOD&amp;quot;=&amp;quot;PUT&amp;quot; (expected: &amp;quot;AUTH&amp;quot;)]
	at org.infinispan.server.hotrod.logging.HotRodAuthAccessLoggingTest.testHotRodAccessLog(HotRodAuthAccessLoggingTest.java:92)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.testing.testng.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #16815

### CODE REVIEW

File: server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAuthAccessLoggingTest.java [hunk 1]
```diff
@@ -89,9 +90,15 @@ public void testHotRodAccessLog() throws SaslException {
       // Initial client PING
       assertThat(parseAccessLog(i++)).containsAllEntriesOf(Map.of("IP", "127.0.0.1", "PROTOCOL", "HOTROD/2.1", "METHOD", "PING", "STATUS", "OK", "WHO", "-"));
       // Failed authentication with wrong password
-      assertThat(parseAccessLog(i++)).containsAllEntriesOf(Map.of("IP", "127.0.0.1", "PROTOCOL", "HOTROD/2.1", "METHOD", "AUTH", "STATUS", "\"Authentication failure\"", "WHO", "-"));
-      assertThat(parseAccessLog(i++)).containsAllEntriesOf(Map.of("IP", "127.0.0.1", "PROTOCOL", "HOTROD/2.1", "METHOD", "PUT", "STATUS", "\"ISPN006017: Operation 'PUT' requires authentication\"", "WHO", "-"));
-      assertThat(parseAccessLog(i++)).containsAllEntriesOf(Map.of("IP", "127.0.0.1", "PROTOCOL", "HOTROD/2.1", "METHOD", "GET", "STATUS", "\"ISPN006017: Operation 'GET' requires authentication\"", "WHO", "-"));
+      // AUTH failure is processed on the executor while PUT/GET are processed on the event loop,
+      // so log entries for these operations can appear in any order
```
Comment (jabolina) [inline server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAuthAccessLoggingTest.java:94]: Tricky. Should we change it? Otherwise, the access log might look confusing.

Comment (tristantarrant) [reply server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAuthAccessLoggingTest.java:94]: I don't think it's a problem. You won't be seeing failed auth connections suddenly performing other ops :)

**Comment by jabolina** [comment]
Thanks, @tristantarrant!
