### PR TITLE
[#16053] Shared container eviction

### LINKED ISSUE #16053: Shared container eviction
### Description

It is sometimes desirable to set a global bound that covers the entire container:

```xml
<cache-container>
    <!-- All caches combined will have to respect this bound -->
    <memory max-size="1.5GB" when-full="REMOVE"/>
    <caches>
        ...
    </caches>
</cache-container>
```

### Implementation ideas

_No response_

### LINKED ISSUE #16203: InternalEntryFactoryImpl.update throws NPE if a null metadata is provided
### Describe the bug

The InternalEntryFactoryImpl.update method specifically checks for a null metadata but then references metadata later which can cause an unexpected NPE. In the case where metadata is null we should assume lifespan and maxIdle are both -1.

Null checks at https://github.com/infinispan/infinispan/blob/b370c83b6cc721da69d1a44e468cc12c39246395/core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java#L182 and https://github.com/infinispan/infinispan/blob/b370c83b6cc721da69d1a44e468cc12c39246395/core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java#L326 but then referenced at https://github.com/infinispan/infinispan/blob/b370c83b6cc721da69d1a44e468cc12c39246395/core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java#L171

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### LINKED ISSUE #16331: DummyInMemoryStore doesn't approximateSize IndexOutOutBoundsException when not segmented
### Describe the bug

The DummyInMemoryStore approximateSize method doesn't work when the store is not segmented. As mentioned in the SPI when segmented the passed in segments will always be all segments if the cache has any. The DummyInMemoryStore stores all of its data in a single array. However it attemps to reference an array for each segment, but obviously they don't exist. Instead it should start with the array and only use the map if the segment is in the passed IntSet.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by wburns**
Fixes #16053
Fixes #16203
Fixes #16331 

Still need to do the following:

- [x] Parser support and tests
- [x] Documentation
- [x] Tweak the size calculation to also take into account storing the KeyValuePair and String cacheName (note cacheName is shared so it is only the object reference for each object)
- [x] Need to also investigate if passivation can be used or not...
- [x] Allow for runtime update of the eviction container size/count. - Need to discuss this as it is global ~~Do we also support adding new eviction containers?~~ This needs https://github.com/infinispan/infinispan/issues/16323 to be implemented first.
- [x] Need to update documentation to mention that container cannot be resized yet
- [x] Add IT ~~/Rolling upgrade~~ tests of adding a cache at runtime/ensure eviction works.

### CODE REVIEW

**Comment by wburns** [comment]
This should be ready for review now 🎉

File: core/src/main/java/org/infinispan/configuration/global/ContainerMemoryConfigurationBuilder.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
+package org.infinispan.configuration.global;
+
+import org.infinispan.commons.configuration.Builder;
+import org.infinispan.commons.configuration.Combine;
+import org.infinispan.commons.configuration.attributes.AttributeSet;
+
+/**
+ * Configures container memory.
+ */
+public class ContainerMemoryConfigurationBuilder extends AbstractGlobalConfigurationBuilder implements Builder<ContainerMemoryConfiguration> {
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/configuration/global/ContainerMemoryConfigurationBuilder.java:16]: This class needs javadocs, since it is public API

File: core/src/main/java/org/infinispan/configuration/global/GlobalConfiguration.java [hunk 2]
```diff
@@ -162,6 +162,15 @@ public boolean isZeroCapacityNode() {
       return cacheContainerConfiguration.getZeroCapacityNode();
    }
 
+   /**
+    *
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/configuration/global/GlobalConfiguration.java]: javadoc

File: core/src/main/resources/schema/infinispan-config-16.1.xsd [hunk 3]
```diff
@@ -324,6 +324,24 @@
           <xs:documentation>Defines the global state persistence configuration. If this element is not present, global state persistence will be disabled.</xs:documentation>
         </xs:annotation>
       </xs:element>
+      <xs:element name="eviction-containers" minOccurs="0">
+        <xs:complexType>
```
Comment (tristantarrant) [inline core/src/main/resources/schema/infinispan-config-16.1.xsd:336]: Please add `<xs:documentation>` everywhere.

File: core/src/main/java/org/infinispan/util/logging/Log.java [hunk 4]
```diff
@@ -2431,4 +2431,13 @@ CacheConfigurationException storeConfiguredHasBothReadAndWriteOnly(String storeC
    @LogMessage(level = WARN)
    @Message(value = "Fallback to %s as required dependencies are not available", id = 714)
    void warnFallbackToNoOpMetrics(String clazz);
+
+   @Message(value = "Memory configuration uses a shared container cannot have individual eviction settings", id = 715)
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/util/logging/Log.java]: `s/uses/using/` on all three messages

File: core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationChildBuilder.java [hunk 5]
```diff
@@ -102,6 +103,14 @@ public interface GlobalConfigurationChildBuilder {
     */
    GlobalConfigurationBuilder defaultCacheName(String defaultCacheName);
 
+   /**
+    *
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationChildBuilder.java:109]: javdoc

File: documentation/src/main/asciidoc/topics/proc_configuring_container_eviction.adoc [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+Configure container eviction to set a limit for the memory usage of the entire container (node), rather than for individual caches.
+{brandname} supports both size-based (`max-size-container`) and count-based (`max-count-container`) eviction containers. You can also define multiple eviction containers as needed.
+This simplifies configuration as you only need to know the limit for the node.
+Note that this setting is not cluster-wide; it applies only to the local node.
+
+.Drawbacks of shared eviction
+All caches using the shared eviction container share the same eviction policy.
+This means that data from one cache can evict data from another cache, which might not be desirable.
+If you need strict control over the memory usage of a specific cache, use per-cache eviction instead.
+Runtime updates of the shared eviction container are not yet supported, but should be coming soon.
```
Comment (tristantarrant) [inline documentation/src/main/asciidoc/topics/proc_configuring_container_eviction.adoc]: Remove the "but should be coming soon". It's implied by the "not yet".

File: core/src/main/java/org/infinispan/factories/DataContainerFactory.java [hunk 7]
```diff
@@ -32,23 +36,34 @@
...
       MemoryConfiguration memoryConfiguration = configuration.memory();
       boolean offHeap = memoryConfiguration.isOffHeap();
 
+      String containerMapName = memoryConfiguration.evictionContainer();
+      int segments = shouldSegment ? clusteringConfiguration.hash().numSegments() : 1;
+      if (containerMapName != null) {
+         String cacheName = componentRegistry.getCacheName();
+         SharedCaffeineMap<?, ?> sharedCaffeineMap = sharedContainerMaps.getMap(containerMapName);
+         if (sharedCaffeineMap == null) {
+            throw new IllegalStateException("Shared container not available: " + containerMapName);
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/factories/DataContainerFactory.java]: This should be a log with its own id

File: commons/all/src/main/java/org/infinispan/commons/util/KeyMapperMap.java [hunk 8]
```diff
@@ -0,0 +1,141 @@
...
+   @Override
+   public Set<Entry<R, V>> entrySet() {
+      return new SetMapper<>(delegate.entrySet(), e -> new AbstractMap.SimpleEntry<>(keyMapper.apply(e.getKey()), e.getValue()));
+   }
+
+   @Override
+   public void putAll(Map<? extends R, ? extends V> m) {
+      Map<R, V> providedMap = (Map) m;
+      Map<? extends K, ? extends V> map = new KeyMapperMap<>(providedMap, keyUnmapper, keyMapper);
+      delegate.putAll(map);
```
Comment (jabolina) [inline commons/all/src/main/java/org/infinispan/commons/util/KeyMapperMap.java:101]: Nice

File: core/src/main/java/org/infinispan/configuration/cache/MemoryConfigurationBuilder.java [hunk 9]
```diff
@@ -121,6 +137,14 @@ public void validate() {
       if (isSizeBounded() && isCountBounded()) {
          throw CONFIG.cannotProvideBothSizeAndCount();
       }
+      if (evictionContainer() != null) {
+         if (isCountBounded() || isCountBounded()) {
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/cache/MemoryConfigurationBuilder.java]: Should one of them be `isSizeBounded`?

File: core/src/main/java/org/infinispan/configuration/global/CacheContainerConfigurationBuilder.java [hunk 10]
```diff
@@ -149,6 +155,18 @@ public ShutdownConfigurationBuilder shutdown() {
       return shutdown;
    }
 
+   @Override
+   public GlobalConfigurationBuilder containerMemoryConfiguration(String namedMemoryConfig, Consumer<? super ContainerMemoryConfigurationBuilder> consumer) {
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/global/CacheContainerConfigurationBuilder.java]: Using the Consumer lambda seems like a different approach utilized in other builders. Just for consistency, should this method return `ContainerMemoryConfigurationBuilder` instead and the calls are chained?

```java
...
      .containerMemoryConfiguration("container-a")
            ...
      .containerMemoryConfiguration("container-b")
            ...
```

Something like this.

File: core/src/main/java/org/infinispan/configuration/global/ContainerMemoryConfiguration.java [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+    * @return the max number of entries in memory or -1 if not configured.
+    */
+   public long maxCount() {
+      return attributes.attribute(MAX_COUNT).get();
+   }
+
+   public void maxCount(long maxCount) {
+      if (!isCountBounded()) throw CONFIG.cannotChangeMaxCount();
+      attributes.attribute(MAX_COUNT).set(maxCount);
+   }
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/global/ContainerMemoryConfiguration.java:62]: Changing the attribute values maxCount and maxSize, shouldn't they be in the builder class instead?

Comment (jabolina) [reply core/src/main/java/org/infinispan/configuration/global/ContainerMemoryConfiguration.java:62]: If moving to the Builder class, after the user changes the maxCount, they can not change it again? Even during the build/configuration of the node?

File: core/src/main/java/org/infinispan/configuration/parsing/Element.java [hunk 12]
```diff
@@ -136,6 +139,7 @@ public enum Element {
     THREAD_FACTORIES,
     THREAD_FACTORY,
     THREAD_POOLS,
+    THRESHOLD,
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/parsing/Element.java]: Seems unused.

File: core/src/test/java/org/infinispan/configuration/ContainerMemoryConfigurationTest.java [hunk 13]
```diff
@@ -0,0 +1,72 @@
...
+import org.infinispan.configuration.global.GlobalConfiguration;
+import org.infinispan.configuration.global.GlobalConfigurationBuilder;
+import org.infinispan.test.AbstractInfinispanTest;
+import org.testng.annotations.Test;
+
+/**
+ * Test for different scenarios of container memory configuration.
+ */
+@Test(groups = "unit", testName = "configuration.ContainerMemoryConfigurationTest")
+public class ContainerMemoryConfigurationTest extends AbstractInfinispanTest {
```
Comment (jabolina) [inline core/src/test/java/org/infinispan/configuration/ContainerMemoryConfigurationTest.java:19]: Maybe some tests that assert not possible to mix max-count and max-size?

File: documentation/src/main/asciidoc/stories/assembly_configuring_data_container.adoc [hunk 14]
```diff
@@ -8,6 +8,9 @@ Control how {brandname} stores data in JVM memory by:
 * Adding lifespan and maximum idle times to expire entries and prevent stale data.
 * Configuring {brandname} to store data in off-heap, native memory.
 
+//Configuring Container Eviction
+include::{topics}/proc_configuring_container_eviction.adoc[leveloffset=+1]
```
Comment (jabolina) [inline documentation/src/main/asciidoc/stories/assembly_configuring_data_container.adoc]: Should it be included after the overview? Just thinking if it would be better to have some context first.

File: core/src/main/java/org/infinispan/configuration/global/CacheContainerConfigurationBuilder.java (hunk 10 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/configuration/global/CacheContainerConfigurationBuilder.java]: We don't have any other places where we are using a Map based configuration in such a manner, so I was trying something out. I believe I tried the way you suggested, but let me take another try at it.

File: core/src/main/java/org/infinispan/configuration/global/ContainerMemoryConfiguration.java (hunk 11 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/configuration/global/ContainerMemoryConfiguration.java:62]: No, these methods are for when we support runtime changing of the maxCount and maxSize. It isn't currently implemented as we have no way to support global configuration changes at runtime yet.

File: documentation/src/main/asciidoc/stories/assembly_configuring_data_container.adoc (hunk 14 above)
Comment (wburns) [reply documentation/src/main/asciidoc/stories/assembly_configuring_data_container.adoc]: Agreed

**Comment by wburns** [comment]
Updated with review comments, except the config builder change, will I add next.

**Comment by wburns** [comment]
Pushed with the config builder change as well. The last commit needs to be squashed before merging.

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by wburns** [comment]
The underlying cache has a key that is composite of the key and the cache
name. So duplicates can't happen.
