### PR TITLE
[#15709] Fix flaky ClusterTopologyManagerTest

### LINKED ISSUE #15709: Flaky test: org.infinispan.statetransfer.ClusterTopologyManagerTest#testClusterRecoveryAfterThreeWaySplit\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/18020329760
java.lang.AssertionError: Merge took too long: 39.81 seconds
	at org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryAfterThreeWaySplit(ClusterTopologyManagerTest.java:195)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

org.infinispan.commons.TimeoutException: Timed out before caches had complete views.  Expected 4 members in each view.  Views are as follows: [[ClusterTopologyManagerTest-NodeA(v=16.0.0)|4] (2) [ClusterTopologyManagerTest-NodeA(v=16.0.0), ClusterTopologyManagerTest-NodeD(v=16.0.0)], [ClusterTopologyManagerTest-NodeB(v=16.0.0)|3] (1) [ClusterTopologyManagerTest-NodeB(v=16.0.0)], [ClusterTopologyManagerTest-NodeC(v=16.0.0)|4] (2) [ClusterTopologyManagerTest-NodeC(v=16.0.0), ClusterTopologyManagerTest-NodeD(v=16.0.0)], [ClusterTopologyManagerTest-NodeA(v=16.0.0)|4] (2) [ClusterTopologyManagerTest-NodeA(v=16.0.0), ClusterTopologyManagerTest-NodeD(v=16.0.0)]]
	at org.infinispan.test.TestingUtil.viewsTimedOut(TestingUtil.java:583)
	at org.infinispan.test.TestingUtil.blockUntilViewsReceived(TestingUtil.java:644)
	at org.infinispan.test.TestingUtil.blockUntilViewsReceived(TestingUtil.java:619)
	at org.infinispan.test.TestingUtil.blockUntilViewsReceived(TestingUtil.java:1154)
	at org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryWithRebalance(ClusterTopologyManagerTest.java:304)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### LINKED ISSUE #15754: Flaky test: org.infinispan.statetransfer.ClusterTopologyManagerTest#testClusterRecoveryWithRebalance
### Github Job:https://github.com/infinispan/infinispan/actions/runs/18169155979
java.lang.AssertionError: Merge took too long: 30.81 seconds
	at org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryWithRebalance(ClusterTopologyManagerTest.java:317)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### LINKED ISSUE #15894: Flaky test: org.infinispan.statetransfer.ClusterTopologyManagerTest#testClusterRecoveryAfterSplitAndCoordLeave\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/18557504251
org.infinispan.commons.TimeoutException: Timed out before caches had complete views.  Expected 2 members in each view.  Views are as follows: [[ClusterTopologyManagerTest-NodeB(v=16.0.0)|3] (1) [ClusterTopologyManagerTest-NodeB(v=16.0.0)], [ClusterTopologyManagerTest-NodeC(v=16.0.0)|3] (1) [ClusterTopologyManagerTest-NodeC(v=16.0.0)]]
	at org.infinispan.test.TestingUtil.viewsTimedOut(TestingUtil.java:583)
	at org.infinispan.test.TestingUtil.viewsTimedOut(TestingUtil.java:569)
	at org.infinispan.test.TestingUtil.blockUntilViewsReceived(TestingUtil.java:561)
	at org.infinispan.test.TestingUtil.blockUntilViewsReceived(TestingUtil.java:605)
	at org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryAfterSplitAndCoordLeave(ClusterTopologyManagerTest.java:234)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### PR DESCRIPTION
**Pull request by jabolina**
* Do not rely on MERGE3 to install the view. Deterministically install the view instead.

The idea is to verify the topology handling on the Infinispan side. So, instead of relying on the time-based approach to identify the merges in JGroups, we just push the views.

Close #15709
Close #15754 
Close #15894

### CODE REVIEW

File: core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java [hunk 1]
```diff
@@ -184,6 +184,7 @@ public void testClusterRecoveryAfterThreeWaySplit() {
       d1.discardAll(false);
       d2.discardAll(false);
       d3.discardAll(false);
+      TestingUtil.installNewView(manager(0), manager(1), manager(2));
```
Comment (wburns) [inline core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java]:
```suggestion
      TestingUtil.installNewView(managers());
```
That or change the other below to be each manager. WDYT @jabolina ?

**Review by wburns — APPROVED** [review]
Just a minor nitpick

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
