### PR TITLE
[#15272] Add RollingUpgrade support for XSite integration tests

### LINKED ISSUE #15272: Add RollingUpgrade support for XSite integration tests
### Description

We need to add a new RollingUpgradeXSiteExtension that is similar to the current RollingUpgradeExtension but it creates an xsite configuration where each site has at least 2 nodes.

This should be done in a way to reuse the existing XSiteIT class and the InfinispanXSiteServerExtension class.

### Implementation ideas

_No response_

### LINKED ISSUE #15340: XSite max_site_masters not working in 16.0
### Describe the bug

The recent changes to handle Address optimizations have broken max site masters for xsite only allowing the coordinator to be a site master. This should resolvable by always forcing address tagging for RELAY to be enabled.

Please see more discussion at https://infinispan.zulipchat.com/#narrow/channel/118645-infinispan/topic/xsite/with/529917868

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
Fixes #15272
Fixes #15340

The extension currently starts up the nodes in each configured site and migrates one server on each site. While this is not how a user would normally do this, I figured it was more strict having a "mixed" cluster for each site to catch various issues.

### CODE REVIEW

**Comment by wburns** [comment]
This PR requires the fixes in https://github.com/infinispan/infinispan/pull/15186 to work with multiple ITs concurrently.

Also changing the XSiteIT test to have 2 nodes per site breaks a couple tests related to the CLI that I still need to investigate.

**Comment by wburns** [comment]
Updated, tests should pass if each node in the cluster would become a site master. Note this change also makes the base XSiteIT fail as it doesn't work there either.

**Comment by wburns** [comment]
Fixed an issue where the container was being reused between the sites. Tests should pass now.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeXSiteHandler.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+      return new RollingUpgradeXSiteHandler(siteHandlers);
+   }
+
+   public RollingUpgradeHandler handlerForSite(String siteName) {
+      return sites.get(siteName);
+   }
+
+   public void completeUpgrade(boolean shouldClose) {
+      try {
+         sites.forEach((siteName, ruh) -> ruh.completeUpgrade(false));
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeXSiteHandler.java]: What does it happen if the sites complete with close?

File: server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java [hunk 2]
```diff
@@ -122,7 +122,13 @@ public void testMetricExists() {
...
 
       //noinspection resource
-      RestClient client = SERVERS.rest(LON).withServerConfiguration(new StringConfiguration(lonXML)).create();
+
+      RestClient client;
+      try {
+         client = SERVERS.rest(LON).withServerConfiguration(new StringConfiguration(lonXML)).create();
+      } catch (Throwable t) {
+         throw t;
+      }
```
Comment (jabolina) [inline server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java]: I guess we can revert this?

File: server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml [hunk 3]
```diff
@@ -55,7 +55,7 @@
       <FD_SOCK2 connect_timeout="3000"/>
       <FD_ALL3 timeout="3000"
                interval="1000"/>
-      <relay.RELAY2 site="${relay.site_name}" max_site_masters="3" xmlns="urn:org:jgroups"/>
+      <relay.RELAY2 site="${relay.site_name}" max_site_masters="100" xmlns="urn:org:jgroups"/>
```
Comment (jabolina) [inline server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml]: Is this still needed with the change in the `EmbeddedJGroupsChannelConfiguration`?

Comment (wburns) [reply server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml]: It may not as the cluster is only 2 members. I can try reverting.

File: server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java (hunk 2 above)
Comment (wburns) [reply server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java]: Yeah, I think I used it for a break point at one point and forgot to revert.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeXSiteHandler.java (hunk 1 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeXSiteHandler.java]: It doesn't stop the "new" cluster and the images are still present. I might be able to remove this now though.

Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeXSiteHandler.java]: Actually, we have this in the RollingUpgradeHandler, so I will keep for symmetry for now.

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @wburns!
