### PR TITLE
[#16034] Virtual threads cause extra allocations for netty responses

### LINKED ISSUE #16034: Virtual threads cause extra allocations for netty responses
### Describe the bug

When a netty request is completed asynchronously this can be done via a JGroups thread much of the time. When this happens this will be a virtual thread now by default. Unfortunately, that means if the response is created in the virtual thread it will allocate additional objects due to netty's use of thread local for its pooling. We should be able to whenever an asynchronous invocation is performed perform the response handling on the event loop from the original request to avoid these extra costs.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
Fixes #16034 

I started down the rabbit hole of fixing every place. But that requires a lot more work as the transaction processor response handling is intertwined in the actual processing logic. And the stats method is directly tied as well, so I stopped with what I had here.

For the benchmark [put isolated](https://github.com/infinispan/infinispan-benchmarks/blob/b8f395013e83c0ec7f5e1153336168b8410afd5c/getputremovetest/src/main/java/org/infinispan/JMHBenchmarks.java#L28) I got just under a 2% increase in throughput due to the reduction in allocations, despite being thread local only.

NEW: 11050.22867 vs MAIN: 10836.26933 average throughput

### CODE REVIEW

File: server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java [hunk 1]
```diff
@@ -161,26 +163,39 @@ public ByteBuf errorResponse(HotRodHeader header, HotRodServer server, Channel c
...
+         flowable = flowable.take(size);
+      } else {
+         flowable = flowable.take(Integer.MAX_VALUE);
       }
-      return buf;
+      return flowable.collectInto(buf, (innerB, i) -> {
+               buf.writeByte(1);
+               consumer.accept(i, buf);
+            }).doOnSuccess(innerB -> innerB.writeByte(0))
+            .toCompletionStage();
```
Comment (jabolina) [inline server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java:180]: Does this run on the event loop?

**Review by jabolina — COMMENTED** [review]
Nice finding! I take that operations that manage to complete locally aren't much affected by this?

The RESP connector should be good, but wondering whether this can apply to Memcached, too. I guess it is likely that it is already only writing in the event loop.

File: server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java (hunk 1 above)
Comment (wburns) [reply server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java:180]: Currently, no. The initial ByteBuf alloc call above though does. Honestly, I had debated about undoing all the changes to the bulk methods as they aren't really used anymore.

I only converted them as I was going to convert every method (as I was detecting non compliance in the https://github.com/infinispan/infinispan/blob/main/server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseRequestProcessor.java#L154 and https://github.com/infinispan/infinispan/blob/main/server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseRequestProcessor.java#L53 methods), but maybe I should revert... I am not sure.

**Comment by wburns** [comment]
> Nice finding! I take that operations that manage to complete locally aren't much affected by this?
> 
> The RESP connector should be good, but wondering whether this can apply to Memcached, too. I guess it is likely that it is already only writing in the event loop.

Correct, which is why in my testing I only was testing the isolated put since get would never hit the new code path as the tests have a stable topology so every get will always complete on the same calling thread.

File: server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java (hunk 1 above)
Comment (wburns) [reply server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java:180]: I think we can just leave it how I have it now. I would really like to revisit all the server processors to ensure that we only create the ByteBuf on the netty threads eventually. By default the netty Recycler class does not do any pooling of io buffers when in a virtual thread as can be seen from the Recycler code here:

```java
   public final T get() {
        if (localPool != null) {
            return localPool.getWith(this);
        } else {
            if (PlatformDependent.isVirtualThread(Thread.currentThread()) &&
                !FastThreadLocalThread.currentThreadHasFastThreadLocal()) {
                return newObject((Handle<T>) NOOP_HANDLE);
            }
            return threadLocalPool.get().getWith(this);
        }
    }
```

**Comment by wburns** [comment]
> The RESP connector should be good, but wondering whether this can apply to Memcached, too. I guess it is likely that it is already only writing in the event loop.

Yeah, I double checked and `handler.stageToReturn` already ensures writes are done on the event loop, so they already have this optimization. There could be an exception here or there, but the main methods seem all good.

It also seems memcached is good as well https://github.com/infinispan/infinispan/blob/main/server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedInboundAdapter.java#L182
