### PR TITLE
[#16447] Fix iteration in replicated zero-capacity nodes

### LINKED ISSUE #16447: Replicated cache in zero capacity nodes return incorrect results
### Describe the bug

A replicated cache in a zero-capacity node returns incorrect results for some operations. I was able to verify operations that iterate in the cache contents (entries, keys, size) will always return empty, since the node is zero-capacity. Keyed operations, like gets, will correctly redirect the request and return the expected values.

This behavior affects operations like backup/restore with the operator and likely HR rolling upgrades of replicated caches. Anything that relies on iterating in the cache through a zero-capacity node.

### Expected behavior

The zero-capacity node would redirect all the requests to the other nodes. This already happens to single-key operations.

### Actual behavior

The node does not verify if it is a zero-capacity node and only uses the local values of the replicated cache.

### How to Reproduce?

1. Start two nodes. The first one has the default configuration, and the second one is a zero-capacity node. They bind to 11222 and 11232, respectively.
2. Create a replicated cache.
3. Insert a few entries through the first node (`curl --digest -u "admin:password" 'http://localhost:11222/rest/v2/caches/repl-c/k1' -X PUT -d 'value' -H 'Content-Type: text/plain'`)
4. Submit operations that iterate the caches through the second node (`curl --digest -u "admin:password" 'http://localhost:11232/rest/v2/caches/repl-c?action=size'`)
5. The response of step 4. is incorrect.

### PR DESCRIPTION
**Pull request by jabolina**
* Do not optimize replicated caches for zero-capacity nodes.

Closes #16447.

### CODE REVIEW

**Comment by ryanemerson** [comment]
Thanks for the quick fix @jabolina

File: core/src/test/java/org/infinispan/stream/ReplicatedStreamIteratorTest.java [hunk 1]
```diff
@@ -22,4 +33,45 @@ public ReplicatedStreamIteratorTest() {
...
+   @Override
+   protected void afterCacheCreated(ConfigurationBuilder builder) {
+      GlobalConfigurationBuilder global = defaultGlobalConfigurationBuilder();
+      global.zeroCapacityNode(true);
+      global.serialization().addContextInitializer(sci);
+      createClusteredCaches(1, global, builder, false, new TransportFlags().withFD(true), CACHE_NAME);
+   }
+
+   public void testIterateFromZeroCapacityNode() {
+      Cache<MagicKey, String> cacheZero = cache(getZeroCapacityIndex(), CACHE_NAME);
```
Comment (wburns) [inline core/src/test/java/org/infinispan/stream/ReplicatedStreamIteratorTest.java:47]: This all looks good. Maybe we can also add a simple iteration where we use CACHE_MODE_LOCAL flag on the zero capacity node to verify it comes back with nothing?

Comment (jabolina) [reply core/src/test/java/org/infinispan/stream/ReplicatedStreamIteratorTest.java:47]: Sounds good, let me update it.

File: core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java [hunk 2]
```diff
@@ -141,7 +143,8 @@ private SizeComposedType sizeComposedType() {
    @Start
    public void start() {
       maxSegment = cacheConfiguration.clustering().hash().numSegments();
-      replicatedCache = cacheConfiguration.clustering().cacheMode().isReplicated();
+      // Only optimize for replicated caches when the node is not zero capacity.
+      replicatedCache = cacheConfiguration.clustering().cacheMode().isReplicated() && !nodeConfiguration.isZeroCapacityNode();
```
Comment (pruivo) [inline core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java:147]: @jabolina don't we need to check that `capacity-factor < 1` (if it works with replicated cache)?
With `capacity-factor < 1`, a node may not have all the segments either.

Comment (pruivo) [reply core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java:147]: PS. It looks like replicated caches only accept 0 or 1. We cannot optimize when `capacity-factor=0`
https://github.com/infinispan/infinispan/blob/e283b386db31ef0c6557ef6177af00fa14dbdcaa/core/src/main/java/org/infinispan/distribution/ch/impl/SyncReplicatedConsistentHashFactory.java#L101-L103

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !

File: core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java (hunk 2 above)
Comment (pruivo) [reply core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java:147]: @jabolina looks like this comment was forgotten :)
