### PR TITLE
[#15897] Client can cause disconnect with getCache called in a tight …

### LINKED ISSUE #15897: Client can cause disconnect with getCache called in a tight loop
### Describe the bug

Discussed here: [#infinispan > hot rod client @ 💬](https://infinispan.zulipchat.com/#narrow/channel/118645-infinispan/topic/hot.20rod.20client/near/545350251)

We should be able to fix the tight loop with the if change. However, two concurrent getCache calls may need some additional thought.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
…loop

Fixes #15897

This reworks submission a bit so that before submitting an operation we optimistically "acquire" the read lock. Then after task submission if the "acquire" didn't work we double check the channel we submitted to to see if it still is the same or not. If not we have to resubmit the task so it can be ran on a new channel.

Also on a channel disconnect we can only close a ChannelHandler if the existing one matches the same one. Otherwise it could close a ChannelHandler tied to a different socket.

### CODE REVIEW

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java [hunk 1]
```diff
@@ -311,11 +312,51 @@ public <E> CompletionStage<E> executeOnSingleAddress(HotRodOperation<E> operatio
...
+      if (!lock.validate(stamp)) {
+         // Note we don't need to acquire the read lock as channelHandler#getChannelForAddress is thread safe. The
+         // callers would would acquire the write lock will try to shut down operations, so all we have to do is
+         // check our own operation only if it is present or not in the queue.
+         handleChannelChangePossibility(operation, socketAddress, operationChannel);
+      }
+      return operation.asCompletableFuture();
+   }
+
+   private void handleChannelChangePossibility(HotRodOperation<?> operation, SocketAddress socketAddress,
```
Comment (pruivo) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java:328]: The `gracefulCloseChannel(SocketAddress server)` method resends the operation again. Is this method still required?

**Comment by pruivo** [comment]
Tested manually with the Keycloak testsuite -> run in a loop for 3h without a single failure :+1:

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java (hunk 1 above)
Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java:328]: Yes. Unfortunately, `gracefulCloseChannel` can be invoked after we call `channelHandler.getOrCreateChannelForAddress` but before we call `operationChannel.sendOperation` and thus `gracefulCloseChannel` wouldn't have seen the operation. So this method is here just in case to resubmit itself if necessary.

Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java:328]: The fact that `gracefulCloseChannel` is only invoked while holding the write lock means this window is extremely extremely rare, since the method to find the target address acquires the read lock if necessary.
