### PR TITLE
[#14441] Reintroduce cache instance variable

### LINKED ISSUE #14441: Shutting down server logs exception
### Describe the bug

While shutting down a server with Ctrl-C, the following exception is logged.

```
2025-03-25 10:52:26,619 INFO  [o.i.SERVER] ISPN080001: Infinispan Server 15.2.0-SNAPSHOT started in 3380ms
^C2025-03-25 10:56:40,359 INFO  [o.i.SERVER] ISPN080002: Infinispan Server stopping
*** Server process (164424) received INT signal ***
2025-03-25 10:56:40,473 ERROR [o.i.f.ComponentRegistry] ISPN000538: Error stopping module org.infinispan.query.impl.LifecycleManager:___event_log_cache org.infinispan.commons.IllegalLifecycleStateException: Cache container has been stopped and cannot be reused. Recreate the cache container.
    at org.infinispan.manager.DefaultCacheManager.assertIsNotTerminated(DefaultCacheManager.java:1185)
    at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:526)
    at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:519)
    at org.infinispan.query.core.impl.QueryCache.getCache(QueryCache.java:80)
    at org.infinispan.query.core.impl.QueryCache.clear(QueryCache.java:76)
    at org.infinispan.query.impl.LifecycleManager.cacheStopped(LifecycleManager.java:422)
    at org.infinispan.factories.ComponentRegistry.postStop(ComponentRegistry.java:298)
    at org.infinispan.factories.AbstractComponentRegistry.stop(AbstractComponentRegistry.java:317)
    at org.infinispan.cache.impl.CacheImpl.performImmediateShutdown(CacheImpl.java:1091)
    at org.infinispan.cache.impl.CacheImpl.stop(CacheImpl.java:1058)
    at org.infinispan.cache.impl.AbstractDelegatingCache.stop(AbstractDelegatingCache.java:524)
    at org.infinispan.security.impl.SecureCacheImpl.stop(SecureCacheImpl.java:164)
    at org.infinispan.manager.DefaultCacheManager.terminate(DefaultCacheManager.java:810)
    at org.infinispan.manager.DefaultCacheManager.stopCaches(DefaultCacheManager.java:915)
    at org.infinispan.manager.DefaultCacheManager.internalStop(DefaultCacheManager.java:880)
    at org.infinispan.manager.DefaultCacheManager.stop(DefaultCacheManager.java:854)
    at org.infinispan.server.SecurityActions.lambda$stopCacheManager$0(SecurityActions.java:50)
    at org.infinispan.security.Security.doPrivileged(Security.java:49)
    at org.infinispan.server.SecurityActions.stopCacheManager(SecurityActions.java:56)
    at org.infinispan.server.Server.localShutdown(Server.java:607)
    at org.infinispan.server.Server.lambda$run$0(Server.java:407)
    at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:980)
    at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:957)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:556)
    at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2231)
    at org.infinispan.server.DefaultExitHandler.exit(DefaultExitHandler.java:13)
    at org.infinispan.server.ShutdownHook.run(ShutdownHook.java:16)

2025-03-25 10:56:40,480 INFO  [o.i.CONTAINER] ISPN000390: Persisted state, version=15.2.0-SNAPSHOT timestamp=2025-03-25T09:56:40.480304501Z
2025-03-25 10:56:40,481 INFO  [o.i.CLUSTER] ISPN000080: Disconnecting JGroups channel `cluster`
*** Server process (164424) received TERM signal ***
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fax4ever**
Closes #14441

### CODE REVIEW

File: query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java [hunk 1]
```diff
@@ -68,16 +70,28 @@ public <T> T get(String cacheName, String queryString, List<FieldAccumulator> ac
...
-      return cacheManager.getCache(QUERY_CACHE_NAME);
+      if (cache != null) {
+         return cache;
+      }
+      synchronized (this) {
+         if (cache == null) {
+            cache = cacheManager.getCache(QUERY_CACHE_NAME);
+         }
+      }
+      return cache;
```
Comment (pruivo) [inline query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java:94]: nitpicking, you don't need the synchronized block because `cacheManager.getCache(QUERY_CACHE_NAME)` always returns the same instance. 

```suggestion
      if (cache == null) {
         cache = cacheManager.getCache(QUERY_CACHE_NAME);
      }
      return cache;
```

**Review by pruivo — APPROVED** [review]

File: query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java (hunk 1 above)
Comment (fax4ever) [reply query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java:94]: great! I'll apply the change. thank you

**Review by wburns — APPROVED** [review]

**Comment by pruivo** [comment]
merged! thanks @fax4ever !
