### PR TITLE
[#15305] Rolling Upgrade tests versions are overridden by INFINISPAN_TEST_SERVER_DIR env var

### LINKED ISSUE #15305: Rolling Upgrade tests versions are overridden by INFINISPAN_TEST_SERVER_DIR env var
### Describe the bug

The rolling upgrade pom.xml is currently specifying `<org.infinispan.test.server.dir>${project.basedir}/../runtime/target/${infinispan.brand.prefix}-server-${infinispan.brand.version}</org.infinispan.test.server.dir>` which is overriding the version passed in and always uses the current directory.

This is causing the test to always run with the SNAPSHOT version which is not intended. We need to remove this and allow the test to specify its own version. We also will need to copy over some xml files as older versions don't work with 16.0 schemas.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #15341: ContainerInfinispanServerDriver should set JAVA_OPTS and JAVA_OPTIONS both
### Describe the bug

Currently ContainerInfinispanServerDriver  will set either JAVA_OPTS or JAVA_OPTIONS based on if the base image name is provided. This doesn't cover the case when a version is provided or a custom image based on a base image. We should just always set both environment variables so it can work in any configuration.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
Fixes #15305
Fixes #15341

This PR also fixes some issues with a container running off of a base image. That is that it uses JAVA_OPTIONS instead of JAVA_OPTS and also that we need to increase the max metaspace when using code coverage as 96MB was not enough.

### CODE REVIEW

**Comment by wburns** [comment]
Figured out the issue with conf directory not being copied over. It is because testcontainers was indiscriminately stripping `file:` from the provided directory and not only from the beginning. If we strip that and not use it as the temporary directory it passes as it should.

**Comment by wburns** [comment]
Have to dig into failures tomorrow.

**Comment by wburns** [comment]
Looks like the failures are related to the jacoco changes, most likely when using `file:///`, need to dig into it.

```
2025-07-17T21:42:30.3353438Z Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"Could not find the file /opt/jacoco.exec in container 73d6fe11241967d476abfcb5bb0e45c5c3e91ce0fde9e418d4e016e81bff68cb"}
2025-07-17T21:42:30.3354763Z 
2025-07-17T21:42:30.3355567Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
2025-07-17T21:42:30.3357378Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
2025-07-17T21:42:30.3359586Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:30)
2025-07-17T21:42:30.3362350Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:13)
2025-07-17T21:42:30.3364553Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
2025-07-17T21:42:30.3366448Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
2025-07-17T21:42:30.3368791Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.CopyArchiveFromContainerCmdImpl.exec(CopyArchiveFromContainerCmdImpl.java:66)
2025-07-17T21:42:30.3370820Z 	at org.testcontainers.containers.ContainerState.copyFileFromContainer(ContainerState.java:411)
2025-07-17T21:42:30.3372604Z 	at org.testcontainers.containers.ContainerState.copyFileFromContainer(ContainerState.java:386)
2025-07-17T21:42:30.3374193Z 	at org.testcontainers.containers.GenericContainer.copyFileFromContainer(GenericContainer.java:1427)
2025-07-17T21:42:30.3376086Z 	at org.infinispan.server.test.core.InfinispanGenericContainer.uploadCoverageInfoToHost(InfinispanGenericContainer.java:140)
2025-07-17T21:42:30.3378219Z 	at org.infinispan.server.test.core.ContainerInfinispanServerDriver.stop(ContainerInfinispanServerDriver.java:538)
2025-07-17T21:42:30.3380073Z 	at org.infinispan.server.test.core.ContainerInfinispanServerDriver.stop(ContainerInfinispanServerDriver.java:477)
2025-07-17T21:42:30.3382026Z 	at org.infinispan.server.test.core.AbstractInfinispanServerDriver.stop(AbstractInfinispanServerDriver.java:189)
2025-07-17T21:42:30.3383877Z 	at org.infinispan.server.test.core.rollingupgrade.RollingUpgradeHandler.cleanup(RollingUpgradeHandler.java:310)
2025-07-17T21:42:30.3385875Z 	at org.infinispan.server.test.core.rollingupgrade.RollingUpgradeHandler.runUntilMixed(RollingUpgradeHandler.java:222)
2025-07-17T21:42:30.3387829Z 	at org.infinispan.server.test.junit5.RollingUpgradeHandlerExtension.onTestsStart(RollingUpgradeHandlerExtension.java:73)
2025-07-17T21:42:30.3398323Z 	at org.infinispan.server.test.junit5.AbstractServerExtension.beforeAll(AbstractServerExtension.java:133)
```

**Comment by wburns** [comment]
It actually appears the failure may be buried by the finally block failing.. but it should have put the original exception as suppressed though..

File: server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java [hunk 1]
```diff
@@ -76,7 +76,8 @@
 public class ClusteredRollingUpgradeIT extends InfinispanSuite {
 
    static {
-      RollingUpgradeConfigurationBuilder builder = new RollingUpgradeConfigurationBuilder(ClusteredRollingUpgradeIT.class.getName(), "15.2.0.Final", "15.2.1.Final")
+      RollingUpgradeConfigurationBuilder builder = new RollingUpgradeConfigurationBuilder(ClusteredRollingUpgradeIT.class.getName(),
```
Comment (ryanemerson) [inline server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java:79]: I might be missing the purpose of this PR, so bare with me...

Instead of explicitly specifying the version in every test via `RollingUpgradeTestUtil`, could we add a `RollingUpgradeConfigurationBuilder(String name);` constructor that just looks up the `rolling.upgrade.*` properties?

We would then set the properties in the `pom.xml`, so it's still possible for users to override them

**Review by ryanemerson — COMMENTED** [review]
@wburns Can we update the title of the issue/commit. The current wording makes it sounds like we're switching from 16.0 to 15.2 when it's the other way around.

File: server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java (hunk 1 above)
Comment (wburns) [reply server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java:79]: This is already done in https://github.com/infinispan/infinispan/blob/main/server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java#L85, I just didn't move it to the Util class yet due to conflicts.

Comment (wburns) [reply server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java:79]: I need to resolve the jacoco issue still, which isn't why I haven't given this PR _that_ much love yet :)

**Comment by wburns** [comment]
> @wburns Can we update the title of the issue/commit. The current wording makes it sounds like we're switching from 16.0 to 15.2 when it's the other way around.

@ryanemerson It is actually correct, sadly. The test _defines_ 15.2 but it is actually currently always using16.0.0.SNAPSHOT -> 16.0.0.SNAPSHOT due to the INFINISPAN_TEST_SERVER_DIR being defined in the pom.xml. The PR main fix is actually therefore https://github.com/infinispan/infinispan/pull/15312/files#diff-8a97017213a6940c026345bf76952a27aabd4eaf1fc07739a503dfca1e4332a8R367 which removes that. However, while I was fixing this we released Dev02 which actually allows running from 16.0.0.Dev02 -> 16.0.0.SNAPSHOT.

I can reword it though to properly state it was using the server dir on accident.

File: server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java (hunk 1 above)
Comment (ryanemerson) [reply server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java:79]: > This is already done in https://github.com/infinispan/infinispan/blob/main/server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java#L85,

This has:

```java
   public RollingUpgradeConfigurationBuilder(String name, String fromVersion, String toVersion) {
      this.fromVersion = System.getProperty(INFINISPAN_ROLLING_UPGRADE_FROM_VERSION, fromVersion);
      this.toVersion = System.getProperty(INFINISPAN_ROLLING_UPGRADE_TO_VERSION, toVersion);
      this.name = name;
   }
```

I'm proposing that we introduce:

```java
   public RollingUpgradeConfigurationBuilder(String name) {
      this.fromVersion = System.getProperty(INFINISPAN_ROLLING_UPGRADE_FROM_VERSION);
      this.toVersion = System.getProperty(INFINISPAN_ROLLING_UPGRADE_TO_VERSION);
      this.name = name;
   }
```
We then set the property in the `pom.xml` and it's no longer necessary for every test to explicitly pass `fromVersion` and `toVersion`.

Comment (wburns) [reply server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java:79]: Hrmm, originally, I didn't like the idea of having the property in a constructor. I personally think it is a loss of IoC, but I can see it being a benefit for tests. Let me update and try it out :)

**Comment by wburns** [comment]
This _should_ work now.. after resolving issues with using a base image.

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @wburns!
