### PR TITLE
[#16474] Don't use AOT cache in the server with --jmx

### LINKED ISSUE #16474: Don't use AOT cache when JMX is enabled
### Describe the bug

enabling JMX introduces changes to the modules which causes AOT cache use to fail.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #16474

### CODE REVIEW

File: server/runtime/src/main/server/bin/common.sh [hunk 1]
```diff
@@ -329,7 +329,7 @@ if [ "$PRESERVE_JAVA_OPTS" != "true" ]; then
             exit
         fi
         PREPEND_JAVA_OPTS="$PREPEND_JAVA_OPTS -XX:AOTCacheOutput=${AOT_CACHE} -Dinfinispan.shutdown.immediately=true -Djgroups.join_timeout=0"
-    elif [ -f "$AOT_CACHE" ]; then
+    elif [ -f "$AOT_CACHE" ] && [ "$JMX_REMOTING" != "true" ]; then
         # If an AOT cache is present, use it
         PREPEND_JAVA_OPTS="$PREPEND_JAVA_OPTS -XX:AOTMode=on -XX:AOTCache=$AOT_CACHE"
```
Comment (pruivo) [inline server/runtime/src/main/server/bin/common.sh]: Have you considered setting `-XX:AOTMode=auto` instead? 
From https://docs.oracle.com/en/java/javase/25/docs/specs/man/java.html
```
When the AOT cache fails to load:

If AOTMode was originally auto, the JVM will continue execution without using the AOT cache. This is the recommended mode for production environments, especially when you may not have complete control of the command-line (e.g., your application's launch script may allow users to inject options to the command-line). This allows your application to function correctly, although sometimes it may not benefit from the AOT cache.
```

I tried locally
```
$ ./bin/server.sh  --jmx

[0.019s][error][aot] An error has occurred while processing the AOT cache. Run with -Xlog:aot for details.
[0.019s][error][aot] Mismatched values for property jdk.module.addmods: jdk.management.agent specified during runtime but not during dump time
[0.019s][error][aot] Disabling optimized module handling
[0.019s][error][aot] AOT cache has aot-linked classes. It cannot be used when archived full module graph is not used.
[0.024s][error][aot] Unable to map shared spaces
2026-01-13 14:57:32,915 INFO  [BOOT] JVM OpenJDK 64-Bit Server VM Eclipse Adoptium 25+36-LTS
2026-01-13 14:57:32,918 INFO  [BOOT] JVM arguments = [--add-exports, java.naming/com.sun.jndi.ldap=ALL-UNNAMED, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.base/java.util.concurrent=ALL-UNNAMED, --enable-native-access=ALL-UNNAMED, -XX:+UseCompactObjectHeaders, -XX:AOTMode=auto, -XX:AOTCache=/home/pedro/Work/infinispan/main/server/runtime/target/infinispan-server-16.1.0-SNAPSHOT/server/cache/infinispan-server.x86_64.aot, -Xlog:gc*:file=/home/pedro/Work/infinispan/main/server/runtime/target/infinispan-server-16.1.0-SNAPSHOT/server/log/gc.log:time,uptimemillis:filecount=5,filesize=3M, -Djava.awt.headless=true, -Djava.net.preferIPv4Stack=true, -XX:+ExitOnOutOfMemoryError, -XX:MetaspaceSize=64M, -Xms64m, -Xmx512m, -Dcom.sun.management.jmxremote.port=9999, -Djava.security.auth.login.config=/home/pedro/Work/infinispan/main/server/runtime/target/infinispan-server-16.1.0-SNAPSHOT/bin/server-jaas.config, -Dcom.sun.management.jmxremote.login.config=ServerJMXConfig, -Dcom.sun.management.jmxremote.ssl=false, -Dvisualvm.display.name=infinispan-server, -Djava.util.logging.manager=org.infinispan.server.loader.LogManager, -Dinfinispan.server.home.path=/home/pedro/Work/infinispan/main/server/runtime/target/infinispan-server-16.1.0-SNAPSHOT, -jar, /home/pedro/Work/infinispan/main/server/runtime/target/infinispan-server-16.1.0-SNAPSHOT/lib/infinispan-server-runtime-16.1.0-SNAPSHOT.jar]
2026-01-13 14:57:32,919 INFO  [BOOT] PID = 795990
2026-01-13 14:57:32,919 INFO  [BOOT] Architecture = amd64
2026-01-13 14:57:32,919 INFO  [BOOT] OS = Linux 6.17.13-1-MANJARO
2026-01-13 14:57:32,919 INFO  [BOOT] Processors = 12
2026-01-13 14:57:32,934 INFO  [BOOT] Memory total = 64MiB
2026-01-13 14:57:32,935 INFO  [BOOT] Memory max = 512MiB
2026-01-13 14:57:32,944 INFO  [o.i.SERVER] ISPN080000: Infinispan Server 16.1.0-SNAPSHOT starting
```
