### PR TITLE
Unable to marshall Collections with JavaSerializationMarshaller 

### LINKED ISSUE #16416: Unable to marshall Collections$UnmodifiableSortedSet with JavaSerializationMarshaller
### Describe the bug

Attempting to marshall key/values using `Collections.unmodifiableSortedSet()` will fail with a custom marshaller when the underlying set is empty, as the GlobalMarshaller will wrongly try to marshall this value with Protostream.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #16416

### CODE REVIEW

File: core/src/main/java/org/infinispan/marshall/protostream/impl/GlobalMarshaller.java [hunk 1]
```diff
@@ -61,7 +61,9 @@ public boolean isMarshallableWithoutWrapping(Object o) {
          // this code and remove the SetAdapter and ListAdapter from the GLOBAL SerializationContext in the
          // SerializationContextRegistry when a custom user marshaller is configured.
          var it = iterable.iterator();
-         return !it.hasNext() || isMarshallableWithoutWrapping(it.next());
```
Comment (wburns) [inline core/src/main/java/org/infinispan/marshall/protostream/impl/GlobalMarshaller.java:64]: Oops :D

**Comment by wburns** [comment]
Integrated into main, thanks @ryanemerson !
