### PR TITLE
[#14562] Rolling Upgrade test handler

### LINKED ISSUE #14562: Add test support for ensuring rolling upgrades work between desired versions
### Description

Infinispan 16.0 will be the first version to begin supporting in place rolling upgrades. We need to have an easy way to test doing this upgrade between versions.

It should be possible to use the test driver which starts up containerized Infinispan servers to verify this.

#### Callback investigation
 We will need various callbacks at each stage so a test can do various things as needed. These are the ones identified thus far.

1. After initial cluster startup
2. After node shutdown
  - After container termination
  - After cluster resize
4. After node startup
  - After container startup
  - After cluster resize
  - Readiness probe ready (what if topology aware client is connected before)
6. On exception handling
7. After completion (readiness probe good for all new nodes)

#### Things that need to be implemented/added

- [x] Handler callback implementation above
- [x] Support RESP, REST, HR, MemcacheD clients (REST be default)
- [x] JUnit support for matrix of configurations (versions to jump between)
- [x] Different tests for different configurations (xsite, DIST, REPL, tcp, udp, stores (shared and unshared), discovery protocols.. etc) - matrix must work for _all_ of these
- JDBC PING, DNSPING, TCPPING
- [ ] Do we need to know what version each container is and how do we report that? REST call into container to report? Might be needed for version specific test handling. Future me does not thank me.
- [x] JUnit 5 support only NO TESTNG
- [x] Way to define caches programmatically in a nice way.
- [x] Way to define server configuration file in some way. (auth, noauth)
- [x] Custom server side jars from users (server side filter, user deployed classes and scripts, custom stores)
- [x] Do we support different JDK versions between rolling upgrades (embedded)? - NO

### PR DESCRIPTION
**Pull request by wburns**
Closes #14562

Initial commit includes changes to the testdriver to allow for it to startup multiple different versions and allow starting up servers one by one. This does not include support yet for xsite or custom cache configurations.

Example of usage can be found at https://github.com/wburns/jbang-catalog/blob/f07336bfad8c390651f74d9cf9d74e8356127372/rollingupgrade.java. JBang script can be ran with something like `jbang rollingupgrade.java 15.1 15.2` which will fail since JGroups doesn't allow mixed versions.

When running JBang, if you pass `-d` it will dump the log files into the `/tmp/infinispanTemp/<version>` for the various servers that were running. You can check the server.log file in there to see the actual failure.

### CODE REVIEW

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java [hunk 1]
```diff
@@ -216,16 +218,18 @@ protected void start(String fqcn, File rootDir, File configurationFile) {
          throw new RuntimeException(e);
       }
       log.infof("Creating image %s", name);
+      String versionProvided = configuration.properties().getProperty(TestSystemPropertyNames.INFINISPAN_TEST_SERVER_VERSION);
+      String versionToUse = versionProvided != null ? versionProvided : Version.getMajorMinor();
```
Comment (ryanemerson) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:222]: We can reduce this to a single variable by using:

```java
String version = configuration.properties().getProperty(TestSystemPropertyNames.INFINISPAN_TEST_SERVER_VERSION, Version.getMajorMinor());
```

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java [hunk 2]
```diff
@@ -296,20 +311,17 @@ private static Path cleanServerDirectory(Path serverOutputPath) {
...
    }
 
-   private GenericContainer<?> createContainer(int i, Consumer<OutputFrame>... logConsumers) {
+   private GenericContainer<?> createContainer(Consumer<OutputFrame>... logConsumers) {
 
       boolean volumesRequired = Boolean.parseBoolean(configuration.properties().getProperty(INFINISPAN_TEST_SERVER_CONTAINER_VOLUME_REQUIRED));
-      if (volumesRequired && this.volumes[i] == null) {
-         String volumeName = Util.threadLocalRandomUUID().toString();
-         DOCKER_CLIENT.createVolumeCmd().withName(volumeName).exec();
-         this.volumes[i] = volumeName;
```
Comment (ryanemerson) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:305]: I think the idea of storing the volume names was so that we can cleanup and remove the volumes once the testsuite completes. Looking at the diff though, it seems this is missing. Can you try adding this logic? I don't think it's a good thing if our testsuite is continually creating new volumes and not removing them after use.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java [hunk 3]
```diff
@@ -600,9 +621,11 @@ public FileVisitResult postVisitDirectory(Path dir, IOException exc) {
       }
    }
 
-   static String createServerImage(String serverOutputDir) {
+   String createServerImage(String serverOutputDir, String versionToUse) {
+      String snapshotImageName = configuration.properties().getProperty(
+            TestSystemPropertyNames.INFINISPAN_TEST_SERVER_SNAPSHOT_IMAGE_NAME, SNAPSHOT_IMAGE);
```
Comment (ryanemerson) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:626]: We should probably extract this logic to a method somewhere. It seems we're using `SNAPSHOT_IMAGE` directly in some places and ignoring the name configured via the property.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java [hunk 4]
```diff
@@ -65,6 +65,20 @@ protected void start(String name, File rootDir, File configurationFile) {
       }
    }
 
+   @Override
+   public void startAdditionalServer(int expectedClusterSize) {
+      // expectedClusterSize is not used as there could be other managers not managed by us in the cluster
```
Comment (ryanemerson) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java:70]: When do we expect this to happen?

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/UpgradeHandler.java [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+         handler.logConsumer.accept("Starting " + nodeCount + " node to version " + versionFrom);
+         handler.fromDriver = handler.startNode(false, configuration.nodeCount(), configuration.nodeCount(),
+               site1Name, configuration.jgroupsProtocol());
+
+         try (RemoteCacheManager manager = handler.createRemoteCacheManager()) {
+            RemoteCache<String, String> cache = configuration.initialHandler().apply(manager);
+
+            for (int i = 0; i < nodeCount; ++i) {
+
+               // TODO: disable state transfer
```
Comment (ryanemerson) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/UpgradeHandler.java:72]: Why? In the case of a StatefulSet rolling update and `num_owners > 1`, we need state to be transferred to the node started with the new version.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java [hunk 6]
```diff
@@ -262,22 +266,33 @@ protected void start(String fqcn, File rootDir, File configurationFile) {
...
+            createContainer(startupLatch, clusterLatch);
             Exceptions.unchecked(() -> startupLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
          }
       }
       // Ensure that a cluster of numServers has actually formed before proceeding
       Exceptions.unchecked(() -> clusterLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
    }
 
+   @Override
+   public void startAdditionalServer(int expectedClusterSize) {
```
Comment (ryanemerson) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:287]: I'm not sure for the scenarios we want to support, starting an additional server in this way makes sense. We never advise that Infinispan is deployed in a K8s Deployment, as it can undermine many of our assumptions and makes data loss more probable.

In the Infinispan Operator and Keycloak, we always leverage a StatefulSet which never adds additional pods during a rolling update. Instead, pods are upgraded individually until all pods have transitioned to the new version: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update. Also see our test `StatefulSetRollingUpgradeIT`.

The important thing is that a pod/container has been gracefully terminated, the new pod/container that rejoins the cluster must use the same volume containing the old global state. In the Operator we mount all data in the server's `data/` dir.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java (hunk 2 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:305]: The `volumes` array is never used outside of this though, so I never saw how it could be used to cleanup. The `containers` list/array however is stopped at the end of the test. In my docker environment after running the upgrade everything is cleaned up as I would think. Is there something else I am missing?

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java (hunk 6 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:287]: Looking at that test though the server driver is using the same version when restarted, while we need a different version upon restart, so I can't see how we can use that approach. We would need something similar to what I have here but copy over the `data` directory if I am not mistaken?

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/UpgradeHandler.java (hunk 5 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/UpgradeHandler.java:72]: Sorry, this was a comment when I was adding steps. The idea was to have a step where we disable state transfer then add the node then perform a check, then enable state transfer. So that way we can verify we are running commands in between each version and also try to have a better chance of seeing operations during the state transfer.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java (hunk 6 above)
Comment (ryanemerson) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:287]: Yes that's correct. I was pointing at that test just as an example of the StatefulSet rolling update procedure.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java (hunk 3 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:626]: Let me take a second look. The handler itself is cleaning these up currently, which isn't correct.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java (hunk 4 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java:70]: Embedded currently only verifies by assuming all managers it controls are the ones in the view. Due to the manager being from different drivers, we can't verify that. Let me reword this. The forked driver is a similar thing. We would have to change these both to check in different ways. But due to them not requiring this currently, I didn't work on them.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java (hunk 2 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:305]: But I am missing a chance to ensure the volume mount is reused on a given offset with this change though.

Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:305]: Will revert, I was able to change the parts of code that this simplified to be different.

Comment (ryanemerson) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:305]: > The `volumes` array is never used outside of this though, so I never saw how it could be used to cleanup. Maybe the code was actually missing before as well?

Yes the cleanup was missing before, I was asking if you could add the cleanup logic. For example, we could have a `InfinispanServerDriver#close` method which is called only at the end of the test. That way we can still stop/kill/restart the server during the test and only remove the volume when we know for sure that the test no longer relies on it.

For debugging purposes, we could even have a property in the `#close` implementation that preserves the volume.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java (hunk 4 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java]: Oops, I meant to remove these methods from forked and embedded. If you notice there is no interface for these methods anymore, so this just goes away.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java (hunk 6 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java]: @ryanemerson this is all in the new https://github.com/infinispan/infinispan/pull/14563/files#diff-2e7fa98e5b1c1e1084ef99b2b71a0da3ba0fc31b0c6f8a8ddb9c796e22735187R55 class. Honestly, at this point an integration test it out of the scope here imo.

The entire rolling upgrade feature is too big to get an abstraction correct in a single commit as there is too much information in disparate locations. Getting something in and iterating on it is much better which is what I want to do here. Note there is no actual support for xsite other than a random boolean in the upgrade configuration.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java [hunk 7]
```diff
@@ -260,22 +304,36 @@ protected void start(String fqcn, File rootDir, File configurationFile) {
...
+         log.infof("Starting new single server for container %d with volume %s", name, volumeName);
+         createContainer(createdContainers(), volumeName, startupLatch, clusterLatch);
          Exceptions.unchecked(() -> startupLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
-      } else {
-         for (int i = 0; i < configuration.numServers(); i++) {
-            CountdownLatchLoggingConsumer startupLatch = new CountdownLatchLoggingConsumer(1, STARTUP_MESSAGE_REGEX);
-            createContainer(i, startupLatch, clusterLatch);
-            Exceptions.unchecked(() -> startupLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
-         }
+         Exceptions.unchecked(() -> clusterLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:326]: This was here before, but on the rolling upgrade context, we'll need to emphasize in the docs that the view must always be stable before proceeding with operations.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+   private int nodeCount = 3;
+   private boolean xSite;
+   private String jgroupsProtocol = "tcp";
+   private int serverCheckTimeSecs = 30;
+   private boolean useSharedDataMount = true;
+   private BiConsumer<Throwable, RollingUpgradeHandler> exceptionHandler = (t, uh) -> {
+      t.printStackTrace();
+   };
+
+   private Consumer<String> logConsumer = System.out::println;
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java:27]: I guess this is to keep it simple and avoid bringing dependencies into scripts (e.g., JBang), but should this utilize a logger instead? I was wondering if we'll have problems in our tests, and the output wasn't written in the file.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+
+   private Consumer<RollingUpgradeHandler> initialHandler = uh -> {
+      RemoteCacheManager rcm = uh.getRemoteCacheManager();
+      RemoteCache<String, String> cache = rcm.administration().createCache("rolling-upgrade",
+            new StringConfiguration("<replicated-cache></replicated-cache>"));
+      cache.put("foo", "bar");
+   };
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java:34]: Is this just simplifying for our use? The cache name + configuration should be required options in the builder, and we do this automatically.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java [hunk 10]
```diff
@@ -0,0 +1,229 @@
...
+      }
+      if (toDriver != null) {
+         toDriver.stop(configuration.toVersion());
+      }
+   }
+
+   public RemoteCacheManager createRemoteCacheManager() {
+      TestUser user = TestUser.ADMIN;
+
+      String hotrodURI = "hotrod://" + user.getUser() + ":" + user.getPassword() + "@" + fromDriver.getServerAddress(0).getHostAddress() + ":11222";
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:174]: Should we use the configuration builder here? Should we extract the port from the InetAddress and fallback to 11222?

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java [hunk 11]
```diff
@@ -0,0 +1,229 @@
...
+
+   public ContainerInfinispanServerDriver getToDriver() {
+      return toDriver;
+   }
+
+   public RollingUpgradeConfiguration getConfiguration() {
+      return configuration;
+   }
+
+   public RemoteCacheManager getRemoteCacheManager() {
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:83]: Nit: Should we make it explicit the RCM connects to the "from" driver?

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java [hunk 12]
```diff
@@ -0,0 +1,229 @@
...
+
+         try (RemoteCacheManager manager = handler.createRemoteCacheManager()) {
+            handler.remoteCacheManager = manager;
+            configuration.initialHandler().accept(handler);
+
+            for (int i = 0; i < nodeCount; ++i) {
+               handler.logConsumer.accept("Shutting down 1 node from version: " + versionFrom);
+               int nodeId = nodeCount - i - 1;
+               String volumeId = handler.fromDriver.volumeId(nodeId);
+               handler.fromDriver.stop(nodeId);
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:112]: It might be a silly question: what would be the difference between starting the new and stopping the old one? It wouldn't be possible to start from the same volume. Is there something else? Then we should also emphasize always stopping the previous and then starting the new version.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java [hunk 13]
```diff
@@ -0,0 +1,229 @@
...
+
+   private ContainerInfinispanServerDriver startNode(boolean toOrFrom, int nodeCount, int expectedCount, String clusterName,
+                                                            String protocol, String volumeId) {
+      ServerConfigBuilder builder = new ServerConfigBuilder("infinispan.xml", true);
+      builder.runMode(ServerRunMode.CONTAINER);
+      builder.numServers(nodeCount);
+      builder.expectedServers(expectedCount);
+      builder.clusterName(clusterName);
+      builder.property(Server.INFINISPAN_CLUSTER_STACK, protocol);
+      builder.property(TestSystemPropertyNames.INFINISPAN_TEST_SERVER_REQUIRE_JOIN_TIMEOUT, "true");
```
Comment (jabolina) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:188]: Curious about this one. What would happen without the delay?

**Review by jabolina — COMMENTED** [review]
Mostly just some questions.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java (hunk 7 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java:326]: I think that is implied already, but we can probably say when doing a user controlled rolling upgrade that should be the first step. K8s already requires this afaik.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java (hunk 10 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:174]: Currently we don't override the port, so it will always be 11222. Honestly, this is just here to get something working which is very simple and replace it with something nicer as we need to.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java (hunk 11 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:83]: There shouldn't be any difference technically as they are clustered together. So no need imo.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java (hunk 13 above)
Comment (wburns) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:188]: This is needed because what this does is disable the first node created via the driver from having join timeout set to 0. This is done because normally the driver is not connecting to an existing cluster and thus it will always be the first. In our case the second driver will be connecting to the first driver cluster and we don't want to have a merge if we don't need to. Writing this though we can have this optional based on if it is the old or new version though, so I will update it.

**Review by jabolina — APPROVED** [review]
The way I see it, we want to get it in and then add the methods/refine as we need down the road.

**Comment by jabolina** [comment]
Thanks, @wburns!
