### PR TITLE
[#15577] Show auth failure in access log

### LINKED ISSUE #15577: Access log failed authentication requests
### Describe the bug

Include to the access log for Hot Rod, RESP, and Memcached when an auth request has failed. We don't need to give too many details. Likely, only the IP is enough to identify a problem.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
The only access log showing failures in authentication is the REST connector. It shows like:

```
127.0.0.1 - [09/Oct/2025:19:17:49 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 401 0 0 11
127.0.0.1 - [09/Oct/2025:19:17:49 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 401 0 0 4
127.0.0.1 - [09/Oct/2025:19:17:55 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 401 0 0 1
127.0.0.1 - [09/Oct/2025:19:17:55 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 200 0 170 10
```

You can see the `401` response status. The remaining connectors did not include auth failures in the access logs. RESP would always register operations as success. Memcached did not register the auth operation (success or not). And HR would always register an operation as `ERROR` instead of the operation.

RESP shows as:

```
127.0.0.1 - [09/Oct/2025:19:16:13 -0300] "COMMAND /[] RESP" OK 24 64 3
127.0.0.1 - [09/Oct/2025:19:16:13 -0300] "INFO /[] RESP" OK 23 64 0
127.0.0.1 - [09/Oct/2025:19:16:13 -0300] "COMMAND /[] RESP" OK 17 64 0
127.0.0.1 - [09/Oct/2025:19:16:17 -0300] "AUTH /[] RESP" java.lang.SecurityException: ELY01151: Evidence Verification Failed. 30 64 48
127.0.0.1 admin [09/Oct/2025:19:16:20 -0300] "AUTH /[] RESP" OK 33 5 16
```

I've started the CLI, entered the incorrect credentials, and then entered the correct ones. RESP required a few changes to make it work. Likely, it would require a closer look at all operations. We catch all failures and manually invoke the write and return a successful CompletableFuture. We would return an error to the client, but always write success in the access logs.

I've changed it so the failure propagates back to the handler. The handler then knows if an operation has failed. This also centralized failure handling in a single place. I've only investigated the AUTH operation. We would need to verify the remaining commands.

Here is the Memcached text:
```
127.0.0.1 - [09/Oct/2025:19:17:01 -0300] "auth /- MCTXT" CLIENT_ERROR authentication failed: java.lang.SecurityException: ELY01151: Evidence Verification Failed. 14 104 1902
127.0.0.1 - [09/Oct/2025:19:17:08 -0300] "auth /- MCTXT" OK 14 8 2187
```

And here is Memcached binary:
```
127.0.0.1 - [09/Oct/2025:19:19:37 -0300] "SASL_AUTH /- MCBIN" OK 0 129 0
127.0.0.1 - [09/Oct/2025:19:19:37 -0300] "SASL_STEP /- MCBIN" javax.security.sasl.SaslException: ELY05055: Authentication rejected (invalid proof) 0 84 0
127.0.0.1 - [09/Oct/2025:19:19:46 -0300] "SASL_AUTH /- MCBIN" OK 0 129 0
127.0.0.1 - [09/Oct/2025:19:19:46 -0300] "SASL_STEP /- MCBIN" OK 0 64 3
```

In both, I enter the incorrect credentials, and then I enter the correct ones. Memcached works more or less like the RESP to parse and run operations. So I've done similar changes.

Lastly, the changes for Hot Rod:
```
127.0.0.1 - [09/Oct/2025:19:18:54 -0300] "AUTH_MECH_LIST /-/- HOTROD/3.1" OK 0 136 0
127.0.0.1 - [09/Oct/2025:19:18:54 -0300] "AUTH /-/- HOTROD/3.1" OK 14 112 2
127.0.0.1 - [09/Oct/2025:19:18:54 -0300] "AUTH /-/- HOTROD/3.1" java.lang.SecurityException: ISPN006024: Invalid credentials 90 152 3
127.0.0.1 - [09/Oct/2025:19:19:03 -0300] "AUTH_MECH_LIST /-/- HOTROD/3.1" OK 0 136 0
127.0.0.1 - [09/Oct/2025:19:19:03 -0300] "AUTH /-/- HOTROD/3.1" OK 14 112 1
127.0.0.1 - [09/Oct/2025:19:19:03 -0300] "AUTH /-/- HOTROD/3.1" OK 90 53 2
127.0.0.1 - [09/Oct/2025:19:19:03 -0300] "EXEC /-/@@cache@getorcreate HOTROD/4.1" OK 63 6 61
127.0.0.1 - [09/Oct/2025:19:19:03 -0300] "PING /cache-1/- HOTROD/4.1" OK 496 674 5
```

The only change needed was for the decoder to use the `getHeader` method, so it creates a header ready to register in the access log. There is a small change so it uses the original operation name when writing to the access log. Otherwise, it writes `ERROR` instead of the operation that failed.

Closes #15577.

### CODE REVIEW

**Comment by jabolina** [comment]
Hmm, let me check those failures.

**Comment by jabolina** [comment]
OK, updated it. I've added the missing code in the Memcached decoder with auth enabled. Thanks to Will for pointing that out.

**Comment by tristantarrant** [comment]
There are a number of failures I haven't seen before in the memcached module.

**Comment by jabolina** [comment]
Updated. I reverted some unneeded changes in the Memcached auto detector.

File: server/core/src/main/java/org/infinispan/server/core/MagicByteDetector.java [hunk 1]
```diff
@@ -33,7 +33,7 @@ protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) {
          trimPipeline(ctx);
          // Add the protocol server handler
          ctx.pipeline().addLast(getInitializer());
-         Log.SERVER.tracef("Detected %s connection %s", getName(), ctx);
+         Log.SERVER.infof("Detected %s connection %s", getName(), ctx);
```
Comment (tristantarrant) [inline server/core/src/main/java/org/infinispan/server/core/MagicByteDetector.java]: messages with level >= `INFO` must have i18n'd logs
Are we sure we want this logged so high ?

Comment (jabolina) [reply server/core/src/main/java/org/infinispan/server/core/MagicByteDetector.java]: Definitely not, updated it and added more tests.

**Comment by jabolina** [comment]
I've also fixed the access log for Hot Rod and REST, where the principal name wasn't included in the logs.

**Comment by jabolina** [comment]
Hot Rod looks like:

```
127.0.0.1 - [14/Oct/2025:17:51:05 -0300] "AUTH_MECH_LIST /-/- HOTROD/3.1" OK 0 136 5
127.0.0.1 - [14/Oct/2025:17:51:05 -0300] "AUTH /-/- HOTROD/3.1" OK 14 112 15
127.0.0.1 - [14/Oct/2025:17:51:05 -0300] "AUTH /-/- HOTROD/3.1" OK 90 53 11
127.0.0.1 admin [14/Oct/2025:17:51:05 -0300] "EXEC /-/@@cache@getorcreate HOTROD/4.1" OK 63 6 65
127.0.0.1 admin [14/Oct/2025:17:51:05 -0300] "PING /cache-1/- HOTROD/4.1" OK 496 674 5
127.0.0.1 admin [14/Oct/2025:17:51:10 -0300] "PUT /cache-1/[B0x4A036B6579 HOTROD/4.1" OK 22 5 7
127.0.0.1 admin [14/Oct/2025:17:51:12 -0300] "GET /cache-1/[B0x4A036B6579 HOTROD/4.1" OK 41 13 0
```

And REST:

```
127.0.0.1 - [14/Oct/2025:17:50:20 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 401 0 0 10
127.0.0.1 admin [14/Oct/2025:17:50:20 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 404 0 0 16
127.0.0.1 - [14/Oct/2025:17:50:25 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 401 0 0 1
127.0.0.1 - [14/Oct/2025:17:50:25 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 401 0 0 2
127.0.0.1 - [14/Oct/2025:17:50:52 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 401 0 0 1
127.0.0.1 admin [14/Oct/2025:17:50:52 -0300] "GET /rest/v2/caches/memcachedCache?action=config HTTP/1.1" 200 0 170 5
```

**Comment by jabolina** [comment]
Replaying CI again, last failure was:

```
2025-10-15T16:26:43.2591014Z [ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:6.1.1.Final:provision (server-provisioning-node1) on project infinispan-third-party-integrationtests: Provisioning failed: Failed to execute an artifact assembling task of feature-pack wildfly-ee@maven(org.jboss.universe:community-universe):current#37.0.1.Final package tools: Faile
d to resolve org.glassfish:jakarta.json:jar:1.1.6: The following artifacts could not be resolved: org.glassfish:jakarta.json:jar:1.1.6 (absent): Could not transfer artifact org.glassfish:jakarta.json:jar:1.1.6 from/to central (https://repo.maven.apache.org/maven2): status code: 500, reason phrase: Internal Server Error (500) -> [Help 1]
2025-10-15T16:26:43.2596693Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jboss.galleon:galleon-maven-plugin:6.1.1.Final:provision (server-provisioning-node1) on project infinispan-third-party-integrationtests: Provisioning failed
```

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
