### PR TITLE
[#14630] Break cycle between local and cluster topology manager

### LINKED ISSUE #13346: Flaky test: org.infinispan.topology.ClusterTopologyStatefulTest#testOnlyCoordinatorKeepsGlobalState
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.opentest4j.AssertionFailedError: [ClusterTopologyStatefulTest-NodeD is rebalance enabled? true] 
Expecting value to be true but was false
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at org.infinispan.topology.ClusterTopologyStatefulTest.testOnlyCoordinatorKeepsGlobalState(ClusterTopologyStatefulTest.java:72)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.base/java.util.Collections$SynchronizedList.get(Collections.java:2718)
	at org.infinispan.test.MultipleCacheManagersTest.manager(MultipleCacheManagersTest.java:512)
	at org.infinispan.topology.AbstractStatefulCluster.assertClusterStateFiles(AbstractStatefulCluster.java:59)
	at org.infinispan.topology.AbstractStatefulCluster.assertClusterStateFiles(AbstractStatefulCluster.java:54)
	at org.infinispan.topology.ClusterTopologyStatefulTest.disableRebalanceAndShutdown(ClusterTopologyStatefulTest.java:47)
	at org.infinispan.topology.ClusterTopologyStatefulTest.testRebalanceAfterRestart(ClusterTopologyStatefulTest.java:52)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13353: Flaky test: org.infinispan.globalstate.ThreeNodeTopologyReinstallTest#testReinstallTopologySafely\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
java.lang.RuntimeException: Cache testCache timed out waiting for rebalancing to complete on node ThreeNodeTopologyReinstallTest-NodeD, current topology is CacheTopology{id=2, phase=READ_OLD_WRITE_ALL, rebalanceId=2, currentCH=DefaultConsistentHash{ns=256, owners = (2)[ThreeNodeTopologyReinstallTest-NodeD: 119+35, ThreeNodeTopologyReinstallTest-NodeE: 137+43]}, pendingCH=DefaultConsistentHash{ns=256, owners = (2)[ThreeNodeTopologyReinstallTest-NodeD: 131+125, ThreeNodeTopologyReinstallTest-NodeE: 125+131]}, unionCH=DefaultConsistentHash{ns=256, owners = (2)[ThreeNodeTopologyReinstallTest-NodeD: 119+137, ThreeNodeTopologyReinstallTest-NodeE: 137+119]}, actualMembers=[ThreeNodeTopologyReinstallTest-NodeD, ThreeNodeTopologyReinstallTest-NodeE], persistentUUIDs=[d0dfe060-0b68-482b-886e-18d9c2f2d223, 1584a570-dd79-478a-98a9-f0857087e118]}. rebalanceInProgress=true, currentChIsBalanced=false
	at org.infinispan.test.TestingUtil.waitForNoRebalance(TestingUtil.java:469)
	at org.infinispan.test.TestingUtil.waitForNoRebalance(TestingUtil.java:540)
	at org.infinispan.test.MultipleCacheManagersTest.waitForClusterToForm(MultipleCacheManagersTest.java:347)
	at org.infinispan.globalstate.ThreeNodeTopologyReinstallTest.executeTestRestart(ThreeNodeTopologyReinstallTest.java:118)
	at org.infinispan.globalstate.ThreeNodeTopologyReinstallTest.testReinstallTopologySafely(ThreeNodeTopologyReinstallTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13356: Flaky test: org.infinispan.globalstate.ThreeNodeDistGlobalStateRestartTest#testDisableRebalanceRestartEnableRebalance
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.opentest4j.AssertionFailedError: 
Expecting value to be false but was true
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at org.infinispan.globalstate.ThreeNodeDistGlobalStateRestartTest.testDisableRebalanceRestartEnableRebalance(ThreeNodeDistGlobalStateRestartTest.java:89)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13362: Flaky test: org.infinispan.topology.ClusterTopologyStatefulTest#testRebalanceAfterRestart
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.opentest4j.AssertionFailedError: [ClusterTopologyStatefulTest-NodeG is rebalance enabled? true
ClusterTopologyStatefulTest-NodeH is rebalance enabled? true
ClusterTopologyStatefulTest-NodeI is rebalance enabled? true] 
Expecting value to be true but was false
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at org.infinispan.topology.ClusterTopologyStatefulTest.testRebalanceAfterRestart(ClusterTopologyStatefulTest.java:60)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13397: Flaky test: org.infinispan.globalstate.ThreeNodeReplGlobalStateRestartTest#testDisableRebalanceRestartEnableRebalance
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.opentest4j.AssertionFailedError: 
Expecting value to be false but was true
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at org.infinispan.globalstate.ThreeNodeReplGlobalStateRestartTest.testDisableRebalanceRestartEnableRebalance(ThreeNodeReplGlobalStateRestartTest.java:82)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13574: Flaky test: org.infinispan.globalstate.ThreeNodeDistGlobalStateRestartTest#testFailedRestartWithExtraneousNode
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.infinispan.globalstate.AbstractGlobalStateRestartTest.shutdownAndRestart(AbstractGlobalStateRestartTest.java:151)
	at org.infinispan.globalstate.ThreeNodeDistGlobalStateRestartTest.testFailedRestartWithExtraneousNode(ThreeNodeDistGlobalStateRestartTest.java:46)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13685: Flaky test: org.infinispan.globalstate.ThreeNodeReplGlobalStateRestartTest#testFailedRestartWithExtraneousNode
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.infinispan.topology.MissingMembersException: ISPN000689: Recovering cache &amp;apos;testCache&amp;apos; but there are missing members, known members [ThreeNodeReplGlobalStateRestartTest-NodeD, ThreeNodeReplGlobalStateRestartTest-NodeF, ThreeNodeReplGlobalStateRestartTest-NodeG] of a total of 3
	at org.infinispan.topology.LocalTopologyManagerImpl.assertTopologyStable(LocalTopologyManagerImpl.java:872)
	at org.infinispan.interceptors.impl.InvocationContextInterceptor.ignoreCommand(InvocationContextInterceptor.java:105)
	at org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:87)
	at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:238)
	at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:329)
	at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:112)
	at org.infinispan.cache.impl.CacheImpl.size(CacheImpl.java:508)
	at org.infinispan.cache.impl.CacheImpl.size(CacheImpl.java:503)
	at org.infinispan.cache.impl.AbstractDelegatingCache.size(AbstractDelegatingCache.java:369)
	at org.infinispan.globalstate.AbstractGlobalStateRestartTest.checkData(AbstractGlobalStateRestartTest.java:219)
	at org.infinispan.globalstate.AbstractGlobalStateRestartTest.shutdownAndRestart(AbstractGlobalStateRestartTest.java:154)
	at org.infinispan.globalstate.ThreeNodeReplGlobalStateRestartTest.testFailedRestartWithExtraneousNode(ThreeNodeReplGlobalStateRestartTest.java:45)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #14605: Flaky test: org.infinispan.topology.ClusterTopologyViewChangesTest#coordinatorLeftDuringCacheJoinWithRebalanceDisabled
### Github Job:https://github.com/infinispan/infinispan/actions/runs/14503957681
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.infinispan.topology.ClusterTopologyViewChangesTest.executeJoinTest(ClusterTopologyViewChangesTest.java:117)
	at org.infinispan.topology.ClusterTopologyViewChangesTest.coordinatorLeftDuringCacheJoinWithRebalanceDisabled(ClusterTopologyViewChangesTest.java:80)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #14630: Race condition to start local and cluster topology components
### Describe the bug

There is a race condition to start the `LocalTopologyManagerImpl` (LTM) and `ClusterTopologyManagerImpl` (CTM) components. The LTM injects the CTM, which requires the CTM to start *before* the LTM. However, the CTM submits requests for topology and cache statuses, and these operations require the LTM to be running. This creates a cycle/race condition when applying those operations.

One example: the coordinator starts and requests the cache statuses. Since the LTM is starting concurrently, the `CacheStatusRequestCommand` operation will not execute properly:

```log
13:58:39,428 DEBUG (non-blocking-thread-ClusterTopologyStatefulTest-NodeG-p32-t3:[]) [o.i.c.t.CacheStatusRequestCommand] Reply with empty status request because topology manager not running
```

This can be a problem in scenarios where the rebalance was disabled, the whole cluster was shut down, and the coordinator starts. This will lead the coordinator to enable rebalance mistakenly.

### Expected behavior

The `LocalTopologyManagerImpl` MUST start before the `ClusterTopologyManagerImpl`.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Remove dependency from LocalTopologyManagerImpl.
* Cached components ensure correct initialization order.

Closes #14630
Closes #13346 
Closes #13356
Closes #13397 
Closes #13362 

I am not sure if there is something else at play for these:
Closes #13353
Closes #13574 
Closes #13685
Closes #14605

### CODE REVIEW

File: core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java [hunk 1]
```diff
@@ -103,8 +103,6 @@ public class LocalTopologyManagerImpl implements LocalTopologyManager, GlobalSta
    @Inject PersistentUUIDManager persistentUUIDManager;
    @Inject EventLogManager eventLogManager;
    @Inject CacheManagerNotifier cacheManagerNotifier;
-   // Not used directly, but we have to start the ClusterTopologyManager before sending the join request
-   @Inject ClusterTopologyManager clusterTopologyManager;
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java:107]: Note the comment we had here, and correct me. Both the local and cluster components are global. The join request comes from the `StateTransferManagerImpl`, a cache component.

I am assuming that any cache component would only start after the global components have started. So, we should always have the ClusterTopologyManager already started when running a join command.

File: core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java [hunk 2]
```diff
@@ -18,15 +17,22 @@ public class ClusterTopologyStatefulTest extends AbstractStatefulCluster {
...
-      return () -> Arrays.stream(managers())
-            .map(ecm -> TestingUtil.extractGlobalComponent(manager(0), ClusterTopologyManager.class))
+      return () -> cacheManagers.stream()
+            .map(ecm -> TestingUtil.extractGlobalComponent(ecm, ClusterTopologyManager.class))
             .noneMatch(ClusterTopologyManager::isRebalancingEnabled);
    }
 
    private Supplier<String> dumpClusterGlobalRebalanceStatus() {
-      return () -> Arrays.stream(managers())
-            .map(ecm -> Map.entry(ecm, TestingUtil.extractGlobalComponent(manager(0), ClusterTopologyManager.class)))
```
Comment (wburns) [inline core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java:29]: Seems like a pretty big issue with the test, heh.

**Review by wburns — APPROVED** [review]
Seems good to me. Will wait to let others take a peak before integrating.

**Comment by wburns** [comment]
Is the ConcurrentStartChanelLookupTest.testConcurrentStart([1, 0])  failure related? Sounds like it could be.

File: core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java (hunk 2 above)
Comment (jabolina) [reply core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java:29]: :sob: :sob: :sob: :sob:

**Comment by jabolina** [comment]
Looks like it is related. I'll look into it.

**Comment by jabolina** [comment]
Updated! The `LocalTopologyManager` and the `ClusterTopologyManager` have an even tighter bond than I anticipated. Since the CTM was injected in the LTM, they would be running (racing to run would be more appropriate). So I couldn't just remove this bond and let they start when injected/required by commands, I had to add a method so each one can ensure the other is running before submitting a command.

LTM ensures the CTM is running before submitting a join command. CTM ensures the LTM is running before submitting a rebalance status command.

**Comment by wburns** [comment]
> Updated! The `LocalTopologyManager` and the `ClusterTopologyManager` have an even tighter bond than I anticipated. Since the CTM was injected in the LTM, they would be running (racing to run would be more appropriate). So I couldn't just remove this bond and let they start when injected/required by commands, I had to add a method so each one can ensure the other is running before submitting a command.
> 
> LTM ensures the CTM is running before submitting a join command. CTM ensures the LTM is running before submitting a rebalance status command.

I wonder maybe instead of throwing an exception we have some way to until the other is started? Or do you think that is too complicated?

**Comment by jabolina** [comment]
> I wonder maybe instead of throwing an exception we have some way to until the other is started? Or do you think that is too complicated?

Yeah, for this PR, it might be too much, but it would be nice to have in a few scenarios.

I had thought of an async start of components before, but I believe it could end up with too many changes. That would be useful in those scenarios where the component is currently doing a `.join` in a CF, or in that case where the cache should only start after it has recovered the previous topology after a graceful shutdown.

**Review by ryanemerson — APPROVED** [review]

**Comment by wburns** [comment]
> > I wonder maybe instead of throwing an exception we have some way to until the other is started? Or do you think that is too complicated?
> 
> Yeah, for this PR, it might be too much, but it would be nice to have in a few scenarios.
> 
> I had thought of an async start of components before, but I believe it could end up with too many changes. That would be useful in those scenarios where the component is currently doing a `.join` in a CF, or in that case where the cache should only start after it has recovered the previous topology after a graceful shutdown.

I was thinking of something simpler like just spawning a blocking thread to wait until the component was started and then resume on the non blocking thread. Having async start of components would be great, but that definitely is way too much.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
