### PR TITLE
[#13750] Log regex for database tests ignored on container startup

### LINKED ISSUE #13750: Log regex for database tests ignored on container startup
### Describe the bug

In `server/tests` we use `ContainerDatabase` to manage the lifecycle of DB containers that we execute tests against. To ensure that a DB is in a ready state before we begin initializing it with test data, we provide the `org.infinispan.test.database.container.log.regex` property that should ensure that we wait for the specified regex pattern in the container logs before proceeding. However, this regex is ignored as by default the test container `JdbcDatabaseContainer` ignores configured `WaitStrategy`.

We can workaround this by overriding the `JdbcDatabaseContainer#waitUntilContainerStarted`.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #13750

### CODE REVIEW

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java [hunk 1]
```diff
@@ -168,6 +169,14 @@ public String getDriverClassName() {
          return database.driverClassName();
       }
 
+      @Override
+      protected void waitUntilContainerStarted() {
+         // Override JdbcContainerAdapter#waitUntulContainerStarted to ensure that any additional waitStrategies defined,
+         // e.g. LogMessageWaitStrategy, are respected
+         getWaitStrategy().waitUntilReady(this);
```
Comment (Crumby) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java:176]: This probably needs to be conditional and only if `getWaitStrategy() != null`. We are setting waitStrategy only if `org.infinispan.test.database.container.log.regex` specified

Comment (ryanemerson) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java:176]: We should be good as `getWaitStrategy` never returns null as the implementation is:

```java
   protected WaitStrategy getWaitStrategy() {
        return this.waitStrategy == DEFAULT_WAIT_STRATEGY ? this.containerDef.getWaitStrategy() : this.waitStrategy;
    }
```

and `containerDef` is always initialized to `GenericContainer.DEFAULT_WAIT_STRATEGY`
