### PR TITLE
[15.2.x] [#14472] Fix ChannelCloseAndInactiveTest failure

### LINKED ISSUE #14472: Flaky test: org.infinispan.client.hotrod.impl.transport.netty.ChannelCloseAndInactiveTest#testKillAndInactiveDifferentChannelsConcurrently
### Github Job:https://github.com/infinispan/infinispan/actions/runs/14138019520
org.opentest4j.AssertionFailedError: 
expected: 1
 but was: 0
	at org.infinispan.client.hotrod.impl.transport.netty.ChannelCloseAndInactiveTest.testKillAndInactiveDifferentChannelsConcurrently(ChannelCloseAndInactiveTest.java:93)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### PR DESCRIPTION
**Pull request by jabolina**
* Increase operation timeout to avoid retries.

The failure happens because the timeout adds the operation to the queue again, and some of the validations don't expect that.
This is failing hard on 15.2.x. The test is only on the legacy HR client and doesn't exist in main.
Closes #14472

### CODE REVIEW

File: client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelCloseAndInactiveTest.java [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package org.infinispan.client.hotrod.impl.transport.netty;
 
 import static org.assertj.core.api.Assertions.assertThat;
+import static org.infinispan.commons.util.Util.threadDump;
```
Comment (pruivo) [inline client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelCloseAndInactiveTest.java]: it is failing to compile
```
Error:  /home/runner/work/infinispan/infinispan/client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelCloseAndInactiveTest.java:4:15: Unused import - org.infinispan.commons.util.Util.threadDump. [UnusedImports]
```
