### PR TITLE
[#16394] Remove all references to deprecated crypto algorithms

### LINKED ISSUE #16394: Remove all references to deprecated crypto algorithms
### Describe the bug

[MD5](https://www.kb.cert.org/vuls/id/836068) and [SHA-1](https://eprint.iacr.org/2005/010) are not considered secure. We should remove all reference to them and stop generating hashes in the CLI.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #16394

### CODE REVIEW

**Review by ryanemerson — COMMENTED** [review]
This is breaking the Operator after all. The upgrades test is failing when trying to upgrade to 16.1.0 and the reason is that the Operator is receiving 401 http responses from the server.

**Comment by tristantarrant** [comment]
can you enable HTTP logging on the client side ?

**Comment by ryanemerson** [comment]
I have added a new commit that should make it so the debug logging is enabled for curl requests. Let's see

**Comment by ryanemerson** [comment]
So the `curl` command seems to be failing, as it's still trying to use md5:

```
DEBUG: Curl exec='curl -i --insecure --digest --http1.1 -u operator:AkTRzTawImkhGXjO   http://test-operand-upgrades-0:11223/rest/v2/container'
DEBUG: execOut='HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="admin"
WWW-Authenticate: Digest realm="admin", nonce="AAAAAQAAAShQ6R2mScsD2GXsCyq9jqW30vTST9i04244dHMkGTHdzD32Hp0=", opaque="00000000000000000000000000000000", algorithm=MD5, qop=auth
content-length: 0

HTTP/1.1 401 Unauthorized
WWW-Authenticate: Digest realm="admin", nonce="AAAAAgAAAShR9pnH0H0l3nmCnOUunP8qE2NVwgxLRZ3xb8k/WOihVuyTBYE=", opaque="00000000000000000000000000000000", algorithm=MD5, qop=auth
content-length: 0

'DEBUG: Rsp<<<<<<<<<<<<<<<<
HTTP/1.1 401 Unauthorized
Www-Authenticate: Digest realm="admin", nonce="AAAAAgAAAShR9pnH0H0l3nmCnOUunP8qE2NVwgxLRZ3xb8k/WOihVuyTBYE=", opaque="00000000000000000000000000000000", algorithm=MD5, qop=auth
Content-Length: 0



```

We have a bigger problem in our testsuite though. The [HTTP client in the testsuite implements the MD5 logic itself](https://github.com/infinispan/infinispan-operator/blob/f7c564a53876d0656c4013dab7947ec07123b2a1/test/e2e/utils/httpClient.go#L123-L147), so we will need to fix that. Ideally by using a go library that handles negotiation for us.

**Comment by wburns** [comment]
It appears we still have some tests using CRAM-MD5

https://github.com/infinispan/infinispan/blob/main/server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodAuthenticationTest.java#L45
https://github.com/infinispan/infinispan/blob/main/server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAuthAccessLoggingTest.java#L40
https://github.com/infinispan/infinispan/blob/main/server/memcached/src/test/java/org/infinispan/server/memcached/logging/MemcachedBaseAuthAccessLoggingTest.java#L49

**Comment by wburns** [comment]
It looks like there are some more here as well:

 M client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AbstractAuthenticationTest.java
 M client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AuthenticationTest.java
 M client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SecureListenerTest.java
 M client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/SecureRemoteCacheAdminTest.java
 M client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SecureServerFailureRetryTest.java
 M documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
 M documentation/src/main/asciidoc/topics/ref_endpoints_sasl_mechanisms.adoc
 M integrationtests/server-integration/third-party-server/src/test/resources/wildfly/standalone-test.xml
 M persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationSerializer.java
 M pom.xml
 M server/core/src/main/java/org/infinispan/server/core/security/sasl/SaslAuthenticator.java
 M server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodAuthenticationTest.java
 M server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAuthAccessLoggingTest.java
 M server/memcached/src/test/java/org/infinispan/server/memcached/logging/MemcachedBaseAuthAccessLoggingTest.java
 M server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedTestingUtil.java
 M server/runtime/src/test/resources/configuration/versions/13.0.xml
 M server/runtime/src/test/resources/configuration/versions/14.0.xml
 M server/runtime/src/test/resources/configuration/versions/15.0.xml
 M server/runtime/src/test/resources/configuration/versions/15.1.xml
 M server/runtime/src/test/resources/configuration/versions/15.2.xml
 M server/runtime/src/test/resources/configuration/versions/16.0.xml
 
 Not sure if we want to change the older xml files or not though.

**Comment by ryanemerson** [comment]
The Operator upgrade tests are still failing with a 401. I have re-added the commit with debug logging to hopefully see what's going on

**Comment by tristantarrant** [comment]
I must look into the rolling upgrade failures

**Comment by tristantarrant** [comment]
Tis all green now

File: commons/all/src/main/java/org/infinispan/commons/util/SecurityProviders.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
+package org.infinispan.commons.util;
+
+import java.security.Provider;
+import java.security.Security;
+import java.util.LinkedHashMap;
+import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
+
+public final class SecurityProviders {
+   private static final ConcurrentHashMap<ClassLoader, Provider[]> PER_CLASSLOADER_PROVIDERS = new ConcurrentHashMap<>(2);
```
Comment (pruivo) [inline commons/all/src/main/java/org/infinispan/commons/util/SecurityProviders.java]: Paranoid Pedro here: wouldn't be safe to store it as an immutable list?  It looks like `discoverSecurityProviders()` can be invoked from anywhere, and the content of the array could be replaced with malicious providers (?)

File: documentation/src/main/asciidoc/topics/changes.adoc [hunk 2]
```diff
@@ -51,6 +51,13 @@ This simplifies eviction configuration for individual nodes by allowing multiple
 This approach means that all caches utilizing the shared container will share the same eviction limit.
 If a particular cache requires more granular control over its memory usage, it should be configured with its own dedicated eviction policy.
 
+=== Security mechanisms
+
+Removed all references to `DIGEST-MD5`, `DIGEST-SHA`, `SCRAM-SHA-1` and `CRAM-MD5` authentication mechanisms as they
```
Comment (pruivo) [inline documentation/src/main/asciidoc/topics/changes.adoc:56]: Do you mean `DIGEST-SHA-1` and `SCRAM-MD5`?

File: documentation/src/main/asciidoc/topics/ref_endpoints_sasl_mechanisms.adoc [hunk 3]
```diff
@@ -13,7 +13,7 @@
 | Similar to the `BASIC` HTTP mechanism.
 
 | `+DIGEST-*+`
-| Uses hashing algorithms and nonce values. Hot Rod connectors support `DIGEST-MD5`, `DIGEST-SHA`, `DIGEST-SHA-256`, `DIGEST-SHA-384`, and `DIGEST-SHA-512` hashing algorithms, in order of strength.
+| Uses hashing algorithms and nonce values. Hot Rod connectors support `DIGEST-SHA`, `DIGEST-SHA-256`, `DIGEST-SHA-384`, and `DIGEST-SHA-512` hashing algorithms, in order of strength.
```
Comment (pruivo) [inline documentation/src/main/asciidoc/topics/ref_endpoints_sasl_mechanisms.adoc]: Is `DIGEST-SHA` still supported?

**Review by pruivo — CHANGES_REQUESTED** [review]
Is this code below still valid?

https://github.com/infinispan/infinispan/blob/1ef21ae5df90588ad3aa050ba69a57ee8fe59d9c/persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationSerializer.java#L91-L98

**Comment by tristantarrant** [comment]
> Is this code below still valid?
> 
> https://github.com/infinispan/infinispan/blob/1ef21ae5df90588ad3aa050ba69a57ee8fe59d9c/persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationSerializer.java#L91-L98

Unfortunately, we still need to be able to connect to older clusters.

File: documentation/src/main/asciidoc/topics/ref_endpoints_sasl_mechanisms.adoc (hunk 3 above)
Comment (tristantarrant) [reply documentation/src/main/asciidoc/topics/ref_endpoints_sasl_mechanisms.adoc]: Right. I also forgot to remove SCRAM-SHA-1 below

File: documentation/src/main/asciidoc/topics/changes.adoc (hunk 2 above)
Comment (tristantarrant) [reply documentation/src/main/asciidoc/topics/changes.adoc:56]: For some bizarre reason it's called `DIGEST-SHA` and `CRAM-MD5` is yet another one https://en.wikipedia.org/wiki/CRAM-MD5

File: commons/all/src/main/java/org/infinispan/commons/util/SecurityProviders.java (hunk 1 above)
Comment (tristantarrant) [reply commons/all/src/main/java/org/infinispan/commons/util/SecurityProviders.java]: I am using a `List.of()` now.

**Comment by pruivo** [comment]
> > Is this code below still valid?
> > https://github.com/infinispan/infinispan/blob/1ef21ae5df90588ad3aa050ba69a57ee8fe59d9c/persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationSerializer.java#L91-L98
> 
> Unfortunately, we still need to be able to connect to older clusters.

Isn't a new branch needed for  `DIGEST-SHA-256`? In `org.infinispan.persistence.remote.configuration.RemoteStoreConfigurationParser#parseAuthenticationDigest()`, you changed the SASL mechanism to `DIGEST-SHA-256`.

**Comment by tristantarrant** [comment]
> > > Is this code below still valid?
> > > https://github.com/infinispan/infinispan/blob/1ef21ae5df90588ad3aa050ba69a57ee8fe59d9c/persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationSerializer.java#L91-L98
> > 
> > 
> > Unfortunately, we still need to be able to connect to older clusters.
> 
> Isn't a new branch needed for `DIGEST-SHA-256`? In `org.infinispan.persistence.remote.configuration.RemoteStoreConfigurationParser#parseAuthenticationDigest()`, you changed the SASL mechanism to `DIGEST-SHA-256`.

Done

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
Merged! thanks @tristantarrant 
FootprintIT to be fixed by https://github.com/infinispan/infinispan/pull/16512
