### PR TITLE
Avoid thread pinning in ClusterCacheStatus

### LINKED ISSUE #14028: Avoid thread pinning in ClusterCacheStatus
### Description

The Keycloak project is using virtual threads to run ISPN, and when combing through our logs with `-Djdk.tracePinnedThreads=full` the following appeared. While it is a rare event, I'd like to keep our logs clean from those messages, and also allow us to be on the safe side when  people run only on a single core. We've seen bug reports where people actually do that, for example in development and staging environments. 

```
VirtualThread[#690]/runnable@ForkJoinPool-1-worker-2 reason:MONITOR
    java.base/java.lang.VirtualThread$VThreadContinuation.onPinned(VirtualThread.java:199)
    java.base/jdk.internal.vm.Continuation.onPinned0(Continuation.java:393)
    java.base/java.lang.VirtualThread.park(VirtualThread.java:596)
    java.base/java.lang.System$2.parkVirtualThread(System.java:2643)
    java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:54)
    java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:219)
    java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
    java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:990)
    java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
    java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
    java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.remove(ScheduledThreadPoolExecutor.java:1046)
    java.base/java.util.concurrent.ThreadPoolExecutor.remove(ThreadPoolExecutor.java:1777)
    java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.cancel(ScheduledThreadPoolExecutor.java:293)
    org.infinispan.topology.LocalTopologyManagerImpl.lambda$withView$29(LocalTopologyManagerImpl.java:746)
    java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
    java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
    java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
    org.infinispan.topology.LocalTopologyManagerImpl.withView(LocalTopologyManagerImpl.java:746)
    org.infinispan.topology.LocalTopologyManagerImpl.handleRebalance(LocalTopologyManagerImpl.java:664)
    org.infinispan.commands.topology.RebalanceStartCommand.invokeAsync(RebalanceStartCommand.java:59)
    org.infinispan.topology.TopologyManagementHelper.invokeAsync(TopologyManagementHelper.java:152)
    org.infinispan.topology.TopologyManagementHelper.executeOnClusterAsync(TopologyManagementHelper.java:74)
    org.infinispan.topology.ClusterTopologyManagerImpl.broadcastRebalanceStart(ClusterTopologyManagerImpl.java:579)
    org.infinispan.topology.ClusterCacheStatus.startQueuedRebalance(ClusterCacheStatus.java:1009) <== monitors:1
    org.infinispan.topology.ClusterCacheStatus.queueRebalance(ClusterCacheStatus.java:152) <== monitors:1
    org.infinispan.partitionhandling.impl.PreferAvailabilityStrategy.onJoin(PreferAvailabilityStrategy.java:40)
    org.infinispan.topology.ClusterCacheStatus.doJoin(ClusterCacheStatus.java:747) <== monitors:1
    org.infinispan.topology.ClusterTopologyManagerImpl.lambda$handleJoin$4(ClusterTopologyManagerImpl.java:265)
    java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
    java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
    java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
    java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144)
    org.infinispan.topology.ClusterTopologyManagerImpl.lambda$handleJoin$5(ClusterTopologyManagerImpl.java:265)
    java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
    java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
    java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
    org.infinispan.topology.ClusterTopologyManagerImpl.handleJoin(ClusterTopologyManagerImpl.java:257)
    org.infinispan.commands.topology.CacheJoinCommand.invokeAsync(CacheJoinCommand.java:46)
    org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler$ReplicableCommandRunner.run(GlobalInboundInvocationHandler.java:156)
    org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleReplicableCommand(GlobalInboundInvocationHandler.java:133)
    org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:79)
    org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1527)
    org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1454)
    org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1649)
    org.jgroups.JChannel.up(JChannel.java:748)
    org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:941)
    org.jgroups.protocols.FRAG2.up(FRAG2.java:139)
    org.jgroups.protocols.FlowControl.up(FlowControl.java:253)
    org.jgroups.protocols.FlowControl.up(FlowControl.java:261)
    org.jgroups.protocols.pbcast.GMS.up(GMS.java:850)
    org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:235)
    org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1144)
    org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:880)
    org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:862)
    org.jgroups.protocols.UNICAST3.up(UNICAST3.java:474)
    org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:669)
    org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
    org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
    org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:190)
    org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
    org.jgroups.protocols.Discovery.up(Discovery.java:296)
    org.jgroups.stack.Protocol.up(Protocol.java:360)
    org.jgroups.protocols.TP.passMessageUp(TP.java:1230)
    org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:95)
    java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
    java.base/java.lang.VirtualThread.run(VirtualThread.java:329)

```

### Implementation ideas

Use a `ReentrantLock` to replace synchronized as outlined in  https://foojay.io/today/lets-replace-the-synchronized-keyword/

### PR DESCRIPTION
**Pull request by ahus1**
Closes #14028

This is my attempt to resolve this thread pinning. 

It would be great to have that eventually in 15.0.x - thanks!

### CODE REVIEW

**Comment by ahus1** [comment]
@pruivo - I know that you consider this a rare case, still I'd like to clear this one out so we can use the JDK log option spot other potential problems. 

Please let me hear your thoughts on this one, and my wish to backport this one to 15.0.x. Thanks!

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
@wburns I may need your expertise here. It looks like BlockHound doesn't detect `synchronized` blocks. 
We are trying to replace them with locks because of the virtual thread pinning, but the test suite is failing with errors like the ones below. 

Would it be ok to ignore the class in BlockHound? I'm slightly concerned about losing BlockHound though...
```
15:17:38,040 ERROR (non-blocking-thread-MergePolicyCustomTest-NodeA-p4196-t1:[]) [o.i.t.TopologyManagementHelper] Failed to execute ReplicableCommand RebalancePhaseConfirmCommand{cacheName='defaultcache', origin=MergePolicyCustomTest-NodeA, throwable=null, topologyId=34, viewId=11} on coordinator async: Blocking call! jdk.internal.misc.Unsafe#park on thread Thread[#11849,non-blocking-thread-MergePolicyCustomTest-NodeA-p4196-t1,5,ISPN-non-blocking-group]
java.lang.AssertionError: Blocking call! jdk.internal.misc.Unsafe#park on thread Thread[#11849,non-blocking-thread-MergePolicyCustomTest-NodeA-p4196-t1,5,ISPN-non-blocking-group]
	at org.infinispan.util.CoreTestBlockHoundIntegration.lambda$applyTo$0(CoreTestBlockHoundIntegration.java:51) ~[test-classes/:?]
	at reactor.blockhound.BlockHound$Builder.lambda$install$8(BlockHound.java:488) ~[blockhound-1.0.10.RELEASE.jar:?]
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:89) ~[?:?]
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java) ~[?:?]
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221) ~[?:?]
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754) ~[?:?]
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:990) ~[?:?]
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153) ~[?:?]
	at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322) ~[?:?]
	at org.infinispan.topology.ClusterCacheStatus.confirmRebalancePhase(ClusterCacheStatus.java:371) ~[classes/:?]
	at org.infinispan.topology.ClusterTopologyManagerImpl.handleRebalancePhaseConfirm(ClusterTopologyManagerImpl.java:340) ~[classes/:?]
```

File: core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java [hunk 1]
```diff
@@ -1179,60 +1288,75 @@ private class ConflictResolution {
...
-
-                  // TODO When CR fails because a node left the cluster, the new CR can start before we cancel the old one
-                  Log.CLUSTER.failedConflictResolution(cacheName, topology, rootCause);
-                  eventLogger.error(EventLogCategory.CLUSTER, MESSAGES.conflictResolutionFailed(
-                     topology.getMembers(), topology.getTopologyId(), rootCause.getMessage()));
-                  // If a node is suspected then we can't restart the CR until a new view is received, so we leave conflictResolution != null
-                  // so that on a new view restartConflictResolution can return true
-                  if (!(rootCause instanceof SuspectException)) {
+      CompletableFuture<Void> queue(CacheTopology topology, Set<Address> preferredNodes) {
+         lock.lock();
```
Comment (luneo7) [inline core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java:1292]: Should this use the external lock or a specific lock for `ConflictResolution`? The previous `synchronized` made Java use the inner class object, so the lock happened in the inner class instance, and not in the outer class, using the lock of the outer class now in a rough look seems change the behaviour now, as it won't be possible to queue, any more `conflictResolution` unless a resolution completed.
If the synchronized wasn't in the method, but a block like this:
```java
  synchronized(ClusterCacheStatus.this) {
     ...
  }
```
^ then it would use the outer class object instance to lock.... and it would make much sense to reuse the lock created in the outer class now... but as it a synchronized method that uses a lock in the inner class object instance... doing the shared lock now seems we are changing the locking behaviour...
Just food for thought though...

**Comment by wburns** [comment]
> @wburns I may need your expertise here. It looks like BlockHound doesn't detect `synchronized` blocks. We are trying to replace them with locks because of the virtual thread pinning, but the test suite is failing with errors like the ones below.
> 
> Would it be ok to ignore the class in BlockHound? I'm slightly concerned about losing BlockHound though...
> 
> ```
> 15:17:38,040 ERROR (non-blocking-thread-MergePolicyCustomTest-NodeA-p4196-t1:[]) [o.i.t.TopologyManagementHelper] Failed to execute ReplicableCommand RebalancePhaseConfirmCommand{cacheName='defaultcache', origin=MergePolicyCustomTest-NodeA, throwable=null, topologyId=34, viewId=11} on coordinator async: Blocking call! jdk.internal.misc.Unsafe#park on thread Thread[#11849,non-blocking-thread-MergePolicyCustomTest-NodeA-p4196-t1,5,ISPN-non-blocking-group]
> java.lang.AssertionError: Blocking call! jdk.internal.misc.Unsafe#park on thread Thread[#11849,non-blocking-thread-MergePolicyCustomTest-NodeA-p4196-t1,5,ISPN-non-blocking-group]
> 	at org.infinispan.util.CoreTestBlockHoundIntegration.lambda$applyTo$0(CoreTestBlockHoundIntegration.java:51) ~[test-classes/:?]
> 	at reactor.blockhound.BlockHound$Builder.lambda$install$8(BlockHound.java:488) ~[blockhound-1.0.10.RELEASE.jar:?]
> 	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:89) ~[?:?]
> 	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java) ~[?:?]
> 	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221) ~[?:?]
> 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754) ~[?:?]
> 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:990) ~[?:?]
> 	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153) ~[?:?]
> 	at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322) ~[?:?]
> 	at org.infinispan.topology.ClusterCacheStatus.confirmRebalancePhase(ClusterCacheStatus.java:371) ~[classes/:?]
> 	at org.infinispan.topology.ClusterTopologyManagerImpl.handleRebalancePhaseConfirm(ClusterTopologyManagerImpl.java:340) ~[classes/:?]
> ```

Correct, BlockHound does not detect synchronized blocks. You have to mark the method as blocking like https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java#L125.

You can ignore a specific method, but I can take a look as well.

**Comment by wburns** [comment]
> Would it be ok to ignore the class in BlockHound? I'm slightly concerned about losing BlockHound though...

Honestly, it should be fine as long as you limit exceptions to only class/methods that hold onto the lock startup/shutdown or for a short period infrequently. This appears it should qualify as the operation is performed asynchronously.

I would recommend adding a method to the ClusterCacheStatus method that calls to the lock and unlock method and then adding those methods as exclusions to the Integration. An example is 

https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java#L218
https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java#L64

File: core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java (hunk 1 above)
Comment (ahus1) [reply core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java:1292]: This change is only present in the later versions of this PR. It was an attempt to make the tests green, but now it seems that I need to change things with Blockhound as William suggested.

**Comment by ahus1** [comment]
@pruivo - can you please approve the build? The change are IMHO now in line what @wburns suggested, and they are green on my local machine for the core tests. Thanks!

**Comment by ahus1** [comment]
@pruivo / @ryanemerson - the Operator Upgrade Tests are failing. Can someone help out here, is it related to this PR?

**Comment by pruivo** [comment]
merged! Thanks @ahus1 !
