### PR TITLE
[#15974] Test start procedure resiliency

### LINKED ISSUE #15974: Test start resilience
### Description

Sometimes, a cache manager (or server) might start with caches that end with a FAILED state. For example, an invalid configuration, a stateful node joining a stateless node after a graceful shutdown. As such, we must verify the resiliency of the start mechanism to ensure the cache manager still starts correctly. The cache manager should start, and the failed caches should remain in a FAILED state until further intervention.

The same applies to the server. If a cache has failed to start, the server should **not** shut down and exit. We must also test the resiliency of the server with invalid caches. If instead, the cache _manager_ has failed to start, then it is reasonable to stop the server.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Verify the cache manager does not fail to start with an invalid cache.
* Verify the server does not fail to start with an invalid cache.

Closes #15974.

### CODE REVIEW

File: core/src/test/java/org/infinispan/manager/FailedCacheDefinitionTest.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+import org.infinispan.test.AbstractInfinispanTest;
+import org.infinispan.test.TestingUtil;
+import org.infinispan.test.fwk.TestCacheManagerFactory;
+import org.infinispan.topology.CacheJoinException;
+import org.testng.annotations.Test;
+
+@Test(groups = "functional", testName = "manager.FailedCacheDefinitionTest")
+public class FailedCacheDefinitionTest extends AbstractInfinispanTest {
+
+   public void testJoinStatelessWithState(Method m) {
```
Comment (jabolina) [inline core/src/test/java/org/infinispan/manager/FailedCacheDefinitionTest.java:26]: We can also add more tests that create caches in an invalid way. Any ideas are welcome to increase coverage.

**Comment by tristantarrant** [comment]
Nice one, merged.
Thanks!
