### PR TITLE
[#17251] Persistence manager stop hang

### LINKED ISSUE #17251: Persistence manager hangs with cancelled defered lock release
### Describe the bug

`PersistenceManagerImpl` uses a `StampedLock` to guard access to stores. Several methods acquire a read lock and defer its release to a `.whenComplete` callback on the returned `CompletionStage`.

If the underlying stage is never completed (e.g., the calling thread is interrupted during a topology update while `stop()` runs concurrently), the `.whenComplete` callback never fires. The read lock is permanently leaked, and `stop()` blocks indefinitely on `StampedLock.writeLock()`. This causes the system to hang and never stop.

We either have to enforce every storage to complete any pending operations in a stop/interrupt, or we update the persistence manager to track the pending operations and complete them exceptionally during a stop.

This happens intermitently when CI hangs during execution.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Concurrent operation to the underlying storage can defer the lock release.
* If the underlying storage doesn't properly stop all pending operations during a stop/interrupt, the operations never complete at the manager.
* This causes the manager to block indefinitely while waiting for the read lock release.

Closes: #17251

---

Author Checklist (all must be checked):
- [X] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [X] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [X] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [ ] ~The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.~
- [ ] ~Log messages of level `INFO` and above have been internationalized.~
- [ ] ~If the PR affects performance, include before/after benchmarks.~
- [ ] ~If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).~
- [ ] ~If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.~

---

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
failing test fixed in another PR

**Comment by pferraro** [comment]
@karesti @jabolina We ran into this issue on 16.0.9.  Can we backport this fix to 16.0.x?  Thanks!

**Comment by jabolina** [comment]
Sounds good, I'll open backports for 16.1.x/16.0.x.

/cc @tristantarrant @alanfx

File: core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java [hunk 1]
```diff
@@ -417,11 +423,29 @@ private CompletionStage<Void> updatePersistenceAvailability(NonBlockingStore<?,
...
    public void stop() {
       AggregateCompletionStage<Void> allStage = CompletionStages.aggregateCompletionStage();
-      long stamp = acquireWriteLock();
+
+      // Complete all pending stages before acquiring the write lock.
+      // If the write lock is not acquired, it means there is something holding the read lock, and it should include the
+      // pending operation to the pendingStages queue.
+      long stamp;
+      CompletionStage<?> stage;
+      while ((stage = pendingStages.poll()) != null || (stamp = tryAcquireWriteLock()) == 0) {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java:444]: We need to have a timeout for this. It is completely possible that while shutting down that it could take some time for some components to process something. This could cause things like stores to not persist stop data before the process is killed or caches to reference dependent caches that may then be shut down.
