### PR TITLE
[#14559] Use bulk strings in RESP HELLO response

### LINKED ISSUE #14559: RESP HELLO 3 should reply with bulk strings
### Describe the bug

wrong "HELLO 3" response

### Expected behavior

Answer should be like:

Image

### Actual behavior

Image

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #14559

### CODE REVIEW

**Comment by rigazilla** [comment]
@tristantarrant seems that the CLUSTER SHARDS command has a similar bug. Want to fix here?

**Comment by tristantarrant** [comment]
I've fixed all commands which used simple string instead of bulk string

**Review by rigazilla — APPROVED** [review]

File: server/resp/src/main/java/org/infinispan/server/resp/serialization/Resp3Type.java [hunk 1]
```diff
@@ -69,6 +72,23 @@ public void serialize(Object object, ResponseWriter writer) {
...
+         if (object instanceof CharSequence s) {
+            writer.string(s);
+         } else if (object instanceof Number n) {
+            writer.integers(n);
+         } else if (object instanceof Collection<?> c) {
+            writer.array(c, AUTO);
+         } else if (object instanceof Map<?,?> m) {
+            writer.map(m, AUTO);
+         } else {
+            throw new UnsupportedOperationException();
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/serialization/Resp3Type.java:89]: It should be possible to invoke `writer.serialize(object)` if it is unknown. But that could cover an underlying issue.

**Review by jabolina — APPROVED** [review]

**Comment by rigazilla** [comment]
thanks @tristantarrant
