### PR TITLE
[#14621] Fix PreferConsistencyRestartTest

### LINKED ISSUE #14621: Flaky test: org.infinispan.partitionhandling.PreferConsistencyRestartTest#testOnlyFreshNodeLeftDuringDegraded\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/14589911939
org.opentest4j.AssertionFailedError: 
expected: DEGRADED_MODE
 but was: null
	at org.infinispan.partitionhandling.PreferConsistencyRestartTest.testOnlyFreshNodeLeftDuringDegraded(PreferConsistencyRestartTest.java:68)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #14635: Flaky test: org.infinispan.partitionhandling.PreferConsistencyRestartTest#testCompletelyNewClusterWhileDegraded\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/14633325885
org.infinispan.partitionhandling.AvailabilityException: ISPN000305: Cluster is operating in degraded mode because of node failures.
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.infinispan.marshall.protostream.impl.MarshallableThrowable.getInstance(MarshallableThrowable.java:119)
	at org.infinispan.marshall.protostream.impl.MarshallableThrowable.lambda$recreateGenericThrowable$2(MarshallableThrowable.java:93)
	at org.infinispan.marshall.protostream.impl.MarshallableThrowable.create(MarshallableThrowable.java:111)
	at org.infinispan.marshall.protostream.impl.MarshallableThrowable.recreateGenericThrowable(MarshallableThrowable.java:93)
	at org.infinispan.marshall.protostream.impl.MarshallableThrowable.get(MarshallableThrowable.java:78)
	at org.infinispan.remoting.responses.ExceptionResponse.getException(ExceptionResponse.java:31)
	at org.infinispan.remoting.transport.ValidResponseCollector.addResponse(ValidResponseCollector.java:29)
	at org.infinispan.remoting.transport.impl.SingleTargetRequest.addResponse(SingleTargetRequest.java:69)
	at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:44)
	at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1531)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1431)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1600)
	at org.jgroups.JChannel.up(JChannel.java:626)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:939)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:137)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:782)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:235)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1165)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:896)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:878)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:489)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:645)
	at org.jgroups.protocols.Discovery.up(Discovery.java:296)
	at org.jgroups.stack.Protocol.up(Protocol.java:360)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1146)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:105)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: org.infinispan.commons.util.logging.TraceException
		at org.infinispan.interceptors.impl.SimpleAsyncInvocationStage.get(SimpleAsyncInvocationStage.java:39)
		at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:240)
		at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:329)
		at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:112)
		at org.infinispan.cache.impl.CacheImpl.size(CacheImpl.java:510)
		at org.infinispan.cache.impl.CacheImpl.size(CacheImpl.java:505)
		at org.infinispan.cache.impl.AbstractDelegatingCache.size(AbstractDelegatingCache.java:372)
		at org.infinispan.partitionhandling.PreferConsistencyRestartTest.testCompletelyNewClusterWhileDegraded(PreferConsistencyRestartTest.java:135)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
		at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
		at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
		at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
		at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
		at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
		at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
		at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
		at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
		at org.testng.TestRunner.privateRun(TestRunner.java:648)
		at org.testng.TestRunner.run(TestRunner.java:505)
		at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
		at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
		at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
		at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		... 3 more

org.opentest4j.AssertionFailedError: 
expected: DEGRADED_MODE
 but was: null
	at org.infinispan.partitionhandling.PreferConsistencyRestartTest.testOnlyFreshNodeLeftDuringDegraded(PreferConsistencyRestartTest.java:68)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #14652: Flaky test: org.infinispan.partitionhandling.PreferConsistencyRestartTest#testCoordinatorChangesWhileDegraded
### Github Job:https://github.com/infinispan/infinispan/actions/runs/14704075805
org.opentest4j.AssertionFailedError: 
expected: DEGRADED_MODE
 but was: null
	at org.infinispan.partitionhandling.PreferConsistencyRestartTest.testCoordinatorChangesWhileDegraded(PreferConsistencyRestartTest.java:160)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### PR DESCRIPTION
**Pull request by jabolina**
* Need to wait until cluster topology manager moves to coordinator

Closes #14621
Closes #14635
Closes #14652

### CODE REVIEW

File: core/src/test/java/org/infinispan/partitionhandling/PreferConsistencyRestartTest.java [hunk 1]
```diff
@@ -182,6 +186,11 @@ public void testCoordinatorChangesWhileDegraded() throws Exception {
       checkPersistentUUIDMatch(addressMappings);
    }
 
+   private void eventuallyClusterTopologyCoordinator(int index) {
+      ClusterTopologyManager ctm = TestingUtil.extractGlobalComponent(manager(index), ClusterTopologyManager.class);
+      eventually(() -> ctm.getStatus() == ClusterTopologyManager.ClusterManagerStatus.COORDINATOR);
```
Comment (wburns) [inline core/src/test/java/org/infinispan/partitionhandling/PreferConsistencyRestartTest.java:191]: Was this an issue before? I am confused why this is happening now and why the ClusterTopologyManager would be in a different state that the manager itself as we assert it is the coordinator just a few lines above with `assertThat(manager(0).isCoordinator()).isTrue();`. Can you confirm why?

Comment (jabolina) [reply core/src/test/java/org/infinispan/partitionhandling/PreferConsistencyRestartTest.java:191]: Looks like it was always there, but even now I wasn't able to reproduce locally, only following CI logs :(

These coordinator statuses are different. The cluster coordinator (the check in the lines above) eventually becomes the coordinator for handling the topology as well. _Eventually_ here because it must recover first. After a view change, if the `ClusterTopologyManager` becomes the cluster coordinator, it will broadcast a message to retrieve the cache statuses from every other node `CacheStatusRequestCommand` and rebuild the cache information from this. It only becomes the `ClusterTopologyManager.ClusterManagerStatus.COORDINATOR` after the recovery procedure is finished.

https://github.com/infinispan/infinispan/blob/a445264f8d539a4b6fffb28dd1220b3a462c0602/core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java#L456

The big caveat here is what was causing the test to fail: some of the methods will treat the cache as non-existent while it is recovering because it is not in the cache status map.
