### PR TITLE
[#14924] GLOBAL components should not start caches in their start method

### LINKED ISSUE #14924: GLOBAL components should not start caches in their start method
### Describe the bug

Some GLOBAL components have @start annotated methods that initialize a cache or sometimes many. This causes dependency startup issues as some caches require many different global components which may or may not have been started at this point. It also causes many issues if that cache fails to start as it causes the global component registry to fail which may shut down the cache in the incorrect order.

We should not allow any cache to be started until the global component registry has been officially started.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
Fixes #14924

Also prevent starting/retrieving caches from the CacheManger until it is started since it requires the global registry to be running.

### CODE REVIEW

**Comment by wburns** [comment]
I ensured core was updated, but other modules may still have issues, CI should confirm.

File: core/src/main/java/org/infinispan/manager/DefaultCacheManager.java [hunk 1]
```diff
@@ -523,6 +523,11 @@ private <K, V> Cache<K, V> internalGetCache(String cacheName) {
       if (cacheName == null)
          throw new NullPointerException("Null arguments not allowed");
 
+      // Caches retrieved during global registry should only be done post startup so it must not be initializing
+      if (globalComponentRegistry.getStatus() == ComponentStatus.INITIALIZING) {
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/manager/DefaultCacheManager.java:527]: Maybe we should use `.allowInvocations()`, in the status? This would allow to retrieve a cache in stopped or failed status.

File: core/src/main/java/org/infinispan/security/mappers/ClusterPermissionMapper.java [hunk 2]
```diff
@@ -39,13 +39,16 @@ public class ClusterPermissionMapper implements MutableRolePermissionMapper {
...
-   void start() {
+   @Override
+   public void start() {
       initializeInternalCache();
       clusterPermissionMap = cacheManager.getCache(CLUSTER_PERMISSION_MAPPER_CACHE);
       clusterPermissionReadMap = clusterPermissionMap.getAdvancedCache().withFlags(Flag.SKIP_CACHE_LOAD, Flag.CACHE_MODE_LOCAL);
    }
 
+   @Override
+   public void stop() { }
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/security/mappers/ClusterPermissionMapper.java:50]: Stop the caches? Same to the `ClusterRolerMapper`.

File: core/src/main/java/org/infinispan/manager/DefaultCacheManager.java [hunk 3]
```diff
@@ -773,11 +778,46 @@ private void internalStart(boolean block) {
       try {
          globalComponentRegistry.getComponent(CacheManagerJmxRegistration.class).start();
          globalComponentRegistry.start();
+         // Some caches are started during postStart and we have to extract it out
+         globalComponentRegistry.postStart();
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/manager/DefaultCacheManager.java:782]: Chicken and egg problem. If a component verifies if the manager is running, would it fail? However, we can't set it to RUNNING before finishing the post-start.

File: core/src/main/java/org/infinispan/CoreModule.java [hunk 4]
```diff
@@ -1,11 +1,43 @@
...
+      gcr.getComponent(GlobalConfigurationManager.class).postStart();
+      startLifecycleComponent(gcr, RolePermissionMapper.class, PrincipalRoleMapper.class);
+   }
+
+   @Override
+   public void cacheManagerStopping(GlobalComponentRegistry gcr) {
+      stopLifecycleComponent(gcr, RolePermissionMapper.class, PrincipalRoleMapper.class);
+   }
+
+   public static void startLifecycleComponent(GlobalComponentRegistry gcr, Class<?>... klasses) {
```
[the remark this answers is not in the document]
Comment (wburns) [reply core/src/main/java/org/infinispan/CoreModule.java:27]: Actually, this is not a good place to do it..

[the remark this answers is not in the document]
Comment (wburns) [reply core/src/main/java/org/infinispan/CoreModule.java:27]: I do this now for all module lifecycles here https://github.com/infinispan/infinispan/pull/14925/files#diff-39e03c9907035ebb7ac30034f3307dc471a6e68515f0c60f44919567f45d04b4R294

**Comment by wburns** [comment]
Fixing the failures that just popped as the tests are now being identified that never bothered to start the cache manager in the past...

**Comment by wburns** [comment]
Updated some more tests to actually start the cache manager.. not sure why report result wasn't generated as the steps finished fine. Hopefully next run comes out better :crossed_fingers:

**Comment by jabolina** [comment]
Thanks, @wburns!
