### PR TITLE
[#16916] Graceful shutdown handle network partition

### LINKED ISSUE #16916: Data loss performing graceful shutdown
### Describe the bug

The problem happens when there are network partitions during the restart of the graceful shutdown procedure. We have observed data loss when the cluster is partitioned into a star-like partition. The coordinator can connect to all nodes, but the nodes are unable to connect to each other.

In this star partition, the nodes will suspect each other at the JGroups level. This causes messages to be dropped to certain nodes. But since the coordinator receives the join request from all nodes, it thinks the cluster is stable and tries to install a stable topology. In addition, it enables state transfer in some of the nodes.

Once the network stabilizes, a merge view is installed with all nodes. Since state transfer was enabled in some nodes, the consistent hashing doesn't match what it was before the shutdown. This is causing data loss.

More concretely, we have observed this behavior when performing an upgrade in Kubernetes. The JGroups stack uses `DNS_PING`, which is cached (both at JDK and in Kubernetes). Starting a cluster, the coordinator publishes its IP. The second node can connect to the coordinator, but because the DNS is cached, a third node will only see the coordinator, and not node 2. This causes the nodes to suspect each other and cause the partition. The merge only happens after the DNS cache is flushed.

In this case, the workaround is to disable the DNS cache in Kubernetes. At least while performing the graceful shutdown procedure. This allows the nodes to always resolve all members because the Infinispan operator publishes the addresses even before the pods are ready.

### Expected behavior

The graceful shutdown procedure should never lose data, even during network partitions.

### Actual behavior

If a network partition occurs, where the coordinator receives all the joins, but they split afterward, the procedure still installs the topology as stable. This leads to data loss as the consistent hash is different.

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* During a network partition, the stable topology could be installed only inside the partition in which the coordinator is.
* The nodes that install the stable topology will become "stateless" by deleting the consistent hash from persistent state.
* The nodes in the other partition become unable to join the cluster, since they are "stateful" with the persistent state.
* The stable topology was never properly recovered.
* The coordinator would broadcast a stable topology with restore=false, and the nodes would clear the storage and lose data.

To avoid this scenario, I've made changes mostly in the topology package so:

* During the stable topology restore from state, the coordinator will track the UUID of the nodes. As long as the array of UUIDs is not empty, no rebalance can happen, and no "stateless" joiner can join.
* The UUID is only removed from the array after the node confirms the stable topology broadcast. This only happens when restoring from a graceful shutdown. In all other cases, it continues a fire-and-forget method.
* When handling a merge, the nodes insert in the CacheStatus response whether they had a stable topology. The coordinator can utilize this information to know whether it is in the middle of recovering the stable topology.

I've added a test that tries to reproduce the star topology. And another test that creates a clean partition during the restore.

Close #16916.

### CODE REVIEW

**Comment by jabolina** [comment]
Creating as draft so I can have an image to test with the operator.

**Comment by jabolina** [comment]
I'll rebase it once we fix the rolling upgrades, but we know it is passing with 16.0.1.

I have tested it with the original reproducing by deploying it with the operator, and it fixes the issue. There was no data loss performing an upgrade with the operator.

The current implementation takes a path similar to a 2PC. This path is utilized ONLY when restoring the stable topology from the persistent state. Everything else remains the same.

The approach uses two phases when restoring the topology. The first phase broadcasts the stable topology to all nodes, and a second broadcast deletes the persistent state. This way, even if there is a network partition, a node crashes or leaves before the restore is completed, we won't lose any data. Until the restore completes, no rebalance is performed. This ensures the consistent hash doesn't change.

File: core/src/main/java/org/infinispan/commands/topology/RebalancePolicyUpdateCommand.java [hunk 1]
```diff
@@ -44,6 +44,7 @@ public NodeVersion supportedSince() {
    public String toString() {
       return "RebalanceEnableCommand{" +
             "cacheName='" + cacheName + '\'' +
+            ", value=" + enabled +
```
Comment (wburns) [inline core/src/main/java/org/infinispan/commands/topology/RebalancePolicyUpdateCommand.java]:
```suggestion
            ", enabled=" + enabled +
```

File: core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java [hunk 2]
```diff
@@ -204,6 +204,21 @@ public Set<Integer> getPrimarySegmentsForOwner(Address owner) {
       return segments;
    }
 
+   @Override
+   public ConsistentHash transform(Function<Address, Address> mapper) {
+      List<Address> remappedMembers = members.stream().map(mapper).toList();
+      Map<Address, Float> remappedCf = new HashMap<>();
+      for (int i = 0; i < members.size(); i++) {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java:211]: We should be able to consolidate this loop with the stream used above.

**Review by wburns — APPROVED** [review]
Minor things, looks alright to me.

File: core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java [hunk 3]
```diff
@@ -792,7 +891,22 @@ public CacheStatusResponse doJoin(Address joiner, CacheJoinInfo joinInfo) {
...
+   }
+
+   /**
+    * Verify whether a joiner is a member missing from the previous topology.
+    *
+    * @param cji The joiner information
+    * @return {@code true} if the joiner UUID is listed as missing. {@code false}, otherwise.
+    */
+   private boolean isRejoiningFromPersistentState(CacheJoinInfo cji) {
+      acquireLock();
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java]: AFAICT you are calling this while the the lock has already been acquired. I guess this is harmless, but still redundant.

File: core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java [hunk 4]
```diff
@@ -1122,6 +1313,25 @@ public void forceRebalance() {
...
+    *
+    * <p>
+    * This execution is triggered in case the cluster is recovering from a graceful shutdown procedure. Until the stable
+    * topology is restored, no rebalancing should happen.
+    * </p>
+    *
+    * @return {@code true} if a stable topology is restoring. {@code false}, otherwise.
+    */
+   public boolean isRestoringStableTopology() {
+      acquireLock();
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java]: I believe all call sites are already holding the lock when calling this method. I guess this is harmless, but still redundant.

File: core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java [hunk 5]
```diff
@@ -942,6 +1127,12 @@ public CompletionStage<Void> doLeave(Address leaver) {
    public void startQueuedRebalance() {
       acquireLock();
       try {
+         if (isRestoringStableTopology()) {
+            log.debugf("Postponing rebalance for cache %s, waiting for stable topology confirmations from %s",
+                  cacheName, resolveConflictsOnMerge);
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java]: shouldn't this be `restoredMembers` ?

File: core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java [hunk 6]
```diff
@@ -842,15 +957,60 @@ private CacheTopology cacheTopologyCreated(CacheTopology topology) {
...
+      List<Address> remappedMembers = new ArrayList<>(oldMembers.size());
+      for (Address oldAddr : oldMembers) {
+         UUID uuid = persistentUUIDManager.getPersistentUuid(oldAddr);
+         Address newAddr = persistentUUIDManager.getAddress(uuid);
+         mapper.put(oldAddr, newAddr);
+         remappedMembers.add(newAddr);
+      }
+
+      ConsistentHash remappedCH = currentTopology.getCurrentCH().transform(addr -> mapper.getOrDefault(addr, addr));
+      int topologyId = currentTopology == null ? stableTopology.getTopologyId() : currentTopology.getTopologyId() + 1;
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java]: useless null check here: if `currentTopology` is null then we'd get an NPE on the dereference in the line above

File: core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java [hunk 7]
```diff
@@ -259,6 +259,12 @@ public Set<Integer> getPrimarySegmentsForOwner(Address owner) {
       return primarySegments;
    }
 
+   @Override
+   public ConsistentHash transform(Function<Address, Address> mapper) {
+      List<Address> remappedMembers = members.stream().map(mapper).toList();
+      return new ReplicatedConsistentHash(remappedMembers, capacityFactors, membersWithoutState, primaryOwners);
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java]: `DefaultConsistentHash` also remaps the owners. Shouldn't this method also do that ?

**Review by tristantarrant — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java (hunk 4 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java]: Changed it to private and removed the acquireLock calls.

**Comment by jabolina** [comment]
Thanks, applied all suggestions.

**Comment by jabolina** [comment]
Too many failures, let me take a look

**Comment by tristantarrant** [comment]
I have seen db failures in other PRs

**Comment by jabolina** [comment]
```
2026-03-30T20:25:24.4783432Z 20:25:24,465 ERROR [t.l.i.s.r.r.1.0.1] received unexpected HTTP status: 502 Bad Gateway
2026-03-30T20:25:24.4787078Z 20:25:24,466 ERROR [o.i.s.t.c.InfinispanServerDriver] Unable to start server org.infinispan.server.rollingupgrade.RollingUpgradeTaskTestIT-16.0.1com.github.dockerjava.api.exception.DockerClientException: Could not build image: received unexpected HTTP status: 502 Bad Gateway
2026-03-30T20:25:24.4790544Z    at com.github.dockerjava.api.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:78)
2026-03-30T20:25:24.4792319Z    at com.github.dockerjava.api.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:50)
2026-03-30T20:25:24.4793945Z    at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:165)
2026-03-30T20:25:24.4795749Z    at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:43)
2026-03-30T20:25:24.4797072Z    at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
2026-03-30T20:25:24.4798134Z    at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
2026-03-30T20:25:24.4799585Z    at org.infinispan.server.test.core.ContainerInfinispanServerDriver.configureImage(ContainerInfinispanServerDriver.java:306)
2026-03-30T20:25:24.4801752Z    at org.infinispan.server.test.core.ContainerInfinispanServerDriver.start(ContainerInfinispanServerDriver.java:158)
2026-03-30T20:25:24.4803740Z    at org.infinispan.server.test.core.AbstractInfinispanServerDriver.start(AbstractInfinispanServerDriver.java:137)
2026-03-30T20:25:24.4805790Z    at org.infinispan.server.test.core.rollingupgrade.RollingUpgradeHandler.startNode(RollingUpgradeHandler.java:479)
2026-03-30T20:25:24.4807709Z    at org.infinispan.server.test.core.rollingupgrade.RollingUpgradeHandler.startOldCluster(RollingUpgradeHandler.java:246)
2026-03-30T20:25:24.4809636Z    at org.infinispan.server.test.core.rollingupgrade.RollingUpgradeHandler.startOldCluster(RollingUpgradeHandler.java:222)
2026-03-30T20:25:24.4811544Z    at org.infinispan.server.test.core.rollingupgrade.RollingUpgradeHandler.runUntilMixed(RollingUpgradeHandler.java:208)
2026-03-30T20:25:24.4813430Z    at org.infinispan.server.test.core.rollingupgrade.RollingUpgradeHandler.performUpgrade(RollingUpgradeHandler.java:326)
2026-03-30T20:25:24.4815575Z    at org.infinispan.server.rollingupgrade.RollingUpgradeTaskTestIT.testHelloWorldTask(RollingUpgradeTaskTestIT.java:44)
2026-03-30T20:25:24.4817354Z    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
2026-03-30T20:25:24.4818585Z    at java.base/java.lang.reflect.Method.invoke(Method.java:565)
2026-03-30T20:25:24.4819729Z    at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:786)
2026-03-30T20:25:24.4821196Z    at org.junit.platform.commons.support.ReflectionSupport.invokeMethod(ReflectionSupport.java:514)
2026-03-30T20:25:24.4822650Z    at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2026-03-30T20:25:24.4824315Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2026-03-30T20:25:24.4826212Z    at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:161)
2026-03-30T20:25:24.4827697Z    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:152)
2026-03-30T20:25:24.4829246Z    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:91)
2026-03-30T20:25:24.4831210Z    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:112)
2026-03-30T20:25:24.4833347Z    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:94)
2026-03-30T20:25:24.4875769Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2026-03-30T20:25:24.4877761Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2026-03-30T20:25:24.4879560Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2026-03-30T20:25:24.4881343Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2026-03-30T20:25:24.4883114Z    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:93)
2026-03-30T20:25:24.4884874Z    at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:87)
2026-03-30T20:25:24.4886882Z    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$4(TestMethodTestDescriptor.java:221)
2026-03-30T20:25:24.4888659Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2026-03-30T20:25:24.4890464Z    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:217)
2026-03-30T20:25:24.4892190Z    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:159)
2026-03-30T20:25:24.4894030Z    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:70)
2026-03-30T20:25:24.4896053Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:157)
2026-03-30T20:25:24.4897682Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2026-03-30T20:25:24.4899259Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:147)
2026-03-30T20:25:24.4900633Z    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2026-03-30T20:25:24.4902007Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:145)
2026-03-30T20:25:24.4903738Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2026-03-30T20:25:24.4905692Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:144)
2026-03-30T20:25:24.4907159Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:101)
2026-03-30T20:25:24.4908288Z    at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
2026-03-30T20:25:24.4909949Z    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2026-03-30T20:25:24.4912064Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:161)
2026-03-30T20:25:24.4913660Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2026-03-30T20:25:24.4915479Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:147)
2026-03-30T20:25:24.4916872Z    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2026-03-30T20:25:24.4918231Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:145)
2026-03-30T20:25:24.4919812Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2026-03-30T20:25:24.4921368Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:144)
2026-03-30T20:25:24.4922861Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:101)
2026-03-30T20:25:24.4923954Z    at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
2026-03-30T20:25:24.4925743Z    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2026-03-30T20:25:24.4927757Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:161)
2026-03-30T20:25:24.4929358Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2026-03-30T20:25:24.4931099Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:147)
2026-03-30T20:25:24.4932637Z    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2026-03-30T20:25:24.4934011Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:145)
2026-03-30T20:25:24.4935822Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2026-03-30T20:25:24.4937382Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:144)
2026-03-30T20:25:24.4938965Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:101)
2026-03-30T20:25:24.4940886Z    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
2026-03-30T20:25:24.4943207Z    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2026-03-30T20:25:24.4945098Z    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
2026-03-30T20:25:24.4947127Z    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.executeEngine(EngineExecutionOrchestrator.java:230)
2026-03-30T20:25:24.4948928Z    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.failOrExecuteEngine(EngineExecutionOrchestrator.java:204)
2026-03-30T20:25:24.4950676Z    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:172)
2026-03-30T20:25:24.4952321Z    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:101)
2026-03-30T20:25:24.4954056Z    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:64)
2026-03-30T20:25:24.4956180Z    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:150)
2026-03-30T20:25:24.4957975Z    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:63)
2026-03-30T20:25:24.4959417Z    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:109)
2026-03-30T20:25:24.4960655Z    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:91)
2026-03-30T20:25:24.4961937Z    at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
2026-03-30T20:25:24.4963331Z    at org.junit.platform.launcher.core.InterceptingLauncher.lambda$execute$1(InterceptingLauncher.java:39)
2026-03-30T20:25:24.4965448Z    at org.junit.platform.launcher.core.ClasspathAlignmentCheckingLauncherInterceptor.intercept(ClasspathAlignmentCheckingLauncherInterceptor.java:25)
2026-03-30T20:25:24.4967329Z    at org.junit.platform.launcher.core.InterceptingLauncher.execute(InterceptingLauncher.java:38)
2026-03-30T20:25:24.4968840Z    at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
2026-03-30T20:25:24.4970557Z    at org.apache.maven.surefire.junitplatform.LauncherAdapter.executeWithoutCancellationToken(LauncherAdapter.java:60)
2026-03-30T20:25:24.4972334Z    at org.apache.maven.surefire.junitplatform.LauncherAdapter.execute(LauncherAdapter.java:52)
2026-03-30T20:25:24.4973912Z    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:203)
2026-03-30T20:25:24.4975895Z    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:168)
2026-03-30T20:25:24.4977696Z    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:136)
2026-03-30T20:25:24.4979227Z    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2026-03-30T20:25:24.4980551Z    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2026-03-30T20:25:24.4981730Z    at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2026-03-30T20:25:24.4982886Z    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

And the blocking call is likely #17192

I'll rebase to have a proper run.

**Comment by tristantarrant** [comment]
@jabolina what happens if a node that is in `restoredMembers` leaves the cluster while the restore is still pending? It seems like  `restoredMembers` is never cleaned up and `isRestoringStableTopology()` will remain true indefinitely

**Comment by jabolina** [comment]
That's intentional; we do not allow operations in the cache. and it remains in a recovering state. A graceful shutdown requires all nodes to resume work without losing data. If that is not possible, we have the `topology set-stable` in the CLI.

Let me double-check that the `--force` flag is working properly with this setup, and I'll adjust the `topology` man page, too.

**Comment by jabolina** [comment]
I've added some tests with the procedure to restore the topology during graceful shutdown instead of waiting for all nodes. And included the man page for the topology command.

**Comment by tristantarrant** [comment]
Thanks @jabolina
