### PR TITLE
[#17133] Fix near cache scrap in spring boot metrics

### LINKED ISSUE #17133: Spring-Boot4 with ISPN Remote Near Cache - the metrics are not scrabed properly
### Describe the bug

I was working on coverage increase for Infinispan and found some strange behaviour. 
I have added a RemoteNearCacheMetricBinderTest which is extended from RemoteCacheMetricBinderTest but uses a near cache . You can find my changes here:  https://github.com/andyuk1986/infinispan/commit/b2bf2f62d57308ad65b9b57d4dfc0ab227bdbd62

Here I have faced 2 things:
1) Seems that the near cache metrics are not scraped during execution, because the nearCache size is always 0, even though there is data in the cache.

2) During the last, `dereferencedCacheIsGarbageCollected` test execution, the test fails with exception: 
`[ERROR] test.org.infinispan.spring.starter.remote.metrics.RemoteNearCacheMetricBinderTest.dereferencedCacheIsGarbageCollected -- Time elapsed: 0.056 s <<< ERROR!
org.infinispan.client.hotrod.exceptions.RemoteCacheManagerNotStartedException:: Cannot perform operations on a cache associated with an unstarted RemoteCacheManager. Use RemoteCacheManager.start before using the remote cache.
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.assertRemoteCacheManagerIsStarted(RemoteCacheImpl.java:702)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.sizeAsync(RemoteCacheImpl.java:308)
	at org.infinispan.client.hotrod.impl.DelegatingRemoteCache.sizeAsync(DelegatingRemoteCache.java:341)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.size(RemoteCacheSupport.java:398)
	at java.base/java.util.TreeMap.putAll(TreeMap.java:350)
	at java.base/java.util.TreeMap.<init>(TreeMap.java:199)
	at org.assertj.core.presentation.StandardRepresentation.toSortedMapIfPossible(StandardRepresentation.java:776)
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:514)
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:250)
	at org.assertj.core.presentation.CompositeRepresentation.toStringOf(CompositeRepresentation.java:43)
	at org.assertj.core.error.ShouldBeEqual.actualAndExpectedHaveSameStringRepresentation(ShouldBeEqual.java:141)
	at org.assertj.core.error.ShouldBeEqual.smartErrorMessage(ShouldBeEqual.java:155)
	at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:120)
	at org.assertj.core.internal.Failures.failure(Failures.java:108)
	at org.assertj.core.internal.Objects.assertNull(Objects.java:236)
	at org.assertj.core.api.AbstractAssert.isNull(AbstractAssert.java:403)
	at io.micrometer.core.instrument.binder.cache.CacheMeterBinderCompatibilityKit.dereferencedCacheIsGarbageCollected(CacheMeterBinderCompatibilityKit.java:114)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
`

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by karesti**
Fixes #17133

### CODE REVIEW

File: spring/spring-boot-4/remote/src/main/java/org/infinispan/spring/starter/remote/metrics/RemoteInfinispanCacheMeterBinder.java [hunk 1]
```diff
@@ -108,7 +109,11 @@ private void nearCacheMetrics(MeterRegistry registry) {
    }
 
    private boolean isNearCacheEnabled() {
-      return getCache().clientStatistics().getNearCacheSize() > 0;
+      RemoteCacheConfiguration remoteCacheConfiguration = getCache().getRemoteCacheContainer()
```
Comment (karesti) [inline spring/spring-boot-4/remote/src/main/java/org/infinispan/spring/starter/remote/metrics/RemoteInfinispanCacheMeterBinder.java:112]: @andyuk1986 there is well a bug, this is the fix

**Comment by andyuk1986** [comment]
Cool, thanks @karesti - I have tested. Now it works. Thanks for the fix.

**Comment by tristantarrant** [comment]
@karesti can you rebase please ?

**Comment by tristantarrant** [comment]
@jabolina db failures here too

**Comment by karesti** [comment]
@jabolina rebased

**Comment by karesti** [comment]
@jabolina could you please merge this ?

**Comment by jabolina** [comment]
Thanks, @karesti!
