### PR TITLE
[#16324] RESP jsonlen return null on legacy non existent path

### LINKED ISSUE #16324: JSON.OBJLEN should return null reply with legacy notation on nonexisting path
### Describe the bug

As per [JSON.OBJLEN](https://redis.io/docs/latest/commands/json.objlen/) requests starting with '.' should return null rather then error.

### Expected behavior

```
127.0.0.1:6379> json.get doc1
"{\"nested1\":{\"a\":{\"foo\":10,\"bar\":20}},\"a\":[\"foo\"],\"nested2\":{\"a\":{\"baz\":50}}}"
127.0.0.1:6379> json.objlen doc1 $.nowhere
(empty array)
127.0.0.1:6379> json.objlen doc1 .nowhere
(nil)
```

### Actual behavior

```
127.0.0.1:6379> json.get doc1
"{\"nested1\":{\"a\":{\"foo\":10,\"bar\":20}},\"a\":[\"foo\"],\"nested2\":{\"a\":{\"baz\":50}}}"
127.0.0.1:6379> json.objlen doc1 $.nowhere
(empty array)
127.0.0.1:6379> json.objlen doc1 .nowhere
(error) ERR Path '.nowhere' does not exist
```

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by rigazilla**
closes #16324

### CODE REVIEW

File: server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java [hunk 1]
```diff
@@ -685,12 +690,24 @@ public void testJSONOBJLEN() {
...
+      // Legacy style returns null on non-existing object.
+      jp = new JsonPath(".nonExistentPath");
+      assertThat(redis.jsonObjlen(key, jp).get(0)).isNull();
+
+      // JsonPath style returns empty array on non-existing object.
+      jp = new JsonPath("$.nonExistentPath");
+      assertThat(redis.jsonObjlen(key, jp)).isEmpty();
+
+      // Legacy style returns first result in path matching
+         assertThat(redis.jsonObjlen(key, new JsonPath("..nested"))).containsExactly(2L);
```
Comment (Crumby) [inline server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java]: Formatting

File: server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJLEN.java [hunk 2]
```diff
@@ -26,6 +26,6 @@ protected CompletionStage<List<Long>> len(EmbeddedJsonCache ejc, byte[] key, byt
 
    @Override
    protected void raiseTypeError(byte[] path) {
-      throw new RuntimeException("Path '" + RespUtil.ascii(path) + "' does not exist or not an object");
```
Comment (Crumby) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJLEN.java:29]: Interestingly enough, this error message is the correct one for OBJLEN command when executed against non-existing key. On the other hand when executing STRLEN it's knows that you are executing operation against non-existing key:

```
127.0.0.1:6379> json.objlen non_existing_doc '$..a'
(error) ERR Path '$..a' does not exist or not an object
127.0.0.1:6379> json.strlen non_existing_doc '$..a'
(error) ERR could not perform this operation on a key that doesn't exist
```

Tbh. syncing error messages with Redis in this case isn't worth it unless somebody comes complaining, they seem to be too inconsistent

Comment (rigazilla) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJLEN.java:29]: I agree. anyway I changed the code so errors are more consistent on our side

Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJLEN.java:29]: Should this be "**is** not an object" like the others?

Comment (rigazilla) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJLEN.java:29]: yep, PR has that message
