### PR TITLE
[#15688] Avoid socket timeout and retry in LockingTest. Also [#15734]

### LINKED ISSUE #15688: Flaky test: org.infinispan.client.hotrod.LockingTest#testPerEntryLockContainer
### Github Job:https://github.com/infinispan/infinispan/actions/runs/17991702585
java.util.concurrent.ExecutionException: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=43 returned server error (status=0x86): org.infinispan.commons.TimeoutException: ISPN000299: Unable to acquire lock after 100 milliseconds for key WrappedByteArray[\J03\k\e\y (5 bytes)] and requestor CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:6791. Lock is held by CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:6102
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at org.infinispan.client.hotrod.LockingTest.doLockTest(LockingTest.java:106)
	at org.infinispan.client.hotrod.LockingTest.testPerEntryLockContainer(LockingTest.java:40)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=43 returned server error (status=0x86): org.infinispan.commons.TimeoutException: ISPN000299: Unable to acquire lock after 100 milliseconds for key WrappedByteArray[\J03\k\e\y (5 bytes)] and requestor CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:6791. Lock is held by CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:6102
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2117)
	at org.infinispan.client.hotrod.impl.Util.await(Util.java:56)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:196)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:186)
	at org.infinispan.client.hotrod.LockingTest.lambda$doLockTest$0(LockingTest.java:83)
	at org.infinispan.test.AbstractInfinispanTest$CallableWrapper.call(AbstractInfinispanTest.java:554)
	... 4 more

java.util.concurrent.ExecutionException: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=37 returned server error (status=0x86): org.infinispan.commons.TimeoutException: ISPN000299: Unable to acquire lock after 100 milliseconds for key WrappedByteArray[\J03\k\e\y (5 bytes)] and requestor CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:8303. Lock is held by CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:7603
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at org.infinispan.client.hotrod.LockingTest.doLockTest(LockingTest.java:106)
	at org.infinispan.client.hotrod.LockingTest.testStrippedLockContainer(LockingTest.java:44)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=37 returned server error (status=0x86): org.infinispan.commons.TimeoutException: ISPN000299: Unable to acquire lock after 100 milliseconds for key WrappedByteArray[\J03\k\e\y (5 bytes)] and requestor CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:8303. Lock is held by CommandInvocation:86b3c4c7-ea4b-44aa-9cc8-b25a7a2e3da6:7603
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2117)
	at org.infinispan.client.hotrod.impl.Util.await(Util.java:56)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:196)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:186)
	at org.infinispan.client.hotrod.LockingTest.lambda$doLockTest$0(LockingTest.java:83)
	at org.infinispan.test.AbstractInfinispanTest$CallableWrapper.call(AbstractInfinispanTest.java:554)
	... 4 more

### LINKED ISSUE #15734: Flaky test: org.infinispan.client.hotrod.LockingTest#testStrippedLockContainer
### Github Job:https://github.com/infinispan/infinispan/actions/runs/18107595430
java.util.concurrent.ExecutionException: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=104 returned server error (status=0x86): org.infinispan.commons.TimeoutException: ISPN000299: Unable to acquire lock after 100 milliseconds for key WrappedByteArray[\J03\k\e\y (5 bytes)] and requestor CommandInvocation:3328eed0-cf33-4708-a43b-0465bd7f702c:7181. Lock is held by CommandInvocation:3328eed0-cf33-4708-a43b-0465bd7f702c:6330
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at org.infinispan.client.hotrod.LockingTest.doLockTest(LockingTest.java:106)
	at org.infinispan.client.hotrod.LockingTest.testStrippedLockContainer(LockingTest.java:44)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=104 returned server error (status=0x86): org.infinispan.commons.TimeoutException: ISPN000299: Unable to acquire lock after 100 milliseconds for key WrappedByteArray[\J03\k\e\y (5 bytes)] and requestor CommandInvocation:3328eed0-cf33-4708-a43b-0465bd7f702c:7181. Lock is held by CommandInvocation:3328eed0-cf33-4708-a43b-0465bd7f702c:6330
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2117)
	at org.infinispan.client.hotrod.impl.Util.await(Util.java:55)
	at org.infinispan.client.hotrod.impl.Util.await(Util.java:50)
	at org.infinispan.client.hotrod.impl.transport.netty.OperationDispatcher.await(OperationDispatcher.java:924)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:197)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:187)
	at org.infinispan.client.hotrod.LockingTest.lambda$doLockTest$0(LockingTest.java:83)
	at org.infinispan.test.AbstractInfinispanTest$CallableWrapper.call(AbstractInfinispanTest.java:554)
	... 4 more

### PR DESCRIPTION
**Pull request by rigazilla**
fixes #15734 
fixes #15688 

Reduced lock acquisition timeout and number of attempts to avoid socket timeout expiration and operation retry

### CODE REVIEW

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/LockingTest.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ protected void teardown() {
    @Override
    protected EmbeddedCacheManager createCacheManager() throws Exception {
       ConfigurationBuilder builder = hotRodCacheConfiguration();
-      builder.locking().lockAcquisitionTimeout(100, TimeUnit.MILLISECONDS);
+      builder.locking().lockAcquisitionTimeout(20, TimeUnit.MILLISECONDS);
```
Comment (rigazilla) [inline client/hotrod-client/src/test/java/org/infinispan/client/hotrod/LockingTest.java:58]: I'm wondering if the new timeout might be too small and could cause the first PUT to fail acquiring the lock, making the test flaky again.
@wburns wdyt?

**Comment by jabolina** [comment]
You could also add `clientBuilder.maxRetries(0);` in the `setup()` method to avoid retries.

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/LockingTest.java (hunk 1 above)
Comment (wburns) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/LockingTest.java:58]: I don't believe it it possible for an uncontested lock to timeout even if 0.

**Comment by rigazilla** [comment]
> You could also add `clientBuilder.maxRetries(0);` in the `setup()` method to avoid retries.

I suppose the first  put will fail with socket timeout then (?)

**Comment by wburns** [comment]
> > You could also add `clientBuilder.maxRetries(0);` in the `setup()` method to avoid retries.
> 
> I suppose the first put will fail with socket timeout then (?)

Correct, it will only change the flaky failure.

**Comment by wburns** [comment]
@pruivo Yeah it is good to me. It wasn't quite clear if we can integrate to main though or if we are waiting for a branch or not.

**Review by wburns — APPROVED** [review]

**Comment by wburns** [comment]
Integrated into main, thanks @rigazilla !
