### PR TITLE
[#15185] Update rolling upgrade exception handler

### LINKED ISSUE #15185: Change default exception handler in rolling upgrades
Our default exception handler is a no-op, which means, unless overridden, the tests do not fail. We need to update the default handler to mark the test as failed.

### PR DESCRIPTION
**Pull request by jabolina**
* Throws an assertion error by default.

Closes #15185.

### CODE REVIEW

**Comment by wburns** [comment]
Looks good to me. Enabled auto merge assuming CI doesn't have an issue :)

**Review by wburns — APPROVED** [review]

**Comment by wburns** [comment]
Looks like it caught something in the RESP transaction tests as well

**Comment by jabolina** [comment]
Looks like it reports the failure on the last test run in the suite. The failure is from `HotRodAdmin` and the alias test, but the `RespTransactionTest` is the last test run.

**Comment by wburns** [comment]
Ah, makes sense. So since it shuts down only at the end it only marks the last test as a failure. I wonder if we can somehow change it so the failure isn't marked as for that test but somehow for the suite instead.

**Comment by jabolina** [comment]
Yeah, planning on doing that here. I want to get the fix to aliases first and will come back to this one.

**Comment by jabolina** [comment]
I had a hard time finding a nice solution for this. I've tried creating a report file for failsafe, but that gets tricky quickly and would have many sharp corners. The current version will add to the exception message which test suite failed to perform.

If the test method fails, failsafe correctly reports it. It is a bit confusing to identify which test suite (e.g., `CacheOperations` running in`ClusteredRollingUpgradeIT` or `ClusteredIT`?) but it does report the correct test.
If it fails during the lifecycle methods of the test suite, there is no way to trace to which test that caused the lifecycle operation to fail. With the current change, the exception message will include the test suite name.

**Comment by jabolina** [comment]
I've removed the auto-merge so reviewers can take another look.

**Review by wburns — APPROVED** [review]

**Comment by jabolina** [comment]
The failure shows like:

image


I'll rebase this PR with main now for a final execution.

**Comment by jabolina** [comment]
Looks like some tests still failing even after rebase :(

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java [hunk 1]
```diff
@@ -192,6 +193,10 @@ public STATE getCurrentState() {
       return currentState;
    }
 
+   public void utilizeName(String name) {
```
Comment (wburns) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java]: Lets make this required, so it is passed in via the constructor and a final field. I feel this will cause us to miss something otherwise.

Comment (jabolina) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java]: Sounds good, let me update.

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java [hunk 2]
```diff
@@ -385,7 +382,8 @@ private ConfigAndDriver startNode(boolean toOrFrom, int nodeCount, int expectedC
          builder.property(TestSystemPropertyNames.INFINISPAN_TEST_SERVER_CONTAINER_VOLUME_REQUIRED, "true");
       }
 
-      String versionToUse = toOrFrom ? configuration.toVersion() : configuration.fromVersion();
+      String prefix = (toOrFrom ? "To-" : "From-") + clusterName;
+      String versionToUse = prefix + (toOrFrom ? configuration.toVersion() : configuration.fromVersion());
 
       if (versionToUse.startsWith("image://")) {
```
Comment (wburns) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:388]: Looks like the if/else here will always be false? Since the versionToUse will always start with To- or From-.

Comment (jabolina) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java:388]: Aah, that's true. I'll remove the To/From prefix.

**Review by wburns — APPROVED** [review]
Waiting on CI.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
