### PR TITLE
[#16123] Handle server failures during post-start

### LINKED ISSUE #16123: Server hang if error in ProtocolServer::postStart
### Describe the bug

If there is an exception in `ProtocolServer::postStart` the server just hangs with no output.
An example:

```
Exception 'java.lang.LinkageError' occurred in thread '' at party.iroiro.luajava.lua51.Lua51.getNatives(Lua51.java:63)
Breakpoint reached
    at party.iroiro.luajava.lua51.Lua51.getNatives(Lua51.java:63)
    at party.iroiro.luajava.lua51.Lua51.<init>(Lua51.java:46)
    at org.infinispan.server.resp.scripting.LuaContext.<init>(LuaContext.java:84)
    at org.infinispan.server.resp.scripting.LuaTaskEngine$$Lambda/0x000000000b90f800.get(Unknown Source:-1)
    at org.infinispan.server.resp.scripting.LuaContextPool.<init>(LuaContextPool.java:19)
    at org.infinispan.server.resp.scripting.LuaTaskEngine.<init>(LuaTaskEngine.java:41)
    at org.infinispan.server.resp.RespServer.initializeLuaTaskEngine(RespServer.java:146)
    at org.infinispan.server.resp.RespServer.internalPostStart(RespServer.java:77)
    at org.infinispan.server.core.AbstractProtocolServer.postStart(AbstractProtocolServer.java:150)
    at org.infinispan.server.SecurityActions$$Lambda/0x000000000b90ac00.accept(Unknown Source:-1)
    at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4800)
    at org.infinispan.server.SecurityActions.lambda$postStartProtocolServer$0(SecurityActions.java:68)
    at org.infinispan.server.SecurityActions$$Lambda/0x000000000b90a800.run(Unknown Source:-1)
    at org.infinispan.security.Security.doPrivileged(Security.java:62)
    at org.infinispan.server.SecurityActions.postStartProtocolServer(SecurityActions.java:67)
    at org.infinispan.server.Server.lambda$run$2(Server.java:530)
    at org.infinispan.server.Server$$Lambda/0x000000000b611c00.accept(Unknown Source:-1)
```
The cause was:
```com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'liblua5164.so' for target: Linux, x86, 64-bitTristan: java.lang.UnsatisfiedLinkError: /tmp/libgdxinfinispan/bf7a6c6/liblua5164.so: libstdc++.so.6: cannot open shared object file: No such file or directory
```

### Expected behavior

The server should log the exception and exit

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Handle failures during post-start and disable the connector.
* Simulate failure with missing binaries.

Now the initialization also handles and logs any failures during the post-start phase.
Closes #16123.

### CODE REVIEW

**Comment by jabolina** [comment]
The failure is related.

**Comment by jabolina** [comment]
Fixed. The test was expecting a CacheConfigurationException from the starting the Hot Rod server and I was throwing a CacheException. I've changed the exception to CacheConfigurationException.

File: server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java [hunk 1]
```diff
@@ -362,11 +362,18 @@ private void addSelfToTopologyView(EmbeddedCacheManager cacheManager) {
...
-            EnumSet.of(InternalCacheRegistry.Flag.EXCLUSIVE));
+      String topologyCacheName = configuration.topologyCacheName();
+      try {
+         internalCacheRegistry.registerInternalCache(topologyCacheName,
+               createTopologyCacheConfig(
+                     cacheManager.getCacheManagerConfiguration().transport()
+                           .distributedSyncTimeout()).build(),
+               EnumSet.of(InternalCacheRegistry.Flag.EXCLUSIVE));
+      } catch (Exception ignore) {
+         if (cacheManager.isRunning(topologyCacheName)) {
```
Comment (wburns) [inline server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java]: This seems really wrong to me... can we throw the exception if it is not running and if it is put it is as caused by or as suppressed?

File: server/runtime/src/main/java/org/infinispan/server/SecurityActions.java [hunk 2]
```diff
@@ -65,7 +65,14 @@ static void startProtocolServer(ProtocolServer<ProtocolServerConfiguration> serv
 
    static void postStartProtocolServer(Collection<ProtocolServer> servers) {
       doPrivileged(() -> {
-         servers.forEach(ProtocolServer::postStart);
+         for (ProtocolServer<?> server : servers) {
+            try {
+               server.postStart();
+            } catch (Throwable t) {
+               Server.log.protocolFailedToStart(server.getName(), t);
+               server.stop();
```
Comment (wburns) [inline server/runtime/src/main/java/org/infinispan/server/SecurityActions.java]: I worry that if a server failed during post start it could fail while invoking stop as well. Should we check for an exception/throwable there as well?

File: server/runtime/src/main/java/org/infinispan/server/Server.java [hunk 3]
```diff
@@ -508,7 +509,7 @@ public synchronized CompletableFuture<ExitStatus> run() {
                   singlePortRouter.ssl().enabled() ? "https" : "http", singlePortRouter.host(), singlePortRouter.port()
             );
          }
-         cacheManagerStart.whenComplete((ignore, t) -> {
+         initialization = cacheManagerStart.whenComplete((ignore, t) -> {
```
Comment (wburns) [inline server/runtime/src/main/java/org/infinispan/server/Server.java]: This seems unneeded. Can we not just widen the try/catch inside the `whenComplete` lambda that catches Throwable which just invokes `r.completeExceptionally(t);` ? And maybe change the try/catch of the sync code path to be Throwable as well.

File: server/tests/src/test/java/org/infinispan/server/resilience/NativeMissingResilienceIT.java [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+import org.junit.jupiter.api.extension.RegisterExtension;
+
+import io.lettuce.core.RedisClient;
+import io.lettuce.core.api.StatefulRedisConnection;
+import io.lettuce.core.api.sync.RedisCommands;
+import party.iroiro.luajava.lua51.Lua51;
+
+/**
+ * @author Tristan Tarrant &lt;tristan@infinispan.org&gt;
+ * @since 10.0
```
Comment (wburns) [inline server/tests/src/test/java/org/infinispan/server/resilience/NativeMissingResilienceIT.java]: Wrong tags here :)

File: server/runtime/src/main/java/org/infinispan/server/Server.java (hunk 3 above)
Comment (jabolina) [reply server/runtime/src/main/java/org/infinispan/server/Server.java]: Yeah, I did this because I didn't want to create a wide try-catch inside whenComplete. But I can change, though.

File: server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java (hunk 1 above)
Comment (jabolina) [reply server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java]: TBH, I was torn with this specific one. I was thinking of removing all this part and just let it throw the CacheConfigurationException.

Comment (jabolina) [reply server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java]: It would open the possibility (very unlikely), of a user defining something like a local cache for it and it wouldn't fail.

File: server/runtime/src/main/java/org/infinispan/server/SecurityActions.java (hunk 2 above)
Comment (jabolina) [reply server/runtime/src/main/java/org/infinispan/server/SecurityActions.java]: I thought of letting it fail. But I'll wrap it on a try-catch. I rather be on the safe side instead of letting the process crash.

File: server/runtime/src/main/java/org/infinispan/server/SecurityActions.java [hunk 5]
```diff
@@ -65,7 +65,19 @@ static void startProtocolServer(ProtocolServer<ProtocolServerConfiguration> serv
...
-         servers.forEach(ProtocolServer::postStart);
+         for (ProtocolServer<?> server : servers) {
+            try {
+               server.postStart();
+            } catch (Throwable t) {
+               Server.log.protocolFailedToStart(server.getName(), t);
+
+               try {
+                  server.stop();
+               } catch (Throwable t2) {
```
Comment (tristantarrant) [inline server/runtime/src/main/java/org/infinispan/server/SecurityActions.java]: I don't think we want to start the server at all if there is a failure. I would probably not even bother stopping the protocol and exit immediately

**Comment by jabolina** [comment]
Updated. Failures during the post-start process will be logged, and the server will stop. Updated so that missing the Lua engine does not crash the server. Instead, the respCache works without the script feature enabled.

**Comment by jabolina** [comment]
Done a proper rebase now.

**Comment by tristantarrant** [comment]
Merged, thanks
