### PR TITLE
[#16260] SIFS illegal state fail to read header

### LINKED ISSUE #13248: Inability to Iterate Over Entries in SIFS-Backed Multimap
### Describe the bug

Iterating over keyset of SIFS is problematic

### Expected behavior

It should be possible to iterate over entries in a SIFS-backed multimap directly. However, this functionality fails when dealing with a large number of entries (approximately 30 million). As a workaround, it should still be possible to iterate over the keyset and fetch each entry individually.

The issue becomes apparent after extended usage or when the multimap grows beyond a certain threshold, leading to the following problems:

Iteration over the keyset becomes unreliable.

Using the work around, to fetch each segment, and not full index in one step:
```
 try {
    log.info("Clone segment: {}", segment);
    org.infinispan.commons.util.IntSet intSet = IntSets.immutableSet(segment);
    CloseableIteratorSet<String> keySet = remoteEventCacheOffline.keySet(intSet);
    Set<String> keys = keySet.stream() //
            .collect(Collectors.toSet());
    return keys;
}catch (Exception ex) {
    log.info("IllegalStateException add to retry set: {} : {}", segment, ex.getMessage());
    retrySet.add(segment);
}
```

### Actual behavior

We get a exception, interesting is that: "Segment 116" - When actually segment 7 was exported with the above code.

```
2024-12-02 16:20:11,829 WARN  [org.infinispan.HOTROD] (HotRod-client-async-pool-4-71) ISPN004098: Closing connection [id: 0x468fb385, L:/49.12.*2.*:33238 - R:49.12.*.*/49.12.*.*:11222] due to transport error: java.lang.IllegalStateException: Segment 116 already completed
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.iteration.SegmentKeyTracker.track(SegmentKeyTracker.java:66)
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.operations.IterationNextOperation.acceptResponse(IterationNextOperation.java:120)
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.decode(HeaderDecoder.java:153)
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.transport.netty.HintedReplayingDecoder.callDecode(HintedReplayingDecoder.java:94)
at deployment.inbound-ear-5.9.2138.ear//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at deployment.inbound-ear-5.9.2138.ear//io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
at deployment.inbound-ear-5.9.2138.ear//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at deployment.inbound-ear-5.9.2138.ear//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [java.base:]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [java.base:]
at java.base/java.lang.Thread.run(Thread.java:833) [java.base:
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

quay.io/infinispan/server:15.0.10.Final-1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #16260: SIFS illegal state fail to read header
### Describe the bug

During operation, SIFS is failing with:

```
01:15:53,859 ERROR (blocking-thread--p3-t75) [org.infinispan.interceptors.impl.InvocationContextInterceptor] ISPN000136: Error executing command RemoveCommand on Cache '<redacted>', writing keys [WrappedByteArray[<redacted>(33 bytes)]] java.lang.IllegalStateException: Error reading header from 468:1857757 | 0
	at org.infinispan.persistence.sifs.IndexNode$LeafNode.getHeaderAndKey(IndexNode.java:1133)
	at org.infinispan.persistence.sifs.IndexNode$LeafNode.loadHeaderAndKey(IndexNode.java:1112)
	at org.infinispan.persistence.sifs.IndexNode.copyWith(IndexNode.java:710)
	at org.infinispan.persistence.sifs.IndexNode.setPosition(IndexNode.java:420)
	at org.infinispan.persistence.sifs.Index$Segment.accept(Index.java:841)
	at org.infinispan.persistence.sifs.Index$Segment.accept(Index.java:720)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:403)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:178)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
	at org.infinispan.executors.LimitedExecutor.actualRun(LimitedExecutor.java:192)
	at org.infinispan.executors.LimitedExecutor.runTasks(LimitedExecutor.java:176)
	at org.infinispan.executors.LimitedExecutor$Runner.run(LimitedExecutor.java:237)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Other operations include `SegmentsClusteredQueryCommand` and `PutMapCommand`. This is running on 15.0.19.Final.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by wburns**
* FileNotFoundException should be thrown if file is empty to read

Fixes #16260
Fixes #13248 

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [x] ~~The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.~~
- [x] ~~Log messages of level `INFO` and above have been internationalized.~~
- [x] ~~If the PR affects performance, include before/after benchmarks.~~
- [x] ~~If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).~~
- [x] ~~If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.~~

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

**Comment by wburns** [comment]
I have tried the for a very long time to try to reproduce this issue as I was pretty sure I found what was happening but I was unable to confirm. I am pretty sure the issue occurs when 3 things happen concurrently:

1. Reshuffle of the index B+ tree and it sets a new root (which only locks the highest root)
2. An entry is read that is one of the leaf nodes down the changes branch of the tree
3. Compaction removes the file for the given read key (which moves it to another file)

But either way this change should fix the issue in general because it should never be possible for the Index read to try to read an empty file and it will now instead throw the IndexNodeOutdatedException which will cause the read operation to be retried as it should. I was able to add tests to verify the FileNotFoundException being thrown which was changed when Index was refactored to use a FileProvider to have limited open files.

File: core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java [hunk 1]
```diff
@@ -236,7 +239,7 @@ protected FileChannel openChannel(File file, boolean create, boolean readSharedM
          if (create) {
             fileChannel = new FileOutputStream(file).getChannel();
          } else {
-            fileChannel = new RandomAccessFile(file, "rw").getChannel();
+            fileChannel = new RandomAccessFile(file, isIndex ? "rw" : "r").getChannel();
```
Comment (wburns) [inline core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java:242]: This is the actual change as data FileProvider used for data files should never be empty unless it is a log file. Thus the "rw" before was making it return a fileChannel pointing to an empty file and thus the error message would show the file size as 0. By being "r" it will now throw a FileNotFoundException which is caught later on and converted to a null and then later into a IndexNodeOutdatedException which then retries the operation.

**Comment by tristantarrant** [comment]
The failure seems related

**Comment by wburns** [comment]
Failure was
```
2026-03-27T06:42:50.1452710Z 	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(A2026-03-27T06:42:50.1976110Z ##[error]No space left on device : '/home/runner/actions-runner/cached/_diag/blocks/58dde947-d66c-4ea7-8f77-240b1608d6dd_dd3d1789-23cd-4217-b7c0-8c511de13c2d.3'
```
 according to log

**Comment by wburns** [comment]
Running it locally the log file is the same size with/without this change. I am rerunning the tests again.

**Comment by wburns** [comment]
I am not sure how to investigate disk usage for this.. I rebased to get a new run.

**Comment by wburns** [comment]
I was able to reproduce the issue locally when running the whole suite, so there definitely is an issue.

**Comment by wburns** [comment]
I have reproduced it locally and it is the error I wanted to see in the first place, but reproducing it with TRACE is being very difficult :(

**Comment by tristantarrant** [comment]
@wburns Checkstyle failures

**Comment by wburns** [comment]
Fixed imports

File: core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+         // Now invoke compaction while the segment cleanup is blocked
+         try {
+            log.trace("Starting compaction...");
+            compactor.forceCompactionForAllNonLogFiles().toCompletableFuture().get(10, TimeUnit.SECONDS);
+            log.trace("Compaction completed successfully");
+         } catch (Exception e) {
+            log.tracef(e, "Compaction failed: %s", e.getMessage());
+         } finally {
+            // Signal compaction is complete (even if it failed)
+            compactionComplete.countDown();
```
Comment (jabolina) [inline core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java:160]: Should we make any assertion on the underlying files before releasing? To ensure they were changed.

File: core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+         removeSegmentsStage.toCompletableFuture().get(10, TimeUnit.SECONDS);
+
+         // Verify file stats are the same after removeSegments
+         Map<Integer, Compactor.Stats> fileStats = compactor.getFileStats();
+         // Note that total of -1 is alright, that means it is a non completed file
+         if (fileStats.values().stream().anyMatch(s -> s.getTotal() == 0)) {
+            fail("At least one stat shows no total: " + fileStats);
+         }
+
+         // Verify the store is still in a consistent state - entries should be removed
```
Comment (jabolina) [inline core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java:176]: Is nice to assert the specific entries are gone, should we assert with an iteration operation, too?

**Comment by wburns** [comment]
Yeah, the failures are because the freeIfPresent doesn't work when the segments are in the log appender file as it hasn't yet created any file states.. so we have to also call free if the log file is currently the log appender file. Need to think on best way to handle this since it is a concurrency issue in that the log file could become a log file while adding the free information.

File: core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java (hunk 3 above)
Comment (wburns) [reply core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java:176]: I could add that, sure.

File: core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java (hunk 2 above)
Comment (wburns) [reply core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java:160]: What were you thinking? This test is here for the index pointing to the wrong location.

**Comment by wburns** [comment]
Updated

File: core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java (hunk 2 above)
Comment (jabolina) [reply core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java:160]: I had something like check the size changed or something to ensure that it would throw the `IndexNodeOutdatedException` when accessed. But it might not be the place for that :thinking:

Comment (wburns) [reply core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSegmentRemovalTest.java:160]: The problem is the test should no longer propagate the exception so there is no great way to asssert that other than reading the log file or something :( If you revert the fix it should complain at least for your own check :)

**Comment by jabolina** [comment]
Thanks, @wburns!
