### PR TITLE
[#16022] Fine-grained configuration match

### LINKED ISSUE #16022: Cache configuration improper serialization and match
### Describe the bug

Currently, when creating a cache, the `GlobalConfigurationManagerImpl` uses `Configuration.toStringConfiguration` to transform the provided configuration to an XML string and insert it into the CONFIG cache.

https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java#L280-L282

After the insertion, the `GlobalConfigurationStateListener` is triggered, and creates the cache locally with the `GlobalConfigurationManagerImpl`. The listener uses the configuration serialized as XML to reconstruct the cache configuration. Right before creating the cache, the XML is serialized back into a `Configuration` object:

https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java#L333-L339

And the `VolatileLocalConfigurationStorage` asserts the configuration matches (in case it was registered previously):

https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/globalstate/impl/VolatileLocalConfigurationStorage.java#L77-L91

To ensure the RESP configuration isn't tampered with, we define the configuration when the server starts. This process ensures the configuration is valid from the start, and can't be changed to something invalid. However, the test suite found several cases where the serialization and deserialization aren't symmetrical, and the `match` method in the configuration uses parameters that it shouldn't.

For example, the following programmatic configuration:

```java
      ConfigurationBuilder cb = new ConfigurationBuilder();
      cb.clustering().cacheMode(CacheMode.LOCAL);
      cb.clustering().hash()
            .numOwners(1)
            .keyPartitioner(new RESPHashFunctionPartitioner());
      cb.invocationBatching().enable(true);
```

Is serialized as:

```xml
<?xml version="1.0"?>
<local-cache name="some-name">
   <transaction mode="BATCH"/>
</local-cache>
```

Which means that the `Configuration` created programmatically and the `Configuration` created by the XML won't match. This also applies to other parameters: 

* Utilizing a `REPL_CACHE`, we can define the `.numOwners(1)`, but this is not permitted in the XML format. The `match` will fail because it takes the `numOwners` parameter into account.
* Utilizing a `DIST_CACHE`, the deserialization of the XML to `Configuration` will set `useSynchronization=true` in the transaction configuration automatically: https://github.com/infinispan/infinispan/blob/1dffe6fa18e011619fcbd22f5ab5926f2313e2c0/core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java#L565-L572 

In all of these cases, it won't be possible to create the cache.

### Expected behavior

The serialization to XML is missing some parameters, and/or the match verification includes more parameters than necessary. For example, numOwners can't be written in the XML configuration, so it shouldn't be taken into consideration when verifying for a match.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Dedicated match for cluster
* Extra configuration when enabling batch

Closes #16022

### CODE REVIEW

File: core/src/main/java/org/infinispan/configuration/cache/InvocationBatchingConfigurationBuilder.java [hunk 1]
```diff
@@ -50,6 +50,8 @@ private void enableTransactions() {
             getBuilder().transaction().attributes.attribute(TRANSACTION_MODE);
       if (!transactionModeAttribute.isModified()) {
          getBuilder().transaction().transactionMode(TRANSACTIONAL);
+         getBuilder().transaction().useSynchronization(true);
+         getBuilder().transaction().recovery().enabled(false);
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/cache/InvocationBatchingConfigurationBuilder.java:55]: For reference, when deserializing the configuration:

https://github.com/infinispan/infinispan/blob/ceae0e1d85aeb6cb797b881a457a288ae68afcc5/core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java#L566-L570

File: core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java [hunk 2]
```diff
@@ -100,4 +100,24 @@ public L1Configuration l1() {
...
+      }
+
+      if (!attributes.matches(other.attributes)) return false;
+      if (children.length != other.children.length) return false;
+      for (int i = 0; i < children.length; i++) {
+         ConfigurationElement ours = children[i];
+         ConfigurationElement theirs = other.children[i];
+
+         // Hash configuration does not matter for replicated caches.
+         if (ours == hashConfiguration && cacheMode().isReplicated()) continue;
```
Comment (wburns) [inline core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java]: I think we need to compare segments and key partitioner for sure. I think even capacity factor should be supported with REPL with a value of 0, but that can be discussed later as we don't parse it at all currently but for distributed caches.

Comment (jabolina) [reply core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java]: Updated. Instead of ignoring the whole configuration element, I've added a match method that ignores specific attributes. By default, it ignores only num-owners, but it seems the capacity factors aren't taken into account already.

**Comment by jabolina** [comment]
Ideally, we should cover any other configuration elements that are specific to the kind of configuration utilized. TBH I don't know which other elements might fall in this :(

File: core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java [hunk 3]
```diff
@@ -100,4 +100,28 @@ public L1Configuration l1() {
...
+         return other.cacheMode == CacheMode.LOCAL;
+      }
+
+      if (!attributes.matches(other.attributes)) return false;
+      if (children.length != other.children.length) return false;
+      for (int i = 0; i < children.length; i++) {
+         ConfigurationElement ours = children[i];
+         ConfigurationElement theirs = other.children[i];
+
+         // Hash configuration does not take num-owners into account for replicated caches.
```
Comment (wburns) [inline core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java]: I feel like this should exist in the HashConfiguration class instead of here. Then we don't have to do this whole ignored method as well.

File: commons/all/src/main/java/org/infinispan/commons/configuration/attributes/ConfigurationElement.java [hunk 4]
```diff
@@ -87,6 +88,17 @@ public boolean matches(T other) {
       return true;
    }
 
+   public boolean matches(T other, Attribute<?> ... ignored) {
```
Comment (wburns) [inline commons/all/src/main/java/org/infinispan/commons/configuration/attributes/ConfigurationElement.java:88]: All these ignored parts should be able to be removed if we move the match skip to the HashConfiguration.

File: core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java (hunk 3 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java]: Yeah, I can create a specific match method in HashConfiguration. I did add it here because the HashConfiguration itself doesn't know whether it is replicated. We need to verify if replicated here and invoke a specific match method.

Comment (jabolina) [reply core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java]: In reality, it is not the ConfigurationElement (and subclass) that are different. The difference is in the `AttributeSet` class. But the attributes don't have any clue to which ConfigurationElement they belong to. So I put it in a mix with the ignore methods.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
