### PR TITLE
[#13834] Install client topology only after a channel is fully connected

### LINKED ISSUE #13793: Client topology installed during authentication can cause NPE in client
### Describe the bug

Same setup as with 13734 but using 15.1.4.Final

1.	The client connects to the VIP.
2.	The VIP responds with a topology update containing the list of real server IPs. The VIP itself is not included in that list.
3.	The client establishes connections to the real server IPs and closes the connection to the VIP.
4.	AuthHandler calls OperationChannel.markAcceptingRequests on closed VIP channel
5.	NPE is thrown

Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.eventLoop()" because "this.channel" is null
	at org.infinispan.client.hotrod.impl.transport.netty.OperationChannel.markAcceptingRequests(OperationChannel.java:122)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.lambda$activate$1(AuthHandler.java:86)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:831)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2223)
	at org.infinispan.client.hotrod.impl.transport.netty.OperationDispatcher.handleResponse(OperationDispatcher.java:688)
	at org.infinispan.client.hotrod.impl.transport.netty.OperationDispatcher.handleResponse(OperationDispatcher.java:670)
	at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.decode(HeaderDecoder.java:292)
	at org.infinispan.client.hotrod.impl.transport.netty.HintedReplayingDecoder.callDecode(HintedReplayingDecoder.java:94)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)

### Expected behavior

client statrup finishes without exceptions

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

15.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #13834: HotRodUpgradeContainerSSLTest crashes testsuite
### Describe the bug

```
11:37:20  [TestSuiteProgress] Test failed: org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest.setup
11:37:20  Dumping threads of process 3072349 to /home/infinispan/workspace/Infinispan_main/persistence/remote/threaddump-HotRodUpgradeContainerSSLTest-20250120-0537-3072349.log
11:37:20  Interrupted thread testng-HotRodUpgradeContainerSSLTest (38).
11:37:20  [OK:   277, KO:     1, SKIP:     4] Test configuration failed: org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest.setup
11:37:20  org.infinispan.commons.CacheConfigurationException: ISPN000659: Component ComponentWrapper{name=org.infinispan.persistence.manager.PersistenceManager, instance=org.infinispan.persistence.manager.PersistenceManagerImpl@5e20187, status=FAILED} failed to start
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:584)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:370)
11:37:20  	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:243)
11:37:20  	at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:222)
11:37:20  	at org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:1037)
11:37:20  	at org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDelegatingCache.java:512)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:731)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:677)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:565)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:528)
11:37:20  	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1016)
11:37:20  	at org.infinispan.persistence.remote.upgrade.TestCluster$Builder.lambda$build$1(TestCluster.java:341)
11:37:20  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
11:37:20  	at org.infinispan.persistence.remote.upgrade.TestCluster$Builder.build(TestCluster.java:341)
11:37:20  	at org.infinispan.persistence.remote.upgrade.TestCluster$Builder$CacheDefinitionBuilder.build(TestCluster.java:257)
11:37:20  	at org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest.configureTargetCluster(HotRodUpgradeContainerSSLTest.java:41)
11:37:20  	at org.infinispan.persistence.remote.upgrade.HotRodUpgradeWithSSLTest.setup(HotRodUpgradeWithSSLTest.java:32)
11:37:20  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
11:37:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
11:37:20  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
11:37:20  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
11:37:20  	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
11:37:20  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
11:37:20  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
11:37:20  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
11:37:20  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
11:37:20  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
11:37:20  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
11:37:20  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
11:37:20  	at org.testng.TestRunner.run(TestRunner.java:505)
11:37:20  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
11:37:20  	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
11:37:20  	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
11:37:20  	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
11:37:20  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
11:37:20  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
11:37:20  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
11:37:20  	at java.base/java.lang.Thread.run(Thread.java:1583)
11:37:20  Caused by: java.lang.RuntimeException: java.lang.InterruptedException
11:37:20  	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
11:37:20  	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:89)
11:37:20  	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1469)
11:37:20  	at org.infinispan.persistence.manager.PersistenceManagerImpl.start(PersistenceManagerImpl.java:195)
11:37:20  	at org.infinispan.persistence.manager.CorePackageImpl$2.start(CorePackageImpl.java:72)
11:37:20  	at org.infinispan.persistence.manager.CorePackageImpl$2.start(CorePackageImpl.java:51)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	... 54 more
11:37:20  Caused by: java.lang.InterruptedException
11:37:20  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
11:37:20  	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
11:37:20  	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:86)
11:37:20  	... 61 more
11:37:20  [OK:   277, KO:     1, SKIP:     5] Test ignored: org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest.testSynchronizationWithInFlightDeletes
11:37:20  [OK:   277, KO:     1, SKIP:     6] Test ignored: org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest.testSynchronizationWithInFlightReads
11:37:20  [OK:   277, KO:     1, SKIP:     7] Test ignored: org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest.testSynchronizationWithInFlightUpdates
11:37:20  05:37:10.776 [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 346.0 s <<< FAILURE! -- in org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest
11:37:20  05:37:10.776 [ERROR] org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest -- Time elapsed: 346.0 s <<< ERROR!
11:37:20  org.infinispan.commons.CacheConfigurationException: ISPN000659: Component ComponentWrapper{name=org.infinispan.persistence.manager.PersistenceManager, instance=org.infinispan.persistence.manager.PersistenceManagerImpl@5e20187, status=FAILED} failed to start
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:584)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
11:37:20  	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:370)
11:37:20  	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:243)
11:37:20  	at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:222)
11:37:20  	at org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:1037)
11:37:20  	at org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDelegatingCache.java:512)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:731)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:677)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:565)
11:37:20  	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:528)
11:37:20  	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1016)
11:37:20  	at org.infinispan.persistence.remote.upgrade.TestCluster$Builder.lambda$build$1(TestCluster.java:341)
11:37:20  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
11:37:20  	at org.infinispan.persistence.remote.upgrade.TestCluster$Builder.build(TestCluster.java:341)
11:37:20  	at org.infinispan.persistence.remote.upgrade.TestCluster$Builder$CacheDefinitionBuilder.build(TestCluster.java:257)
11:37:20  	at org.infinispan.persistence.remote.upgrade.HotRodUpgradeContainerSSLTest.configureTargetCluster(HotRodUpgradeContainerSSLTest.java:41)
11:37:20  	at org.infinispan.persistence.remote.upgrade.HotRodUpgradeWithSSLTest.setup(HotRodUpgradeWithSSLTest.java:32)
11:37:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
11:37:20  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
11:37:20  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
11:37:20  	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
11:37:20  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
11:37:20  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
11:37:20  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
11:37:20  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
11:37:20  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
11:37:20  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
11:37:20  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
11:37:20  	at org.testng.TestRunner.run(TestRunner.java:505)
11:37:20  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
11:37:20  	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
11:37:20  	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
11:37:20  	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
11:37:20  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
11:37:20  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
11:37:20  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
11:37:20  	at java.base/java.lang.Thread.run(Thread.java:1583)
11:37:20  Caused by: java.lang.RuntimeException: java.lang.InterruptedException
11:37:20  	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
11:37:20  	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:89)
11:37:20  	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1469)
11:37:20  	at org.infinispan.persistence.manager.PersistenceManagerImpl.start(PersistenceManagerImpl.java:195)
11:37:20  	at org.infinispan.persistence.manager.CorePackageImpl$2.start(CorePackageImpl.java:72)
11:37:20  	at org.infinispan.persistence.manager.CorePackageImpl$2.start(CorePackageImpl.java:51)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
11:37:20  	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
11:37:20  	... 53 more
11:37:20  Caused by: java.lang.InterruptedException
11:37:20  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100)
11:37:20  	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
11:37:20  	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:86)
11:37:20  	... 60 more
11:37:20  
11:37:20  Killed processes 3072349
11:37:20  05:37:13.211 [INFO] 
11:37:20  05:37:13.212 [INFO] Results:
11:37:20  05:37:13.212 [INFO] 
11:37:20  05:37:13.212 [ERROR] Errors: 
11:37:20  05:37:13.212 [ERROR]   HotRodUpgradeContainerSSLTest>HotRodUpgradeWithSSLTest.setup:32->configureTargetCluster:41 » CacheConfiguration ISPN000659: Component ComponentWrapper{name=org.infinispan.persistence.manager.PersistenceManager, instance=org.infinispan.persistence.manager.PersistenceManagerImpl@5e20187, status=FAILED} failed to start
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
Fixes #13834

This probably also fixes #13793, but would need to be confirmed.

### CODE REVIEW

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java [hunk 1]
```diff
@@ -369,8 +369,12 @@ private void readNewTopologyAndHash(ByteBuf buf, String cacheName) {
          segmentOwners = null;
       }
 
-      dispatcher.updateTopology(cacheName, operation, newTopologyId,
-            addresses, segmentOwners, hashFunctionVersion);
+      // Only update the topology if this channel is fully connected and authenticated
```
Comment (danfaer) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:372]: How often server sends topology updates ?

Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:372]: The topology is sent back as a response every time the client sends a request that is not the same one.

Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:372]: What you are talking about is if all of the IPs are no longer accessible in the topology provided. In that case the client resets its server list back to the initial hosts list and effectively "resets". This transition should work seamlessly over as it has in the past.

**Comment by jabolina** [comment]
The operator failure is my old nemesis (#13571) and is not related to the changes here.

```java
16:26:22,191 ERROR (non-blocking-thread--p2-t2) [org.infinispan.server.core.backup.BackupManagerImpl] ISPN005040: Cannot restore cluster backup '/opt/infinispan/backups/upgrade-backup/upgrade-backup.zip': java.util.concurrent.CompletionException: org.infinispan.commons.CacheConfigurationException: ISPN000436: Cache 'persistentCache' has been requested, but no matching cache configuration exists
	at org.infinispan.commons.util.concurrent.CompletionStages.join(CompletionStages.java:90)
	at org.infinispan.server.core.backup.BackupReader.lambda$restore$0(BackupReader.java:74)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000436: Cache 'persistentCache' has been requested, but no matching cache configuration exists
	at org.infinispan.configuration.ConfigurationManager.getConfiguration(ConfigurationManager.java:65)
	at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:682)
	at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:672)
	at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:565)
	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:528)
	at org.infinispan.manager.DefaultCacheManagerAdmin.getOrCreateCache(DefaultCacheManagerAdmin.java:50)
	at org.infinispan.security.actions.GetOrCreateCacheAction.get(GetOrCreateCacheAction.java:29)
	at org.infinispan.security.actions.GetOrCreateCacheAction.get(GetOrCreateCacheAction.java:14)
	at org.infinispan.security.Security.doPrivileged(Security.java:49)
	at org.infinispan.security.actions.SecurityActions.getOrCreateCache(SecurityActions.java:163)
	at org.infinispan.server.core.backup.resources.CacheResource.lambda$createCache$3(CacheResource.java:154)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
	... 1 more
```

@wburns any chance that the DB failures are related?

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java (hunk 1 above)
Comment (danfaer) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:372]: @wburns , 
Client ignores topology updates if the server perspective of topology has not changed -  
```
case READ_TOPOLOGY:
               short topologyChangeByte = in.readUnsignedByte();
               if (topologyChangeByte == 1) {
                  readNewTopologyAndHash(in, operation.getCacheName());
               }
```

Does that mean that by ignoring topology updates when the channel is not accepting requests, the channel might remain stuck with an outdated topology?

Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:372]: We only ignore topology updates while the channel is initially connecting. This only happens very briefly at the start, in the case of when auth is enabled it is until the auth is complete (without auth it is just the initial ping). Any response after that will apply the new topology. Since the request has an older topology _every_ response will contain the new topology, until it is finally applied.

Comment (danfaer) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:372]: What do you think about comparing response topologyId with `cacheInfo.getTopologyId()`  instead of relying on topologyChangeByte ?

Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java:372]: The server already does this comparison and if they don't match includes it in the response. This way the server only includes this information in the response when they don't match.

https://github.com/infinispan/infinispan/blob/main/server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java#L696
