### PR TITLE
[#14564] Query bug (hotrod) - projection and filtering in nested lists not working 

### LINKED ISSUE #14564: Nested items query errors on embedded items and filtering with selection don't work
### Describe the bug

With this schema:

```proto
syntax = "proto3";
package dev.langchain4j;
/*
 * @Indexed
 */
message LangChainItem384 {
  /*
   * @Keyword
   */
  string text = 2;

  /*
   * @Embedded
   */
  repeated LangChainMetadata384 metadata = 4;
  /*
   * @Vector(dimension=384, similarity=COSINE)
   */
  repeated float embedding = 3;
  /*
   * @Text
   */
  string id = 1;
}
/*
 * @Indexed
 */
message LangChainMetadata384 {
  /*
   * @Text
   */
  string name = 1;
  /*
   * @Text
   */
  string value = 2;
}

```

I can perform this query

```text
from dev.langchain4j.LangChainItem384 i where i.metadata.name : 'name' and i.metadata.value : 'Klaus'
```

however, this query

```
select i from dev.langchain4j.LangChainItem384 i where i.metadata.name : 'name' and i.metadata.value : 'Klaus'
```
Responds with: ISPN028502: Unknown alias: metadata.

In consequence, vector search filtering on metadata is failing too:

```
select i from dev.langchain4j.LangChainItem384 i where i.embedding <-> [0.015031195, 0.03973271, -0.023383677, 0.06372783, -0.0051405085, .... vector data .... -0.043156274]~3 filtering(i.metadata.name : 'name' and i.metadata.value : 'Klaus')
```

Responds with: ISPN028502: Unknown alias: metadata.

This query works:

```
select i, score(i) from dev.langchain4j.LangChainItem384 i where i.embedding <-> [.......... -0.043156274]~3
```
(I get the scores only)

but if I add the filtering clause `filtering(i.metadata.name : 'name' and i.metadata.value : 'Klaus')` 

I get unknown metadata error in all the cases

And if I run 

```
select count(*) from dev.langchain4j.LangChainItem384 i where i.embedding <-> [.......... -0.043156274]~3 filtering(i.metadata.name : 'name' and i.metadata.value : 'Klaus') 

```
I get the values, but not the scores

### PR DESCRIPTION
**Pull request by karesti**
Closes #14564

### CODE REVIEW

**Comment by karesti** [comment]
retest please

**Comment by wburns** [comment]
Looks like CI failed to complete :(

**Comment by wburns** [comment]
Looks like ParentJoinNestedTest.nested_usingJoinWithNegation  failure is related.

**Comment by karesti** [comment]
@wburns looks good now

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/SingleHotRodServerTest.java [hunk 1]
```diff
@@ -47,6 +47,7 @@ protected ConfigurationBuilder createHotRodClientConfigurationBuilder(String hos
       builder.addServer()
             .host(host)
             .port(serverPort);
+      builder.socketTimeout(100000);
```
Comment (wburns) [inline client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/SingleHotRodServerTest.java]: Looks like this snuck in.

Comment (karesti) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/SingleHotRodServerTest.java]: done

**Comment by wburns** [comment]
Integrated into main, thanks @karesti !
