### PR TITLE
[#16204] REST security resource blocking operations

### LINKED ISSUE #16204: Server becomes non-responsive randomly which affects console nightly builds
### Describe the bug

Quite usually it started to happen that during Console nightly builds, directly after the first access management test, which creates/updates/deletes a principle/role, the server starts to throw exceptions and becomes unresponsive for the most of the other tests. 

Please find attached the log and the thread dump for that server (all in one file). 

[Server Log & Thread Dump.log](https://github.com/user-attachments/files/23648692/Server.Log.Thread.Dump.log)

You can also find the logs here: https://github.com/infinispan/infinispan-console/actions/runs/19520590949/job/55882978958  (please look at the docker logs dump phase in the end after tests failures, as well as you can take a look at the screenshots from the console to see how it behaved from here: https://github.com/infinispan/infinispan-console/actions/runs/19520590949/artifacts/4622005107 )

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Cluster role mapper has some blocking methods.
* Update REST security resource to offload blocking operations to blocking manager.

Close #16204

### CODE REVIEW

File: server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java [hunk 1]
```diff
@@ -259,8 +261,12 @@ private CompletionStage<RestResponse> deny(RestRequest request, boolean all) {
       if (roles == null) {
          return completedFuture(builder.status(HttpResponseStatus.BAD_REQUEST).build());
       }
-      roles.forEach(r -> principalRoleMapper.deny(r, principal));
-      return aclCacheFlush(request);
+      AggregateCompletionStage<Void> acs = CompletionStages.aggregateCompletionStage();
```
Comment (wburns) [inline server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java]: I don't see any reason to do these in parallel, we can replace this with:

```java
CompletionStages.performSequentially(roles.iterator(), CompletableFuture.runAsync(() -> principalRoleMapper.deny(role, principal), invocationHelper.getExecutor())
.thenCompose(ignore -> aclCacheFlush(request))
```

File: server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java [hunk 2]
```diff
@@ -283,8 +289,14 @@ private CompletionStage<RestResponse> grant(RestRequest request, boolean newAcce
          return completedFuture(invocationHelper.newResponse(request).status(CONFLICT).build());
       }
 
-      roles.forEach(r -> principalRoleMapper.grant(r, principal));
-      return aclCacheFlush(request);
+
+      AggregateCompletionStage<Void> acs = CompletionStages.aggregateCompletionStage();
```
Comment (wburns) [inline server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java]: We can replace this section like the previous comment as well.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
