### PR TITLE
[#15887] ThreadLeak detection in tests uses too much memory with virt…

### LINKED ISSUE #15887: ThreadLeak detection in tests uses too much memory with virtual threads
### Describe the bug

When running the core test suite a single run there can be over 1.5GB of memory temporarily used by thread leak detection if enough of the blocking thread pool is used. This can cause the suite to throw OutOfMemory errors sometimes causing it to not complete.

Image

We should ignore virtual threads in the thread leak detection.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
…ual threads

Fixes #15887 

With this in place I never saw more than 500-600 MB at the same time when I saw near 2 GB.

### CODE REVIEW

File: commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java [hunk 1]
```diff
@@ -122,7 +122,20 @@ public class ThreadLeakChecker {
...
-         return new LeakException(Thread.currentThread().getName(), parentValue);
+         Thread thread = Thread.currentThread();
+         if (!isVirtualThread(thread)) {
+            return new LeakException(Thread.currentThread().getName(), parentValue);
+         }
+         return null;
+      }
+   }
+
+   private static boolean isVirtualThread(Thread thread) {
```
Comment (pruivo) [inline commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java:134]: You have the following method available: https://github.com/infinispan/infinispan/blob/d00d4f61924af36c8a3aa97d6cb644a3e883e5a6/commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java#L14

Comment (wburns) [reply commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java:134]: Yeah, I tried at first, but we can't access it :( But now that I think about I included commons and not commons-api so that might work.

Comment (wburns) [reply commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java:134]: Yeah, I can't do it with just commons-spi, so I can't use this method as commons and commons-test cause a circular dependency :(

**Review by pruivo — APPROVED** [review]

**Comment by wburns** [comment]
Not sure why disabling causes the test suite to hang, need to look further.

**Comment by wburns** [comment]
Cause was that when a virtual thread spawns a non virtual thread the parent exception wasn't propagated. I changed it now so that the virtual thread just passes along its parent's value. Hopefully that will fix it :crossed_fingers:

File: commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java [hunk 2]
```diff
@@ -122,10 +122,24 @@ public class ThreadLeakChecker {
    private static class ThreadInfoLocal extends InheritableThreadLocal<LeakException> {
       @Override
       protected LeakException childValue(LeakException parentValue) {
+         Thread thread = Thread.currentThread();
+         if (!isVirtualThread(thread)) {
```
Comment (pruivo) [inline commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java]: Isn't the condition inverted?

Comment (wburns) [reply commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java]: Oh whoops. Yeah I swapped them and mean to remove the ! but didn't :D
