### PR TITLE
[#16222] RESP MGET returns null instead of notfound error

### LINKED ISSUE #16222: JSON.MGET should return nulls on non-existing paths
### Describe the bug

JSON.MGET returns ERR on non-existing path while it should return null

### Expected behavior

```
127.0.0.1:6379> JSON.SET doc1 $ '{"a":1, "b": 2, "nested": {"a": 3}, "c": null}'
OK
127.0.0.1:6379> JSON.SET doc2 $ '{"a":4, "b": 5, "nested": {"a": 6}, "c": null}'
OK
127.0.0.1:6379> JSON.MGET doc1 doc2 42isnotapath
1) (nil)
2) (nil)
```

### Actual behavior

```
127.0.0.1:6379> JSON.SET doc1 $ '{"a":1, "b": 2, "nested": {"a": 3}, "c": null}'
OK
127.0.0.1:6379> JSON.SET doc2 $ '{"a":4, "b": 5, "nested": {"a": 6}, "c": null}'
OK
127.0.0.1:6379> JSON.MGET doc1 doc2 42isnotapath
(error) ERR Path '$.42isnotapath' does not exist
```

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by rigazilla**
fixes  #16222

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java [hunk 1]
```diff
@@ -51,6 +51,12 @@ private static byte[] handleWrongTypeError(Throwable ex) {
       if (RespUtil.isWrongTypeError(ex)) {
          return null;
       }
+      // Handle non-existing path error - should return null instead of error
+      if (ex.getCause() instanceof RuntimeException &&
```
Comment (Crumby) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java]: My Java best practices are bit rusty but wouldn't it be better to throw a new custom exception that's a subclass of `RuntimeException` and catch that one rather then catching any `RuntimeException`?

Comment (tristantarrant) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java]: Yes. Also, if a JDK exception already exists with the same meaning, we should be using that instead. In this case `java.util.NoSuchElementException`

Comment (rigazilla) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java]: ok, done

**Review by Crumby — APPROVED** [review]

File: server/resp/src/main/java/org/infinispan/server/resp/json/JsonGetFunction.java [hunk 2]
```diff
@@ -92,7 +93,7 @@ public byte[] apply(ReadWriteEntryView<byte[], JsonBucket> entryView) {
             // If legacy return just the first one
             if (isLegacy) {
                if (nodeList.size()==0) {
-                  throw new RuntimeException("Path '"+pathStr+"' does not exist");
+                  throw new NoSuchElementException("Path '"+pathStr+"' does not exist");
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/json/JsonGetFunction.java:96]: I have to admit using an exception for flow control here feels really bad. Could this not just return null and handle that somewhere else up the stack?

Comment (rigazilla) [reply server/resp/src/main/java/org/infinispan/server/resp/json/JsonGetFunction.java:96]: true. null is sometime a good return value for json, maybe returning a MissingNode object could work

https://github.com/infinispan/infinispan/issues/16322
