### PR TITLE
[#13405] - nested queries improvements - proper handling of OR predicates

### LINKED ISSUE #13405: Ickle Query with nested elements returns error when using OR expressions
### Describe the bug

When running an ickle query with JOIN elements that has OR predicates based on these nested fields, an error is returned instead of result. Example query based on the model in _ParentJoinNestedTest_:

```
select t.name from org.infinispan.query.model.Team t 
join t.firstTeam p
where (p.color ='red' AND p.number=7) or (p.color='blue' AND p.number=7)
```

### Expected behavior

correct results are returned that match the query

### Actual behavior

Query error - Error executing search is returned

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gybandi**
Fixes #13405

Implemented proper handling of OR predicates when using it with nested objects in an ickle query. 

Problematic query example:
```
select t.name from org.infinispan.query.model.Team t 
join t.firstTeam p
where (p.color ='red' AND p.number=7) or (p.color='blue' AND p.number=7)
```
After the fix this returns correct results instead of an error

### CODE REVIEW

**Comment by fax4ever** [comment]
Thanks @gybandi, great that you're expanding the support for this use case.

File: object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java [hunk 1]
```diff
@@ -106,6 +106,8 @@ public void addNestedComparison(PropertyPath<?> propertyPath, ComparisonExpr.Typ
       if (!nestedExprMap.containsKey(joinAlias)) {
          nestedExprMap.put(joinAlias, new NestedExpr(getNestedPath(propertyPath)));
          push(nestedExprMap.get(joinAlias));
+      }else if(stack.peek() instanceof LazyNegationExpr && !nestedExprMap.isEmpty()){
```
Comment (fax4ever) [inline object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java:109]: the second check seems to be redundant

```suggestion
      } else if (stack.peek() instanceof LazyNegationExpr) {
```

**Review by fax4ever — COMMENTED** [review]
Thanks for the contribution.
I have just one suggestion after that we can merge for me.
I don't know if we want update also `ParentJoinNestedRemoteTest` (not mandatory for me - just an idea).

File: object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java (hunk 1 above)
Comment (gybandi) [reply object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java:109]: hm you're right, I will fix these soon. Thanks for the feedback!

**Comment by gybandi** [comment]
> Thanks for the contribution. I have just one suggestion after that we can merge for me. I don't know if we want update also `ParentJoinNestedRemoteTest` (not mandatory for me - just an idea).

great idea, I will do that soon! thx!

**Review by fax4ever — APPROVED** [review]
LGMT, let's merge it after the CI passes. Thanks

**Comment by fax4ever** [comment]
I restarted the Jenkins CI

**Comment by fax4ever** [comment]
Merged, thanks for the contribution!
