### PR TITLE
[#17307] Move RocksDB cache store out of the server distribution

### LINKED ISSUE #17307: infinispan 16.0.9 server with rocksdb does not works in docker mode.
### Describe the bug

I was previously using infinispan 15.2.6 with rocksdb, it was working fine. But after I switched to 16.0.9 I started getting error when creating a cache with persistance

```
<distributed-cache statistics="true" owners="1">\    
<encoding media-type="application/x-protostream"/>\    
<locking striping="false" concurrency-level="256"/>\    
<persistence>\        
<rocksdb-store xmlns="urn:infinispan:config:store:rocksdb:16.0" path="publish-status-cache-rocksdb" shared="false" purge="false" transactional="false">\            
<compression type="SNAPPY"/>\        
</rocksdb-store>\    
</persistence>\    
<state-transfer await-initial-transfer="false" />\  
</distributed-cache>
```
Error I get is

```
Caused by: java.lang.NoClassDefFoundError: org/rocksdb/CompressionType
infinispan-1  |     at org.infinispan.persistence.rocksdb.configuration.CompressionType.<clinit>(CompressionType.java:4)
infinispan-1  |     at org.infinispan.persistence.rocksdb.configuration.RocksDBStoreConfiguration.<clinit>(RocksDBStoreConfiguration.java:23)
infinispan-1  |     at org.infinispan.persistence.rocksdb.configuration.RocksDBStoreConfigurationBuilder.<init>(RocksDBStoreConfigurationBuilder.java:23)
infinispan-1  |     at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
infinispan-1  |     ... 28 more
infinispan-1  | Caused by: java.lang.ClassNotFoundException: org.rocksdb.CompressionType
infinispan-1  |     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
infinispan-1  |     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
infinispan-1  |     ... 32 more
```
Below is my docker file

```
FROM quay.io/infinispan/server:16.0.9

RUN echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">' \
         '<profiles>' \
           '<profile>' \
             '<id>infinispan</id>' \
             '<repositories>' \
               '<repository>' \
                 '<id>infinispan</id>' \
                 '<url>https://repository.infinispan.org/</url>' \
               '</repository>' \
               '<repository>' \
                 '<id>central</id>' \
                 '<url>https://repo1.maven.org/maven2/</url>' \
               '</repository>' \
             '</repositories>' \
           '</profile>' \
         '</profiles>' \
         '<activeProfiles>' \
           '<activeProfile>infinispan</activeProfile>' \
         '</activeProfiles>' \
       '</settings>' > /tmp/settings.xml

ENV MAVEN_OPTS="-s /tmp/settings.xml"

RUN /opt/infinispan/bin/cli.sh install org.rocksdb:rocksdbjni:9.0.1
RUN /opt/infinispan/bin/cli.sh install org.infinispan:infinispan-cachestore-rocksdb:16.0.9

RUN cp /opt/infinispan/server/lib/rocksdbjni-9.0.1.jar /opt/infinispan/lib/
RUN cp /opt/infinispan/server/lib/infinispan-cachestore-rocksdb-16.0.9.jar /opt/infinispan/lib/

USER root
RUN chown -R 1000:1000 /opt/infinispan/server
USER 1000:1000

ENTRYPOINT ["/opt/infinispan/bin/launch.sh"]
```
I have confirmed that rocksdbjni jar is present in /opt/infinispan/lib and /opt/infinispan/server/lib

### Expected behavior

cache creation with rocksdb persistance should work

### Actual behavior

cache creation fails 

### How to Reproduce?

1. Use the docker file pasted above to create a docker image
2. run docker image to start server
3. Use any client to try to create cache based on cache config above

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes: #17307

Remove `infinispan-cachestore-rocksdb` from the server distribution's `lib/` directory. Users who want the RocksDB cache store must install both `infinispan-cachestore-rocksdb` and `rocksdbjni` into `server/lib/` using the CLI `install` command.

This also fixes `Bootstrap.configureClasspath()` which was creating a TCCL with `parent=null`, making it a sibling of the home/lib classloader. Classes loaded from `server/lib` could not resolve core Infinispan classes. The fix chains the TCCL to the existing classloader from the Loader, restoring proper parent delegation.

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
  - Added `RocksDBStoreIT` server integration test that installs both JARs via `mavenArtifacts()` and exercises put, get, update, remove operations.
- [x] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.
  - Updated `ref_cache_store_rocksdb.adoc` with server installation instructions and `changes.adoc` with updated CLI commands.
- [x] Log messages of level `INFO` and above have been internationalized.
~~- [ ] If the PR affects performance, include before/after benchmarks.~~
~~- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).~~
~~- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.~~

Reviewer Checklist (all must be checked):
- [x] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [x] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [x] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

Created with the assistance of an AI tool

### CODE REVIEW

File: server/tests/src/test/java/org/infinispan/server/persistence/RocksDBStoreIT.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import org.infinispan.commons.util.Version;
+import org.infinispan.server.test.core.ServerRunMode;
+import org.infinispan.server.test.core.tags.Persistence;
+import org.infinispan.server.test.junit5.InfinispanServerExtension;
+import org.infinispan.server.test.junit5.InfinispanServerExtensionBuilder;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.RegisterExtension;
+
+@Persistence
+public class RocksDBStoreIT {
```
Comment (Crumby) [inline server/tests/src/test/java/org/infinispan/server/persistence/RocksDBStoreIT.java:17]: Not sure why but when running the test locally in isolation it timeouts:

```
[ERROR] org.infinispan.server.persistence.RocksDBStoreIT.testRocksDBStore -- Time elapsed: 2.358 s <<< ERROR!
org.infinispan.client.hotrod.exceptions.TransportException:: java.net.SocketTimeoutException: NoCacheExecuteOperation{(default), flags=0}- CompletableFuture[org.infinispan.client.hotrod.impl.operations.NoCacheExecuteOperation@15a752b7[Not completed, 1 dependents]] timed out after 2000 ms
	at org.infinispan.client.hotrod.impl.Util.rewrap(Util.java:91)
	at org.infinispan.client.hotrod.impl.Util.await(Util.java:61)
	at org.infinispan.client.hotrod.impl.Util.await(Util.java:50)
	at org.infinispan.client.hotrod.impl.transport.netty.OperationDispatcher.await(OperationDispatcher.java:998)
	at org.infinispan.client.hotrod.impl.RemoteCacheManagerAdminImpl.getOrCreateCache(RemoteCacheManagerAdminImpl.java:94)
	at org.infinispan.server.test.api.HotRodTestClientDriver.create(HotRodTestClientDriver.java:147)
	at org.infinispan.server.test.api.HotRodTestClientDriver.create(HotRodTestClientDriver.java:129)
	at org.infinispan.server.test.api.HotRodTestClientDriver.create(HotRodTestClientDriver.java:119)
	at org.infinispan.server.persistence.RocksDBStoreIT.testRocksDBStore(RocksDBStoreIT.java:37)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.net.SocketTimeoutException: NoCacheExecuteOperation{(default), flags=0}- CompletableFuture[org.infinispan.client.hotrod.impl.operations.NoCacheExecuteOperation@15a752b7[Not completed, 1 dependents]] timed out after 2000 ms
	at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.checkForTimeouts(HeaderDecoder.java:116)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:160)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```


```
$ mvn -v
Apache Maven 3.9.9 (Red Hat 3.9.9-14)
Maven home: /usr/share/maven
Java version: 25.0.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-25-openjdk
$ mvn clean install -DskipTests
$ mvn verify -pl server/tests -Dit.test=RocksDBStoreIT
```

File: documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc [hunk 2]
```diff
@@ -7,6 +7,27 @@ RocksDB cache stores, `RocksDBStore`, use two databases. One database provides
 a primary cache store for data in memory; the other database holds entries that
 {brandname} expires from memory.
 
+.Server installation
```
Comment (Crumby) [inline documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc:10]: So I did try creating the cache manually after installing the libs via CLI but all I got is. There's nothing else to it but installing the libs before running the server, right?

```
ISPN000327: Cannot find a parser for element 'rocksdb-store' in namespace 'urn:infinispan:config:store:rocksdb:16.2' at [1,379]. Check that your configuration is up-to-date for Infinispan '16.2.0-SNAPSHOT' and you have the proper dependency in the classpath
```

**Review by Crumby — APPROVED** [review]

**Comment by Crumby** [comment]
Thanks @tristantarrant
