### PR TITLE
[#13284] shared storage index startup

### LINKED ISSUE #13284: Index consistency with shared stores and `auto` startup mode
### Describe the bug

Shared stores behave differently when a node starts; its content is not sent via state transfer (this is an optimization). The index startup mode does nothing when the data and indexes are persistent, assuming the data did not change. I suspect the following scenario will cause a mismatch between the indexes and the content of the shared store.

Let's start with 2 nodes, `A` and `B`, and a replicated cache (or a distributed cache with `owners>=2`). Indexing is enabled and stored in the filesystem (persistent indexes).

* Store `k=v` in the cache: `cache.put(k, v)`
* Perform query using an indexed field on node `B`: returns `k,v`
* Stops node `B`
* On node `A`, update the key, such as the indexed field has a different value: `cache.put(k,v')` 
* Evict the key so it is not sent by the state transfer: `cache.evitc(k)`
* Start node `B` (startup mode = AUTO)
* Perform query using an indexed field on node `B`: it should return an empty result if the index is not stale.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fax4ever**
Closes #13284

Thanks again @pruivo for the reproducer. It will be a nice template for possible similar tests in the future.
It is very cool IMO since with it we simulate the classic node crash / recovery scenario, in this case used to
verify the index consistency when a node recovers.

The fix I'm proposing is quite simple. Since we always have the data and the indexes and the data is always the
source of truth, we can realign the indexes.
Other suggestions are more than welcome.

### CODE REVIEW

File: query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java [hunk 1]
```diff
@@ -55,6 +58,46 @@ private static IndexStartupMode computeFinalMode(Configuration configuration) {
...
+      VOLATILE, PERSISTENT, SHARED_MEMORY_MAX_COUNT
+   }
+
+   private static DataKind computeDataKind(Configuration configuration) {
+      List<StoreConfiguration> cacheStores = configuration.persistence().stores();
+      if (cacheStores.isEmpty()) {
+         return DataKind.VOLATILE;
+      }
+
+      boolean nonSharedCacheStore = false;
```
Comment (wfink) [inline query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java:82]: isn't that superfluos?
sharedCacheStore=TRUE means that nonSharedCacheStore must be FALSE !!

File: query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java [hunk 2]
```diff
@@ -55,6 +58,46 @@ private static IndexStartupMode computeFinalMode(Configuration configuration) {
...
+            sharedCacheStore = true;
+         } else {
+            nonSharedCacheStore = true;
+         }
+      }
+
+      if (nonSharedCacheStore) {
+         return DataKind.PERSISTENT;
+      }
+      if (sharedCacheStore && configuration.memory().maxCount() > -1L) {
```
Comment (wfink) [inline query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java:98]: Is it only maxCount?
If maxSize has been set it is still eviction=enabled and the index need reindex as well?
So it is not SHARED_MEMORY_MAX_COUNT but SHARED_WITH_EVICTION ?

**Review by wfink — CHANGES_REQUESTED** [review]

File: query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java (hunk 2 above)
Comment (pruivo) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java:98]: @wfink is right. I'll make it simpler: if a shared store is configured, it must re-index the data to be on the safer side.

Comment (fax4ever) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java:98]: You're right, adding it! Thanks

Comment (fax4ever) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java:98]: @pruivo if `isEvictionEnabled` is false is it possible to have this issue?

File: query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java (hunk 1 above)
Comment (fax4ever) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java:82]: Not sure we can remove it. Since if we have 2 cache stores (one shared one not shared - I don't know if it is possible). In this case should return `DataKind.PERSISTENT`

**Comment by fax4ever** [comment]
Thanks for the review @wfink. I applied the changes.

File: query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java (hunk 2 above)
Comment (fax4ever) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java]: could you reproduce those other cases with a test? I'm asking since I want to limit the redindex at startup as much as we can.

Comment (fax4ever) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java]: If a user calls `evict` explicitly using indexes and a shared store, and a node crashes and recover, he deserves to have not aligned indexes .) I don't want to add more reindex on normal case to support this very peculiar and unsafe case.

Comment (pruivo) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java]: Added both combinations: https://github.com/pruivo/infinispan/blob/a513e727b5284c22a9fb6f758e0c39c80a969591/query/src/test/java/org/infinispan/query/distributed/IndexWithSharedStoreTest.java

`cache.evict()` is not unsafe and it is used by users who want to customize the eviction strategy.

Comment (fax4ever) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java]: At most we can add a note on the documetation saying that if the user does explicit eviction (only possible with embedded caches I think) if indexes are used, if shared storages are used if a node crash, the index could be not aligned. But I would avoid to support it with the auto, adding non required reindex at startup for more cases, where those are not required.

Comment (pruivo) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java]: https://infinispan.org/docs/stable/titles/configuring/configuring.html#eviction-manual_configuring-memory-usage

Comment (fax4ever) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java]: Is this supported by remote API?

File: query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java (hunk 1 above)
Comment (wfink) [reply query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java:82]: I would think that it can be simple 
If one is shared => must be true
Or
If one is unshared => must be false
So at least only 2 possibilities or am I missing a third case where you need to decide different?

**Review by wfink — APPROVED** [review]
LGTM

**Comment by pruivo** [comment]
> LGTM

I disagree. We are shooting ourselves in the foot and should re-index with a shared store, even in a topology change. The data in the shared store is not sent via state transfer and when a node leaves, the segments assigned to it will be assigned to a different node and the index won't reflect that. 

There are too many edge cases where indexes become out of sync with shared stores that should not be ignored.

**Comment by fax4ever** [comment]
@pruivo @wfink I give up in the spirit of collaboration. The team decision is more important than my point of view.

**Comment by fax4ever** [comment]
Rebased on top of the current main to not have the log4J issue running the test con CIs.

**Comment by tristantarrant** [comment]
Please mention the change in the upgrading guide

**Comment by fax4ever** [comment]
> Please mention the change in the upgrading guide

Done! Thanks for the suggestion

**Comment by fax4ever** [comment]
Thanks @tristantarrant for merging it!
