### PR TITLE
[#17058] Adjust rolling upgrade test parameters

### LINKED ISSUE #17058: Adjust rolling upgrade test parameters
### Description

We are having some flaky failures of the `DefaultRollingUpgradeTestIT`. The failure usually involves the servers starting in a partitioned, the test check waits for the default 45s until the containers are clustered, but then it times out. The merge view is installed a few milliseconds later. For example:

```
2026-03-16T20:01:37.4588099Z Caused by: java.util.concurrent.TimeoutException: After the await period 45 SECONDS the count down should be 0 and is 3
2026-03-16T20:01:37.4589109Z 	at org.infinispan.server.test.core.CountdownLatchLoggingConsumer.await(CountdownLatchLoggingConsumer.java:31)
2026-03-16T20:01:37.4590122Z 	at org.infinispan.server.test.core.ContainerInfinispanServerDriver.lambda$start$3(ContainerInfinispanServerDriver.java:175)
2026-03-16T20:01:37.4590983Z 	at org.infinispan.testing.Exceptions.unchecked(Exceptions.java:302)
2026-03-16T20:01:37.4591673Z 	... 84 more
2026-03-16T20:01:37.4591828Z 
2026-03-16T20:01:37.6225689Z 20:01:37,448 INFO  [o.i.s.t.c.r.RollingUpgradeHandler] Configurations for version 16.0.4 using org.infinispan:infinispan-server-tests:16.0.4:configurations
2026-03-16T20:01:37.9230027Z 20:01:37,894 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#0]STDOUT: 2026-03-16 20:01:37,890 INFO  [o.i.CLUSTER] ISPN000093: Received new, MERGED cluster view for channel org.infinispan.server.rollingupgrade.DefaultRollingUpgradeTestIT: MergeView::[bcdec1eb5676-52036(v=16.0.1)|2] (3) [bcdec1eb5676-52036(v=16.0.1), 5be8d89e1034-37469(v=16.0.1), 8b50682b0c55-2127(v=16.0.1)], 2 subgroups: [5be8d89e1034-37469(v=16.0.1)|1] (2) [5be8d89e1034-37469(v=16.0.1), 8b50682b0c55-2127(v=16.0.1)], [bcdec1eb5676-52036(v=16.0.1)|0] (1) [bcdec1eb5676-52036(v=16.0.1)]
2026-03-16T20:01:37.9243467Z 20:01:37,897 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#0]STDOUT: 2026-03-16 20:01:37,895 INFO  [o.i.CLUSTER] [Scope=5be8d89e1034-37469]ISPN100000: Node bcdec1eb5676-52036 joined the cluster
2026-03-16T20:01:37.9246331Z 20:01:37,900 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#0]STDOUT: 2026-03-16 20:01:37,897 INFO  [o.i.CLUSTER] [Scope=5be8d89e1034-37469]ISPN100000: Node bcdec1eb5676-52036 joined the cluster
2026-03-16T20:01:37.9250315Z 20:01:37,900 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#1]STDOUT: 2026-03-16 20:01:37,898 INFO  [o.i.CLUSTER] ISPN000093: Received new, MERGED cluster view for channel org.infinispan.server.rollingupgrade.DefaultRollingUpgradeTestIT: MergeView::[bcdec1eb5676-52036(v=16.0.1)|2] (3) [bcdec1eb5676-52036(v=16.0.1), 5be8d89e1034-37469(v=16.0.1), 8b50682b0c55-2127(v=16.0.1)], 2 subgroups: [5be8d89e1034-37469(v=16.0.1)|1] (2) [5be8d89e1034-37469(v=16.0.1), 8b50682b0c55-2127(v=16.0.1)], [bcdec1eb5676-52036(v=16.0.1)|0] (1) [bcdec1eb5676-52036(v=16.0.1)]
2026-03-16T20:01:37.9254071Z 20:01:37,903 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#1]STDOUT: 2026-03-16 20:01:37,903 INFO  [o.i.CLUSTER] [Scope=bcdec1eb5676-52036]ISPN100000: Node 5be8d89e1034-37469 joined the cluster
2026-03-16T20:01:37.9255872Z 20:01:37,911 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#1]STDOUT: 2026-03-16 20:01:37,911 INFO  [o.i.CLUSTER] [Scope=bcdec1eb5676-52036]ISPN100000: Node 8b50682b0c55-2127 joined the cluster
2026-03-16T20:01:37.9257596Z 20:01:37,913 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#1]STDOUT: 2026-03-16 20:01:37,912 INFO  [o.i.CLUSTER] [Scope=bcdec1eb5676-52036]ISPN100000: Node 5be8d89e1034-37469 joined the cluster
2026-03-16T20:01:37.9259325Z 20:01:37,916 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#1]STDOUT: 2026-03-16 20:01:37,914 INFO  [o.i.CLUSTER] [Scope=bcdec1eb5676-52036]ISPN100000: Node 8b50682b0c55-2127 joined the cluster
2026-03-16T20:01:38.0324102Z 20:01:37,927 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#2]STDOUT: 2026-03-16 20:01:37,917 INFO  [o.i.CLUSTER] ISPN000093: Received new, MERGED cluster view for channel org.infinispan.server.rollingupgrade.DefaultRollingUpgradeTestIT: MergeView::[bcdec1eb5676-52036(v=16.0.1)|2] (3) [bcdec1eb5676-52036(v=16.0.1), 5be8d89e1034-37469(v=16.0.1), 8b50682b0c55-2127(v=16.0.1)], 2 subgroups: [5be8d89e1034-37469(v=16.0.1)|1] (2) [5be8d89e1034-37469(v=16.0.1), 8b50682b0c55-2127(v=16.0.1)], [bcdec1eb5676-52036(v=16.0.1)|0] (1) [bcdec1eb5676-52036(v=16.0.1)]
2026-03-16T20:01:38.0331837Z 20:01:37,935 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#2]STDOUT: 2026-03-16 20:01:37,932 INFO  [o.i.CLUSTER] [Scope=8b50682b0c55-2127]ISPN100000: Node bcdec1eb5676-52036 joined the cluster
2026-03-16T20:01:38.0352826Z 20:01:37,939 INFO  [o.i.CONTAINER] [o.i.s.r.D.1.0.1#2]STDOUT: 2026-03-16 20:01:37,938 INFO  [o.i.CLUSTER] [Scope=8b50682b0c55-2127]ISPN100000: Node bcdec1eb5676-52036 joined the cluster
```

But then it's too late. The test has already failed.

### Implementation ideas

Adjust the starting sequence of containers, slightly increase the 45s timeout. 50s would be enough. Many other tests utilize a custom JGroups stack with the default values of MERGE3 updated. The `DefaultRollingUpgradeTestIT` runs with the default TCP stack.

### PR DESCRIPTION
**Pull request by jabolina**
Close #17058.

### CODE REVIEW

File: server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java [hunk 1]
```diff
@@ -429,6 +429,12 @@ private ConfigAndDriver startNode(VersionType versionType, int nodeCount, int ex
       // If the nodeCount was the same as expected it means it is the start of a fresh cluster. In that case we don't
       // need the join timeout as there shouldn't be any existing nodes in the cluster and don't wait
       builder.property(TestSystemPropertyNames.INFINISPAN_TEST_SERVER_REQUIRE_JOIN_TIMEOUT, Boolean.toString(nodeCount != expectedCount));
+
+      // Starting a fresh cluster in-order to avoid a split brain scenario during start up.
```
Comment (wburns) [inline server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java]: If this is the case then there is no reason to even use parallel startup imo.. Since we only start with nodeCount either equal to expected or 1, so we will never have parallel.

I am guessing parallel was introduced before to reduce total test time.. so I wonder what difference this makes in rolling upgrade test times.

Comment (jabolina) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java]: Thinking more about it, I guess I can take another approach. AFAICT, only the `DefaultRollingUpgrateTestIT` is using the default stack configuration/timeouts. This change would make all tests take longer instead of adjusting one specific test.

Comment (jabolina) [reply server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java]: Let's see how it goes. It should utilize the downloaded configuration from the old version and the one in the classpath from the new version.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
