### PR TITLE
[#15394] Fixes ProgrammaticSearchMappingProvider use case

### LINKED ISSUE #15394: Fixes Embedded Programmatic Schema use case
### Describe the bug

Create a cache where the config sets a class that is not annotated, but programmatically creating the index definition with the `ProgrammaticSearchMappingProvider` is broken in the embedded use case.

### PR DESCRIPTION
**Pull request by karesti**
Fixes #15394

### CODE REVIEW

File: query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+@Test(groups = "functional", testName = "query.query.ProgrammaticSearchMappingProviderTest")
+public class ProgrammaticSearchMappingProviderTest extends SingleCacheManagerTest {
+
+   @Override
+   protected EmbeddedCacheManager createCacheManager() throws Exception {
+      ConfigurationBuilder config = new ConfigurationBuilder();
+      config.indexing()
+              .enable()
+              .storage(LOCAL_HEAP)
+              .addIndexedEntity(ProgrammaticPerson.class.getName());
```
Comment (karesti) [inline query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java:27]: @marko-bekhta in this case, it will fail on start with ISPN000404: The configured entity class org.infinispan.query.mapper.ProgrammaticSearchMappingProviderTest$ProgrammaticPerson is not indexable. Please remove it from the indexing configuration.

This happens because in startup, there is a validation 

https://github.com/infinispan/infinispan/blob/main/query/src/main/java/org/infinispan/query/impl/LifecycleManager.java#L223

But the load in the mapper provider comes first by calling 

https://github.com/infinispan/infinispan/blob/main/query/src/main/java/org/infinispan/query/impl/LifecycleManager.java#L123C29-L123C48

It passes into MyProgrammaticSearchMappingProvider

but when it comes to

https://github.com/infinispan/infinispan/blob/793535578abda64e56754e52161903b816bd171b/query/src/main/java/org/infinispan/query/impl/LifecycleManager.java#L224

Fails because it is not indexed

File: query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+         typeMapping.property("name").fullTextField();
+         typeMapping.property("surname").fullTextField();
+         typeMapping.property("age").genericField(); // for numeric filtering/sorting
+      }
+   }
+
+   @Test
+   public void test() {
+      ConfigurationBuilder config = new ConfigurationBuilder();
+      config.indexing()
```
Comment (karesti) [inline query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java]: however, here the check is not done on the startup, so it does not fail

File: query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+              .enable()
+              .storage(LOCAL_HEAP)
+              .addIndexedEntity(ProgrammaticPerson.class.getName());
+
+      Cache<Object, Object> indexed = cacheManager.administration()
+              .withFlags(CacheContainerAdmin.AdminFlag.VOLATILE)
+              .getOrCreateCache("indexed", config.build());
+
+      indexed.put("person1", new ProgrammaticPerson("William", "Shakespeare", 50));
+      indexed.query("FROM " + ProgrammaticPerson.class.getName() + " WHERE name='William'");
```
Comment (karesti) [inline query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java]: however, this will fail if I perform a fulltext search with `name:'William'` because it is not indexed ...

**Comment by wburns** [comment]
Other tests are failing now as the services is being picked up by all the other tests now :( Is there a way to dynamically add the mapping providers, so we can do it per cache manger? 😆

**Comment by marko-bekhta** [comment]
> Other tests are failing now as the services is being picked up by all the other tests now :( Is there a way to dynamically add the mapping providers, so we can do it per cache manger? 😆

😖 😕 IDK if this would work for Infinispan... but maybe as an idea, in Validator we have something like this: https://github.com/hibernate/hibernate-validator/blob/3f8dc0abec5d81e62761003cacbb288a24ab7c59/engine/src/test/java/org/hibernate/validator/test/internal/xml/XmlMappingMixedWithServiceLoaderAndProgrammaticDefinitionTest.java#L199-L245 to "trick" it to think that it loads the services ...

**Comment by karesti** [comment]
I'll try to make this local

**Comment by karesti** [comment]
since the issue is that the test-jar in embedded mode is a dependency in client/server, I'm trying to register only when the test runs
having all the test-jar as a dependency, looks not super great to me, would be better to have as a dependency only the parts we need, from query (the models essentially)

**Comment by karesti** [comment]
@wburns looks it worked now

**Comment by wburns** [comment]
Weird, I thought it was like that before, but maybe not. But CI passed so :)

**Comment by wburns** [comment]
Integrated into main, thanks @karesti !
