### PR TITLE
[#16529] Encapsulate functional map implementation

### LINKED ISSUE #16529: FunctionalMap API is not encapsulated
### Describe the bug

The functional map API has a set of interfaces in the `org.infinispan.functional` package, but requires users to reference the `org.infinispan.functional.impl` package to construct instances. 
We should hide the impl package wherever possible

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #16529

### CODE REVIEW

File: core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java [hunk 1]
```diff
@@ -189,4 +189,19 @@ protected Set<?> encodeKeys(Set<? extends K> keys) {
...
+   }
+
+   @Override
+   public ReadOnlyMap<K, V> toReadOnlyMap() {
+      return new ReadOnlyMapImpl<>(Params.from(fmap.params.params), fmap);
+   }
+
+   @Override
+   public WriteOnlyMap<K, V> toWriteOnlyMap() {
+      return new WriteOnlyMapImpl<>(Params.from(fmap.params.params), fmap);
```
Comment (pruivo) [inline core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java]: All of these should use the `create` factory method, as it has some logic for simple caches.

**Review by pruivo — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/infinispan/functional/FunctionalMap.java [hunk 2]
```diff
@@ -66,6 +69,20 @@
...
+
+   static <K, V> FunctionalMap<K, V> create(AdvancedCache<K, V> cache) {
+      return FunctionalMapImpl.create(cache);
+   }
+
+   ReadWriteMap<K, V> toReadWriteMap();
+
+   ReadOnlyMap<K, V> toReadOnlyMap();
+
+   WriteOnlyMap<K,V> toWriteOnlyMap();
```
Comment (pruivo) [inline core/src/main/java/org/infinispan/functional/FunctionalMap.java]: Some Javadoc would be nice too

File: core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java (hunk 1 above)
Comment (tristantarrant) [reply core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java]: And I just noticed that `Params` is in the `impl` package. I need to refactor things slightly.

File: core/src/main/java/org/infinispan/functional/FunctionalMap.java (hunk 2 above)
Comment (tristantarrant) [reply core/src/main/java/org/infinispan/functional/FunctionalMap.java]: Added javadoc

**Comment by tristantarrant** [comment]
Failures should be fixed by https://github.com/infinispan/infinispan/pull/16560

**Comment by tristantarrant** [comment]
@pruivo this is ready.

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
merged! thanks @tristantarrant !
