### PR TITLE
[#17299] Retry @BeforeClass on setup failures

### LINKED ISSUE #17299: Flaky test detection does not retry TestNG @BeforeClass failures
## Problem

Maven Surefire's `rerunFailingTestsCount` correctly retries `@Test` method failures via the JUnit Platform / testng-engine delegation. However, it does **not** cover TestNG configuration methods (`@BeforeClass`, `@BeforeMethod`, etc.).

When a transient infrastructure issue hits a `@BeforeClass` method, all tests in the class are skipped rather than failed. Surefire never sees a test failure, so no retry is attempted and no `TEST-*FLAKY.xml` report is generated. These show up as hard failures in the test report.

## Evidence

Across multiple PRs, the following transient failures were reported as hard failures because they occurred in configuration methods:

- `ByteArrayValueReplEmbeddedHotRodTest.setup` — `BindException: Address already in use` (`@BeforeClass`)
- `RollbackNoPreparePessimisticTest.createBeforeClass` — timeout waiting for cross-site bridge view (`@BeforeClass`)
- `HotRodUpgradeContainerSSLTest.setup` — `Unable to start JGroups Channel` (`@BeforeClass`)

Examples:
- https://github.com/infinispan/infinispan/pull/16955/checks?check_run_id=72047677207
- https://github.com/infinispan/infinispan/pull/17286/checks?check_run_id=71831992389

## Root cause

All three base test classes have `@BeforeClass` methods that perform cluster/cache setup:

- `SingleCacheManagerTest.createBeforeClass()` → calls `setup()`
- `MultipleCacheManagersTest.createBeforeClass()` → calls `callCreateCacheManagers()`
- `AbstractXSiteTest.createBeforeClass()` → calls `createSites()`

TestNG's `IRetryAnalyzer` does not apply to configuration methods, and surefire's rerun mechanism only re-executes `@Test` methods that fail — not configuration methods.

## Fix

Add `Testing.retryOnFailure()` that wraps `@BeforeClass` methods in the base test classes with retry logic, using the same `rerunFailingTestsCount` property already passed by CI.

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #17299

Maven Surefire's `rerunFailingTestsCount` correctly retries `@Test` method failures via the JUnit Platform / testng-engine delegation. However, it does not cover TestNG `@BeforeClass` failures — when `@BeforeClass` fails, all tests in the class are skipped rather than failed, so surefire never retries them.

This PR adds retry logic for `@BeforeClass` methods:

- Add `Testing.retryOnFailure()` that wraps setup actions with retry (using the same `rerunFailingTestsCount` property already passed by CI)
- Apply to `SingleCacheManagerTest`, `MultipleCacheManagersTest`, `AbstractXSiteTest`, `EndpointsCacheFactory`, and persistence/remote tests
- Migrate `EntryActivatingTest` to `SingleCacheManagerTest` to gain coverage

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
~~- [ ] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.~~
~~- [ ] Log messages of level `INFO` and above have been internationalized.~~
~~- [ ] If the PR affects performance, include before/after benchmarks.~~
~~- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).~~
~~- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.~~

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

Created with the assistance of an AI tool

### CODE REVIEW

**Review by jabolina — APPROVED** [review]

File: core/src/test/java/org/infinispan/test/AbstractCacheTest.java [hunk 1]
```diff
@@ -93,4 +93,5 @@ public EmbeddedCacheManager manager(Cache<?, ?> c) {
    public String getDefaultCacheName() {
       return TestCacheManagerFactory.DEFAULT_CACHE_NAME;
    }
+
```
Comment (wburns) [inline core/src/test/java/org/infinispan/test/AbstractCacheTest.java]: Unneeded

File: core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java [hunk 2]
```diff
@@ -540,6 +540,42 @@ public void run() {
       }
    }
 
+   private static final int SETUP_RETRY_COUNT =
```
Comment (wburns) [inline core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java]: I wonder if we should have this in a common place instead of spreading out the reference to the `rerunFailingTestsCount` system property. Maybe in some sort of Test util class or something? We could probably even refactor the retry logic to a common method as well, so the logic isn't in many class files.

File: core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java [hunk 3]
```diff
@@ -540,6 +540,42 @@ public void run() {
...
+    * This compensates for the fact that Maven Surefire's {@code rerunFailingTestsCount}
+    * only retries {@code @Test} method failures, not TestNG configuration method
+    * ({@code @BeforeClass}) failures.
+    */
+   protected static void retryOnSetupFailure(ThrowingRunnable action, Runnable cleanup) throws Throwable {
+      for (int attempt = 0; ; attempt++) {
+         try {
+            action.run();
+            return;
+         } catch (Throwable t) {
```
Comment (wburns) [inline core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java]: Should we limit what kind of Exception we are catching?

Comment (tristantarrant) [reply core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java]: Are there passable exceptions?

Comment (wburns) [reply core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java]: I meant more to not retry.

Comment (tristantarrant) [reply core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java]: At worst it will fail all retries. It will be raised in the report

File: integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointsCacheFactory.java [hunk 4]
```diff
@@ -339,7 +339,22 @@ public Builder<K, V> withMediaType(MediaType mediaType) {
...
+                  try {
+                     endpointsCacheFactory.teardown();
+                  } catch (Exception ignored) {
+                  }
+                  Thread.sleep(2000);
+               } else {
+                  throw e;
+               }
+            }
+         }
```
Comment (rigazilla) [inline integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointsCacheFactory.java]:
```suggestion
         for (int attempt = 0; attempt < retryCount; attempt++) {
            try {
               return endpointsCacheFactory.setup();
            } catch (Exception ignored) {
               try {
                  endpointsCacheFactory.teardown();
               } catch (Exception ignored2) {
                 // ignored
               }
               Thread.sleep(2000);
            }
         }
         return endpointsCacheFactory.setup();
```

**Review by rigazilla — APPROVED** [review]
looks good, just an hint

**Comment by tristantarrant** [comment]
I have refactored the code so that the retry logic is in `Testing.retryOnFailure()`. Should be much cleaner now

**Comment by tristantarrant** [comment]
The failure is unrelated: #17071

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @tristantarrant!
