### PR TITLE
[#13399] RESP batch of flaky fixes

### LINKED ISSUE #13382: Flaky test: org.infinispan.server.resp.RespBxPOPTest#testBxpopThreeListenersTwoProducers\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.opentest4j.AssertionFailedError: 
expected: 1
 but was: 0
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at org.infinispan.server.resp.RespBxPOPTest.testBxpopThreeListenersTwoProducers(RespBxPOPTest.java:406)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13395: Flaky test: org.infinispan.server.resp.dist.BlockingCommandsClusteredTest#testBLMPOPTimeoutWhenNotAList
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
java.util.concurrent.ExecutionException: io.lettuce.core.RedisCommandExecutionException: WRONGTYPE Operation against a key holding the wrong kind of value
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.infinispan.server.resp.RespBxPOPTest.testBLMPOPTimeoutWhenNotAList(RespBxPOPTest.java:640)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.lettuce.core.RedisCommandExecutionException: WRONGTYPE Operation against a key holding the wrong kind of value
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:745)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:680)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:597)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

### LINKED ISSUE #13399: Flaky test: org.infinispan.server.resp.dist.BlockingCommandsClusteredTest#testSplitBLMPOP\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.opentest4j.AssertionFailedError: 
Expecting actual:
  [&amp;quot;v2&amp;quot;, &amp;quot;v1&amp;quot;]
to contain exactly (and in same order):
  [&amp;quot;v1&amp;quot;]
but some elements were not expected:
  [&amp;quot;v2&amp;quot;]

	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at org.infinispan.server.resp.RespBxPOPTest.testSplitBLMPOP(RespBxPOPTest.java:553)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #13660: Flaky test: org.infinispan.server.resp.RespBxPOPTest#testBxpopTwoListenersTwoProducers\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
org.opentest4j.AssertionFailedError: 
expected: 1
 but was: 0
	at org.infinispan.server.resp.RespBxPOPTest.testBxpopTwoListenersTwoProducers(RespBxPOPTest.java:356)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### PR DESCRIPTION
**Pull request by jabolina**
The only code change is for #13395. All the other fixes are changes in the test.

Basically, concurrency issues around the order of operation. In the tests, we needed to wait for push operations to complete before doing a range check.

Closes #13399.
Closes #13660.
Closes #13382.
Closes #13395.

### CODE REVIEW

**Review by rigazilla — APPROVED** [review]
great job!

File: server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java [hunk 1]
```diff
@@ -221,7 +223,12 @@ private PollListenerSynchronizer(EmbeddedMultimapListCache<byte[], byte[]> multi
          this.configuration = configuration;
          whenCompleteConsumer = (v, t) -> {
             if (t != null) {
-               resultFuture.completeExceptionally(t);
+               // Between installing the listener and doing the first poll, an entry was created.
+               // When trying to poll, we identify it is not a list element.
+               // We do not complete the future in this case, we leave it until the timeout elapses.
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java:228]: Should we reregister the listener but with a reduced timeout in case if a valid value comes later?

Comment (jabolina) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java:228]: Do you mean to deregister the current one and register again with (current - start) timeout?

Initially, I thought of completing with `null`, which is what happens in the timeout. But after comparing with Redis, the caller remains blocked until a timeout or a list is created. I guess the current one is the simplest way to have the same behavior.

Comment (wburns) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java:228]: Correct, reregister with (current - start) timeout so that if a list is added later it would be retrieved. Correct, me if I am wrong but the way this works now it will always cause a timeout if the type doesn't match, right?

Comment (jabolina) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java:228]: That's right. The listener should block until the timeout or a list is created. Not sure if showing the client console helps, but this is the expected behavior:

Client 1:
```text
127.0.0.1:6379> blpop list 0
1) "list"
2) "v3"
(25.54s)
```

Client 2:
```text
127.0.0.1:6379> set list v1
OK
127.0.0.1:6379> set list v2
OK
127.0.0.1:6379> del list
(integer) 1
127.0.0.1:6379> lpush list v1 v2 v3
(integer) 3
```

The command in client 1 is submitted first. The commands in client 2 are submitted later. The listener releases only after the push.

Comment (wburns) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java:228]: Okay, I see how it all flows now. The indirect recursion of the polling makes it so there is no need to do a reregistration.

File: server/resp/src/main/java/org/infinispan/server/resp/serialization/bytebuf/ByteBufThrowableSerializer.java [hunk 2]
```diff
@@ -12,11 +14,14 @@
  * @author José Bolina
  */
 final class ByteBufThrowableSerializer implements ResponseSerializer<Throwable, ByteBufPool> {
+   private static final Log log = LogFactory.getLog(ByteBufThrowableSerializer.class);
    static final ByteBufThrowableSerializer INSTANCE = new ByteBufThrowableSerializer();
    private static final String DEFAULT_ERROR_MESSAGE = "failed handling command";
 
    @Override
    public void accept(Throwable throwable, ByteBufPool alloc) {
+      log.errorf(throwable, "Exception while handling a command");
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/serialization/bytebuf/ByteBufThrowableSerializer.java:23]: Did you mean to include this? If we do want to log as ERROR we need it added to the Log interface.

Comment (jabolina) [reply server/resp/src/main/java/org/infinispan/server/resp/serialization/bytebuf/ByteBufThrowableSerializer.java:23]: I used it briefly to debug something. I can remove it.

**Review by wburns — APPROVED** [review]

File: server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java [hunk 3]
```diff
@@ -84,6 +85,7 @@ private CompletableFuture<Collection<byte[]>> addSubscriber(PopConfiguration con
       if (log.isTraceEnabled()) {
          log.tracef("Subscriber for keys: " + configuration.keys());
       }
+      log.info("Adding a pop subscriber");
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java:88]: Oh this has to be removed :)

Comment (jabolina) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java:88]: Doh

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
