### PR TITLE
[#13908] Manually load JDBC driver

### LINKED ISSUE #13908: JGroupsJdbcPing2IT failing due to JDBC driver not found
### Description

The `JGroupsJdbcPing2IT` tests are frequently failing in the `mssql`, `oracle` and normal testsuite with the following error:

```java
 ERROR [o.j.p.JDBC_PING2] fv-az1308-781-50785: failed reading from the DB java.sql.SQLException: No suitable driver found for jdbc:sqlserver://172.17.0.3:1433;encrypt=true;trustServerCertificate=true
  java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
  java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
  org.infinispan.server.persistence.JGroupsJdbcPing2IT$DummyDataSource.getConnection(JGroupsJdbcPing2IT.java:190)
  org.infinispan.server.persistence.JGroupsJdbcPing2IT$DummyDataSource.getConnection(JGroupsJdbcPing2IT.java:185)
  org.jgroups.protocols.JDBC_PING2.getConnection(JDBC_PING2.java:308)
  org.jgroups.protocols.JDBC_PING2.readFromDB(JDBC_PING2.java:219)
  org.jgroups.protocols.JDBC_PING2.readAll(JDBC_PING2.java:203)
  org.jgroups.protocols.FILE_PING.findMembers(FILE_PING.java:146)
  org.jgroups.protocols.Discovery.callFindMembersInAllDiscoveryProtocols(Discovery.java:400)
  org.jgroups.protocols.Discovery.findMembers(Discovery.java:240)
  org.jgroups.protocols.Discovery.down(Discovery.java:437)
  org.jgroups.protocols.FILE_PING.down(FILE_PING.java:141)
  org.jgroups.protocols.MERGE3.down(MERGE3.java:268)
  org.jgroups.protocols.FD_SOCK2.down(FD_SOCK2.java:232)
  org.jgroups.protocols.FailureDetection.down(FailureDetection.java:159)
  org.jgroups.protocols.VERIFY_SUSPECT2.down(VERIFY_SUSPECT2.java:84)
  org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:632)
  org.jgroups.protocols.UNICAST3.down(UNICAST3.java:661)
  org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:285)
  org.jgroups.protocols.pbcast.ClientGmsImpl.joinInternal(ClientGmsImpl.java:67)
  org.jgroups.protocols.pbcast.ClientGmsImpl.join(ClientGmsImpl.java:37)
  org.jgroups.protocols.pbcast.GMS.down(GMS.java:905)
  org.jgroups.protocols.FlowControl.down(FlowControl.java:201)
  org.jgroups.protocols.FlowControl.down(FlowControl.java:201)
  org.jgroups.stack.Protocol.down(Protocol.java:308)
  org.jgroups.protocols.FRAG2.down(FRAG2.java:103)
  org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:948)
  org.jgroups.JChannel.down(JChannel.java:612)
  org.jgroups.JChannel._connect(JChannel.java:825)
  org.jgroups.JChannel.connect(JChannel.java:331)
  org.jgroups.JChannel.connect(JChannel.java:321)
  org.infinispan.server.persistence.JGroupsJdbcPing2IT.testDBConnectionLost(JGroupsJdbcPing2IT.java:85)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:767)
  org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
  org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
  org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
  org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
  org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
```

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Only fallback to DriverManager if needed.

Closes #13908

### CODE REVIEW

File: server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java [hunk 1]
```diff
@@ -230,4 +236,109 @@ public Logger getParentLogger() {
...
+
+               @Override
+               public Logger getParentLogger() throws SQLFeatureNotSupportedException {
+                  return driver.getParentLogger();
+               }
+            });
+            return driver;
+         }
+
+         throw new SQLException("No suitable driver", "08001");
```
Comment (wburns) [inline server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java:321]: We should probably put the caused by to the original exception we caught.

File: server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java [hunk 2]
```diff
@@ -230,4 +236,109 @@ public Logger getParentLogger() {
...
+      }
+
+      public static Connection getConnection(String url, String user, String password, ClassLoader[] cls) throws SQLException {
```
Comment (wburns) [inline server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java:324]: Should we instead call `DriverManager.getConnection(connectionUrl, username, password);` here like it was before and then do the catch?

**Comment by tristantarrant** [comment]
My local aot branch gets rid of the layered classloaders, and might be a better solution

**Comment by jabolina** [comment]
Updated with suggestion.


> My local aot branch gets rid of the layered classloaders, and might be a better solution

That sounds interesting. I'll put this one on hold.

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by tristantarrant** [comment]
@jabolina I think it would be a good idea to backport this to 15.2, 15.1, 15.0
