### PR TITLE
[#16266] Per-version test configuration files

### LINKED ISSUE #16266: Per-version server test configuration
### Describe the bug

To test rolling upgrades when we bump versions, the configuration files should be included in Maven with the respective files. The configurations should include everything under `server/tests/src/test/resources/configuration`.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Assembly all the configuration files utilized by tests.
* Publish zip with `configurations` classifier.
* Rolling-upgrades download the files with the correct from version.
* Version identifier represents maven and image label.

Closes #16266.

### CODE REVIEW

File: server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTestUtil.java [hunk 1]
```diff
@@ -1,26 +1,32 @@
...
 
+import org.infinispan.commons.util.Version;
+import org.infinispan.server.test.core.rollingupgrade.RollingUpgradeVersion;
+
 public class RollingUpgradeTestUtil {
-   public static String getFromVersion() {
-      return System.getProperty(INFINISPAN_ROLLING_UPGRADE_FROM_VERSION, "latest");
+   public static RollingUpgradeVersion getFromVersion() {
+      String label = System.getProperty(INFINISPAN_ROLLING_UPGRADE_FROM_VERSION, "latest");
+      String version = System.getProperty(INFINISPAN_ROLLING_UPGRADE_FROM_VERSION_MAVEN, "16.0.3");
```
Comment (tristantarrant) [inline server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTestUtil.java]: There is also the `infinispan.old.version` property in https://github.com/infinispan/infinispan/blob/main/build/configuration/pom.xml#L51 which could be used here. It will need to be added to the system properties in the surefire configuration

**Comment by jabolina** [comment]
I've added on hold label so we wait until the PR for 16.0.x and a release is in place.

File: server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTestUtil.java (hunk 1 above)
Comment (jabolina) [reply server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTestUtil.java]: That one seems to be the property we want.

**Comment by jabolina** [comment]
Updated. Fixed the old version in 16.0.3.

**Comment by tristantarrant** [comment]
I've merged this. We'll fix the namespace version issue in https://github.com/infinispan/infinispan/pull/16292
