### PR TITLE
[RESP] Added dependency for json/regex filter and fixed pattern syntax

### LINKED ISSUE #16144: JSON.GET with filter fails on NoClassDefFound: net/minidev/json/parser/ParseException
### Describe the bug

Using filters in JSON.GET results either in incorrect response or `NoClassDefFound: net/minidev/json/parser/ParseException'.

**Test:** `tests/pytests/test.py:testFilter`

**StackTrace:**
```
ERROR [o.i.i.i.InvocationContextInterceptor] ISPN000136: Error executing command ReadWriteKeyCommand on Cache 'respCache', writing keys [WrappedByteArray[\d\o\c (3 bytes)]]java.lang.NoClassDefFoundError: net/minidev/json/parser/ParseException
	at com.jayway.jsonpath.internal.filter.ValueNode.createJsonNode(ValueNode.java:207)
	at com.jayway.jsonpath.internal.filter.ValueNodes$PathNode.evaluate(ValueNodes.java:703)
	at com.jayway.jsonpath.internal.filter.RelationalExpressionNode.apply(RelationalExpressionNode.java:37)
	at com.jayway.jsonpath.internal.filter.FilterCompiler$CompiledFilter.apply(FilterCompiler.java:430)
	at com.jayway.jsonpath.internal.path.PredicatePathToken.accept(PredicatePathToken.java:77)
	at com.jayway.jsonpath.internal.path.PredicatePathToken.evaluate(PredicatePathToken.java:60)
	at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:90)
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:80)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:66)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:99)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:107)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:191)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:88)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:77)
	at org.infinispan.server.resp.json.JsonGetFunction.apply(JsonGetFunction.java:91)
	at org.infinispan.server.resp.json.JsonGetFunction.apply(JsonGetFunction.java:27)
	at org.infinispan.interceptors.impl.CallInterceptor.visitReadWriteKeyCommand(CallInterceptor.java:986)
	at org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:70)
	at org.infinispan.interceptors.impl.CallInterceptor.visitCommand(CallInterceptor.java:151)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:60)
	at org.infinispan.interceptors.BaseAsyncInterceptor.asyncInvokeNext(BaseAsyncInterceptor.java:231)
	at org.infinispan.interceptors.impl.EntryWrappingInterceptor.setSkipRemoteGetsAndInvokeNextForDataCommand(EntryWrappingInterceptor.java:732)
	at org.infinispan.interceptors.impl.EntryWrappingInterceptor.visitReadWriteKeyCommand(EntryWrappingInterceptor.java:512)
	at org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:70)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndFinally(BaseAsyncInterceptor.java:154)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.lambda$nonTxLockAndInvokeNext$0(AbstractLockingInterceptor.java:318)
	at org.infinispan.interceptors.SyncInvocationStage.andHandle(SyncInvocationStage.java:71)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.nonTxLockAndInvokeNext(AbstractLockingInterceptor.java:313)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitNonTxDataWriteCommand(AbstractLockingInterceptor.java:138)
	at org.infinispan.interceptors.locking.NonTransactionalLockingInterceptor.visitDataWriteCommand(NonTransactionalLockingInterceptor.java:41)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitReadWriteKeyCommand(AbstractLockingInterceptor.java:202)
	at org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:70)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextThenApply(BaseAsyncInterceptor.java:78)
	at org.infinispan.interceptors.impl.CacheMgmtInterceptor.updateStatisticsReadWrite(CacheMgmtInterceptor.java:332)
	at org.infinispan.interceptors.impl.CacheMgmtInterceptor.visitReadWriteKeyCommand(CacheMgmtInterceptor.java:354)
	at org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:70)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:58)
	at org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:54)
	at org.infinispan.interceptors.DDAsyncInterceptor.visitReadWriteKeyCommand(DDAsyncInterceptor.java:195)
	at org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:70)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndExceptionally(BaseAsyncInterceptor.java:127)
	at org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:90)
	at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invokeAsync(AsyncInterceptorChainImpl.java:211)
	at org.infinispan.functional.impl.AbstractFunctionalMap.invokeAsync(AbstractFunctionalMap.java:141)
	at org.infinispan.functional.impl.ReadWriteMapImpl.eval(ReadWriteMapImpl.java:59)
	at org.infinispan.functional.FunctionalMap$ReadWriteMap.eval(FunctionalMap.java:524)
	at org.infinispan.server.resp.json.EmbeddedJsonCache.get(EmbeddedJsonCache.java:63)
	at org.infinispan.server.resp.commands.json.JSONGET.perform(JSONGET.java:40)
	at org.infinispan.server.resp.Resp3Handler.actualHandleRequest(Resp3Handler.java:96)
	at org.infinispan.server.resp.RespRequestHandler.handleRequest(RespRequestHandler.java:88)
	at org.infinispan.server.resp.RespHandler.handleCommandAndArguments(RespHandler.java:194)
	at org.infinispan.server.resp.RespHandler.channelRead(RespHandler.java:170)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.infinispan.server.core.transport.StatsChannelHandler.channelRead(StatsChannelHandler.java:28)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: net.minidev.json.parser.ParseException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 76 more
```

### Expected behavior

```
127.0.0.1:6379> JSON.SET doc $ '{"arr": ["kaboom", "kafoosh", "four", "bar", 7.0, "foolish", ["food", "foo", "FoO", "fight"], -9]}'
OK
127.0.0.1:6379> JSON.GET doc '$.arr[?(@ =~ ".*foo")]'
["kafoosh", "foolish"]
127.0.0.1:6379> JSON.SET doc2 $ '{"arr": ["kaboom", "kafoosh", "four", "bar", 7.0, "foolish", -9]}'
OK
127.0.0.1:6379> JSON.GET doc2 '$.arr[?(@ =~ ".*foo")]'
["kafoosh", "foolish"]
```

### Actual behavior

```
127.0.0.1:6379> JSON.SET doc $ '{"arr": ["kaboom", "kafoosh", "four", "bar", 7.0, "foolish", ["food", "foo", "FoO", "fight"], -9]}'
OK
127.0.0.1:6379> JSON.GET doc '$.arr[?(@ =~ ".*foo")]'
(error) ERR net.minidev.json.parser.ParseException
127.0.0.1:6379> JSON.SET doc2 $ '{"arr": ["kaboom", "kafoosh", "four", "bar", 7.0, "foolish", -9]}'
OK
127.0.0.1:6379> JSON.GET doc2 '$.arr[?(@ =~ ".*foo")]'
"[]"
```

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by rigazilla**
Fixes #16144 

When filtering with regex an additional dependecy is needed (net.minidev.json-smart)
Added conversion to support Redis style regex pattern.
Documented Redis/infinispan diff

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/json/JSONUtil.java [hunk 1]
```diff
@@ -9,131 +11,221 @@
 import com.jayway.jsonpath.ParseContext;
 
 public class JSONUtil {
-   private static byte JSON_ROOT_BYTE = '$';
```
Comment (Crumby) [inline server/resp/src/main/java/org/infinispan/server/resp/json/JSONUtil.java:12]: @rigazilla There's something off with the formatting of this file. What's the Infinispan project policy for tab width? I thinks it's 3 spaces but the lines are reformatted to 4 (I can see that some methods did use 2 only so they should be synced)

File: documentation/src/main/asciidoc/topics/ref_redis_commands.adoc [hunk 2]
```diff
@@ -159,6 +159,16 @@ NOTE: This implementation attempts to return all attributes that a real Redis se
 * link:https://redis.io/commands/json.forget[JSON.FORGET]
 
 * link:https://redis.io/commands/json.get[JSON.GET]
++
+[NOTE]
+=====
+ JSON filter with RegEx differencies from Redis implementation:
+
+1. Pattern could be expressed in Redis style "(i)pattern" or Java style "/.*pattern.*/i)".
+2. Dynamic filter with regex is not supported. i.e. `$.store.book[?(@.name < $.pattern)]` doesn't work.
```
Comment (Crumby) [inline documentation/src/main/asciidoc/topics/ref_redis_commands.adoc]: Do you know why it doesn't work? Is there a missing supported in the used library?

Comment (rigazilla) [reply documentation/src/main/asciidoc/topics/ref_redis_commands.adoc]: yes jsonpath doesn't support dynamic filter with regex

File: server/resp/pom.xml [hunk 3]
```diff
@@ -39,6 +39,16 @@
...
          <version>${version.json-path}</version>
       </dependency>
+      <dependency>
+         <groupId>net.minidev</groupId>
+         <artifactId>json-smart</artifactId>
+         <version>${version.json-smart}</version>
+      </dependency>
+      <dependency>
+         <groupId>net.minidev</groupId>
+         <artifactId>json-smart</artifactId>
```
Comment (Crumby) [inline server/resp/pom.xml]: Duplicate?

File: documentation/src/main/asciidoc/topics/ref_redis_commands.adoc (hunk 2 above)
Comment (rigazilla) [reply documentation/src/main/asciidoc/topics/ref_redis_commands.adoc]: I've created an issue: https://github.com/json-path/JsonPath/issues/1062

Comment (Crumby) [reply documentation/src/main/asciidoc/topics/ref_redis_commands.adoc]: Looking at the README on JsonPath there's an example that seems to suggest it should work: `$..book[?(@.price <= $['expensive'])]`: https://github.com/json-path/JsonPath/blob/master/README.md?plain=1#L161

File: server/resp/src/test/java/org/infinispan/server/resp/JsonFilterCommandsTest.java [hunk 4]
```diff
@@ -0,0 +1,232 @@
...
+      JsonPath combinedFilterPath = new JsonPath("$.scores[?(@.score > @.threshold && @.bonus > 10)]");
+      result = redis.jsonGet(key4, combinedFilterPath);
+      assertThat(result).hasSize(1);
+      assertThat(result.get(0).asJsonArray().size()).isEqualTo(1);
+      resultStr = result.get(0).toString();
+      assertThat(resultStr).contains("charlie");
+      assertThat(resultStr).doesNotContain("alice");
+      assertThat(resultStr).doesNotContain("bob");
+
+      JsonPath dynRegexFilterPath = new JsonPath("$.scores[?(@.player == $.pattern)]");
```
Comment (Crumby) [inline server/resp/src/test/java/org/infinispan/server/resp/JsonFilterCommandsTest.java]: Here it looks like we are testing a functionality we claim doesn't work

Comment (rigazilla) [reply server/resp/src/test/java/org/infinispan/server/resp/JsonFilterCommandsTest.java]: > Here it looks like we are testing a functionality we claim doesn't work

This works because it's not a regex filter. The name of the variable was misleading, changed

File: documentation/src/main/asciidoc/topics/ref_redis_commands.adoc (hunk 2 above)
Comment (rigazilla) [reply documentation/src/main/asciidoc/topics/ref_redis_commands.adoc]: this should work cause is not a regex operator `=~`

File: documentation/src/main/asciidoc/topics/ref_redis_commands.adoc [hunk 5]
```diff
@@ -159,6 +159,16 @@ NOTE: This implementation attempts to return all attributes that a real Redis se
...
+3. Filtering an array returns all matching elements and all nested arrays containing matching elements.
```
Comment (rigazilla) [inline documentation/src/main/asciidoc/topics/ref_redis_commands.adoc:169]: I've opened an issue also for this
https://github.com/json-path/JsonPath/issues/1063

File: documentation/src/main/asciidoc/topics/ref_redis_commands.adoc (hunk 2 above)
Comment (Crumby) [reply documentation/src/main/asciidoc/topics/ref_redis_commands.adoc]: Should we change the example `$.store.book[?(@.name < $.pattern)]` to reflect the pattern usage?

**Comment by Crumby** [comment]
Looks like new dependency is causing the `FootprintIT.testDiskFootprint` failure due and it'll require new adjusted values.

File: server/resp/pom.xml [hunk 6]
```diff
@@ -39,6 +39,11 @@
          <artifactId>json-path</artifactId>
          <version>${version.json-path}</version>
       </dependency>
+      <dependency>
+         <groupId>net.minidev</groupId>
+         <artifactId>json-smart</artifactId>
```
Comment (Crumby) [inline server/resp/pom.xml:44]: @rigazilla I believe this addition is causing `FootprintIT.testDiskFootprint` to fail, the test should be  adjusted to account for a new dependency and increased disk footprint.

Comment (rigazilla) [reply server/resp/pom.xml:44]: thanks @Crumby, I raised the thresholds by 1.5 M

**Comment by Crumby** [comment]
@rigazilla Can you please squash (and rebase) the changes? The code changes look good but I think it should go in as a single commit, new dependency and limit increase as they are related.

**Comment by rigazilla** [comment]
> @rigazilla Can you please squash (and rebase) the changes? The code changes look good but I think it should go in as a single commit, new dependency and limit increase as they are related.

ok done

File: build/configuration/pom.xml [hunk 7]
```diff
@@ -117,6 +117,7 @@
       <version.jgroups>5.5.1.Final</version.jgroups>
       <version.jgroups.raft>1.1.3.Final</version.jgroups.raft>
       <version.json-path>2.10.0</version.json-path>
+      <version.json-smart>2.6.0</version.json-smart>
```
Comment (tristantarrant) [inline build/configuration/pom.xml:120]: @pminz new dependency
