### PR TITLE
[#14459] Fix RESP script load authorization

### LINKED ISSUE #14459: SCRIPT LOAD - raises ISPN000287: Unauthorized access: subject 'null' lacks 'CREATE' permission
### Describe the bug

```bash
redis-cli -3 -p 11222 --raw
127.0.0.1:11222> AUTH admin password
OK
127.0.0.1:11222> EVAL "return ARGV[1]" 0 Parameterization!
Parameterization!
127.0.0.1:11222> SCRIPT LOAD "return 'Immabe a cached script'"
ERR ISPN000287: Unauthorized access: subject 'null' lacks 'CREATE' permission
```

### Expected behavior

```bash
127.0.0.1:6379> SCRIPT LOAD "return 'Immabe a cached script'"
"c664a3bf70bd1d45c4284ffebb65a6f2299bfc9f"
127.0.0.1:6379>
```

### Actual behavior

A warning is logged in the server, the user is not getting propagated, the SCRIPT LOAD is failing

### How to Reproduce?

Already described above

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

15.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #14459

### CODE REVIEW

File: server/tests/src/test/java/org/infinispan/server/functional/resp/RespScriptTest.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+import java.util.List;
+
+import org.junit.jupiter.api.Test;
+
+import io.vertx.core.Vertx;
+import io.vertx.junit5.VertxTestContext;
+import io.vertx.redis.client.RedisAPI;
+import io.vertx.redis.client.impl.types.ErrorType;
+
+public class RespScriptTest extends AbstractRespTest {
```
Comment (karesti) [inline server/tests/src/test/java/org/infinispan/server/functional/resp/RespScriptTest.java:17]: I believed we had already a test, ScriptingTest, but I'm fine on adding this one

**Review by wburns — APPROVED** [review]
