### PR TITLE
[#15742] Fix BaseDistSyncL1Test flaky tests

### LINKED ISSUE #15742: Flaky test: org.infinispan.distribution.DistSyncTxL1FuncTest#testRemoteGetArrivesButWriteOccursBeforeRegistration\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/18130483092
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:259)
	at java.base/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:437)
	at org.infinispan.distribution.BaseDistSyncL1Test.testRemoteGetArrivesButWriteOccursBeforeRegistration(BaseDistSyncL1Test.java:326)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #15742

### CODE REVIEW

File: core/src/test/java/org/infinispan/distribution/BaseDistSyncL1Test.java [hunk 1]
```diff
@@ -332,8 +332,10 @@ public void testRemoteGetArrivesButWriteOccursBeforeRegistration() throws Throwa
       try {
          Future<String> future = fork(() -> nonOwnerCache.get(key));
 
-         // Wait until get goes remote and retrieves value before going back into L1 interceptor
-         checkPoint.awaitStrict(Mocks.AFTER_INVOCATION, 2, 10, TimeUnit.SECONDS);
+         // Wait until get goes remote and retrieves value before going back into L1 interceptor.
+         // The staggered RPC sends to the primary owner first, then waits for a stagger delay before
+         // trying the backup. We only need one owner to have processed the command to proceed.
+         checkPoint.awaitStrict(Mocks.AFTER_INVOCATION, 1, 10, TimeUnit.SECONDS);
```
Comment (wburns) [inline core/src/test/java/org/infinispan/distribution/BaseDistSyncL1Test.java]:
```suggestion
         checkPoint.awaitStrict(Mocks.AFTER_INVOCATION, 10, TimeUnit.SECONDS);
```

File: core/src/test/java/org/infinispan/distribution/BaseDistSyncL1Test.java
Comment (wburns) [inline core/src/test/java/org/infinispan/distribution/BaseDistSyncL1Test.java]: Please remove this line as well

**Comment by tristantarrant** [comment]
Applied your suggestions

**Comment by wburns** [comment]
Integrated into main, thanks @tristantarrant !
