### PR TITLE
[#16084] Prevent IOUring warning when EPOLL used

### LINKED ISSUE #16084: Prevent IOUring warning when EPOLL used
### Description

We always get the following server log regardless of whether EPOLL is used instead of NIO.

```
2025-11-06 11:45:43,828 INFO  [o.i.SERVER] ISPN005054: Native IOUring transport not available, using NIO instead: java.lang.RuntimeException: failed to create io_uring ring fd: Operation not permitted
```

We should only log this warning if EPOLL & IORING are not available

### Implementation ideas

The problem seems to be that we're using eagerly inisitialized static variables:

```
   static final boolean USE_NATIVE_EPOLL = useNativeEpoll();
   static final boolean USE_NATIVE_IOURING = useNativeIOUring();
```

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #16084

### CODE REVIEW

File: server/core/src/main/java/org/infinispan/server/core/transport/NativeTransport.java [hunk 1]
```diff
@@ -22,8 +22,23 @@ public final class NativeTransport {
...
+   enum Type {
+      EPOLL,
+      IOURING,
+      NIO
+   }
+
+   private static Type transportType() {
+      if (useNativeEpoll()) {
+         return Type.EPOLL;
+      } else if (useNativeIOUring()) {
```
Comment (pruivo) [inline server/core/src/main/java/org/infinispan/server/core/transport/NativeTransport.java:36]: shouldn't checking `useNativeIOUring` be the first?

Comment (ryanemerson) [reply server/core/src/main/java/org/infinispan/server/core/transport/NativeTransport.java:36]: AFAICT the current behaviour is that we always check for EPOLL first before IOUring.

If we want to change the default behaviour, to favour IOURing over Epoll I think that's a different issue and ideally one we don't tackle this close to 16.0.0 :sweat_smile:

Comment (ryanemerson) [reply server/core/src/main/java/org/infinispan/server/core/transport/NativeTransport.java:36]: `netty-incubator-transport-native-io_uring` is part of `io.netty.incubator` until Netty 4.2, where it has graduated to being part of the main release: https://netty.io/wiki/netty-4.2-migration-guide.html#compatibility-highlights

Maybe we should make the change when we're able to upgrade to Netty 4.2?

Comment (pruivo) [reply server/core/src/main/java/org/infinispan/server/core/transport/NativeTransport.java:36]: My bad, for some reason I thought IO_Uring was the default :facepalm: 
It fails if I enable it :sweat_smile: 
```
Caused by: java.lang.RuntimeException: failed to allocate memory for io_uring ring; try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l): Cannot allocate memory
	at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:209)
	at io.netty.incubator.channel.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:79)
```
