### PR TITLE
[#17016] Cache stop waits pending state transfer

### LINKED ISSUE #17016: Cache stop waits for state transfer to complete
### Description

Right now, the cache stop mechanism is completely non-blocking: multiple nodes can leave simultaneously. The caveat is that this can lead to data loss. We should provide an API to stop the cache and wait for any pending state transfer. The API should be available in the `Cache` and `EmbeddedCacheManager` interfaces, something like:

```
// Cache
boolean stop(long timeout, TimeUnit unit) throws InterruptedException;

// EmbeddedCacheManager, to stop all caches.
boolean stop(long timeout, TimeUnit unit) throws InterruptedException;

// EmbeddedCacheManager, for a single cache.
boolean stopCache(String cacheName, long timeout, TimeUnit unit) throws InterruptedException
```

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* New methods to stop a cache and wait for a period of time until state transfer has completed.
* Avoid data loss when scaling down the cluster to a single node.

I had to change the state tracker to global. Otherwise, when the cache stops, I wouldn't be able to retrieve it.

The idea is to wait for the pending state transfer to complete before leaving. We use the state transfer tracker to wait until a new topology is installed.

On the coordinator side, we serialize the leave requests to tolerate concurrent node leaves. We also wait until this chain of leave requests is complete before the coordinator stops.

This way, we should tolerate data loss even when concurrent nodes leave and the coordinator changes. 

Closes: #17016

There will be a follow-up to add a REST/CLI command: https://github.com/infinispan/infinispan/issues/17017

---

Author Checklist (all must be checked):
- [X] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [X] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [X] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [ ] ~The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.~
- [X] Log messages of level `INFO` and above have been internationalized.
- [ ] ~If the PR affects performance, include before/after benchmarks.~
- [ ] ~If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).~
- [X] If the PR requires a follow-up or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.

---

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

**Comment by jabolina** [comment]
Looks like a flaky in the new test. I'll take a look.

**Comment by jabolina** [comment]
Pushed an update for the flaky failure. When the coordinators are leaving in sequence, we retry the leave command (if it has a timeout), until it lands on a stable coordinator to serially handle the leave commands.

File: core/src/main/java/org/infinispan/commands/topology/CacheLeaveCommand.java [hunk 1]
```diff
@@ -22,20 +23,24 @@ public class CacheLeaveCommand extends AbstractCacheControlCommand {
    @ProtoField(1)
    final String cacheName;
 
+   @ProtoField(2)
```
Comment (wburns) [inline core/src/main/java/org/infinispan/commands/topology/CacheLeaveCommand.java]: Should the default be Long.MIN_VALUE like others?

File: core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java [hunk 2]
```diff
@@ -395,7 +443,11 @@ public CompletionStage<ManagerStatusResponse> handleStatusRequest(int viewId) {
                      final String name = cacheName;
                      join(name, cacheStatus)
                            .whenComplete((ignore, t) -> {
-                              if (t != null) leave(name, getGlobalTimeout());
+                              if (t != null) {
+                                 try {
+                                    leave(name, getGlobalTimeout(), false);
+                                 } catch (InterruptedException ignored1) { }
```
Comment (wburns) [inline core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java]: I am not a fan of ignoring InterruptedExceptions.. we should at least set the thread interrupt state.

File: core/src/main/java/org/infinispan/topology/OrderedGracefulLeaveHandler.java [hunk 3]
```diff
@@ -0,0 +1,236 @@
...
+      return chain.append(leaver, timeout, unit, status);
+   }
+
+   /**
+    * Removes the leave chain for a cache. Called when the last member leaves and the cache status is removed.
+    *
+    * @param cacheName the cache to clean up
+    */
+   public void remove(String cacheName) {
+      chains.remove(cacheName);
```
Comment (wburns) [inline core/src/main/java/org/infinispan/topology/OrderedGracefulLeaveHandler.java:87]: Is it possible that this is invoked while an enqueue is adding a new chain and it is "lost"?

Comment (jabolina) [reply core/src/main/java/org/infinispan/topology/OrderedGracefulLeaveHandler.java:87]: Ugh, following the code, it _could_ have a race in case of a leave (with timeout) arriving with just bad enough time to be in the `cacheStatusMap`, but right about when it doesn't have any more members, so we are invoking the `remove` method concurrently. Maybe a retry could trigger this scenario?

I noticed that the `ClusterTopologyManagerImpl#handleLeave` wasn't acquiring the lock to read the status, and `ClusterTopologyManagerImpl#removeCacheStatus` was using a `synchronized` instead of the locks. So fixing those should fix a race with the enqueue/remove, too, if there was room for one.

File: core/src/main/java/org/infinispan/commands/topology/CacheLeaveCommand.java (hunk 1 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/commands/topology/CacheLeaveCommand.java]: The annotation only accepts a String. The trick doesn't look very good, but it makes it work with annotation. Let me know if we should revert it.

**Comment by jabolina** [comment]
The failures seem flaky, and the disk footprint is also failing in main.

**Comment by wburns** [comment]
All I had was nits, so I am fine with integrating as is. Great work @jabolina !
