### PR TITLE
[#14510] Properties can containt Integer values

### LINKED ISSUE #14510: Fix socket timeout property not being replaced
### Describe the bug

The code 
```
public long getDurationProperty(String key, long defaultValue, boolean doStringReplace) {
      Object value = this.get(key);
      if (value instanceof Long) {
         return (long) value;
      } else {
         return getPropertyFn(value, defaultValue, doStringReplace, valueStr -> {
            try {
               return TimeQuantity.valueOf(valueStr).longValue();
            } catch (NumberFormatException nfe) {
               log.unableToConvertStringPropertyToLong(valueStr, defaultValue);
               return defaultValue;
            }
         });
      }
   }
```

Checks for a duration to be a Long, however, the Socket Timeout is an integer, so the default value 2000 can't be updated

### Expected behavior

I can override the value with mu properties

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by karesti**
Closes #14510

### CODE REVIEW

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java [hunk 1]
```diff
@@ -562,6 +562,10 @@ public ConfigurationBuilder withProperties(Properties properties) {
       return this;
    }
 
+   private long getDurationProperty(TypedProperties typed) {
```
Comment (pruivo) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java:565]: unused

File: commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java [hunk 2]
```diff
@@ -88,14 +88,10 @@ public long getLongProperty(String key, long defaultValue, boolean doStringRepla
       }
    }
 
-   public long getDurationProperty(String key, long defaultValue) {
```
Comment (pruivo) [inline commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java:91]: Public API for users, do not remove.

File: commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java [hunk 3]
```diff
@@ -88,14 +88,10 @@ public long getLongProperty(String key, long defaultValue, boolean doStringRepla
...
-      return getDurationProperty(key, defaultValue, false);
-   }
-
    public long getDurationProperty(String key, long defaultValue, boolean doStringReplace) {
```
Comment (pruivo) [inline commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java:91]: `getIntProperty` and `getLongProperty` require the same fix.

**Review by pruivo — COMMENTED** [review]
My suggestion is to change the test 
https://github.com/infinispan/infinispan/blob/7ac61b248dd5f1220117b0f0f0f345665105552b/commons/all/src/test/java/org/infinispan/commons/util/TypedPropertiesTest.java#L15

In the create properties, you can cast the int and long values to short to test the fix
```java
p.put("int_sort", (short) 2);
p.put("long_short", (short) 3);
```
and add the new asserts. 
```java
assertEquals(2, p.getIntProperty("int_short", 999));
```
It is missing a test for `getDurationProperty`

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java [hunk 4]
```diff
@@ -305,6 +305,35 @@ public void testWithProperties() {
...
+      p.put(KEY_SIZE_ESTIMATE, 128);
+      p.put(VALUE_SIZE_ESTIMATE, 1024);
+      p.put(MAX_RETRIES, 0);
+      p.put(USE_SSL, true);
+      p.put(USE_AUTH, true);
+      p.put(NEAR_CACHE_MAX_ENTRIES, 10000);
+      p.put(STATISTICS, true);
+      p.put(JMX, true);
+      p.put(TRACING_PROPAGATION_ENABLED, false);
+      validateConfiguration(newConfiguration);
```
[the remark this answers is not in the document]
Comment (karesti) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java:335]: I was getting a failure on the test before the fix! 

Thanks for the review, I'll apply the requested changes

File: commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java (hunk 2 above)
Comment (karesti) [reply commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java:91]: we need to add a test then, since the code tells me it's not used

File: commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java (hunk 3 above)
Comment (karesti) [reply commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java:91]: are you sure about this ? The thing with those is that the notion of "duration" corresponds to Int and Long, but int value or long value are only applied in LONG and INT properties

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (pruivo) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java:335]: I changed `p.put(SO_TIMEOUT, 100);` to `p.put(SO_TIMEOUT, 1000);` and the test still passes for me. I expect the assertion `assertEqualsConfig(100, SO_TIMEOUT, configuration);` to fail.

File: commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java (hunk 3 above)
Comment (pruivo) [reply commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java:91]: In my opinion, yes. It is just a simple fix, and I wouldn't be surprised if a user puts an int/short/byte in the properties expecting it to work. 
It is up to you. I'll merge the PR either way.

File: commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java (hunk 2 above)
Comment (pruivo) [reply commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java:91]: It's not being tested in `TypedPropertiesTest`. Please do.

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java (hunk 1 above)
Comment (karesti) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java:565]: there bu mistake! thanks

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (karesti) [reply client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java:335]: I'm going to add a test somewhere else

**Comment by karesti** [comment]
@pruivo here

File: client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java [hunk 5]
```diff
@@ -300,6 +300,12 @@ public void testWithProperties() {
       Configuration configuration = builder.withProperties(p).build();
       validateConfiguration(configuration);
 
+      ConfigurationBuilder builderWithOtherTypes = HotRodClientTestingUtil.newRemoteConfigurationBuilder();
```
Comment (karesti) [inline client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java:303]: @pruivo added a small without testing all
