### PR TITLE
[#16009] Expand authorization test

### LINKED ISSUE #16009: Ensure secure cache override all methods
### Describe the bug

Expand the `CacheAuthorizationTest` to ensure it catches when the `SecureCacheImpl` is missing a method. Make the test "eager", so we need to manually intervene if we want to ignore a method in the tests.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Verify the methods in the class hierarchy.
* Ensure the secure cache overrides the methods in the hierarchy. Otherwise, manual intervention is needed to ignore a method.

Closes #16009

### CODE REVIEW

File: core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java [hunk 1]
```diff
@@ -83,6 +85,36 @@ public AdvancedCache<K, V> getDelegate() {
...
+
+   @Override
+   public boolean isRebalancingEnabled() {
+      authzManager.checkPermission(subject, AuthorizationPermission.MONITOR);
+      return super.isRebalancingEnabled();
+   }
+
+   @Override
+   public void setRebalancingEnabled(boolean enabled) {
+      authzManager.checkPermission(subject, AuthorizationPermission.LIFECYCLE);
```
Comment (tristantarrant) [inline core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java]: LIFECYCLE should only be for start/stop. This is `ADMIN`

**Review by tristantarrant — CHANGES_REQUESTED** [review]

**Comment by jabolina** [comment]
Let me check the failure. Maybe one of the methods has started to fail now.

**Comment by jabolina** [comment]
Just a fluke, it was a timeout in the DB tests. It should be good.

**Comment by tristantarrant** [comment]
Merged, thanks
