### PR TITLE
[#17280] Test TRACE doesn't work properly and doesn't have thread nam…

### LINKED ISSUE #17280: Test TRACE doesn't work properly and doesn't have thread names and goes into the wrong log file
### Describe the bug

Currently we track a test by the name when deciding where the log goes. Messages that don't have the name set properly go into the infinispan-infinispan-<module>.log file. This causes much confusion as you don't know what test the message goes to and it has no thread name so multi node tests are really hard to debug.

We should wrap the thread factory so that tasks submitted get tied to the proper test. We also may need to disable virtual threads to get this to work properly, but this can be done by the user.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by wburns**
…es and goes into the wrong log file

Closes: #17280

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [ ] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.
- [ ] Log messages of level `INFO` and above have been internationalized.
- [ ] If the PR affects performance, include before/after benchmarks.
- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).
- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

**Comment by wburns** [comment]
With this change and running with virtual threads disabled I can now properly track log messages even when running in the blocking or non blocking pool. 🎉

**Comment by wburns** [comment]
Failures are related.. fixing

**Comment by wburns** [comment]
Tests should be fixed now.. interestingly this exposed an issue in an unrelated test that I fixed as well.

File: core/src/main/java/org/infinispan/executors/ManageableExecutorService.java [hunk 1]
```diff
@@ -28,8 +28,9 @@ public abstract class ManageableExecutorService<T extends ExecutorService> {
          dataType = DataType.TRAIT
    )
    public int getPoolSize() {
-      if (executor instanceof ThreadPoolExecutor) {
-         return ((ThreadPoolExecutor) executor).getPoolSize();
+      T unwrapped = unwrapExecutor(executor);
+      if (unwrapped instanceof ThreadPoolExecutor) {
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/executors/ManageableExecutorService.java]: Nit: I guess the calls here can do `unwrapped instanceof ThreadPoolExecutor tpe`

**Review by jabolina — APPROVED** [review]
