### PR TITLE
[#15212] Fix flaky AsyncOfflineTest

### LINKED ISSUE #13560: Flaky test: org.infinispan.xsite.offline.AsyncOfflineTest#testSFOOffline
### Github Job:https://github.com/infinispan/infinispan/actions/runs/120896640
java.lang.AssertionError: Site SFO-3 is offline. status=OfflineStatus{takeOffline=[after-failures=6, min-wait=0ms], recordingOfflineStatus=false, firstFailureTime=-1, isOffline=true, failureCount=0}
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:254)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:233)
	at org.infinispan.xsite.offline.AsyncOfflineTest.assertEventuallySFOOnline(AsyncOfflineTest.java:203)
	at org.infinispan.xsite.offline.AsyncOfflineTest.doTestInNode(AsyncOfflineTest.java:163)
	at org.infinispan.xsite.offline.AsyncOfflineTest.testSFOOffline(AsyncOfflineTest.java:64)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #15212: Flaky test: org.infinispan.xsite.offline.AsyncOfflineTest#testSlowSFO
### Github Job:https://github.com/infinispan/infinispan/actions/runs/16072275799
java.lang.AssertionError: expected:&amp;lt;value&amp;gt;, got:&amp;lt;null&amp;gt;
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:253)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:232)
	at org.infinispan.test.AbstractInfinispanTest.eventuallyEquals(AbstractInfinispanTest.java:222)
	at org.infinispan.xsite.offline.AsyncOfflineTest.testSlowSFO(AsyncOfflineTest.java:84)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### LINKED ISSUE #15805: Flaky test: org.infinispan.xsite.offline.AsyncOfflineTest#testReset
### Github Job:https://github.com/infinispan/infinispan/actions/runs/18270012609
java.lang.AssertionError: Condition is still false after 10000 MILLISECONDS
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:253)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:265)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:402)
	at org.infinispan.xsite.offline.AsyncOfflineTest.testReset(AsyncOfflineTest.java:132)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### LINKED ISSUE #16958: Flaky test: org.infinispan.xsite.offline.AsyncOfflineTest#testSlowSFO
### Github Job:https://github.com/infinispan/infinispan/actions/runs/22858870482
java.lang.AssertionError: Site SFO-3 is online. status=OfflineStatus{takeOffline=[after-failures=6, min-wait=0ms], recordingOfflineStatus=false, firstFailureTime=-1, isOffline=false, failureCount=0}
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:253)
	at org.infinispan.test.AbstractInfinispanTest.eventually(AbstractInfinispanTest.java:232)
	at org.infinispan.xsite.offline.AsyncOfflineTest.assertEventuallyOffline(AsyncOfflineTest.java:205)
	at org.infinispan.xsite.offline.AsyncOfflineTest.doTestInNode(AsyncOfflineTest.java:187)
	at org.infinispan.xsite.offline.AsyncOfflineTest.testSlowSFO(AsyncOfflineTest.java:96)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.testing.testng.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### PR DESCRIPTION
**Pull request by jabolina**
* Do not rely on the time-based timeout to kick in. Instead, complete with an exception to simulate the failure if discard is enabled.

Closes #15212 
Closes #15805
Closes #13560
Closes #16958

### CODE REVIEW

File: core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java [hunk 1]
```diff
@@ -293,6 +308,7 @@ public void handleFromCluster(Address origin, ReplicableCommand command, Reply r
       @Override
       public void handleFromRemoteSite(String origin, XSiteRequest<?> command, Reply reply, DeliverOrder order) {
          if (discard) {
+            reply.reply(CacheNotFoundResponse.INSTANCE);
```
Comment (wburns) [inline core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java:311]: Doesn't this change the behavior? Before it was getting no response, but now it is getting an exception. Is this okay?

Comment (pruivo) [reply core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java:311]: If I recall correctly, the `CacheNotFoundResponse` triggers a `SuspectException` in the sender. 
Although it changes the test semantics slightly, it should be fine :crossed_fingers:, as this method still returns the correct value
https://github.com/infinispan/infinispan/blob/7d0836cda36743e73f74bdb4b1f6e35bdee402c3/core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java#L78-L89

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !
