### PR TITLE
[#14272] JavaDoc linting

### LINKED ISSUE #14272: Fix errors reported by javadoc -Xdoclint
### Describe the bug

Our javadocs are rife with errors, reported by `javadoc -Xdoclint`:
* broken HTML tags
* nested links
* broken references
* lots more

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #14272

### CODE REVIEW

File: commons/all/src/main/java/org/infinispan/commons/api/BasicCache.java [hunk 1]
```diff
@@ -12,25 +12,20 @@
...
+  * Also, like many {@link ConcurrentMap} implementations, BasicCache does not support the use of <code>null</code> keys or
  * values.
- * <p/>
- * <h3>Unsupported operations</h3>
+  * <h2>Unsupported operations</h2>
  * <p>{@link #containsValue(Object)}</p>
  *
  * Please see the <a href="http://www.jboss.org/infinispan/docs">Infinispan documentation</a> and/or the <a
  * href="https://docs.jboss.org/author/display/ISPN/Getting+Started+Guide#GettingStartedGuide-5minutetutorial">5 Minute Usage Tutorial</a> for more details.
- * <p/>
```
Comment (wburns) [inline commons/all/src/main/java/org/infinispan/commons/api/BasicCache.java:32]: The url above doesn't resolve anymore btw, if we want to remove it.

File: commons/all/src/main/java/org/infinispan/commons/util/ImmutableListCopy.java [hunk 2]
```diff
@@ -22,12 +22,9 @@
 /**
  * A lightweight, read-only copy of a List.  Typically used in place of the common idiom: <code> return
  * Collections.unmodifiableList(new ArrayList( myInternalList )); </code>
- * <p/>
- * a it is far more efficient than making a defensive copy and then wrapping the defensive copy in a read-only wrapper.
- * <p/>
- * Also used whenever a read-only reference List is needed.
- * <p/>
- *
+  * a it is far more efficient than making a defensive copy and then wrapping the defensive copy in a read-only wrapper.
```
Comment (wburns) [inline commons/all/src/main/java/org/infinispan/commons/util/ImmutableListCopy.java:25]: Looks like we want to reword this line as well. Maybe just 
```suggestion
  * It is more efficient than making a defensive copy and then wrapping the defensive copy in a read-only wrapper.
```

File: commons/all/src/main/java/org/infinispan/commons/util/IntSet.java [hunk 3]
```diff
@@ -127,17 +126,13 @@ default void forEach(IntConsumer action) {
     * <p>The {@code Spliterator.OfInt} reports {@link Spliterator#DISTINCT}.
     * Implementations should document the reporting of additional
     * characteristic values.
-    *
-    * @implSpec
```
Comment (wburns) [inline commons/all/src/main/java/org/infinispan/commons/util/IntSet.java:131]: Any reason we are removing these? Should the previous line just be moved up? It is standard for implSpec to talk about the default implementation.

Comment (tristantarrant) [reply commons/all/src/main/java/org/infinispan/commons/util/IntSet.java:131]: implSpect, apiNote and implNote are not quite standard: they are not processed automatically by JavaDoc and would require custom tag configs

File: commons/all/src/main/java/org/infinispan/commons/util/ImmutableListCopy.java (hunk 2 above)
Comment (tristantarrant) [reply commons/all/src/main/java/org/infinispan/commons/util/ImmutableListCopy.java]: Don

File: commons/all/src/main/java/org/infinispan/commons/api/BasicCache.java (hunk 1 above)
Comment (tristantarrant) [reply commons/all/src/main/java/org/infinispan/commons/api/BasicCache.java:32]: Removed

**Comment by wburns** [comment]
Integrated into main, thanks @tristantarrant !
