### PR TITLE
[#16954] Add MemoryMonitor with GC duration and pressure tracking

### LINKED ISSUE #16954: Add MemoryMonitor with GC duration and pressure tracking
## Summary

Add a `MemoryMonitor` component that tracks JVM memory and GC health, providing alerts when configurable thresholds are exceeded. The monitor is registered per-CacheManager in the global component registry and can be injected into other components.

## Monitoring capabilities

- **Memory threshold**: Alerts when old generation heap usage exceeds a configurable percentage (default 85%). Auto-clears after GC when usage drops back below the threshold.
- **GC duration threshold**: Alerts when a single GC pause exceeds a configurable duration (default 5 seconds)
- **GC pressure tracking**: Alerts when the ratio of time spent in GC over a rolling window exceeds a configurable percentage (default 20% over 60 seconds). Auto-clears when pressure drops.

## Configuration

All thresholds are mutable at runtime via the `MemoryMonitor` API and exposed as a new `<memory-monitor>` element in the cache container configuration:

```xml
<cache-container>
  <memory-monitor memory-threshold="0.85"
                  gc-duration-threshold="5000"
                  gc-pressure-threshold="0.20"
                  gc-pressure-window="60000" />
</cache-container>
```

## Programmatic configuration

```java
GlobalConfigurationBuilder builder = new GlobalConfigurationBuilder();
builder.memoryMonitor()
       .memoryThreshold(0.90)
       .gcDurationThreshold(3000)
       .gcPressureThreshold(0.15)
       .gcPressureWindow(30000);
```

## Query integration

Sorted non-indexed queries (which load all results into a `PriorityQueue` in memory) are rejected with a `CacheException` when the system is under memory pressure (low memory or GC pressure exceeded).

## Logging

All alerts use JBoss Logging messages:
- ISPN000977: Low memory detected
- ISPN000978: GC pause duration exceeded threshold
- ISPN000979: GC pressure exceeded threshold
- ISPN014069: Query rejected due to memory pressure

## Components

- `MemoryMonitor` (commons/all) — instance-based monitor with JMX notification listeners, auto-recovery of low memory alert, proper cleanup on stop
- `GlobalMemoryMonitorConfiguration` / `GlobalMemoryMonitorConfigurationBuilder` (core) — configuration with mutable attributes
- `BaseEmbeddedQuery` (query) — memory pressure check before sorted non-indexed queries
- Registered in `GlobalComponentRegistry` for injection into other components
- XSD schema updated with documented attributes
- Validation errors use JBoss Logging messages (IDs 975, 976)

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #16954

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [x] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.
- [x] Log messages of level `INFO` and above have been internationalized.
~~- [ ] If the PR affects performance, include before/after benchmarks.~~
~~- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).~~
~~- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.~~

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

File: core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+   }
+
+   @Override
+   public AttributeSet attributes() {
+      return attributes;
+   }
+
+   /**
+    * Sets the fraction of old generation heap usage that triggers a low memory alert.
+    * Must be between 0 (exclusive) and 1.0 (inclusive). Default is 0.85.
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java:46]: Seems to be the inverse. 0 inclusive and 1 exclusive.

File: core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+    * @param gcDurationThreshold the GC duration threshold in milliseconds
+    */
+   public GlobalMemoryMonitorConfigurationBuilder gcDurationThreshold(long gcDurationThreshold) {
+      attributes.attribute(GC_DURATION_THRESHOLD).set(gcDurationThreshold);
+      return this;
+   }
+
+   /**
+    * Sets the fraction of time spent in GC over the pressure window that triggers a GC pressure alert.
+    * Must be between 0 (exclusive) and 1.0 (inclusive). Default is 0.20.
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java:68]: Same.

File: core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java (hunk 1 above)
Comment (tristantarrant) [reply core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java:46]: It is correct. The code throws an exception when:
```java
if (percentage <= 0 || percentage > 1.0)
```

File: core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java (hunk 2 above)
Comment (tristantarrant) [reply core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfigurationBuilder.java:68]: It is correct. The code throws an exception when:
```java
if (percentage <= 0 || percentage > 1.0)
```

**Comment by tristantarrant** [comment]
@jabolina I've made some changes:
* added docs referencing the different kinds of GCs and tested that this works with Generational ZGC and Shenandoah
* added some javadocs
* added an `enabled` attribute to make it easy to enable/disable the feature declaratively
* cache the memory mbean instead of looking it up every time and also make the search a bit more robust to catch the right one
* removed gcDurationAlert flag: resetting it is a bit tricky in order to get a reliable value. We still log about it when it happens, though. The other two flags are enough for our needs

File: core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfiguration.java [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+import org.infinispan.commons.configuration.attributes.AttributeSet;
+import org.infinispan.commons.configuration.attributes.ConfigurationElement;
+import org.infinispan.configuration.parsing.Element;
+
+/**
+ * Configuration for the memory monitor. All attributes are mutable at runtime.
+ *
+ * @since 16.2
+ */
+public class GlobalMemoryMonitorConfiguration extends ConfigurationElement<GlobalMemoryMonitorConfiguration> {
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfiguration.java:13]: Should we make them mutable + non-global?

Comment (tristantarrant) [reply core/src/main/java/org/infinispan/configuration/global/GlobalMemoryMonitorConfiguration.java:13]: Done

**Comment by jabolina** [comment]
Thanks, @tristantarrant!
