### PR TITLE
[#17347] ClusterPublisherManager can cause a timeout in persistence w…

### LINKED ISSUE #17347: ClusterPublisherManager can cause a timeout in persistence when requesting from multiple nodes
### Describe the bug

While testing with https://github.com/infinispan/infinispan/issues/17321 I found a case where data is not transferred because publisher ends too early.

The cause is due to a timeout with persistence where an entry is not requested within 15 seconds

```
14:25:27,564 TRACE (timeout-thread-StateTransferWithSIFSAndEvictionTest-NodeC-p16-t1:[]) [o.i.r.p.i.PublisherHandler] Exception encountered while processing publisher
org.infinispan.commons.TimeoutException: Store publisher didn't publish a value in 15000 ms. Stack trace of the original caller is:
    at org.infinispan.persistence.manager.PersistenceManagerImpl.lambda$publishEntries$2(PersistenceManagerImpl.java:806)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:57)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16095)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatArray$ConcatArraySubscriber.onComplete(FlowableConcatArray.java:141)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatArray.subscribeActual(FlowableConcatArray.java:41)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatWithSingle.subscribeActual(FlowableConcatWithSingle.java:44)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16095)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:318)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onSubscribe(FlowableConcatMap.java:124)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16095)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap.subscribeActual(FlowableConcatMap.java:66)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
    at org.infinispan.reactive.publisher.impl.PublisherHandler$PublisherState.startProcessing(PublisherHandler.java:294)
    at org.infinispan.reactive.publisher.impl.PublisherHandler.register(PublisherHandler.java:130)
    at org.infinispan.reactive.publisher.impl.commands.batch.InitialPublisherCommand.invokeAsync(InitialPublisherCommand.java:178)
    at org.infinispan.remoting.inboundhandler.BasePerCacheInboundInvocationHandler.invokeCommand(BasePerCacheInboundInvocationHandler.java:105)
    at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.invoke(BaseBlockingRunnable.java:111)
    at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.runAsync(BaseBlockingRunnable.java:79)
    at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.run(BaseBlockingRunnable.java:48)
    at org.infinispan.remoting.inboundhandler.TrianglePerCacheInboundInvocationHandler.handleStateRequestCommand(TrianglePerCacheInboundInvocationHandler.java:83)
    at org.infinispan.remoting.inboundhandler.TrianglePerCacheInboundInvocationHandler.handle(TrianglePerCacheInboundInvocationHandler.java:62)
    at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleCacheRpcCommand(GlobalInboundInvocationHandler.java:121)
    at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:74)
    at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1544)
    at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1468)
    at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1641)
    at org.jgroups.JChannel.up(JChannel.java:678)
    at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:944)
    at org.jgroups.protocols.FRAG2.up(FRAG2.java:136)
    at org.jgroups.protocols.FlowControl.up(FlowControl.java:252)
    at org.jgroups.protocols.FlowControl.up(FlowControl.java:260)
    at org.jgroups.protocols.pbcast.GMS.up(GMS.java:796)
    at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:234)
    at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1172)
    at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:898)
    at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:880)
    at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:490)
    at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:644)
    at org.jgroups.protocols.Discovery.up(Discovery.java:304)
    at org.jgroups.stack.Protocol.up(Protocol.java:365)
    at org.jgroups.protocols.TP.passMessageUp(TP.java:425)
    at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:101)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090
```
This then causes the publisher to terminate early and ST completes without an exception.

First thing is we should ensure this exception is propagated to ST so that we can properly expose it instead of ending without raising the exception. This is caused by the Publisher future handling not expecting an exception except during entry processing. In this case the timeout occurs after a full batch is completed and thus isn't raised properly.

Secondly we need to find out how there is a case where a batch is not requested. It should be that we are always requesting batches. I have two ideas of what it could be:

1. The backpressure request amount could have an exact number that when hit may delay the request until another node completes.
2. The processing of another node had no interruptions. This is a sign where retrieving the batch size is faster than processing causing all entries to be received possibly from the same node until it delivers its entire segment.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by wburns**
…hen requesting from multiple nodes

* Change so timeut only happens when request is not satisfied

Closes: #17347

Author Checklist (all must be checked):
- [ ] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [ ] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [ ] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [ ] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.
- [ ] Log messages of level `INFO` and above have been internationalized.
- [ ] If the PR affects performance, include before/after benchmarks.
- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).
- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

File: core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java [hunk 1]
```diff
@@ -0,0 +1,229 @@
...
+               log.tracef("TimeoutAfterRequest[%08x] request(%d), outstanding demand: %d, arming timer",
+                     System.identityHashCode(this), n, total + n);
+            }
+            upstream.get().request(n);
+            scheduleTimeout();
+         }
+      }
+
+      @Override
+      public void cancel() {
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java:108]: Should it set `terminated` to true?

File: core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java [hunk 2]
```diff
@@ -0,0 +1,229 @@
...
+            worker.dispose();
+            downstream.onComplete();
+         }
+      }
+
+      void scheduleTimeout() {
+         long idx = incrementAndGet();
+         if (idx == TERMINATED_INDEX) {
+            return;
+         }
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java]: `getAndIncrement()`? This if doesn't seem to evaluate to true.

File: core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java [hunk 3]
```diff
@@ -0,0 +1,229 @@
...
+            log.tracef("TimeoutAfterRequest[%08x] timed out after %d %s with %d outstanding demand",
+                  System.identityHashCode(this), timeout, unit, requested.get());
+         }
+         SubscriptionHelper.cancel(upstream);
+         worker.dispose();
+
+         if (onTimeout != null) {
+            onTimeout.subscribe(new OnTimeoutSubscriber<>(downstream));
+         } else {
+            downstream.onError(new java.util.concurrent.TimeoutException());
```
Comment (jabolina) [inline core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java]: nit: can we have after how long?

**Review by jabolina — COMMENTED** [review]
Just a couple of questions

File: core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java (hunk 1 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java:108]: Sure, actually we can just reuse the index and set it to TERMINATED_INDEX and remove the terminated value.

File: core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java (hunk 2 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java]: Yeah, it would only evaluate on an overflow. Actually, let me redo this part, not a fan of what Claude did looking at it a second time :)

File: core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java (hunk 3 above)
Comment (wburns) [reply core/src/main/java/org/infinispan/reactive/FlowableTimeoutAfterRequest.java]: Sure, I can reuse the message from the trace above.

**Comment by wburns** [comment]
Updated per comments

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @wburns!
