### PR TITLE
[#15192] Fix non-tx issue with Invalidation

### LINKED ISSUE #15192: Invalidation mode anomalies for non transactional caches
### Describe the bug

Cache configuration:
* Invalidation mode
* Shared persistence (DB or similar)
* Non-transactional

With the configuration above, invalidation mode miss behaves incorrectly when interacting with the persistence layer. The following problems are identified:
 * It does not read from the persistence layer if the node is not the "primary owner". In invalidation mode, the primary owner definition is irrelevant, as the nodes store data locally and send invalidation messages.
 *  * Removals are not persisted. When a remove operation is invoked on a node that is not the "primary owner," the operation is skipped and the data is not removed. 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pruivo**
Fixes #15192

### CODE REVIEW

File: core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+/**
+ * Extends the {@link CacheWriterInterceptor} to add logic for {@link CacheType#INVALIDATION}.
+ * <p>
+ * With invalidation, the {@link RemoveCommand} should always try to remove from persistence, even if the originator
+ * does not have the data in memory. The removing non-existing value logic has an optimization that skips the
+ * persistence removal; it is disabled in this interceptor.
+ *
+ * @since 16.0
+ */
+public class InvalidationCacheWriterInterceptor extends CacheWriterInterceptor {
```
Comment (wburns) [inline core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java:16]: Just food for thought: Is this an issue if someone has invalidation cache with passivation..? Although, I think that _shouldn't_ be possible as passivation is not supported with shared stores and INVALIDATION cache really needs a shared store.

Comment (wburns) [reply core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java:16]: Although invalidation requires a shared store it doesn't make as much sense to be configured as such I guess. I think that we may want to have a validation check to prevent passivation with INVALIDATION caches.

Comment (pruivo) [reply core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java:16]: As you mentioned, shared + passivation is not possible and it will throw an exception.

`invalidation` + `non-shared-store` may be (is!) broken. The `CacheWriterInterceptor` and subclasses ignore the `InvalidateCommand`, so it will never remove anything from the disk.

File: core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java [hunk 2]
```diff
@@ -0,0 +1,806 @@
...
+            .segmented(true)
+            .storeName(storeName);
+      return builder;
+   }
+
+   @DataProvider(name = "caches")
+   public static Object[][] cacheNames() {
+      return new Object[][]{
+            {NON_TX_CACHE_NAME},
+            // TODO will be fixed by https://github.com/infinispan/infinispan/issues/15193
```
Comment (wburns) [inline core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java:73]: Seems we should be able to enable these now?

Comment (pruivo) [reply core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java:73]: It's another issue affecting transactional caches: https://github.com/infinispan/infinispan/issues/15193
I'll open a PR for it after this one is merged (since this one is quite large already).

**Comment by wburns** [comment]
Integrated into main, thanks @pruivo !
