### PR TITLE
[#17355] Fix CMS.MERGE weight ordering in clustered mode

### LINKED ISSUE #17355: CMS.MERGE produces wrong results with weights in clustered mode
CMS.MERGE uses `CompletionStages.performConcurrently()` to fetch source sketches, which does not preserve input order. Since weights are positional, sketches can be paired with wrong weights in clustered mode, producing incorrect merge results.

Affects `CountMinSketchClusteredTest`: `testCmsMergeWithWeights` and `testCmsMergeNegativeWeights` fail intermittently.

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes: #17355

`CMS.MERGE` used `CompletionStages.performConcurrently()` to fetch source sketches, which internally uses `Flowable.parallel()` and does not preserve input order. Since weights are positional (weight[i] corresponds to sourceKey[i]), sketches returned out of order get paired with wrong weights, producing incorrect merge results.

Replaced with sequential `thenCompose` chaining to guarantee correct weight-to-sketch ordering. The number of source keys is typically small (2-3), so sequential fetching has negligible performance impact.

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
  - No new tests needed: existing `CountMinSketchClusteredTest.testCmsMergeWithWeights` and `testCmsMergeNegativeWeights` cover this fix and were previously failing.
- [x] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.
  - Bug fix only, no documentation changes needed.
- [x] Log messages of level `INFO` and above have been internationalized.
- [x] If the PR affects performance, include before/after benchmarks.
- [x] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).
- [x] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.

Created with the assistance of an AI tool

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/countmin/CMSMERGE.java [hunk 1]
```diff
@@ -88,22 +83,21 @@ public CompletionStage<RespRequestHandler> perform(Resp3Handler handler, Channel
...
+      for (byte[] srcKey : sourceKeys) {
+         fetches = fetches.thenCompose(v -> cache.getAsync(srcKey)
+               .thenAccept(obj -> {
+                  if (obj == null) {
+                     throw CompletableFutures.asCompletionException(
+                           new IllegalStateException(ProbabilisticErrors.CMS_KEY_NOT_FOUND));
+                  }
+                  sources.add((CountMinSketch) obj);
+               }));
+      }
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/countmin/CMSMERGE.java]: I guess the `List<CountMinSketch> sources` needs to be synchronized? On the other hand, we also have sequential:


```suggestion
      CompletionStage<List<CountMinSketch>> sketches = CompletionStages.performSequentially(
            sourceKeys.iterator(),
            srcKey -> cache.getAsync(srcKey)
                  .thenApply(obj -> {
                     if (obj == null) {
                        throw new IllegalStateException(ProbabilisticErrors.CMS_KEY_NOT_FOUND);
                     }
                     return (CountMinSketch) obj;
                  }), Collectors.toList());
```

Comment (tristantarrant) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/countmin/CMSMERGE.java]: I've included your suggestion

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @tristantarrant!
