### PR TITLE
[#16778] Fix RESP command arity, key specs, and ACL categories to mat…

### LINKED ISSUE #16778: Some RESP commands have wrong arity and ACL
### Describe the bug

* BITCOUNT
* BITFIELD
* BITOP 
* BITPOS 
* GETBIT 
* SETBIT
* QUIT
* SELECT
* ZRANGE
* ZRANGESTORE
* ZREVRANGE

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #16778

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITCOUNT.java [hunk 1]
```diff
@@ -21,7 +21,7 @@
  */
 public class BITCOUNT extends RespCommand implements Resp3Command {
    public BITCOUNT() {
-      super(-2, 1, 1, 1, AclCategory.READ.mask() | AclCategory.STRING.mask() | AclCategory.FAST.mask());
+      super(-2, 1, 1, 1, AclCategory.READ.mask() | AclCategory.BITMAP.mask() | AclCategory.FAST.mask());
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITCOUNT.java]: FAST -> SLOW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITPOS.java [hunk 2]
```diff
@@ -20,7 +20,7 @@
  */
 public class BITPOS extends RespCommand implements Resp3Command {
    public BITPOS() {
-      super(-3, 1, 1, 1, AclCategory.READ.mask() | AclCategory.STRING.mask() | AclCategory.FAST.mask());
+      super(-3, 1, 1, 1, AclCategory.READ.mask() | AclCategory.BITMAP.mask() | AclCategory.FAST.mask());
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITPOS.java]: FAST -> SLOW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITCOUNT.java (hunk 1 above)
Comment (tristantarrant) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITCOUNT.java]: Fixed

File: server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITPOS.java (hunk 2 above)
Comment (tristantarrant) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITPOS.java]: Fixed

**Comment by jabolina** [comment]
Thanks, @tristantarrant!
