### PR TITLE
[#14556] Skip IPv6 in HotRodMultiHomedAddressTest

### LINKED ISSUE #14556: Workaround issues with network interfaces on Github Actions
### Describe the bug

GitHub actions don't currently support IPv6 interfaces, so we should skip `HotRodMultiHomedAddressTest`
Additionally, the order of interfaces returned in `HotRodSingleClusteredNonLoopbackTest` is causing failures, so we should skip non-functional ones until we find one that works.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #14556

### CODE REVIEW

File: server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiHomedAddressTest.java [hunk 1]
```diff
@@ -29,19 +28,19 @@
 public class HotRodMultiHomedAddressTest extends HotRodMultiNodeTest {
 
    public void testInAddrAny() throws IOException {
-      // GitHub actions don't support IPv6 https://github.com/actions/runner-images/issues/668
-      SkipTestNG.skipProperty("github.action");
```
Comment (wburns) [inline server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiHomedAddressTest.java:33]: Is the change required because we are removing the property now?

Comment (tristantarrant) [reply server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiHomedAddressTest.java:33]: I'll leave the property in the action in case we need it elsewhere.
I made this change because this test is also failing downstream.

**Review by wburns — APPROVED** [review]

**Comment by wburns** [comment]
Integrated into main, thanks @tristantarrant !
