### PR TITLE
[#16462] Transactional store interceptor handle remote tx

### LINKED ISSUE #16462: JDBC-Store does not write to database in cluster mode
### Describe the bug

We are using a shared transactional cache with an underlying JDBC store. The cache is configured as REPL_SYNC.

When executing cache.put() operations, the entry is added to the cache, but in some cases it is not written to the database. In approximately 50% of the test cases, the value is not persisted successfully.

The setup works correctly when running with a single node (no clustering). However, when using two nodes, the problem occurs.

I have created a test project to reproduce the issue. The project is configured to use Infinispan 14.0.35, which is the version we currently use. The same issue also occurs with newer versions, including Infinispan 15.

Test-Project: https://github.com/thaefner/infinispan-jdbc-store-bug

Please refer to the README.md for instructions on how to set up the database and IP addresses.

We have debugged Infinispan but have not been able to identify where the problem occurs. It may be related to the following code section:
https://github.com/infinispan/infinispan/blob/20cae302e073b6108dd016b9155abe2dbd0610d3/persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/sql/BaseTableOperations.java#L166

We use the JDBC cache store as our primary persistence mechanism. Therefore, this issue is a major showstopper for us, as it leads to data loss in production.

At the moment, the only workaround available to us is to run the system in a single-node cluster, which is not a viable solution for all of our customers.

### Expected behavior

cache.put() should always persist into the database.

### Actual behavior

When executing cache.put() operations, the entry is added to the cache, but in some cases it is not written to the database. In approximately 50% of the test cases, the value is not persisted successfully.

### How to Reproduce?

Test-Project: https://github.com/thaefner/infinispan-jdbc-store-bug

### PR DESCRIPTION
**Pull request by jabolina**
* TransactionStoreInterceptor should handle redirected transactions to prepare/commit/rollback on each node, not only the initiator.
* Otherwise, primary owners who receive the redirected tx will not include the operations in the underlying storage.

Close #16462.

### CODE REVIEW

**Comment by pruivo** [comment]
@jabolina this does not seem the right way to do it. Custom stores may rely on the `Transaction`  to be from the `TransactionManager`, so they can enlist the changes. 
IMO, it is better to change `org.infinispan.persistence.manager.PersistenceManagerImpl#batchOperation()` to avoid any ownership filtering, when invoked from prepare/commit/rollback.

**Comment by jabolina** [comment]
Sounds good, yeah. I'll add a comment in the transactional store interceptor as well. Updating real quick.

**Comment by jabolina** [comment]
Updated. The persistence manager avoids filtering if it is executing in a TX context. There is still a change needed in the transactional store interceptor.

File: core/src/main/java/org/infinispan/interceptors/impl/TransactionalStoreInterceptor.java [hunk 1]
```diff
@@ -26,12 +27,14 @@ public class TransactionalStoreInterceptor extends DDAsyncInterceptor {
...
    @Override
    public Object visitPrepareCommand(TxInvocationContext ctx, PrepareCommand command) {
+      // The operation is only applied in the transaction originator.
+      // The transactional stores need to enlist and that can only happen in the node the TX originates.
       if (ctx.isOriginLocal()) {
          if (!command.isOnePhaseCommit()) {
             return asyncInvokeNext(ctx, command, persistenceManager.prepareAllTxStores(ctx, BOTH));
          } else {
             return invokeNextThenApply(ctx, command, (rCtx, rCommand, rv) -> {
-               if (command.isSuccessful())
```
Comment (wburns) [inline core/src/main/java/org/infinispan/interceptors/impl/TransactionalStoreInterceptor.java:34]: Seems this was pretty broken before for single phase commit :(

**Review by wburns — APPROVED** [review]
LGTM, @pruivo want to do one more check over?

**Comment by pruivo** [comment]
@wburns @jabolina give me some time, I need to try it out myself after the morning meetings. I suspect the combination of transactional cache + non-transaction shared store, it writes the same key `n` times to the shared store with this change (where `n` is the cluster size).

**Comment by pruivo** [comment]
Adding the following test to your class confirms my concerns. It fails with `java.lang.AssertionError: expected:<1> but was:<2>`.
```java
   public void testWriteCount() {
      SkipTestNG.skipIf(!useAutoCommit, "requires auto-commit to be true");
      var builder = buildConfiguration();
      builder.persistence().clearStores();
      builder.persistence().addStore(DummyInMemoryStoreConfigurationBuilder.class)
            .storeName("test-write-count")
            .shared(true);
      manager(0).defineConfiguration("write-count", builder.build());
      manager(1).defineConfiguration("write-count", builder.build());
      TestingUtil.waitForNoRebalance(caches("write-count"));

      DummyInMemoryStore store = TestingUtil.getFirstStore(cache(0, "write-count"));

      cache(0, "write-count").put(new MagicKey("key", cache(1, "write-count")), "value");

      assertEquals(1, (int) store.stats().get("write"));
   }
```

File: core/src/main/java/org/infinispan/interceptors/impl/TransactionalStoreInterceptor.java (hunk 1 above)
Comment (jabolina) [reply core/src/main/java/org/infinispan/interceptors/impl/TransactionalStoreInterceptor.java:34]: Yeah :(

**Comment by jabolina** [comment]
Thanks, @pruivo. I'll add the test and think a bit more.

**Comment by pruivo** [comment]
@jabolina I would keep things simpler and add a `boolean skipOwnership` to `batchOperation`. `prepareAllTxStores` will set this to `true` while others invocation will keep this at `false`. 
The `performBatch` also needs it too, and only `TransactionalStoreInterceptor` would set it to `true`.

**Comment by wburns** [comment]
Integrated, thanks @jabolina !
