### PR TITLE
[#16228] Avoid pinning carrier during start

### LINKED ISSUE #16228: Server unable to cluster with constrained CPU
### Describe the bug

Utilizing taskset to constrain the server causes different failures. A single server seems to start fine. A second node joins, and the state transfer is not triggered. A third node joins and the coordinator says the other nodes have left the cluster.

```
2025-11-21 14:43:13,454 INFO  [o.i.CLUSTER] ISPN000094: Received new cluster view for channel cluster: [node-0(v=16.0.2)|1] (2) [node-0(v=16.0.2), node-1(v=16.0.2)]
2025-11-21 14:43:13,458 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100000: Node node-1 joined the cluster
2025-11-21 14:43:13,470 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100000: Node node-1 joined the cluster
2025-11-21 14:43:32,362 INFO  [o.i.CLUSTER] ISPN000094: Received new cluster view for channel cluster: [node-0(v=16.0.2)|2] (3) [node-0(v=16.0.2), node-1(v=16.0.2), node-2(v=16.0.2)]
2025-11-21 14:43:32,363 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100000: Node node-2 joined the cluster
2025-11-21 14:43:32,366 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100000: Node node-2 joined the cluster
2025-11-21 14:43:33,411 INFO  [o.i.CLUSTER] ISPN000094: Received new cluster view for channel cluster: [node-0(v=16.0.2)|3] (2) [node-0(v=16.0.2), node-2(v=16.0.2)]
2025-11-21 14:43:33,412 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100001: Node node-1 left the cluster
2025-11-21 14:43:33,417 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100001: Node node-1 left the cluster
2025-11-21 14:43:36,420 INFO  [o.i.CLUSTER] ISPN000094: Received new cluster view for channel cluster: [node-0(v=16.0.2)|4] (1) [node-0(v=16.0.2)]
2025-11-21 14:43:36,421 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100001: Node node-2 left the cluster
2025-11-21 14:43:36,424 INFO  [o.i.CLUSTER] [Scope=node-0]ISPN100001: Node node-2 left the cluster
```

I had all 3 nodes running at this point. On the third node, I had the following log:

```
2025-11-21 14:53:37,121 INFO  [o.i.CLUSTER] ISPN000078: Starting JGroups channel `cluster` with stack `tcp`
2025-11-21 14:53:37,122 INFO  [o.j.JChannel] local_addr: node-2(v=16.0.2), name: node-2
2025-11-21 14:53:37,148 INFO  [o.j.p.FD_SOCK2] server listening on *:58000
2025-11-21 14:53:37,209 WARN  [o.j.p.TCP] JGRP000032: node-2(v=16.0.2): no physical address for 88c59ee7-dc2b-4369-bdc4-df08f16d8cc3(v=16.0.2), dropping message
2025-11-21 14:53:37,212 INFO  [o.i.CLUSTER] ISPN000094: Received new cluster view for channel cluster: [node-0(v=16.0.2)|2] (3) [node-0(v=16.0.2), 88c59ee7-dc2b-4369-bdc4-df08f16d8cc3(v=16.0.2), node-2(v=16.0.2)]
2025-11-21 14:53:37,269 INFO  [o.i.CLUSTER] ISPN000079: Channel `cluster` local address is `node-2`, physical addresses are `[192.168.100.106:7900]`
```

This behavior happens consistently when starting with `taskset`. This also causes the server to hang during shutdown. If I stop the 2nd or 3rd nodes, they will hang and need to receive SIGKILL.

The workaround seems to be disabling virtual threads (`-Dorg.infinispan.threads.virtual=false`). Likely something is pinning the carrier, and we deadlock. 

### Expected behavior

The server should work correctly in CPU-constrained scenarios.

### Actual behavior

The server is unable to cluster and operate.

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Carrier pinning during the start of the server.
* Component registry uses a reentrant lock.

Closes #16228.

### CODE REVIEW

**Comment by jabolina** [comment]
Ouch, it seems like something is not happy. Taking a closer look.

File: server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java [hunk 1]
```diff
@@ -99,7 +96,7 @@ private void registerGlobalTxTable() {
             EnumSet.noneOf(InternalCacheRegistry.Flag.class));
    }
 
-   private synchronized void createGlobalTxTable(EmbeddedCacheManager cacheManager) {
+   private void createGlobalTxTable(EmbeddedCacheManager cacheManager) {
```
Comment (pruivo) [inline server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java]: I don't think you can remove the `synchronized` here. 
You can end up with multiple `GlobalTxTable` instances; use an `AtomicBoolean` and do a CAS operation to ensure a single `GlobalTxTable`.

Comment (pruivo) [reply server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java]: Or create a component factory :)

File: core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java [hunk 2]
```diff
@@ -265,9 +275,12 @@ private synchronized void updateStatusRunning() {
    }
```
Comment (pruivo) [inline core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java:280]: `updateStatusRunning()`  need locking too.

**Comment by jabolina** [comment]
Thanks! I've created a component factory for the `GlobalTxTable`.

**Review by pruivo — APPROVED** [review]
