### PR TITLE
[#14506] Ad-hoc JsonBucket mem size

### LINKED ISSUE #14506: Memory size computation fails for JsonBucket (only in CI)
### Describe the bug

ehcache.sizeof() method fails for some reasons (maybe because JsonBucket is a record?) only in CI.
Not able to reproduce it locally with different JVMs

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rigazilla**
special handling for JsonBucket memory sizeof.
closes #14506

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java [hunk 1]
```diff
@@ -17,6 +18,11 @@ public static long calculateSize(byte[] key, InternalCacheEntry<byte[], Object>
 
    static long internalCalculateSize(byte[] key, Object value) {
       try {
+         if (value instanceof JsonBucket jb) {
+            // JsonBucket is a special case, we need to use the sizeOf library
+            // to calculate the size of the JsonBucket
+            return sizeof.deepSizeOf(key) + sizeof.deepSizeOf(jb.value());
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java:24]: Should we had a bit of overhead for the JsonBucket class to compensate?

Comment (rigazilla) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java:24]: yeah, I need to check how records are represented in memory

File: server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java [hunk 2]
```diff
@@ -17,6 +18,11 @@ public static long calculateSize(byte[] key, InternalCacheEntry<byte[], Object>
 
    static long internalCalculateSize(byte[] key, Object value) {
       try {
+         if (value instanceof JsonBucket jb) {
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java:21]: Any chance the other structures might fall in this as well?

**Comment by rigazilla** [comment]
@wburns  @jabolina pls have a look at the latest version

**Review by jabolina — APPROVED** [review]

File: server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java [hunk 3]
```diff
@@ -15,12 +16,30 @@ public static long calculateSize(byte[] key, InternalCacheEntry<byte[], Object>
...
+         }
          return sizeof.deepSizeOf(key) + sizeof.deepSizeOf(value);
       } catch (Exception ex) {
          // Try an old style computation
          return pesc.calculateSize(key, value);
       }
    }
+
+   public static long objHeader() {
+      return MemoryEntrySizeUtils.calculateSize(MemoryHeader.EmptyObj);
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java:38]: Should we just store the value in a static variable so it doesn't need to be calculated every time?

Also I think technically we need to add an additional instance field in the MemoryHeader class to more appropriately estimate the size.

Comment (rigazilla) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java:38]: Yeah, my initial idea was to provide a general-purpose empty MemoryHeader, since the overhead I've checked that an empty class and a class with a single field have the same overhead.  
However, it seems this isn't a general rule, for i.e. a class with two fields appears to have greater overhead.
I'm adding class specific for JsonBucket

**Comment by wburns** [comment]
Rerunning as CI seems to have hung for some reason.

**Comment by wburns** [comment]
Actually it also requires a rebase now @rigazilla with the new serialization changes.

**Comment by tristantarrant** [comment]
Thanks @rigazilla
