### PR TITLE
[#16104] Bounded eviction happening in wrong order

### LINKED ISSUE #16104: Bounded eviction happening in wrong order
### Describe the bug

I'm seeing an issue that entries in a bounded heap cache are not evicted in the expected order (according to Caffeine's TinyLfu).

Using Caffeine directly the most frequently used entries are kept as expected (the sleeps are because Caffeine runs eviction asynchronously):

```java
Cache<String, String> cache = Caffeine.newBuilder()
        .maximumSize(3)
        .build();

cache.put("1", "1");
cache.put("2", "2");
cache.put("3", "3");
Thread.sleep(100);
cache.getIfPresent("3");
cache.getIfPresent("3");
cache.getIfPresent("3");
Thread.sleep(100);
cache.put("4", "4");
cache.getIfPresent("4");
cache.getIfPresent("4");
cache.getIfPresent("4");
Thread.sleep(100);
cache.put("5", "5");
cache.put("6", "6");
Thread.sleep(100);

System.out.println(cache.asMap().keySet());
// Prints [3, 4, 6] as expected. 3, 4 are most used and 6 is most recent
```

But with Infinispan they are evicted in wrong order:

```java
Configuration config = new ConfigurationBuilder()
        .clustering().cacheMode(CacheMode.REPL_SYNC)
        .memory().maxCount(3)
        .build();
cacheManager.defineConfiguration("foo", config);
Cache<String, String> cache = cacheManager.getCache("foo");

cache.put("1", "1");
cache.put("2", "2");
cache.put("3", "3");
Thread.sleep(100);
cache.get("3");
cache.get("3");
cache.get("3");
Thread.sleep(100);
cache.put("4", "4");
cache.get("4");
cache.get("4");
cache.get("4");
Thread.sleep(100);
cache.put("5", "5");
cache.put("6", "6");
Thread.sleep(100);

System.out.println(cache.keySet());
// Prints [1, 2, 6] which is not as expected. 3, 4 are most used
```

It looks like Infinispan fetches entries [specifically so as to not update Caffeine's statistics](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/container/impl/PeekableTouchableCaffeineMap.java#L27), and there is a [comment referring to a `get`](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/container/impl/PeekableTouchableMap.java#L11C74-L11C77) that does not exist.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by wburns**
Fixes #16104

### CODE REVIEW

File: core/src/test/java/org/infinispan/eviction/impl/EvictionAccessTest.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+import org.infinispan.configuration.cache.ConfigurationBuilder;
+import org.infinispan.manager.DefaultCacheManager;
+import org.infinispan.test.AbstractInfinispanTest;
+import org.testng.annotations.Test;
+
+@Test (groups = "functional", testName = "eviction.impl.EvictionAccessTest")
+public class EvictionAccessTest extends AbstractInfinispanTest {
+   public void testAccess() {
+      Configuration config = new ConfigurationBuilder()
+            .clustering().cacheMode(CacheMode.LOCAL)
```
Comment (pruivo) [inline core/src/test/java/org/infinispan/eviction/impl/EvictionAccessTest.java]: The simple cache may be affected too:
https://github.com/infinispan/infinispan/blob/7826e0be6152624dc920b82c0dd7fa9fdb4683cb/core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java#L233

File: core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java [hunk 2]
```diff
@@ -32,6 +32,15 @@
  */
 public interface InternalDataContainer<K, V> extends DataContainer<K, V> {
 
+   /**
+    * Retrieves from the underlying container, same as {@link #peek(int, Object)} but also updates any reference
+    * for eviction. Note this also doesn't affect expiration in any manner either.
+    * @param segment segment for the key
+    * @param k key under which entry is stored
+    * @return entry, if it exist, or nulll if not
```
Comment (pruivo) [inline core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java]: typo, `nulll` :)

File: core/src/test/java/org/infinispan/eviction/impl/EvictionAccessTest.java (hunk 1 above)
Comment (wburns) [reply core/src/test/java/org/infinispan/eviction/impl/EvictionAccessTest.java]: Good catch 👍

File: core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
Comment (cfredri4) [inline core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java:1]: Can `get(key)` be added to `DataContainer` instead?
I use `DataContainer` for optimized reading in some cases.

**Review by pruivo — APPROVED** [review]

File: core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
Comment (pruivo) [reply core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java:1]: @wburns, your thoughts?

Comment (wburns) [reply core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java:1]: Yeah, I was originally not adding it there just to be safe. But having some time to think on it should be fine.

**Review by pruivo — APPROVED** [review]

**Comment by wburns** [comment]
I am just double checking the test failures as they might be related.

**Comment by wburns** [comment]
Fixed tests, just needed to be updated to new method.

**Comment by pruivo** [comment]
merged! thanks @wburns !
