### PR TITLE
[#13260] Fixes index rebuild on startup

### LINKED ISSUE #13260: Index configuration settings should have good defaults to ensure a valid configuration by default
### Description

We decided to not to make the index storage configuration should be defaulted to: 
  * `local-heap` if the cache is not persistent
  * `filesystem` if the cache is persistent
 
But to keep `filesystem` as default in any case, since `local-heap` is more suitable for tests.

The issue has been re-scoped to: 

1. Make the index startup mode should be defaulted to `auto` 
2. Presenting a WARN message if the index startup mode is not consistent with the cache configuration
3. Document it

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #13260

Supersedes https://github.com/infinispan/infinispan/pull/16418

### CODE REVIEW

File: server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java [hunk 1]
```diff
@@ -141,9 +144,15 @@ public void cacheStarting(ComponentRegistry cr, Configuration cfg, String cacheN
...
             cr.registerComponent(searchMapping, SearchMapping.class);
+            Indexer indexer = cr.getComponent(Indexer.class);
+            if (indexer == null) {
+               Indexer massIndexer = new DistributedExecutorMassIndexer(cache);
+               cr.registerComponent(massIndexer, Indexer.class);
+            }
             BasicComponentRegistry bcr = cr.getComponent(BasicComponentRegistry.class);
             bcr.replaceComponent(IndexStatistics.class.getName(), new LocalIndexStatistics(), true);
             bcr.rewire();
+            new IndexStartupRunner(cache).run();
```
Comment (jabolina) [inline server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java:155]: Does the runner execute twice? Here in the server and then again at the `LifecycleManager` in the query module?

File: query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java [hunk 2]
```diff
@@ -62,7 +63,8 @@ public void purge(Collection<Class<?>> javaClasses) {
    }
 
    public Collection<Class<?>> allJavaClasses() {
-      return getSearchMapping().allIndexedEntityJavaClasses();
+      getSearchMapping();
+      return searchMapping != null ? searchMapping.allIndexedEntityJavaClasses() : Collections.emptyList();
```
Comment (jabolina) [inline query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java]: The other methods don't require the null check?

File: server/tests/src/test/java/org/infinispan/server/functional/rest/RestReindexAutoCacheIT.java [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+      org.infinispan.configuration.cache.ConfigurationBuilder builder = new org.infinispan.configuration.cache.ConfigurationBuilder();
+      builder.encoding().mediaType(APPLICATION_PROTOSTREAM_TYPE);
+      builder.clustering().cacheMode(CacheMode.DIST_SYNC).stateTransfer().awaitInitialTransfer(true);
+      builder
+            .persistence()
+            .addSoftIndexFileStore()
+            .segmented(false);
+      builder.statistics().enable();
+      builder.indexing().enable()
+               .storage(LOCAL_HEAP)
```
Comment (jabolina) [inline server/tests/src/test/java/org/infinispan/server/functional/rest/RestReindexAutoCacheIT.java]: Should it use FILESYSTEM to run that file tree walk? Or maybe we make the test parameterized.

**Review by jabolina — COMMENTED** [review]
Deleting the files sounds reasonable.

Can we create a test that also runs in the rolling-upgrade module? I guess this way we can verify with different Lucene versions.

File: server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java (hunk 1 above)
Comment (tristantarrant) [reply server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java:155]: Embedded and Server use different SearchMappings. The IndexStartupRunner only runs once.

File: server/tests/src/test/java/org/infinispan/server/functional/rest/RestReindexAutoCacheIT.java (hunk 3 above)
Comment (tristantarrant) [reply server/tests/src/test/java/org/infinispan/server/functional/rest/RestReindexAutoCacheIT.java]: I've removed the storage type, so it uses FILESYSTEM

**Comment by tristantarrant** [comment]
> Deleting the files sounds reasonable.
> 
> Can we create a test that also runs in the rolling-upgrade module? I guess this way we can verify with different Lucene versions.

I felt that simply corrupting the index would cover all cases

File: query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java (hunk 2 above)
Comment (tristantarrant) [reply query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java]: This is a leftover from a previous experiment. I can undo the fix

**Review by andyuk1986 — APPROVED** [review]
Manual test and automation work properly. The build is green. The PR looks good to me.
