### PR TITLE
[#15139] Fixes 500 REST endpoint with local server

### LINKED ISSUE #15139: Local Server Running fails 500 in some REST Endpoints
### Describe the bug

/v2/cluster/members
/server/connections

Return 500 because the address is null. 
Return to "local" 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by karesti**
Fixes #15139

### CODE REVIEW

**Comment by karesti** [comment]
Screenshot 2025-06-23 at 19 52 28
Screenshot 2025-06-23 at 19 52 32

**Comment by karesti** [comment]
without the fix, we get 500 and a big error on screen

**Comment by karesti** [comment]
@tristantarrant anything needed here ?

File: server/rest/src/test/java/org/infinispan/rest/resources/LocalClusterResourceTest.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+import static org.infinispan.rest.resources.AbstractRestResourceTest.REALM;
+import static org.infinispan.rest.resources.AbstractRestResourceTest.USER;
+import static org.infinispan.rest.resources.ClusterResource.CACHE_MANAGER_STATUS;
+import static org.infinispan.rest.resources.ClusterResource.MEMBERS;
+import static org.infinispan.rest.resources.ClusterResource.NODE_ADDRESS;
+import static org.infinispan.rest.resources.ClusterResource.PHYSICAL_ADDRESSES;
+import static org.infinispan.rest.resources.ClusterResource.ROLLING_UPGRADE;
+import static org.infinispan.rest.resources.ClusterResource.VERSION;
+
+@Test(groups = "functional", testName = "rest.ClusterResourceTest")
```
Comment (tristantarrant) [inline server/rest/src/test/java/org/infinispan/rest/resources/LocalClusterResourceTest.java]: This test class needs to killl the RestServer it starts in the @AfterClass

**Review by tristantarrant — CHANGES_REQUESTED** [review]

File: server/rest/src/test/java/org/infinispan/rest/resources/LocalClusterResourceTest.java (hunk 1 above)
Comment (karesti) [reply server/rest/src/test/java/org/infinispan/rest/resources/LocalClusterResourceTest.java]: done

**Comment by karesti** [comment]
@andyuk1986
