### PR TITLE
[#13734] Client topology installed during authentication can cause

### LINKED ISSUE #13734: Client topology installed during authentication can cause client to hang
### Describe the bug

Cause of this bug:

The CompletionStage attemptedConnect returned by `OperationChannel.attemptConnect`  is missing a call to `completeExceptionally` in `AuthHandler.activate`

Reference: [AuthHandler.java#L88](https://github.com/infinispan/infinispan/blob/4dc70d8bc985896bf53a9b5745bf579da242fb2d/client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/AuthHandler.java#L88-L88)

If authentication completes successfully, `operationChannel.markAcceptingRequests()` is invoked, which completes attemptedConnect. However, if authentication fails, attemptedConnect remains uncompleted.

Overal behavioral: 
We use VIP which redirects calls to one of the real IPs of infinispan server.
This setup worked for us in 15.0.x but after upgrade to 15.1.3 `RemoteCacheManager.start()` started hanging
in [OperationDispatcher.java#L202](https://github.com/infinispan/infinispan/blob/4dc70d8bc985896bf53a9b5745bf579da242fb2d/client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java#L202-L202)

	1.	The client connects to the VIP.
	2.	The VIP responds with a topology update containing the list of real server IPs. The VIP itself is not included in that list.
	3.	The client establishes connections to the real server IPs and closes the connection to the VIP.
	4.	AuthHandler fails to authenticate the VIP due to the closed connection.
	5.	The CompletableFuture associated with the VIP connection is never completed, causing RemoteCacheManager.start() to hang for 1 day.

### Expected behavior

`AuthHandler.activate` should call  `attemptedConnect.get().completeExceptionally()` in `exceptionally` block of code.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "23.0.1" 2024-10-15

### Infinispan version or git rev

15.1.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
client to hang

Fixes #13734

### CODE REVIEW

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java [hunk 1]
```diff
@@ -239,6 +239,13 @@ public Queue<HotRodOperation<?>> pendingChannelOperations() {
 
    public List<HotRodOperation<?>> close() {
       acceptingRequests = false;
+      CompletableFuture<Void> future = attemptedConnect.getAndSet(null);
+      if (future != null) {
+         // If we closed a channel before we even established the connection fully just finish normally.
+         // This is most likely due to interruption or connecting to a server that returned a topology without
+         // itself in the list (which can happen with DNS hostnames, proxy hosts, etc.).
+         future.complete(null);
```
Comment (danfaer) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java:247]: 👍 
`OperationalChanel.close()` is definitely needs a call to `complete`
Is it possible to fail in `AuthHandler.activate` and do not reach `OperationalChanel.close()` ?
calling to `completeExceptionally` in  `AuthHandler.activate` too will not hurt.

Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java:247]: The `completeExceptionally` was done correctly in `AuthHandler`. The one that was a problem is the one that only lives in `OperationChannel` in the `attemptedConnect` variable. This one is separate and is specific to the `OperationChannel` which is used to signify it is successfully connected to a netty `Channel`. This variable will hold a non null value while it is in the middle of this operation, which we obviously are during startup (more specifically while authenticating), it can also be present when attempting a retry in some cases.

The problem is we were setting the throwable properly in the retry case and works in the startup case with exceptions as well (note other tests in the AuthenticationTest class).

The case that was missing is when the underlying channel was closed in the middle of startup. Normally, startup is protected by running exclusively on the netty event loop and thus the `Channel` can't be closed. The problem is the topology update is processed and directly closes the `Channel`, so it can effectively barge in between. The fix here is just when the Channel is explicitly closed.

Note this is different then if the socket itself was closed externally as this is processed via the `HeaderDecoder#channelInactive` and it invokes `OperationChannel#reconnect` which does this code as well.

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @wburns!

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java (hunk 1 above)
Comment (danfaer) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java:247]: Thanks for the fix and the explanation!
