### PR TITLE
[#14490] Server new cache startup should not block

### LINKED ISSUE #14490: Server new cache startup should not block
### Describe the bug

If you have a cluster configured with at least 2 or more nodes and then add a new cache with a remote store, there is a possibility that it can hang while trying to create the cache.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Run GetWithMetadataTest with `taskset -c 0`. You have a 50% chance of hitting the issue.

The problem is when connecting to node A it will create the cache and in turn block waiting for the persistence manager on a netty thread. The remote store will then create a new connection to Node A which will in turn also create its own remote store which then connects back to node A. If the new connection is done on the same netty thread that originally started the cache on node A it will hang the entire startup procedure.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wburns**
* PING and AUTH_MECH commands offload cache initialization
* Rely on cache always invoking above commands

Fixes #14490

### CODE REVIEW

**Review by jabolina — APPROVED** [review]

**Comment by wburns** [comment]
I have not been able to reproduce any hangs in the persistence/remote module at all with these changes running the module tests in a tight loop.

File: client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java [hunk 1]
```diff
@@ -81,29 +81,33 @@ CompletionStage<Void> attemptConnect() {
...
-            Throwable cause = f.cause();
-            log.tracef("Connection attempt to %s encountered exception for %s", address, cause);
-            // Allow another attempt later
-            handleError(connectFuture, cause);
-         }
-      });
       // This check here is in case if there is an issue with the event loop executor where it doesn't actually run
       // the listener above, which can happen if the event loop group is shutdown
       Throwable immediateError = channelFuture.cause();
+      if (immediateError == null) {
```
Comment (jabolina) [inline client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java:87]: I guess the PR needs a rebase to pull #13742 changes in?

Comment (wburns) [reply client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java:87]: yup, I broke it out to make it easier to integrate :)

**Review by jabolina — APPROVED** [review]
Waiting for CI to finish.

**Comment by wburns** [comment]
Fixed issue with tx cache and the new blocking check.

**Comment by jabolina** [comment]
Failures in `org/infinispan/server/hotrod/tx/ServerConfigurationTest` might be related?

**Comment by wburns** [comment]
Weird they should have been fixed. Will confirm on Monday.

**Comment by wburns** [comment]
Should be fixed now

**Comment by jabolina** [comment]
Thanks, @wburns!
