### PR TITLE
[#17276] BITOP DIFF DIFF1 ANDOR ONE subcommands

### LINKED ISSUE #17276: RESP BITOP: implement DIFF, DIFF1, ANDOR, ONE operations from Redis 8.2
Redis 8.2 added four new bitwise operations to the `BITOP` command:

- **DIFF**: `BITOP DIFF destkey X [Y1 Y2 ...]` — sets a bit if it is set in X but not in any of Y1, Y2, ... (`X AND NOT(Y1 OR Y2 OR ... OR Yn)`)
- **DIFF1**: `BITOP DIFF1 destkey X [Y1 Y2 ...]` — sets a bit if it is set in one or more of Y1, Y2, ... but not in X (`(Y1 OR Y2 OR ... OR Yn) AND NOT(X)`)
- **ANDOR**: `BITOP ANDOR destkey X [Y1 Y2 ...]` — sets a bit if it is set in X and also in one or more of Y1, Y2, ... (`X AND (Y1 OR Y2 OR ... OR Yn)`)
- **ONE**: `BITOP ONE destkey X1 [X2 X3 ...]` — sets a bit if it is set in exactly one of the source keys

Reference: https://redis.io/docs/latest/commands/bitop/

### LINKED ISSUE #17277: RESP BITOP fails in clustered mode (DIST_SYNC and REPL_SYNC)
All BITOP operations (AND, OR, XOR, NOT, and the new DIFF, DIFF1, ANDOR, ONE from #17276) fail in clustered mode with `ERR null` (server-side NullPointerException).

**To reproduce:**

Create a `BitOpsClusteredTest` extending `BitOpsTest` with `TestSetup.clusteredTestSetup(3)` and either `CacheMode.DIST_SYNC` or `CacheMode.REPL_SYNC`. All BITOP tests fail with:

```
io.lettuce.core.RedisCommandExecutionException: ERR null
```

The SETBIT/BITFIELD commands also fail in clustered mode with a separate marshaller issue:
```
ERR No marshaller registered for object of Java type org.infinispan.server.resp.commands.bitmap.BitfieldFunction
```

BITCOUNT, BITPOS, GETBIT work correctly in clustered mode.

**Impact:** BITOP is limited to single-node deployments. There was no `BitOpsClusteredTest` covering this.

### PR DESCRIPTION
**Pull request by tristantarrant**
This also fixes all `BIT*` operations in clustered mode

Closes #17276
Closes #17277

Author Checklist (all must be checked):
- [x] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [x] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [x] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
~~- [ ] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.~~
~~- [ ] Log messages of level `INFO` and above have been internationalized.~~
~~- [ ] If the PR affects performance, include before/after benchmarks.~~
~~- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).~~
~~- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.~~

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

**Review by wburns — APPROVED** [review]

File: server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITOP.java [hunk 1]
```diff
@@ -32,30 +33,28 @@ public CompletionStage<RespRequestHandler> perform(Resp3Handler handler,
       byte[] destKey = arguments.get(1);
       List<byte[]> srcKeys = arguments.subList(2, arguments.size());
 
-      List<CompletableFuture<byte[]>> futures = new ArrayList<>();
-      for (byte[] srcKey : srcKeys) {
-         futures.add(handler.cache().getAsync(srcKey));
-      }
+      CompletionStage<List<byte[]>> readStage = CompletionStages.performSequentially(
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITOP.java]: I am just curious, any reason this is sequential now instead of concurrent as it was before?

Comment (tristantarrant) [reply server/resp/src/main/java/org/infinispan/server/resp/commands/bitmap/BITOP.java]: Fixed it

**Comment by wburns** [comment]
Integrated into main, thanks @tristantarrant !
