### PR TITLE
[#15973] RESP configuration defined at start

### LINKED ISSUE #15973: RESP connector accepts invalid configuration
### Describe the bug

The configuration for the cache utilized by the RESP connector has a few requirements to work properly. Since #15704, the RESP cache initializes lazily on the user's first access. When this happens, we validate the configuration.

However, if the user has started the cache through other means before the first access through the connector, the cache might utilize an invalid configuration. For example, starting the server, running:

```
curl --digest -u "admin:password" 'http://localhost:11222/rest/v2/caches/respCache' -H 'Content-Type: application/json' -X POST -d '{"respCache":{"distributed-cache":{"mode":"SYNC"}}}'
```

Will create and initialize the RESP cache utilizing an invalid configuration. Once the user access the connector, the cache is already initialized, so no configuration is verified.

### Expected behavior

An invalid configuration provided to the RESP connector should **not** be accepted.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Infinispan version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jabolina**
* Defines the RESP configuration at start to avoid any overrides from users.
Closes #15973

### CODE REVIEW

**Comment by jabolina** [comment]
Some related failures.

**Comment by jabolina** [comment]
The tests are failing because of #16022.
We define the RESP cache configuration at start. When we start the cache, the verification says the configuration doesn't match.

**Comment by jabolina** [comment]
This one also requires #16453.

File: server/resp/src/main/java/org/infinispan/server/resp/RespServer.java [hunk 1]
```diff
@@ -121,19 +122,27 @@ public CompletionStage<Void> initializeDefaultCache() {
...
+   }
+
+   @Override
+   public CompletionStage<Void> initializeDefaultCache() {
+      Objects.requireNonNull(defaultCacheConfiguration, "Cache configuration is null");
+      String cacheName = configuration.defaultCacheName();
+      segmentSlots = new SegmentSlotRelation(defaultCacheConfiguration.clustering().hash().numSegments());
       return getBlockingManager()
-            .runBlocking(() -> SecurityActions.getOrCreateCache(cacheManager, cacheName, c), "create-resp-cache");
+            .runBlocking(() -> SecurityActions.getOrCreateCache(cacheManager, cacheName, defaultCacheConfiguration), "create-resp-cache");
```
Comment (wburns) [inline server/resp/src/main/java/org/infinispan/server/resp/RespServer.java:151]: Can't this just be `getCache` since the configuration is defined in the manager?

Comment (jabolina) [reply server/resp/src/main/java/org/infinispan/server/resp/RespServer.java:151]: I guess it is worth adding a comment in the code. I was refreshing my memory on this.

This one needs to be `getOrCreateCache` because it executes cluster-wide. So it starts the cache in all nodes in the cluster. If we utilize only `getCache`, it happens only to the node the client is connected to. This is an issue because we _start_ the cache lazily when the client connects, even though the configuration will be defined in all nodes.

**Comment by jabolina** [comment]
Updated to fix the related failures.

I've deleted one test in the `ResilienceStartupIT`. That test was overwriting the RESP configuration during runtime with something invalid. This isn't really possible now. Additionally, if the server starts with an invalid user-defined configuration, it will log the error and crash.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !

**Comment by jabolina** [comment]
Looks like 16.0.x didn't work automatically. I'll open manually.
