### PR TITLE
[#15776] RESP Blocking command listener timeout fix

### LINKED ISSUE #15776: Flaky test: org.infinispan.server.resp.dist.BlockingCommandsClusteredTest#testBLMPOPListenerTimeout
### Github Job:https://github.com/infinispan/infinispan/actions/runs/18202605670
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1981)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
	at org.infinispan.server.resp.RespBxPOPTest.testBLMPOPListenerTimeout(RespBxPOPTest.java:646)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1981)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
	at org.infinispan.server.resp.RespBxPOPTest.testBxpopThreeListenersOneTimesOutTwoProducers(RespBxPOPTest.java:385)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### LINKED ISSUE #16489: Flaky test: org.infinispan.server.resp.RespBxPOPTest#testBxpopTwoListenersOneTimeout\
### Github Job:https://github.com/infinispan/infinispan/actions/runs/20954727385
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1981)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
	at org.infinispan.server.resp.RespBxPOPTest.testBxpopTwoListenersOneTimeout(RespBxPOPTest.java:336)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:17)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #15776
Closes #16489

### CODE REVIEW

File: server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java [hunk 1]
```diff
@@ -75,18 +76,26 @@ public CompletionStage<RespRequestHandler> perform(Resp3Handler handler,
...
-      PubSubListener pubSubListener = new PubSubListener(handler, cache, configuration);
+      // Use the connection's EventLoop for scheduling timeouts instead of the shared
+      // single-threaded TIMEOUT_SCHEDULE_EXECUTOR, which can starve under load.
+      PubSubListener pubSubListener = new PubSubListener(ctx.channel().eventLoop(), cache,
+            handler.getListMultimap(), configuration);
       EventListenerKeysFilter filter = new EventListenerKeysFilter(configuration.keys().stream());
+      // Record the deadline before listener installation, which may take time in clustered environments.
+      // The timeout should be relative to when the command was issued, not when the listener is fully installed.
+      long timeout = configuration.timeout();
+      long deadline = timeout > 0 ? handler.respServer().getTimeService().wallClockTime() + timeout : 0;
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java]:
```suggestion
      long deadline = timeout > 0 ? handler.respServer().getTimeService().expectedEndTime(timeout, TimeUnit.MILLISECONDS) : 0;
```

File: server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java [hunk 2]
```diff
@@ -98,8 +107,17 @@ private CompletableFuture<Collection<byte[]>> addSubscriber(PopConfiguration con
          // Listener can lose events during its install, so we need to poll again
          // and if we get values complete the listener future. In case of exception
          // completeExceptionally
-         // Start a timer if required
-         pubSubListener.startTimer(configuration.timeout());
+         // Start a timer with the remaining time, accounting for time spent installing the listener.
+         if (timeout > 0) {
+            long remaining = deadline - handler.respServer().getTimeService().wallClockTime();
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java]:
```suggestion
            long remaining = handler.respServer().getTimeService().remainingTime(deadline, TimeUnit.MILLISECONDS);
```

File: server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java [hunk 3]
```diff
@@ -75,18 +76,26 @@ public CompletionStage<RespRequestHandler> perform(Resp3Handler handler,
...
+   private CompletableFuture<Collection<byte[]>> addSubscriber(PopConfiguration configuration, Resp3Handler handler,
+         ChannelHandlerContext ctx) {
       if (log.isTraceEnabled()) {
          log.tracef("Subscriber for keys: " + configuration.keys());
       }
       AdvancedCache<byte[], Object> cache = handler.typedCache(null);
       DataConversion vc = cache.getValueDataConversion();
-      PubSubListener pubSubListener = new PubSubListener(handler, cache, configuration);
+      // Use the connection's EventLoop for scheduling timeouts instead of the shared
+      // single-threaded TIMEOUT_SCHEDULE_EXECUTOR, which can starve under load.
```
Comment (jabolina) [inline server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java]: The timeout executor starving would be a general problem in the test suite. Would we need to change the configuration then?

**Review by jabolina — COMMENTED** [review]
I think the change to measuring the timeout makes sense, but I think we should stick with the timeout executor instead of delegating to the event loop.

I also noticed the tests are not updating the controlled time service. We should include `timeService.advance(10_000);` in between these lines:

https://github.com/infinispan/infinispan/blob/8156a6fad24957bdf32c24f88ccad8c52f460f50/server/resp/src/test/java/org/infinispan/server/resp/RespBxPOPTest.java#L334-L335

And `timeService.advance(5_000);` between these two:

https://github.com/infinispan/infinispan/blob/8156a6fad24957bdf32c24f88ccad8c52f460f50/server/resp/src/test/java/org/infinispan/server/resp/RespBxPOPTest.java#L649-L650

**Comment by tristantarrant** [comment]
@jabolina I've addressed all comments. I've restored the old behavior

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @tristantarrant!

**Comment by jabolina** [comment]
Doh! I've merged it, but the flaky test comment still includes the test as flaky. Sorry :man_facepalming:
