### PR TITLE
[#16238] Ensure configured user marshaller serializes collection and map entries

### LINKED ISSUE #16238: JGroupsTransport always use Protostream regardless if JavaSerializationMarshaller is defined
### Describe the bug

We use the following config
```xml
	<jgroups>
		<stack-file name="external-file" path="${jgroups.config:jgroups.xml}" />
	</jgroups>

	<cache-container default-cache="default" statistics="false">
		<transport stack="external-file" lock-timeout="600000"/>
		<serialization marshaller="org.infinispan.commons.marshall.JavaSerializationMarshaller">
			<allow-list>
```

And when upgrading from version 15.2.6.Final to 16.0.2 we're getting the exception bellow:

```
ISPN000559: Cannot marshall 'class org.infinispan.commands.statetransfer.StateResponseCommand'java.lang.IllegalArgumentException: No marshaller registered for object of Java type com.mypackage.MyClass : MyClass [<redacted toString()>]
	at org.infinispan.protostream.impl.SerializationContextImpl.getMarshallerDelegate(SerializationContextImpl.java:572)
	at org.infinispan.protostream.WrappedMessage.writeCustomObject(WrappedMessage.java:308)
	at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:258)
	at org.infinispan.protostream.WrappedMessage.writeContainerElementWrapped(WrappedMessage.java:405)
	at org.infinispan.protostream.WrappedMessage.writeContainerWrappingElements(WrappedMessage.java:365)
	at org.infinispan.protostream.WrappedMessage.writeContainer(WrappedMessage.java:354)
	at org.infinispan.protostream.WrappedMessage.writeCustomObject(WrappedMessage.java:312)
	at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:258)
	at org.infinispan.protostream.WrappedMessage$1.write(WrappedMessage.java:849)
	at org.infinispan.protostream.WrappedMessage$1.write(WrappedMessage.java:830)
	at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:28)
	at org.infinispan.protostream.GeneratedMarshallerBase.writeNestedMessage(GeneratedMarshallerBase.java:45)
	at org.infinispan.marshall.protostream.impl.MarshallableObject$Marshaller.write(MarshallableObject.java:145)
	at org.infinispan.marshall.protostream.impl.MarshallableObject$Marshaller.write(MarshallableObject.java:70)
	at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:28)
	at org.infinispan.protostream.GeneratedMarshallerBase.writeNestedMessage(GeneratedMarshallerBase.java:45)
	at org.infinispan.container.entries.ImmortalCacheEntry$___Marshaller_d65ae9d411d0dce22b84ac83a2838ff26beb51340bfeb6e4c3356a22f72af085.write(ImmortalCacheEntry$___Marshaller_d65ae9d411d0dce22b84ac83a2838ff26beb51340bfeb6e4c3356a22f72af085.java:89)
	at org.infinispan.container.entries.ImmortalCacheEntry$___Marshaller_d65ae9d411d0dce22b84ac83a2838ff26beb51340bfeb6e4c3356a22f72af085.write(ImmortalCacheEntry$___Marshaller_d65ae9d411d0dce22b84ac83a2838ff26beb51340bfeb6e4c3356a22f72af085.java:13)
	at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:28)
	at org.infinispan.protostream.WrappedMessage.writeCustomObject(WrappedMessage.java:327)
	at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:258)
	at org.infinispan.protostream.WrappedMessage$1.write(WrappedMessage.java:849)
	at org.infinispan.protostream.WrappedMessage$1.write(WrappedMessage.java:830)
	at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:28)
	at org.infinispan.protostream.GeneratedMarshallerBase.writeNestedMessage(GeneratedMarshallerBase.java:45)
	at org.infinispan.marshall.protostream.impl.AbstractMarshallableCollection$Marshaller.write(AbstractMarshallableCollection.java:105)
	at org.infinispan.marshall.protostream.impl.MarshallableList$Marshaller.write(MarshallableList.java:66)
	at org.infinispan.marshall.protostream.impl.AbstractMarshallableCollection$Marshaller.write(AbstractMarshallableCollection.java:35)
	at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:28)
	at org.infinispan.protostream.GeneratedMarshallerBase.writeNestedMessage(GeneratedMarshallerBase.java:45)
	at org.infinispan.statetransfer.StateChunk$___Marshaller_507b6e69d93a5acdb5b295dfa7387a38d8551ae8b6dd8b73fe99514ef1711c0.write(StateChunk$___Marshaller_507b6e69d93a5acdb5b295dfa7387a38d8551ae8b6dd8b73fe99514ef1711c0.java:76)
	at org.infinispan.statetransfer.StateChunk$___Marshaller_507b6e69d93a5acdb5b295dfa7387a38d8551ae8b6dd8b73fe99514ef1711c0.write(StateChunk$___Marshaller_507b6e69d93a5acdb5b295dfa7387a38d8551ae8b6dd8b73fe99514ef1711c0.java:13)
	at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:28)
	at org.infinispan.protostream.GeneratedMarshallerBase.writeNestedMessage(GeneratedMarshallerBase.java:45)
	at org.infinispan.commands.statetransfer.StateResponseCommand$___Marshaller_25f774980e5228fe95c0c99868837608e0281d3d49917c83984fa407a4ee8186.write(StateResponseCommand$___Marshaller_25f774980e5228fe95c0c99868837608e0281d3d49917c83984fa407a4ee8186.java:96)
	at org.infinispan.commands.statetransfer.StateResponseCommand$___Marshaller_25f774980e5228fe95c0c99868837608e0281d3d49917c83984fa407a4ee8186.write(StateResponseCommand$___Marshaller_25f774980e5228fe95c0c99868837608e0281d3d49917c83984fa407a4ee8186.java:13)
	at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:28)
	at org.infinispan.protostream.WrappedMessage.writeCustomObject(WrappedMessage.java:327)
	at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:258)
	at org.infinispan.protostream.WrappedMessage.write(WrappedMessage.java:251)
	at org.infinispan.protostream.ProtobufUtil.toWrappedStream(ProtobufUtil.java:189)
	at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectToOutputStream(AbstractInternalProtoStreamMarshaller.java:67)
	at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectToBuffer(AbstractInternalProtoStreamMarshaller.java:90)
	at org.infinispan.marshall.protostream.impl.GlobalMarshaller.objectToBuffer(GlobalMarshaller.java:71)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.marshallRequest(JGroupsTransport.java:1201)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.doSendForCluster(JGroupsTransport.java:1193)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.sendCommandCheckingView(JGroupsTransport.java:1181)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.invokeCommand(JGroupsTransport.java:967)
	at org.infinispan.remoting.rpc.RpcManagerImpl.invokeCommand(RpcManagerImpl.java:236)
	at org.infinispan.statetransfer.OutboundTransferTask.sendChunks(OutboundTransferTask.java:156)
	at org.infinispan.statetransfer.OutboundTransferTask.lambda$execute$1(OutboundTransferTask.java:140)
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver.drain(FlowableConcatMapCompletable.java:187)
	at io.reactivex.rxjava3.internal.operators.mixed.ConcatMapXMainSubscriber.onNext(ConcatMapXMainSubscriber.java:106)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeUntilPredicate$InnerSubscriber.onNext(FlowableTakeUntilPredicate.java:57)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:124)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:75)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:53)
	at io.reactivex.rxjava3.internal.util.HalfSerializer.onNext(HalfSerializer.java:46)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.innerNext(FlowableConcatMap.java:206)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapInner.onNext(FlowableConcatMap.java:563)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatWithSingle$ConcatWithSubscriber.onNext(FlowableConcatWithSingle.java:71)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:75)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$IteratorConditionalSubscription.slowPath(FlowableFromIterable.java:380)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:131)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.rxjava3.internal.subscribers.SinglePostCompleteSubscriber.request(SinglePostCompleteSubscriber.java:115)
	at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.setSubscription(SubscriptionArbiter.java:87)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapInner.onSubscribe(FlowableConcatMap.java:556)
	at io.reactivex.rxjava3.internal.subscribers.SinglePostCompleteSubscriber.onSubscribe(SinglePostCompleteSubscriber.java:59)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:66)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16095)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatWithSingle.subscribeActual(FlowableConcatWithSingle.java:44)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16095)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:318)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onSubscribe(FlowableConcatMap.java:124)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16095)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap.subscribeActual(FlowableConcatMap.java:66)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer.subscribeActual(FlowableBuffer.java:45)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeUntilPredicate.subscribeActual(FlowableTakeUntilPredicate.java:33)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16149)
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable.subscribeActual(FlowableConcatMapCompletable.java:56)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2860)
	at io.reactivex.rxjava3.core.Completable.subscribeWith(Completable.java:2910)
	at io.reactivex.rxjava3.core.Completable.toCompletionStage(Completable.java:3470)
	at org.infinispan.statetransfer.OutboundTransferTask.execute(OutboundTransferTask.java:142)
	at org.infinispan.statetransfer.StateProviderImpl.startOutboundTransfer(StateProviderImpl.java:297)
	at org.infinispan.commands.statetransfer.StateTransferStartCommand.invokeAsync(StateTransferStartCommand.java:38)
	at org.infinispan.remoting.inboundhandler.BasePerCacheInboundInvocationHandler.invokeCommand(BasePerCacheInboundInvocationHandler.java:95)
	at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.invoke(BaseBlockingRunnable.java:111)
	at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.runAsync(BaseBlockingRunnable.java:79)
	at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.run(BaseBlockingRunnable.java:48)
	at org.infinispan.remoting.inboundhandler.TrianglePerCacheInboundInvocationHandler.handleStateRequestCommand(TrianglePerCacheInboundInvocationHandler.java:84)
	at org.infinispan.remoting.inboundhandler.TrianglePerCacheInboundInvocationHandler.handle(TrianglePerCacheInboundInvocationHandler.java:63)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleCacheRpcCommand(GlobalInboundInvocationHandler.java:121)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:74)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1543)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1467)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1640)
	at org.jgroups.JChannel.up(JChannel.java:678)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:938)
	at org.jgroups.protocols.SEQUENCER.up(SEQUENCER.java:187)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:137)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:252)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:260)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:799)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:234)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1171)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:897)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:879)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:489)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:642)
	at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:104)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:181)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:190)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:271)
	at org.jgroups.protocols.Discovery.up(Discovery.java:304)
	at org.jgroups.stack.Protocol.up(Protocol.java:360)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1127)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:105)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```

### Expected behavior

To use infinispan 16 with java serialization for my classes without the need to use protostream

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### PR DESCRIPTION
**Pull request by ryanemerson**
Closes #16238

### CODE REVIEW

File: core/src/main/java/org/infinispan/marshall/protostream/impl/GlobalMarshaller.java [hunk 1]
```diff
@@ -51,6 +51,19 @@ public boolean isMarshallableWithProtoStream(Object o) {
...
 
    public boolean isMarshallableWithoutWrapping(Object o) {
+      if (isProtostreamNativeType(o))
+         return true;
+
+      if (!skipUserMarshaller && o instanceof Iterable<?> iterable) {
+         // Custom user marshaller configured so we need to make sure that nested classes in objects are also marshallable
+         // with ProtoStream
+         var it = iterable.iterator();
+         return !it.hasNext() || isMarshallableWithoutWrapping(it.next());
```
Comment (ryanemerson) [inline core/src/main/java/org/infinispan/marshall/protostream/impl/GlobalMarshaller.java:64]: @tristantarrant This is pretty ugly and won't work if the Iterable contains mixed types, where the first element is serializable with ProtoStream.

An alternative solution would be to remove the `ListAdapter` and `SetAdapters` from the Global Protostream SerializationContext when a custom marshaller is used. This would force the user marshaller to be used for Lists & Sets, as outside of key/values, our internal commands etc should be using `MarshallableList` or `MarshallableSet`.

However, the problem is that I don't seem to be able to cleanly remove all of the marshallers from the SerializationContext when using a `@ProtoAdapter`.  I tried doing:

```
var marshaller = ctx.getMarshallerDelegate(ProtoStreamTypeIds.ADAPTER_LIST).getMarshaller();
ctx.unregisterMarshaller(marshaller);
```

However this does not remove the `subClassNames` instances from the `marshallersByClass`. I think we need a solution that allows us to remove a `@ProtoAdapter` marshaller and all state/marshallers associated with it's configured `subClassNames`.

Comment (tristantarrant) [reply core/src/main/java/org/infinispan/marshall/protostream/impl/GlobalMarshaller.java:64]: I wouldn't be concerned about mixed types. 
Create an issue on ProtoStream for the marshaller unregistration

Comment (ryanemerson) [reply core/src/main/java/org/infinispan/marshall/protostream/impl/GlobalMarshaller.java:64]: Ok, I'll stick with the current solution for now then.

I have created https://github.com/infinispan/protostream/issues/588 to track the required ProtoStream changes and added a comment to the current code detailing possible follow-up work.

**Comment by wburns** [comment]
Integrated into main, thanks @ryanemerson !
